litmuschaos/litmus

- tpcc-client/README.md
Added the license related note
> Updates to README for tpcc-client 

- executor/ansible/roles/inventory/files/inventory.py
- executor/ansible/roles/inventory/files/utils.py
- tools/jupyter-scripts/generate_io.py
Also, changed shebang line to let `env` find `python3` executable.
Signed-off-by: Shubham Bhattar <shubhambhattar@users.noreply.github.com>
>  Used `with` construct to handle files open/close. 

- README.md
Signed-off-by: Dipansh Khandelwal (deepanshrocks438@gmail.com)
Some links can be formatted in a better way.
> Update link formatting in README

- ISSUE_TEMPLATE.md
Signed-off-by: Tanisha Jalota (tanishajalota@gmail.com)
Closes https://github.com/openebs/litmus/issues/16
> [Added] ISSUE_TEMPLATE.md

- tools/ansible-runner/Dockerfile
> Fix ansible-runner Dockerfile: copy /apps 

- master.yaml
Addresses suggestions in https://github.com/openebs/elves/pull/52.
After a suggestion made by @ksatchit in an offline discussion, I am raising this PR which is derrived from https://github.com/openebs/elves/pull/52 raised by @ksatchit in `openebs/elves` to quick start development in MayaOnline side.
Signed-off-by: Abhishek Kashyap <abhishek.kashyap@mayadata.io>
> Adds master test spec for Maya-Online

- master.yaml
- Replace placeholders in master.yaml run template with actual test/chaos job info
> Update master.yaml with chaos job info

- k8s/utils/health/cluster_health_check.py
- Add timeout period of 30 seconds to avoid too much checking and log blast in Gitlab job
> Add sleep of 30s in python script

- apps/percona/deployers/deploy_percona_litmus.yaml
> Updates to default storage class and claim name (made pvc generic)

- providers/openebs/installers/operator/master/litmusbook/openebs_cleanup.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
- Path referenced to a non-existing directory (0.7) 
> Update litmusbook paths for openebs installer (master)

- apps/percona/chaos/openebs_cstor_target_failure/chaosutil.j2
- apps/percona/chaos/openebs_cstor_target_failure/run_litmus_test.yaml
- apps/percona/chaos/openebs_cstor_target_failure/test.yaml
- apps/percona/chaos/openebs_cstor_target_failure/test_prerequisites.yaml
- apps/percona/chaos/openebs_cstor_target_failure/test_vars.yaml
- chaoslib/openebs/openebs_cstor_target_failure.yaml
* Percona target failure test on cstor storage engine.
**Please review**:
@ksatchit 
@dargasudarshan
> Litmus book for percona chaos test on cstor 

- apps/percona/deployers/percona-installer.yaml
- apps/percona/deployers/percona_vars.yaml
This commit does the following:
- Enable to record test-status in litmus result CR
Signed-off-by: ranjanshashank <ranjanshashank855@gmail.com>
> Modified litmusbook for percona deployment

- master.yaml
> Update master.yaml to add new app_tag i.e. percona

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Remove cas annotation related tasks from setup openebs litmus book
> Remove cas annotations related tasks from setup openebs litmus book

- apps/crunchy-postgres/deployers/deploy-postgres-litmus.yaml
- apps/crunchy-postgres/deployers/postgres-installer.yaml
- apps/crunchy-postgres/deployers/postgres-statefulset.yaml
- apps/crunchy-postgres/deployers/postgres-vars.yaml
- Deploys postgres statefulset application with 2 application replicas.
- Verifying if all the replicas are created and in running state.
@ksatchit @gprasath @dargasudarshan can you please review this PR
> Deploy crunchy postgres application as k8s statefulset

- k8s/gcp/k8s-installer/create-k8s-cluster.yml
- k8s/utils/health/cluster_health_check.py
- Modify and add wait in cluster health check python script to minimize api
calls and avoid log burst
fixes: reduces api calls and avoid log bursts in gitlab, and fixes indentation fault in create cluster playbook
>  Modify timeout in health check python script

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- providers/openebs/installers/operator/master/ansible/vars.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
-> Adds image pull policy env variable to litmus job.
-> Fix ndm check.
> feat(yaml): Add image pull policy env variable and fix ndm check

- apps/cassandra/liveness/cassandra_liveness_litmus.yml
This PR does the following:
1. Add a litmus job for cassandra-liveness
Signed-off-by: ranjanshashank <ranjanshashank855@gmail.com>
> Add a litmusbook for cassandra-liveness

- apps/jenkins/deployers/deploy_jenkins_litmus.yml
- apps/jenkins/deployers/jenkins-installer.yml
- apps/jenkins/deployers/jenkins.yml
- apps/jenkins/deployers/jenkins_vars.yml
This commit Add the following files:
1. jenkins_vars.yml for test-specific parametres
2. jenkins-installer.yml for jenkins-deployment
3. jenkins.yml as a jenkins deployement yaml
Signed-off-by: ranjanshashank <ranjanshashank855@gmail.com>
> Add a litmusbook for Jenkins-Deployment

- master.yaml
- Adds missing single quotes around list elements in the app_tag
> fix(yaml): fix the elements in app_tags list in master yaml

- k8s/azure/k8s-installer/README.md
- k8s/azure/k8s-installer/create-k8s-cluster.yml
- k8s/azure/k8s-installer/delete-k8s-cluster.yml
- Add the playbook `create-k8s-cluster.yml`, that brings up an AKS Cluster on Azure Cloud.
- Add the playbook `delete-k8s-cluster.yml`, that deletes the AKS Cluster on Azure Cloud.
- Initialize these files with README with pre-requisites as well as running, viz. creating/deleting AKS cluster.
To create the Cluster, this playbook first creates the Resource Group, then creates a AKS Cluster and associates with the created Resource Group. Upon deletion of cluster, such intended playbook deletes the Resource Group which also deletes all associated stuffs with it, including AKS Cluster.
**Creates Cluster**
`$ ansible-playbook k8s/azure/k8s-installer/create-k8s-cluster.yml --extra-vars "nodes=2"`
```bash
[WARNING]: …
```
> Add Playbooks to create/delete AKS cluster on Azure Cloud

- k8s/packet/k8s-installer/create_packet_cluster.yml
- k8s/packet/k8s-installer/pre_requisite.sh
- modify pre_requisite.sh for passing the argument variable
> Modify packet cluster provisioning file

- k8s/packet/k8s-installer/create_packet_cluster.yml
- k8s/packet/k8s-installer/vars.yml
- Modify `create_packet_cluster.yml` and add task for `wait till ssh`
and provide master and workers config.
- Modify vars.yml for store master and workers config
> Add support for multiple cluster provisioning

- providers/openebs/installers/operator/0.6/ansible/openebs_cleanup.yaml
- providers/openebs/installers/operator/0.6/ansible/openebs_setup.yaml
- providers/openebs/installers/operator/0.6/ansible/vars.yaml
- providers/openebs/installers/operator/0.6/litmusbook/openebs_cleanup.yaml
- providers/openebs/installers/operator/0.6/litmusbook/openebs_setup.yaml
- providers/openebs/installers/operator/master/ansible/openebs_cleanup.yaml
- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- providers/openebs/installers/operator/master/ansible/vars.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_cleanup.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
- providers/openebs/installers/storageclass/0.6/ansible/storageclass_cleanup.yaml
- providers/openebs/installers/storageclass/0.6/ansible/storageclass_setup.yaml
- providers/openebs/installers/storageclass/0.6/ansible/vars.yaml
- providers/openebs/installers/storageclass/0.6/litmusbook/storageclass_cleanup.yaml
- providers/openebs/installers/storageclass/0.6/litmusbook/storageclass_setup.yaml
- providers/openebs/installers/storageclass/0.7/ansible/storageclass_cleanup.yaml
- providers/openebs/installers/storageclass/0.7/ansible/storageclass_setup.yaml
- providers/openebs/installers/storageclass/0.7/ansible/vars.yaml
- providers/openebs/installers/storageclass/0.7/litmusbook/storageclass_cleanup.yaml
- providers/openebs/installers/storageclass/0.7/litmusbook/storageclass_setup.yaml
-> Adds CR update logic to openebs and storage class installer and cleanup litmus book.
-> Increase number of retries and delays for CAS template check on openebs 0.7 installer.
-> Changed the jiva image version to 0.7.
> (Refactor) Refactor openebs installer to add CR update logic

- k8s/packet/packet-storage/README.md
- k8s/packet/packet-storage/create-volume.yml
- k8s/packet/packet-storage/delete-volume.yml
- k8s/packet/packet-storage/vars.yml
- Add file `create-volume.yml` will create and attach volume to the
packet cloud using the device id
- Add file `delete-volume.yml` will detach and delete volume from packet
cloud
- Add file `vars.yml` will store all the necessary variables
Packet provides multi-tenant block storage service (backed by the fine folks at Datera) 
O/P of create-volume.yml
```
ansible-playbook 2.6.1
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/home/chandan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
executable location = /usr/bin/ansible-playbook …
```
> Add playbook for create & delete volume in packet

- apps/percona/chaos/openebs_target_failure/run_litmus_test.yml
- apps/percona/chaos/openebs_target_network_delay/run_litmus_test.yml
- apps/percona/chaos/openebs_volume_replica_failure/run_litmus_test.yml
- Update the test job labels with test-specific name to  identification of test pod in cluster
> refactor(yaml): update labels on the chaos test jobs to reflect testname

- apps/crunchy-postgres/deployers/run_litmus_test.yml
- Changed the docker image name in postgres litmus book
@ksatchit can you please review this PR
> Changed the docker image in postgres litmus book

- apps/percona/chaos/openebs_volume_replica_failure/test.yml
This PR will change the file extension in a openebs volume replica failure test playbook task
@dargasudarshan can you please review this PR
> Changed the file extension in volume replica failure test playbook

- apps/percona/chaos/openebs_target_failure/chaosutil.j2
- apps/percona/chaos/openebs_target_failure/test_prerequisites.yml
- Update chaosutil to select storage engine by deriving the volume provisioner
> Fix (litmus): Update chaosutil to select storage engine by deriving the volume provisioner

- k8s/aws/k8s-installer/README.md
- k8s/aws/k8s-installer/create-aws-cluster.yml
- k8s/aws/k8s-installer/delete-aws-cluster.yml
- k8s/aws/k8s-installer/delete-pre-requisite.yml
- k8s/aws/k8s-installer/pre-requisite.yml
- Fix `block` and `rescue` in playbook
> Fix block and rescue in playbook

- k8s/gke/k8s-installer/README.md
- k8s/gke/k8s-installer/create-gke-cluster.yml
- k8s/gke/k8s-installer/delete-gke-cluster.yml
- k8s/gke/k8s-installer/vars.yml
- Added the GKE Platform to the list of k8s-installers.
Signed-off-by: Uday Kiran Y uday.kiran@openebs.io
> Added the GKE Platform to the list of k8s-installers.

- k8s/aws/ebs-volumes/create-ebs-volume.yml
- k8s/aws/ebs-volumes/delete-ebs-volume.yml
- k8s/packet/k8s-installer/create_packet_cluster.yml
- k8s/packet/k8s-installer/delete_packet_cluster.yml
- k8s/packet/packet-storage/create-volume.yml
- k8s/packet/packet-storage/delete-volume.yml
- Fix `block` and `rescue` condition in Playbook of Packet and AWS
> Update playbook for block and rescue condition

- apps/cassandra/deployers/cassandra_statefulset.yml
- apps/cassandra/deployers/run_litmus_test.yml
- apps/cassandra/deployers/test.yml
- apps/cassandra/deployers/test_vars.yml
- apps/cockroachdb/deployers/run_litmus_test.yml
- apps/crunchy-postgres/deployers/postgres_statefulset.yml
- apps/crunchy-postgres/deployers/run_litmus_test.yml
- apps/crunchy-postgres/deployers/test.yml
- apps/crunchy-postgres/deployers/test_vars.yml
- apps/jenkins/deployers/jenkins.yml
- apps/jenkins/deployers/run_litmus_test.yml
- apps/jenkins/deployers/test.yml
- apps/jenkins/deployers/test_vars.yml
- apps/jupyter/deployers/jupyter_openebs.yml
- apps/jupyter/deployers/run_litmus_test.yml
- apps/jupyter/deployers/test.yml
- apps/jupyter/deployers/test_vars.yml
- apps/mongodb/deployers/mongo_statefulset.yml
- apps/mongodb/deployers/run_litmus_test.yml
- apps/mongodb/deployers/test.yml
- apps/mongodb/deployers/test_vars.yml
- apps/percona/deployers/percona.yml
- apps/percona/deployers/run_litmus_test.yml
- apps/percona/deployers/test.yml
- apps/percona/deployers/test_vars.yml
- updated the litmus book to pass the application label and namespace as a ENV variable
- Modified the application deployment spec files to use testlabels
- Modified the PROVIDER_PVC env name into APP_PVC
- Included a task in test playbook to replace the testlabel in application deployment spec
@ksatchit @dargasudarshan @gprasath  can you please review this PR
> Updated the litmus-book to deploy applications using dedicated label

- apps/cockroachdb/deployers/cockroachdb_sts.yml
- apps/cockroachdb/deployers/cockroachdb_svc.yml
- apps/cockroachdb/deployers/run_litmus_test.yml
- apps/cockroachdb/deployers/test.yml
- apps/cockroachdb/deployers/test_vars.yml
- apps/jenkins/deployers/jenkins.yml
- apps/jupyter/deployers/jupyter_openebs.yml
- apps/percona/deployers/percona.yml
- Updated the application spec files to use dedicated labels for services
- Updated cocroachdb litmus book to deploy the application using dedicated label
@ksatchit @dargasudarshan @gprasath can you please review this PR
> Updated the application spec files to use dedicated label for services

- apps/percona/chaos/openebs_target_failure/chaosutil.j2
- chaoslib/openebs/jiva_controller_pod_failure.yaml
- Include a chaoslib util to perform jiva controller failure test.
- This util is called by a Litmus Job and based on the PVC details provided as ENV the specific chaosutil will be invoked based on the storage engine and storage provisioner of the underlying volume.
> [Litmus] Include chaoslib for jiva controller failure.

- k8s/gke/k8s-installer/create-gke-cluster.yml
- k8s/gke/k8s-installer/vars.yml
Added ability to the playbook to establish SSH connections between host and cluster nodes.
> Added ability to the playbook to establish SSH connections between host and cluster nodes.

- apps/jenkins/deployers/test.yml
- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- providers/openebs/installers/operator/master/ansible/vars.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_cleanup.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
- Adds job-specific labels to provider setup litmus jobs 
- Increases retry count for operator yaml fetch task in provider litmusbook
- Remove references to version in artifacts in master folder
- Increases retry count in jenkins pod deployment status check task
> refactor(yaml): Add labels to provider setup jobs & improved status check logic

- README.md
> Add the docker pulls badge for litmus runner

- apps/mongodb/deployers/mongo_statefulset.yml
- apps/percona/workload/run_litmus_test.yml
- apps/percona/workload/test.yml
- Modified the replace task in percona loadgen playbook
- changed the service name in percona litmus loadgen yml
- changed the mongodb statefulset deployment spec
@ksatchit @dargasudarshan can you please review this
> Modified the replace task in percona loagen playbook

- apps/cassandra/workload/run_litmus_test.yml
- apps/mongodb/workload/run_litmus_test.yml
- apps/percona/workload/run_litmus_test.yml
- Update the workload litmus job to have uniform container name
> refactor(yaml): Update the workload litmus job to have uniform container name

- apps/mongodb/workload/mongo_loadgen.yml
- apps/percona/workload/tpcc_bench.yml
-  Update mongodb and percona loadgen docker images
> refactor(yaml): Update mongodb and percona loadgen docker images

- README.md
**What this PR does / why we need it**: I only fixed a typo
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes no known issue
I fixed only a typo
> do you mean 'scenario'?

- LICENSE
**What this PR does / why we need it**: Update Licence fields
**Which issue this PR fixes**: #234
> Update LICENSE fields

- apps/cassandra/deployers/run_litmus_test.yml
- apps/cockroachdb/deployers/run_litmus_test.yml
- apps/crunchy-postgres/deployers/run_litmus_test.yml
- apps/jenkins/deployers/run_litmus_test.yml
- apps/jupyter/deployers/run_litmus_test.yml
- apps/mongodb/deployers/run_litmus_test.yml
- apps/percona/deployers/run_litmus_test.yml
- This will help creation of same job with different parameters on the cluster
> refactor(yaml): update the deployer litmus jobs to use generateName API (unique job names)

- chaoslib/openebs/openebs_cstor_target_failure.yaml
- Update cstor taget failure to do graceful kill.
- This will be workaround for the issue where cstor target pod gets stuck in Terminating. The changes will be reverted once the actual issue is fixed in future releases.
> Litmus(fix) : Update cstor taget failure to do graceful kill.

- apps/percona/chaos/openebs_target_network_delay/test.yml
- There was mismatch in the file extension for chaosutil. Modified it to use .yml.
> Changing file extension of chaosutil 

- apps/percona/chaos/openebs_target_network_delay/run_litmus_test.yml
Changes the image tag in network delay playbook
> Updated the image tag in target network delay chaos litmus book

- funclib/openebs/openebs_snapshot_restore.yml
- Implemented an utility file that can create openebs volume snapshot using mayactl providing volume name, snapshot name, and namespaces as input variables.
- Obtaining maya-apiserver pod name and uses the mayaapi-server container to create the snapshot.
- This can also restore volume to the earlier state using snapshot.
> Implemented tasks file for creating openebs volume snapshot and restoring it.

- README.md
Signed-off-by: marci010101 <marcellkisshu@gmail.com>
**What this PR does / why we need it**: It corrects some grammatical mistakes in file README.md
> Corrected spelling mistakes

- apps/cassandra/deployers/run_litmus_test.yml
- apps/cockroachdb/deployers/run_litmus_test.yml
- apps/crunchy-postgres/deployers/run_litmus_test.yml
- apps/fio/tests/run_litmus_test.yml
- apps/jenkins/deployers/run_litmus_test.yml
- apps/jupyter/deployers/run_litmus_test.yml
- apps/mongodb/deployers/run_litmus_test.yml
- apps/percona/chaos/openebs_replica_network_delay/run_litmus_test.yml
- apps/percona/chaos/openebs_target_failure/run_litmus_test.yml
- apps/percona/chaos/openebs_volume_replica_failure/run_litmus_test.yml
- apps/percona/deployers/run_litmus_test.yml
- apps/percona/tests/mysql_data_persistence/run_litmus_test.yml
- apps/percona/tests/mysql_storage_benchmark/run_litmus_test.yml
Fixes the bug report below.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #191
I used the following to ensure all images were updated:
`find . -name "run_litmus_test.yml" -exec grep "ansible-runner" {} \;`
Just to be sure you can use the below command to be sure nothing is left with the "bare" image that implies latest:
`find . -type f -exec grep "ansible-runner$" {} \;`
> Update all ansible-runner images to use ci tag

- apps/percona/tests/mysql_data_persistence/test.yml
Fix mysql_data_persistence chaos (e2e) test with correct path references
**Which issue this PR fixes** : fixes #261
> Fix path in mysql_data_persistence test

- apps/cassandra/workload/test.yml
Added RUN_ID/Instance metadata to cassandra workload litmus book
> Add RUN_ID/Instance metadata to cassandra workload litmus book

- apps/cassandra/deployers/test.yml
- Did the ansible lint of the cassandra deployer playbbok because facing failure in the deployment
@ksatchit @dargasudarshan @gprasath can you please review this PR
> Removed lint errors in cassandra deployer ansible playbook

- apps/percona/workload/run_litmus_test.yml
- apps/percona/workload/test.yml
- apps/percona/workload/test_vars.yml
- This PR will modifies and removed the  unwanted task in the percona workload litmus book.
@ksatchit @dargasudarshan @gprasath can you please review this PR
> Modified the percona workload litmus book

- apps/cassandra/deployers/run_litmus_test.yml
- apps/cassandra/workload/run_litmus_test.yml
- apps/cockroachdb/deployers/run_litmus_test.yml
- apps/cockroachdb/workload/run_litmus_test.yml
- apps/crunchy-postgres/deployers/run_litmus_test.yml
- apps/jenkins/deployers/run_litmus_test.yml
- apps/jupyter/deployers/run_litmus_test.yml
- apps/mongodb/deployers/run_litmus_test.yml
- apps/percona/chaos/openebs_replica_network_delay/run_litmus_test.yml
- apps/percona/chaos/openebs_target_failure/run_litmus_test.yml
- apps/percona/chaos/openebs_target_network_delay/run_litmus_test.yml
- apps/percona/chaos/openebs_volume_replica_failure/run_litmus_test.yml
- apps/percona/deployers/run_litmus_test.yml
- apps/percona/workload/run_litmus_test.yml
- refactor(yaml): provide distinct namespaces for all applications
> refactor(yaml): provide distinct namespaces for all applications

- apps/crunchy-postgres/workload/run_litmus_test.yml
- Update job label name to make it consistent with other workload jobs 
> refactor(yaml): update job-label of postgres workload litmusbook

- tools/ansible-runner/Dockerfile
- Need to include the funclib in the image to run app_functional tests 
> fix(dockerfile): include funclib into ansible-runner image

- apps/jenkins/upgrade/run_litmus_test.yml
- apps/jenkins/upgrade/test.yml
- apps/jenkins/upgrade/test_vars.yml
- funclib/kubectl/app_upgrade.yml
- tools/ansible-runner/Dockerfile
- Included functional library for the application upgrade test job.
-  Also included its associated test-jobs.
(Used jenkins as a test application )
1) This PR also includes changes in ansible-runner dockerfile (included funclib path ).
2) This test is using jenkins images "jenkins/jenkins:2.124".
@gprasath @dargasudarshan @ksatchit @nsathyaseelan
> Included application upgrade funclib utils file and its associated litmusbook .

- providers/openebs/installers/operator/master/ansible/vars.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
- The master provider setup litmusbook can now take YAMLs from different branch heads as per the ENV provided (master implies the branch under which a specific release version's artifacts are stored)
> refactor(yaml): update openebs provider setup from master to take branch ENV

- k8s/eks/k8s-installer/README.md
- k8s/eks/k8s-installer/create-eks-cluster.yml
- k8s/eks/k8s-installer/delete-eks-cluster.yml
- k8s/eks/k8s-installer/vars.yml
Adds the EKS platform to the litmus pipeline.
> Adding the EKS platform to the litmus pipeline.

- chaoslib/openebs/cstor_target_network_delay.yaml
- Update the chaoslib util for cstor network delay to get the cstor target details by using PV.
> refactor(yaml): Get cstor target details using PV

- README.md
Small improvements made to the main Readme file.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
Not an issue, didn't know whether to open one for something so small, of if this PR will be taken into account at all.
> Small improvements to Readme

- tools/ansible-runner/Dockerfile
- Includes aws-iam-authenticator binary in ansible-runner to support litmus job execution on eks 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #297 
> refactor(dockerfile): include aws-iam-authenticator tool in ansible-runner 

- apps/redis/deployers/redis_statefulset.yml
- apps/redis/deployers/run_litmus_test.yml
- apps/redis/deployers/test.yml
- apps/redis/deployers/test_vars.yml
- Includes redis statefulset application deployment litmusbook.
@giri @dargasudarshan @ksatchit @nsathyaseelan
> Included litmusbook redis application statefulset deployers

- apps/fio/tests/data-integrity/run_litmus_test.yml
- k8s/eks/k8s-installer/create-eks-cluster.yml
- k8s/eks/k8s-installer/vars.yml
Added the node type variable in eks cluster create playbook
@yudaykiran please review this PR
> Added the Node type in variable for eks cluster create playbook

- apps/fio/tests/data-integrity/run_litmus_test.yml
Included the openebs/logger task in run litmus job
@yudaykiran can you please review this PR
> Included Logger task in litmus book

- apps/jenkins/upgrade/test.yml
Signed-off-by: Skchoudhary <choudharysaab786@gmail.com>
(cherry picked from commit 2c68fb10e16a6f4b3c291cb5b480926aac185105)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #260 
> add code to append runid to testname #260

- apps/memleak/tests/memleak.yml
- apps/memleak/tests/run_litmus_test.yml
- apps/memleak/tests/test-mem.py
- apps/memleak/tests/test.yml
- apps/memleak/tests/test_vars.yml
- This PR includes Litmus book to run memory utilization test on OpenEBS volume.
- Perform this test by obtaining memory consumed by longhorn process from the controller pod.
- A watermark of 800MB (re-calibrated based on results observed from latest sanity run) profile chosen in this test.
> Litmus book to run memory utilization test on OpenEBS volume

- CONTRIBUTING.md
> remove dots

- pkg/verify/verify.go
Signed-off-by: Prabhu Jayakumar <j.prabhu91@gmail.com>
**What this PR does / why we need it**: Fixes compile failures
**Which issue this PR fixes** : fixes #320
> Fix compile error

- apps/percona/tests/mysql_data_persistence/test.yml
- apps/percona/tests/mysql_data_persistence/test_cleanup.yml
- Update pumba sigkill chaoslib tasks with new variables in mysql data persistence litmus book
> refactor(yaml): Update pumba sigkill chaoslib tasks with new variables in mysql data persistence litmus book

- k8s/utils/health/test_health.py
**This PR is to write unit tests for health checks**:
**This PR fixes** : fixes #205
**This is my first pull request, kindly let me know the comments**:
> Unit tests for health checks

- pkg/exec/exec_test.go
Issue https://github.com/openebs/litmus/issues/298
@satyamz  @princerachit @Akash4927 
Signed-off-by: Kaustumbh <kaustumbhjaiswal11@gmail.com>
> Generated unit test for function NewShellExec

- k8s/gke/k8s-installer/create-gke-cluster.yml
- k8s/gke/k8s-installer/vars.yml
Adds autoscaling to the GKE cluster creation logic.
> feat(gke): Add autoscaling to the GKE cluster creation logic.

- docs/litmus_deep_dive.md
**What this PR does / why we need it**: For Better Understanding of the Documentation 
Signed-off-by: Shyam Jalan shyamjalan.bitmesra@gmail.com
> The use of 'a' looks inappropriate

- README.md
> Updated README.md to correct a few capitalization errors

- apps/cassandra/deployers/test.yml
- apps/cassandra/functional/scale_replicas/test.yml
- apps/cassandra/workload/test.yml
- apps/cockroachdb/deployers/test.yml
- apps/cockroachdb/workload/test.yml
- apps/crunchy-postgres/deployers/test.yml
- apps/crunchy-postgres/workload/test.yml
- apps/fio/tests/data-integrity/test.yml
- apps/jenkins/deployers/test.yml
- apps/jenkins/upgrade/test.yml
- apps/jupyter/deployers/test.yml
- apps/memleak/tests/test.yml
- apps/mongodb/deployers/test.yml
- apps/mongodb/workload/test.yml
- apps/percona/chaos/openebs_replica_network_delay/test.yml
- apps/percona/chaos/openebs_target_failure/test.yml
- apps/percona/chaos/openebs_target_network_delay/test.yml
- apps/percona/chaos/openebs_volume_replica_failure/test.yml
- apps/percona/deployers/test.yml
- apps/percona/functional/snapshot/test.yml
- apps/percona/workload/test.yml
- apps/redis/deployers/test.yml
- common/utils/update_litmus_result_resource.yml
- tools/ansible-runner/Dockerfile
Signed-off-by: Prabhu Jayakumar <j.prabhu91@gmail.com>
**What this PR does / why we need it**: Refactoring: remove duplicate code in tests
**Which issue this PR fixes** : fixes #318
> Use the litmus result CR update util on all the litmusbooks

- providers/openebs/installers/storageclass/0.7/ansible/storageclass-cstor.j2
- providers/openebs/installers/storageclass/0.7/ansible/storageclass-jiva.j2
- providers/openebs/installers/storageclass/0.7/ansible/vars.yaml
- providers/openebs/installers/storageclass/0.7/litmusbook/storageclass_cleanup.yaml
- providers/openebs/installers/storageclass/0.7/litmusbook/storageclass_setup.yaml
- This PR will updated the custom storage-class setup litmus book 
- Modified the storage class jinja templates
@ksatchit @dargasudarshan @gprasath can you please review this PR
> refactor(yaml):Updated custom storage class and storage pool creation litmus book

- apps/crunchy-postgres/deployers/run_litmus_test.yml
- apps/crunchy-postgres/liveness/run_litmus_test.yml
- apps/crunchy-postgres/liveness/test.yml
- apps/crunchy-postgres/liveness/test_vars.yml
- Include litmus job for performing liveness check of crunchy postgres application.
- Liveness is performed by checking the end point of the application service.
> feat(yaml): Liveness litmus job for crunchy-postgres

- apps/percona/deployers/run_litmus_test.yml
- Update percona deployer to use openebs-standard sc by default
> refactor(yaml) Update percona deployer to use openebs-standard sc by default

- apps/mongodb/liveness/run_litmus_test.yml
- apps/mongodb/liveness/test.yml
- apps/mongodb/liveness/test_vars.yml
- Include litmus book to perform liveness check of mongodb deployment.
> feat (yaml): Litmus job for mongodb liveness check

- common/utils/deprovision_deployment.yml
- common/utils/deprovision_statefulset.yml
- Implemented task files that can deprovision both deployment and statefulset applications and its underlying resources.
- This utility file has to be included where we are about to delete the application.
> Adding utils to delete deployment and statefulsets

- apps/fio/tests/data-integrity/run_litmus_test.yml
- Removed logger scripts from litmus job
@ksatchit can you please review this PR
> refactor(yaml) Modified litmus job for data integrity on jiva

- apps/cassandra/deployers/run_litmus_test.yml
- apps/cassandra/deployers/test.yml
- apps/cassandra/deployers/test_vars.yml
- apps/crunchy-postgres/deployers/run_litmus_test.yml
- apps/crunchy-postgres/deployers/test.yml
- apps/crunchy-postgres/deployers/test_vars.yml
- apps/jenkins/deployers/run_litmus_test.yml
- apps/jenkins/deployers/test.yml
- apps/jenkins/deployers/test_vars.yml
- apps/mongodb/deployers/run_litmus_test.yml
- apps/mongodb/deployers/test.yml
- apps/mongodb/deployers/test_vars.yml
- apps/prometheus/deployers/run_litmus_test.yml
- apps/prometheus/deployers/test.yml
- apps/prometheus/deployers/test_vars.yml
- common/utils/deprovision_deployment.yml
- common/utils/deprovision_statefulset.yml
- Include litmus job to perform stateful apps de-provisioning.
- Verify if all the resources are cleared post de-provisioning.
> feat(yaml) Include litmus job to perform stateful apps de-provisioning.

- apps/prometheus/functional/memcheck/test-mem.py
- Fix invalid literal error in python memcheck script
> Fix invalid literal error in python memcheck script

- apps/prometheus/functional/memcheck/test-mem.py
- Enhance the memory consumption python script to get the cstor-istgt pid dynamically.
>  Fetch istgt process id dynamically  

- apps/percona/functional/k8s_snapshot/test.yml
- apps/percona/functional/k8s_snapshot/test_vars.yml
- Making snapshot/clone creation case applicable for cstor volume providing PVC name as input.
- Obtaining the storage class used from PVC spec.
- Obtaining the storage engine from volume spec and spc from the storage class spec.
- Checking if the snapshots are created using zfs list command based on the storage engine.
> Snapshot & clone creation test on cStor volume.

- apps/cassandra/deployers/run_litmus_test.yml
- apps/crunchy-postgres/deployers/run_litmus_test.yml
- apps/jenkins/deployers/run_litmus_test.yml
- apps/mongodb/deployers/run_litmus_test.yml
- apps/percona/deployers/run_litmus_test.yml
- apps/prometheus/deployers/run_litmus_test.yml
- Update deployer litmus job action ENV with default value
> refactor(yaml): Update deployer litmus job action ENV with default value

- common/utils/deprovision_deployment.yml
- common/utils/deprovision_statefulset.yml
- Removed the condition that checks if all the resources in the namespace are removed.
- Added the condition that checks if the PVC is deleted upon app deletion.
> Checking if the corresponding PVC is deleted upon deleting deployment

- apps/crunchy-postgres/deployers/test.yml
- common/utils/deprovision_statefulset.yml
- Changed variable name in deprovisioning utility.It was conflicting with a variable in LR utility. The problem occurs when we use both the utils in the same playbook.
- Fixed indentation error in postgres deployer.
> Updated a variable name in deprovision utility.

- k8s/aws/ebs-volumes/create-ebs-volume.yml
- k8s/aws/ebs-volumes/delete-ebs-volume.yml
- k8s/aws/ebs-volumes/vars.yml
- k8s/gcp/gpd-disks/create-gpd.yml
- k8s/gcp/gpd-disks/delete-gpd.yml
- k8s/gcp/gpd-disks/vars.yml
- Update the AWS and GPD disk attach playbooks to format/mount conditionally based on a var.
- Disks will be formatted & mounted/unmounted only upon `disk_attach: format` extra_var
> (refactor)(yaml): update the disk attach playbooks to take disk actions

- k8s/aws/k8s-installer/create-aws-cluster.yml
- k8s/azure/k8s-installer/create-k8s-cluster.yml
- k8s/eks/k8s-installer/create-eks-cluster.yml
- k8s/gcp/k8s-installer/create-k8s-cluster.yml
- k8s/gke/k8s-installer/create-gke-cluster.yml
- k8s/packet/k8s-installer/create_packet_cluster.yml
- Included a fail module in rescue block of cluster creation playbooks
@ksatchit can you please review this PR
> refactor(yaml): Included a fail module in rescue block of cluster creation playbooks

- apps/percona/chaos/openebs_pool_network/run_litmus_test.yml
- apps/percona/chaos/openebs_pool_network/test.yml
- apps/percona/chaos/openebs_pool_network/test_vars.yml
- chaoslib/openebs/cstor_pool_network.yml
This PR is to add litmus job to induce incoming network packet loss in randomly selected replica.
> network(chaos): adding network ingress network loss on replica 

- apps/percona/deployers/test.yml
- apps/percona/workload/test.yml
- common/utils/check_db_connection.yml
- common/utils/deprovision_deployment.yml
- Deployer jobs take longer to complete due to higher wait periods b/w status checks. This PR reduces the wait and increases retry count while maintaining overall timeouts.
> (refactor)(yaml): decrease the delay period & increase retry count in pod status and init checks 

- k8s/aws/ebs-volumes/README.md
- k8s/aws/k8s-installer/README.md
- k8s/aws/k8s-installer/create-aws-cluster.yml
- k8s/aws/k8s-installer/delete-pre-requisite.yml
- k8s/aws/k8s-installer/pre-requisite.yml
- k8s/aws/k8s-installer/vars.yml
- Modify `available_zone` variable to `zone`
- Provide Example in Readme file for specify cluster_name  at the time of EBS volume creation and cluster creation
> (refactor): Modify available_zone variable to zone

- k8s/packet/k8s-installer/create_packet_cluster.yml
Included a task to install xfs binaries in packet cluster nodes
https://gitlab.openebs.ci/openebs/e2e-packet/pipelines/5007
@yudaykiran @ksatchit @chandankumar4 can you please review this PR
> refactor(yaml): Included a task to install XFS binaries in workers nodes es of Packet

- common/utils/create_ns.yml
- Sometimes, there are requirements to deploy apps into existing namespaces. This PR allows the same
by implementing a check.
- In case of multiple deployment of *same* applications into a given namespace, **ensure that the application PVC name & application label are modified in the litmus book (job)**
> (refactor)(yaml): create ns only if not present in app deploy litmusbooks 

- chaoslib/openebs/cstor_verify_pool_provisioning.yml
- common/utils/mysql_data_persistence.yml
This PR reduces the time taken during the LOAD action of mysql.
Also, changed the checks for verifying the pool provision.
> fix(load): reducing time taken for load time

- chaoslib/openebs/cstor_pool_delete.yml
- Temporarily reduce failure attempts 
- Future PRs to obtain a neater way to make chaos iterative
> (refactor)(yaml): reduce pool failure attempts in cstor pool delete playbook

- k8s/gke/k8s-installer/create-gke-cluster.yml
- k8s/gke/k8s-installer/vars.yml
- Added more regions to randomize the cluster creation process.
- Increased the default node size from n1-standard-2 to n1-standard-4
> perf<yaml>:Add more regions and increase node size.

- k8s/gke/k8s-installer/create-gke-cluster.yml
- k8s/gke/k8s-installer/delete-gke-cluster.yml
- Use set_zone throughout the tasks.
- Persist and load the zone from a file.
> Fix the zone variable issue in other tasks.

- funclib/openebs/access-mode-check.yml
Update 'volume info' command to 'volume describe' 
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
> fix(litmus-util) update volume info to describe

- apps/percona/chaos/drain_node/test.yml
- apps/percona/chaos/taint_node/test.yml
-  Append uniq string for dbname creation/verification tasks for data persistence check util.
> refactor(yaml) : Append uniq string for dbname creation/verification tasks for data persistence util

- k8s/eks/k8s-installer/create-eks-cluster.yml
- k8s/eks/k8s-installer/delete-eks-cluster.yml
- k8s/eks/k8s-installer/vars.yml
- Have refactored the code to select the region randomly.
- Helps resolve the VPC limit reached error to some extent.
Dependent PR: https://github.com/openebs/e2e-eks/pull/8
> perf<playbook>: Add ability to select random region for cluster creation

- k8s/gke/k8s-installer/delete-gke-cluster.yml
- The set_zone has to be declared in the vars, before being used in the task.
> fix<playbook>: Add the missing set_zone variable to the vars.

- apps/percona/chaos/openebs_pool_failure/test.yml
- apps/percona/chaos/openebs_pool_failure/test_vars.yml
- chaoslib/openebs/cstor_pool_delete.yml
- chaoslib/openebs/cstor_pool_health_check.yml
Performs following checks on all pools corresponding to a CVR
- Add check to perform a log-parse of cstor pool to identify errors
- Check for container restarts on cstor pool containers
- Sometimes, the application may not restart upon single pool failure/corruption. A better test indicator is to analyze pool status
> (feat)(yaml): include a cstor pool health check util

- providers/openebs/installers/storageclass/0.7/ansible/storageclass_setup.yaml
- providers/openebs/installers/storageclass/0.7/ansible/templates/cstor-xfs.j2
- providers/openebs/installers/storageclass/0.7/ansible/vars.yaml
- Update setup storage class litmus book to create cstor xfs storage class
> refactor(yaml): Update setup storage class litmus book to create cstor xfs storage class

- apps/percona/chaos/openebs_app_svc_chaos/run_litmus_test.yml
- apps/percona/chaos/openebs_app_svc_chaos/test.yml
- apps/percona/chaos/openebs_app_svc_chaos/test_vars.yml
- chaoslib/service_chaos/aws-docker.yml
- chaoslib/service_chaos/svc_chaos.yml
- chaoslib/service_chaos/svc_chaos_kube.yml
- Update service chaos util to include tasks to perform docker crash on AWS
- Invokes the platform specific util based on job ENV 'PLATFORM' 
- Verifies the AUT post chaos.
> refactor(yaml) : Update service chaos util to include tasks to perform docker crash on AWS

- chaoslib/service_chaos/aws-service.yml
- chaoslib/service_chaos/svc_chaos.yml
- Include litmus util to stop kubelet service on AWS
- Done Testing
> refactor(yaml) : Include litmus util to stop kubelet service on AWS

- .travis.yml
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
> fix(build): bump Go version to 1.11.2

- apps/custom/tests/memcheck/test-mem.py
Fix typo in the memleak python script file
> Fix typo in memleak python script

- common/utils/openebs/target_affinity_check.yml
- Add labels to identify controller/target pods 
> (fix)(yaml): add labels to identify target node

- common/utils/openebs/target_affinity_check.yml
- Use jsonpath filter with persistent-volume label to derive target node 
> (fix)(yaml): update task to derive node from target pod in affinity util

- apps/fio/tests/data-integrity/run_litmus_test.yml
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
Intendation correction in data_integrity/run_litmus_test.yml)
> Intendation correction in data_integrity yml(run_litmus_test.yml)

- apps/nuodb/deployers/test_vars.yml
> refactor(yaml) : Fix nuodb te label

- apps/nuodb/deployers/nuodb-sm.yaml
- apps/nuodb/deployers/nuodb-te.yaml
- apps/nuodb/deployers/test.yml
- Reduced CPU limit for nuo-db deployers
> Reduced cpu limit for nuo db deployers

- k8s/gke/k8s-installer/vars.yml
- Removed us-east1-a zone in vars and add us-east1-b zone
> refactor(yaml):Changed the gke cluster creation zone in vars

- apps/jenkins/deployers/test_vars.yml
- apps/mongodb/deployers/test_vars.yml
- apps/prometheus/deployers/test_vars.yml
- common/utils/deprovision_deployment.yml
- common/utils/deprovision_statefulset.yml
- Included operator namespace in test_vars
- modified deprovision statefulset and deployment utils
> Modified deprovision of deployment and statefulset application utils

- apps/nuodb/deployers/nuodb-ycsb.yaml
- apps/percona/functional/k8s_snapshot/test_vars.yml
- Modified nuodb ycsb yaml and snapshot clone test vars
> Modified nuodb ycsb yaml and snapshot clone test vars

- apps/percona/functional/k8s_snapshot/test_vars.yml
- common/utils/deprovision_statefulset.yml
- Included storage class variable in k8s-snapshot-clone playbook
- removed debug task in deprovisioning statefulset util
> Included storage class variable in snapshot clone playbook

- apps/nuodb/deployers/nuodb.yaml
- apps/nuodb/deployers/test.yml
- Update nuodb insights manager storage class
> refactor(yaml) : Update nuodb insights manager storage class

- apps/nuodb/deployers/nuodb-sm.yaml
- apps/nuodb/deployers/nuodb-te.yaml
- apps/nuodb/deployers/nuodb.yaml
- apps/nuodb/deployers/test.yml
- Update nuodb storage manager and admin pods sc
> refactor(yaml): Update nuodb storage manager and admin pods sc

- apps/fio/tests/performance/test.yml
**What this PR does / why we need it**
This PR updates the name of the file in the included task.
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
> Updating name of the file in include task

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Included a task to replace openebs operator analytics value in ansible playbook
> refactor(yaml): Included a task to replace the openebs analytics value

- apps/fio/tests/data-integrity/fio-read.yml
- apps/fio/tests/data-integrity/fio-write.yml
- apps/fio/tests/data-integrity/pvc.yml
- apps/fio/tests/data-integrity/run_litmus_test.yml
- apps/fio/tests/data-integrity/test.yml
- apps/fio/tests/data-integrity/test_vars.yml
- Modified data integrity playbook for jiva and cstor
- replaced and removed task as part of the new fio image.
> Modified data integrity litmus book for jiva and cstor

- k8s/eks/k8s-installer/delete-eks-cluster.yml
- Included a failed debug task if the cluster creation is failed
> Modified cluster deletion playbook for eks platform

- apps/prometheus/deployers/prometheus.yml
-  Included pod affinity annotation for prometheus deployment spec
>  Included pod affinity annotation for prometheus deployment spec

- apps/mongodb/deployers/mongo_statefulset.yml
- apps/percona/chaos/node_freeze/run_litmus_test.yml
- Included pod affinity annotations for mongo statefulset spec
- fix typo in node freeze run litmus test yaml
> Included pod affinity annotations for mongo statefulset spec

- apps/fio/tests/data-integrity/fio-write.yml
- Modified hte data integrity fio write profile
> refactor(yaml): Modified data integrity fio write profie 

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
* For getting the number of worker nodes grep command needs change.
**reviewers**:
@dargasudarshan @gprasath
> Refactor openebs setup task to get the node

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Include a task to replace Node Disk manager image in setup openebs ansible playbook
> Include a task to replace ndm image in openebs setup playbook

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
1) Getting the node count with the condition (openebs_infra_chaos) to check the condition equals to  NDM counts.
> Added openebs_infra_chaos as environment variable to get the node count.

- apps/busybox/tests/pvc_creation/busybox.yml
- apps/busybox/tests/pvc_creation/main.yml
- apps/busybox/tests/pvc_creation/pvc_provision.yaml
- apps/busybox/tests/pvc_creation/run_litmus_test.yml
- apps/busybox/tests/pvc_creation/test.yml
- apps/busybox/tests/pvc_creation/test_vars.yml
1) This Litmusbook will deploy multiple busybox application with multiple pvc's.
2) Multiple namespaces are also created for each and every busybox app and its related PVC.
3) The feature of creation and deletion is provided as a controlled environment variable as a part of an efficient cleanup task.
@dargasudarshan @gprasath @nsathyaseelan  @shashank855 
note: Here using on 5 application and PVC for convenience during the development of the code.
cluster output
```NAMESPACE     NAME                                                               READY     STATUS      RESTARTS   AGE
busybox-0     app-busybox-ccdcb4bcd-5wr5k …
```
> Litmusbook to create multiple pvc's with busybox deployment

- apps/busybox/pvc_creation_deletion/busybox.yml
- apps/busybox/pvc_creation_deletion/pvc_provision.yaml
- apps/busybox/pvc_creation_deletion/run_litmus_test.yml
- apps/busybox/pvc_creation_deletion/test.yml
- apps/busybox/pvc_creation_deletion/test_vars.yml
- Included conditions in deletion section of playbook that validated the deletion of application and pvc.
- Changed the test name.
> refactor(yaml): Validating the deletion in bulk pvc deletion litmusbook

- apps/percona/tests/mysql_storage_benchmark/mysql.yml
- fix(test): mysql storage benchmark custom percona image
> fix(test): mysql storage benchmark custom percona image

- k8s/packet/k8s-installer/pre_requisite.sh
- Modified the docker installation steps in prerequisites shell script for packet cluster
> Modified docker version for packer cluster

- apps/busybox/deployers/busybox_deployment.yml
- apps/busybox/deployers/busybox_statefulset.yml
- apps/busybox/deployers/run_litmus_test.yml
- apps/busybox/deployers/test.yml
- apps/busybox/deployers/test_vars.yml
- Litmus book for Busybox application stateful set and deployment.
- By changing the env deploy type in run litmus test yaml will be able to deploy statefulset and deployment of busybox application
Deployment logs:
[deploy_app.log](https://github.com/openebs/litmus/files/2960294/deploy_app.log)
[deprovision_app.log](https://github.com/openebs/litmus/files/2960295/deprovision_app.log)
Statefulset logs
[deprovision_sts.log](https://github.com/openebs/litmus/files/2960298/deprovision_sts.log)
[sts_deploy.log](https://github.com/openebs/litmus/files/2960299/sts_deploy.log)
> feat[litmus]: Litmus Book for busybox statefulset and deployment

- providers/cstor-storage-policies/cstor-volume-monitor-sc.j2
- providers/cstor-storage-policies/cstor-xfs-sc.j2
- providers/cstor-storage-policies/run_litmus_test.yml
- providers/cstor-storage-policies/test.yml
- providers/cstor-storage-policies/test_vars.yml
- tools/ansible-runner/Dockerfile
- Litmus  book for creating storage class for various cstor storage policies
- In this litmus book it creates two storage classes
1. storage class using xfs filesystem
2. storage class using volume monitor policy
[sc-create.log](https://github.com/openebs/litmus/files/2961518/sc-create.log)
[sc-delete.log](https://github.com/openebs/litmus/files/2961519/sc-delete.log)
> feat[litmus]: Included litmus book to create storage class with storage policy

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Updated the openebs operator setup llitmus book to check the pool pod status using maxpool count
> refactor(yaml): Included a task to check the pool pod status in operator setup litmus book

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
> refactor(yaml): Modified the pool pod status check task

- providers/cstor-storage-policies/run_litmus_test.yml
- Fixed the typo in cstor storage policy litmusbook
> Fix typo in cstor storage policy litmusbook

- providers/cstor/cstor-disk-pool/test.yml
- Included task to check status of disk pool pods
> Included task to check status of disk pool pods

- providers/cstor/cstor-disk-pool/test.yml
- Modified cstor disk pool create litmus book to check the pool pod status
```
2019-03-19T05:12:29.789307 (delta: 0.059986)         elapsed: 0.059986 ******** 
2019-03-19T05:12:29.805170 (delta: 0.015812) …
```
> Modified cstor disk pool create litmus book to check the pool pod status

- apps/busybox/deployers/test_vars.yml
- Modified test name in test vars of busybox deployer util
> Changed the test name for busy-box deploy litmusbook

- providers/cstor-storage-policies/cstor-disk-standalone.j2
- providers/cstor-storage-policies/test.yml
- providers/cstor-storage-policies/test_vars.yml
- Included replica count storage policy in openebs storage policies litmusbook
> Included replica count storage policy in openebs storage policies litmusbook

- apps/percona/functional/snapshot_rebuild/snap_rebuild_multiple_rep/run_litmus_test.yml
- apps/percona/functional/snapshot_rebuild/snap_rebuild_multiple_rep/test_vars.yml
- apps/percona/functional/snapshot_rebuild/snap_rebuild_single_rep/run_litmus_test.yml
- apps/percona/functional/snapshot_rebuild/snap_rebuild_single_rep/test_vars.yml
- Passing snapshot name as env in snapshot rebuild litmusbook
> Passing snapshot name as env in snapshot rebuild litmusbook

- apps/busybox/deployers/busybox_deployment.yml
- apps/percona/chaos/openebs_pool_failure/test.yml
- apps/percona/chaos/openebs_target_failure/chaosutil.j2
- Included target affinity label inapplication deployment 
- Modified cstor pool failure litmusbook
- update target failure chaos util jinja template
> Modified busybox deployment and target failure util

- apps/nuodb/deployers/OpenShift/test.yml
- Include Nuodb version env in deployment litmus book
> refactor(yaml): Include Nuodb version env in deployment litmus book

- apps/prometheus/functional/memcheck/test-mem.py
- apps/prometheus/functional/memcheck/test.yml
**What this PR does / why we need it**: This PR improves the pylint score of test-mem.py script
> refactor(pylint): refactor test-mem.py to boost up pylint score

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Removed the task to check the status of default sparse pool pod
- Included task to check the admission server in openebs deploy litmusbook
> Included the task to check the status of admission server in openebs deploy litmus book

- chaoslib/openebs/cstor_kill_and_verify_pool.yml
> Modified the task to check the container status of pool pod

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Enabled the default cstor pool in openebs operator.
> refactor[Yaml]: Included a task to enable the default cstor pool

- apps/prometheus/functional/memcheck/test.yml
- Updated arguments in memcheck litmusbook
> refactor[yaml]: Updated arguments in memcheck litmusbook

- apps/datastax/chaos/dse_pod_failure/run_litmus_test.yml
- apps/datastax/chaos/dse_pod_failure/test.yml
- apps/datastax/chaos/dse_pod_failure/test_vars.yml
- Included the litmusbook to induce chaos at DSE application pod.
- Utilising the pumba util to induce chaos.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #531 
> feat(litmus):Implement DSE application component failure litmusbook using pumba

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Removed the task to check the status of the admission server as the feature is not in 0.8.2
> Removed the task to check the admission server status

- providers/cstor-storage-policies/jiva-standalone.yml
- providers/cstor-storage-policies/test.yml
- providers/cstor-storage-policies/test_vars.yml
- Included single replica storage class policy for jiva.
> feat[yaml]: Included single replica storage class policy for jiva

- apps/nuodb/deployers/OpenShift/nuodb.yaml
- Changed the application label in nuodb application spec file.
> refactor[yaml]: Modified the label in nuobd deployer spec

- experiments/chaos/openebs_node_service_failure/chaosutil.j2
- experiments/chaos/openebs_node_service_failure/run_litmus_test.yml
- experiments/chaos/openebs_node_service_failure/test.yml
- experiments/chaos/openebs_node_service_failure/test_prerequisites.yml
- experiments/chaos/openebs_node_service_failure/test_vars.yml
- experiments/chaos/openebs_pool_failure/run_litmus_test.yml
- experiments/chaos/openebs_pool_failure/test.yml
- experiments/chaos/openebs_pool_failure/test_vars.yml
- experiments/chaos/openebs_target_failure/chaosutil.j2
- experiments/chaos/openebs_target_failure/run_litmus_test.yml
- experiments/chaos/openebs_target_failure/test.yml
- experiments/chaos/openebs_target_failure/test_prerequisites.yml
- experiments/chaos/openebs_target_failure/test_vars.yml
- experiments/chaos/openebs_target_network_delay/chaosutil.j2
- experiments/chaos/openebs_target_network_delay/run_litmus_test.yml
- experiments/chaos/openebs_target_network_delay/test.yml
- experiments/chaos/openebs_target_network_delay/test_prerequisites.yml
- experiments/chaos/openebs_target_network_delay/test_vars.yml
- Moved chaos tests into experiments directory to make it generic across applications.
> Moving chaos tests into experiments directory

- chaoslib/pumba/pod_failure_by_sigkill.yaml
- Added a comment to do for pumba pod failure util
> Added a comment to do for pumba pod failure util

- chaoslib/pumba/pod_failure_by_sigkill.yaml
Signed-off-by: nsathyaseelan sathyaseelan.n@mayadata.io
- Updated the retry count to check the status of pumba daemonset
> refactor(yaml):Updated the retry count to check the status of pumba daemonset

- apps/percona/functional/k8s_snapshot/run_litmus_test.yml
- Included snapshot name as an ENV in snapshot clone litmus test
> refactor(yaml): Included snapshot name as an ENV in snapshot clone litmus test

- apps/fio/tests/data-integrity/run_litmus_test.yml
- apps/prometheus/functional/memcheck/run_litmus_test.yml
- Removed Logger container from cstor memcheck and fio data integrity litmus test.
> refactor(yaml): Remove Logger container in litmus pod

- apps/percona/functional/k8s_snapshot/run_litmus_test.yml
- apps/percona/functional/k8s_snapshot/test_vars.yml
- Included snapshot name as an ENV in k8s snapshot litmusbook
> refactor(yaml): Included snapshot name as an ENV in k8s snapshot litmusbook

- apps/prometheus/deployers/prometheus.yml
[Refactor] Added label in configmap of prometheus.yml
> [Refactor] Added label in configmap of prometheus.yml

- apps/percona/functional/k8s_snapshot/test_vars.yml
- chaoslib/openebs/cstor_kill_and_verify_pool.yml
- providers/cstor/cstor-disk-pool/test.yml
- Included clone claim name for snapshot test_vars
-Modified the task to check the container status for cstor pool pod.
> refactor(yaml): Fix for obtaining the cstor pool pod container status

- apps/redis/workload/redis_loadgen.yml
- apps/redis/workload/run_litmus_test.yml
- apps/redis/workload/test.yml
- apps/redis/workload/test_vars.yml
…
1) This PR contains Litmus book for redis-sts workload.
2) Generate workload for redis statefulset using Yahoo! Cloud Serving Benchmark (YCSB).
**YCSB is helpful in retrieving the capability of computer programs.**
**Special notes for your reviewer**: 
This PR will also contain its related workload generation tool i.e YCSB which is going to be added in https://github.com/openebs/test-tools repository.
> [WIP] Litmus book for Redis-sts workload using Yahoo! Cloud Serving Benchmark (YCSB)

- apps/percona/chaos/openebs_target_network_loss/README.md
- Introduce a README template for Litmusbook to help developers & users
> (feat)(doc) sample readme for litmusbook

- funclib/kubectl/k8s_snapshot_clone/clone_during_rebuild.yml
- funclib/kubectl/k8s_snapshot_clone/clone_post_rebuild.yml
- funclib/kubectl/k8s_snapshot_clone/clone_pre_rebuild.yml
- Modified clone rebuild utils to pass the app PVC name as the variable for creating clone util
> refactor(util): Modified clone rebuild utils

- contribute/design/litmus-design-proposal.md
This PR is intended to cover the requirements and design of Litmus.  The design is placed in the google doc mentioned below and is open for review & comments.
Refer: https://docs.google.com/document/d/1EmHlk8TZM6B2os8nQx87DPkqHvPMKuTx1ycUQ14mBAI/edit?usp=sharing
Note : The repo already contains an initial implementation of this design with sample tests & directory structure
Signed-off-by: ksatchit <karthik.s@cloudbyte.com>
> Design proposal for Litmus 

- Makefile
- tools/ansible-runner/Dockerfile
- Keeping only ansible-runner and ansible syntax-checker in Makefile.
> refactor(cleanup):Removing go dependency checks in Makefile

- providers/cstor-storage-policies/test.yml
- providers/cstor/cstor-disk-pool/test.yml
- providers/openebs/installers/openebs_helm/test.yml
- Update re-segregated utils path in litmus providers
> refactor(yaml): Update re-segregated utils path in litmus providers

- apps/busybox/deployers/test.yml
- apps/busybox/liveness/test.yml
- apps/cassandra/deployers/test.yml
- apps/cassandra/liveness/test.yml
- apps/cassandra/workload/test.yml
- apps/cockroachdb/deployers/test.yml
- apps/cockroachdb/workload/test.yml
- apps/couchbase/deployers/test.yml
- apps/crunchy-postgres/deployers/test.yml
- apps/crunchy-postgres/liveness/test.yml
- apps/crunchy-postgres/workload/test.yml
- apps/datastax/chaos/dse_pod_failure/test.yml
- apps/datastax/deployers/test.yml
- apps/elasticsearch/deployers/test.yml
- apps/elasticsearch/workload/test.yml
- apps/jenkins/deployers/test.yml
- apps/jenkins/liveness/test.yml
- apps/mongodb/deployers/test.yml
- apps/mongodb/liveness/test.yml
- apps/mongodb/workload/test.yml
- apps/nuodb/chaos/app_pod_failure/test.yml
- apps/nuodb/deployers/OpenShift/test.yml
- apps/nuodb/deployers/test.yml
- apps/percona/deployers/test.yml
- apps/percona/functional/snapshot/test.yml
- apps/percona/liveness/test.yml
- apps/percona/workload/test.yml
- apps/prometheus/deployers/test.yml
- apps/redis/deployers/test.yml
- apps/redis/workload/test.yml
- Changed the common/utils path reference in deployer litmusbook
> refactor(yaml): Changed the common/utils path reference in deployer litmusbook

- providers/openebs/installers/operator/master/litmusbook/openebs_cleanup.yaml
- providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
- Updating playbooks paths in providers litmusbook
> refactor(yaml):Updating playbooks paths in providers litmusbook

- utils/k8s/pre_create_app_deploy.yml
- fix the fetch_replica_values utils path issue
> fix(yaml): fix the fetch_replica_values utils path issue

- utils/k8s/deploy_single_app.yml
- fix utils/scm/openebs/check_replica_count.yml path issue
> fix(path): fix utils/scm/openebs/check_replica_count.yml path issue

- providers/openebs/installers/storageclass/0.7/litmusbook/storageclass_cleanup.yaml
- providers/openebs/installers/storageclass/0.7/litmusbook/storageclass_setup.yaml
> fix(yaml):Updating path for storage classes playbook

- apps/percona/functional/k8s_snapshot/run_litmus_test.yml
- apps/percona/functional/k8s_snapshot/test.yml
- apps/percona/functional/k8s_snapshot/test_vars.yml
- Modified snapshot clone creation litmusbook to get the capacity from env
> refactor(script): Modified snapshot clone litmus book for percona

- providers/cstor/cstor-disk-pool/run_litmus_test.yml
> Accomodated variable in quotes

- experiments/chaos/app_pod_failure/run_litmus_test.yml
> Removing logger container in app pod failure litmusbook

- experiments/functional/app-target-affinity/README.md
- experiments/functional/clone-creation/README.md
- experiments/functional/clone-snapshot-rebuild/README.md
- experiments/functional/memcheck/README.md
- experiments/functional/restrict-parent-volume-deletion/README.md
- experiments/functional/scale_app_replica/README.md
- experiments/functional/scale_jiva_replica/README.md
- experiments/functional/snapshot-creation/README.md
- experiments/functional/sts-volume-distribution/README.md
- Created readme files for functional experiments and described the procedure.
> Including readme for functional experiments

- README.md
- Refactors the Litmus README with updated information
- A GIF(?)  of the app_pod_failure litmus experiment referred to it the README will be included in a subsequent PR.
> (refactor)readme: update litmus readme with recent developments

- apps/busybox/deployers/test.yml
- tools/ansible-runner/Dockerfile
- tools/plugins/actionable.py
- tools/plugins/timestamp.py
- Python script for custom plugins that can be integrated into Ansible.
> Included python scripts for custom ansible plugins

- experiments/chaos/replica_node_affinity/test.yml
- Included a task to create test name in replica node affinity litmusbook
> refactor[yaml]: Included a task to create test name in replica node affinity litmusbook

- providers/cstor/cstor-block-device-pool/test.yml
> refactor[yaml]: Removed bdc reference tasks fro the litmusbook

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Included task to replace the ndm operator image in openebs operator yaml.
> refactor[litmusbook]: Included a task to replace the ndm operator image in setup openebs test

- providers/cstor/cstor-block-device-pool/spc.yml
- Modified the spc type in the spc spec file
> refactor[yaml]: Modified the type of spc name in the spec

- k8s/packet/k8s-installer/delete_packet_cluster.yml
- k8s/packet/k8s-installer/vars.yml
- Refactor packet-cleanup ansible playbook
> Refactor packet-cleanup ansible playbook

- chaoslib/openebs/cstor_verify_pool_provisioning.yml
- Changed the command to fetch the replica count value in pool delete chaos util
> feat[yaml]: Modified the task to fetch the replica count value in cstor pool delete chaos util

- apps/wordpress/deployers/README.md
- apps/wordpress/deployers/mysql.yml
- apps/wordpress/deployers/run_litmus_test.yml
- apps/wordpress/deployers/test.yml
- apps/wordpress/deployers/test_vars.yml
- apps/wordpress/deployers/wordpress.yml
- LitmusBook for Provision/deProvision the MySQL and WordPress application.
- Storage class, VolumeCapacity, PVC name are all modified in the deployment spec as the values given in run litmus test.
- Use the AccessMode as ReadWriteMany is want to deploy the application using NFS provisioner. Use the storage class that created using NFS provision.
```
[root@master-1554817485 nfs]# kubectl logs -f litmus-wordpress-deployment-cq6zq-ggsf7 -n litmus
[WARNING]: Found variable using reserved name: …
```
> feat[wordpress]: LitmusBook to deploy the Wordpress and MySQL application

- k8s/packet/packet-storage/vars.yml
- Modified the default location to attach the disks for a cluster
> refactor[litmusbook]: Changed the cluster location for litmusbook to attach disks

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- This PR is checking the default, sparse pool count, when it is enabled
> refactor[script]: Modified the litmusbook for openebs deploy to check the sparse pool pod status

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- This PR is modified the openebs setup litmusbook to get the maxpool count from SPC.
> refactor[yaml]: Modified openebs setup litmusbook to check the default cstor pool status

- providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- providers/openebs/installers/operator/master/ansible/vars.yaml
- This PR modifies the openebs deploy Litmusbook to Add the task to provision the cspc operator and checking the status of the cspc operator.
> Included a task to provision the cspc operator in openebs deploy

- providers/nfs-provisioner/test.yml
- included ignoring errors condition for deprovison of nfs
> refactor[yaml]: Modified nfs deprovision litmus book

- .github/PULL_REQUEST_TEMPLATE.md
> (refactor)github: update the PR template with a checklist

- utils/scm/applications/busybox/busybox_data_persistence.yml
- Currently busybox app doesn't have a data consistency check. CI pipelines using this need one
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #706 
- Takes a randomly generated filename & dd-based IO params such as blocksize & blockcount as params. 
- The flow is very similar to the mysql persistence check, with md5sum as the method to check consistency.
> (feat)busybox: add busybox consistency check util

- tools/ansible-runner/Dockerfile
> Modified ansible runner docker file to run the touch command in mnt directory

- ci/gitlab/templates/pod-delete/pod-failure-template.yml
> (refactor)templates: add result checks

- ci/gitlab/templates/pod-delete/pod-failure-template.yml
> Result checks

- ci/gitlab/templates/pod-delete/pod-failure-template.yml
> (refactor)gitlab: reduce job instantiation wait period

- experiments/functional/snapshot_deletion/jiva/snapshot_delete_verify_test.yml
Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>
**Checklist**
> Refactor litmusbook for jiva-snapshot-delete

- ci/gitlab/utils/result_check.sh
- experiments/chaos/kubernetes/pod_delete/run_litmus_test.yml
> (demo)gitlab: refactor chaos templates

- chaoslib/vmware_chaos/vm_power_operations.yml
- experiments/chaos/node_failure/README.md
- experiments/chaos/node_failure/chaosutil.j2
- experiments/chaos/node_failure/data_persistence.j2
- experiments/chaos/node_failure/run_litmus_test.yml
- experiments/chaos/node_failure/test.yml
- experiments/chaos/node_failure/test_vars.yml
- tools/ansible-runner/Dockerfile
- Litmusbook creates litmus job, a configmap(application details) and secret(holding vmware password).
- It includes an util which is capable to perform power operation on ESX server where the k8s hosts are created.
- Checks data persistence based on the details provided in configmap.
- At last, powering on the node after test completion.
- Included sshpass into ansible-runner image.
Currently, this experiment fails due to multi-attach error issue
**Checklist**
> feat(yaml):Inject node-failure chaos

- experiments/chaos/node_failure/run_litmus_test.yml
- litmus pod fails as the required secret is not found.
- secret was getting created in default namespace rather than creating in litmus namespace.
**Checklist**
> refactor(yaml):create secret in litmus namespace

- apps/cassandra/deployers/cassandra_statefulset.yml
1. Removed the annotations in cassandra_statefulset.yaml
-  volume.beta.kubernetes.io/storage-class:
2. Added a field storageClassName in spec of cassandra_statefulset.yaml
[cassandra_logs.txt](https://github.com/litmuschaos/litmus/files/3647113/cassandra_logs.txt)
**Checklist**
> refactor[yaml]: Added storageClassName field in cassandra_statefulset

- README.md
> Update Litmus ReadMe: Point to litmus docs for installation steps

- README.md
> Update the title of Litmus ReadMe

- Makefile
- hack/push
- MOdified the docker org name in Makefile.
**Checklist**
> refactor[Makefile]: Modified the docker organisation name in Makefile

- README.md
- executor/README.md
- executor/engine_env_getter.yml
- executor/executor.yml
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
**Checklist**
> Fetching of ChaosEngine Varibles, and overriding the default variables

- chaoslib/litmus/app_pod_random_delete.yaml
- executor/README.md
- executor/engine_env_getter.yml
- executor/executor.yml
- executor/experiment_configmap.yml
- executor/experiment_env_getter.yml
-  Refactor executor to add data persistence
**Checklist**
[logs-job-withoutconfigmap.txt](https://github.com/litmuschaos/litmus/files/3681174/logs-job-withoutconfigmap.txt)
[logs-executor-withoutconfigmap.txt](https://github.com/litmuschaos/litmus/files/3681175/logs-executor-withoutconfigmap.txt)
[logs-job-withconfigmap.txt](https://github.com/litmuschaos/litmus/files/3681226/logs-job-withconfigmap.txt)
[logs-executor-withconfigmap.txt](https://github.com/litmuschaos/litmus/files/3681227/logs-executor-withconfigmap.txt)
> refactor[executor]: add ability to mount experiment specific configmaps

- executor/executor.yml
- Removes step to replace litmus job spec with service account. Now executor uses the imperative command to run chaos
**Checklist**
> (fix)executor: remove step to update job spec with svc account

- chaoslib/litmus/pod_failure_by_litmus.yml
> (fix)experiment: update variable names

- README.md
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
**Checklist**
> Added demo link

- CONTRIBUTING.md
- contribute/design/litmus-design-proposal.md
- Removes the reference to OpenEBS project in the contribution guide
**Checklist**
> (refactor)contribution: Update the contribution guide

- executor/executor.yml
- executor/experiment_configmap.yml
- Patch chaosengine status
**Checklist**
[logs-executor.txt](https://github.com/litmuschaos/litmus/files/3707138/logs-executor.txt)
[engineCrAfterJobCompletion.txt](https://github.com/litmuschaos/litmus/files/3707139/engineCrAfterJobCompletion.txt)
> refactor[executor] to patch engine status

- README.md
Signed-off-by: Parikshit Hooda <phooda804@live.com>
Fixes typos in the README.md
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #836 
**Checklist**
> fix issue #836. Typo fixes - README.md

- experiments/generic/container_kill/README.md
- experiments/generic/pod_delete/README.md
- experiments/generic/pod_network_latency/README.md
- experiments/generic/pod_network_loss/README.md
- Adds dev docs (readme) to pod-failure experiments 
**Checklist**
> (refactor)readme: add experiment dev docs

- .travis.yml
Signed-off-by: Nikita Titov <nekit94-12@hotmail.com>
Refer to https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration.
> In the next phase of the migration, all builds will run on virtual-machine-based infrastructure – regardless of the configuration for `sudo` in the `.travis.yml`.
> Soon we will run all projects on the virtual-machine-based infrastructure, the sudo keyword will be fully deprecated.
**Checklist**
> (fix)Deprecated: Removed deprecated field in Travis config

- .travis.yml
- sonar-project.properties
- Adds sonarqube quality check
**Checklist**
> (chore)ci: add sonarqube quality check

- README.md
- Adds sonarqube quality-gate badge to README
**Checklist**
> (chore)badge: add sonarqube quality gate badge

- .travis.yml
- README.md
- experiments/generic/container_kill/README.md
- experiments/generic/pod_delete/README.md
- experiments/generic/pod_network_latency/README.md
- experiments/generic/pod_network_loss/README.md
- sonar-project.properties
Commits
36bcc1b9c7a180b0a919c2cb1409bf58e0b26767 b7bd06a7a2d262ce355f82ad4bbb1fe4a26d7ca9 164f201db71b03e992dab605d22e4590d1e15230 d5cbd8ee3fc774fe46b0d85c9029c7cfbca36682
**Checklist**
> Cherry picking 

- executor/README.md
- executor/executor.yml
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
https://github.com/litmuschaos/litmus/issues/857
**Checklist**
> [Feat.]Executor feature to delete jobs after completion

- contribute/developer_guide/README.md
- contribute/developer_guide/attributes.yaml.sample
- contribute/developer_guide/generate_chart.py
- contribute/developer_guide/templates/chartserviceversion.tmpl
- contribute/developer_guide/templates/experiment_ansible_logic.tmpl
- contribute/developer_guide/templates/experiment_ansible_prerequisites.tmpl
- contribute/developer_guide/templates/experiment_custom_resource.tmpl
- contribute/developer_guide/templates/experiment_k8s_job.tmpl
- This PR introduces a developer how-to guide, along with a script to help generate the artefacts that constitute a chaos-experiment/chart.
- The script `generate_chart`.py  creates the following, by taking experiment metadata as input in the form of a simple yaml file.
- Top-level/Experiment-level chartserviceversion.yaml
- Litmusbook, i.e., K8s job to execute the experiment
- Ansible playbook/auxiliary (pre-requisites) file to hold business logic
- Experiment custom resource
- The README explains the procedure to construct the experiment, test it & submit PRs into the relevant litmuschaos repositories
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> (feat)developer_docs: add tool to scaffold experiment artefacts

- contribute/developer_guide/README.md
- Removes reference to a stale contribution guide in the developer guide 
**Checklist**
> (Refactor)docs: remove reference to chaos-charts contrib

- contribute/developer_guide/generate_chart.py
Adopts a more recommended way to load the jinja templates, as per jinja2 documentation: 
```
Notes on Autoescaping
In future versions of Jinja2 we might enable autoescaping by default for security reasons. 
As such you are encouraged to explicitly configure autoescaping now instead of relying on the default.
```
- Uses `select_autoescape` with template type as `yaml`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #889 
**Checklist**
- By default, the sonarqube checks are not applicable in travis builds for Pull Requests (Ref: …
> (refactor)fix_vulnerability: enable autoescape for yaml template 

- chaoslib/pumba/network_chaos/network_chaos.yml
- chaoslib/pumba/pod_failure_by_sigkill.yaml
- chaoslib/pumba/pumba.j2
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/container_kill/container_kill_k8s_job.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
- experiments/generic/pod_network_latency/pod_network_latency_k8s_job.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
- experiments/generic/pod_network_loss/pod_network_loss_k8s_job.yml
- Fetch lib image from the envs of job or experiment CR
**Checklist**
**logs of  container kill job** 
[logs-container_kill.txt](https://github.com/litmuschaos/litmus/files/3789306/logs-container_kill.txt)
**logs of podn/wloss**
[logs-pod-network-loss.txt](https://github.com/litmuschaos/litmus/files/3789308/logs-pod-network-loss.txt)
**logs of pod n/w latency**
[logs-pod-network-latency.txt](https://github.com/litmuschaos/litmus/files/3789318/logs-pod-network-latency.txt)
> (feat): Fetch lib_image from the envs of job/experiment CR

- contribute/maturity.md
- Provides a set of first-cut guidelines to measure the maturity level of a chaos experiment.  
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #903 
**Checklist**
> (chore)experiment: add initial maturity guidelines for experiments

- ceps/0001-cep-template.md
- ceps/README.md
- Introduces a CEP template 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #865 
**Checklist**
> (chore)cep: add cep template

- chaoslib/litmus/kill_random_pod.yml
- experiments/generic/container_kill/container_kill_k8s_job.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
- experiments/generic/pod_network_latency/pod_network_latency_k8s_job.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
- experiments/generic/pod_network_loss/pod_network_loss_k8s_job.yml
-  fix the duplicated envs
-  update pod-delete util- able to delete specific pod
**Checklist**
> (fix) modify the experiments to remove duplicate envs

- experiments/generic/disk_loss/disk_status_check.j2
Signed-off-by: Raj <mail.rajdas@gmail.com>
Fixing disk loss j2
**Checklist**
> fixing disk loss j2

- experiments/generic/disk_loss/disk_loss_ansible_logic.yml
- experiments/kafka/kafka-broker-disk-failure/chaosutil.j2
- experiments/kafka/kafka-broker-disk-failure/disk_status_check.j2
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-prerequisites.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-k8s-job.yml
- utils/common/status_app_pod.yml
- Introduces a kafka broker disk loss experiment with liveness checks
- The experiment mandates specification of platform specific disk names & the kafka broker pod to be killed. Random pod selection may require dynamic determination of gcloud/other platform disks which are not desirable. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # (partially fulfilment of #822 ) 
**Checklist**
> (feat) kafka: include kafka broker disk failure experiment

- executor/README.md
- executor/executor.yml
- executor/experiment_configmap.yml
- experiments/generic/disk_loss/disk_loss_k8s_job.yml
- utils/cloud/gcp/gcloud_configure.yml
-    Add ability to mount secrets in executor
-  Covered all  4 conditions
1. When no configmap nor secret required 
[logs-no-configmap-and-no-secret.txt](https://github.com/litmuschaos/litmus/files/3845379/logs-no-configmap-and-no-secret.txt)
2. When only configmap is required
[logs-only-configmap.txt](https://github.com/litmuschaos/litmus/files/3845382/logs-only-configmap.txt)
3. When only secret is required
[logs-only-secret.txt](https://github.com/litmuschaos/litmus/files/3845377/logs-only-secret.txt)
4. When both configmap & secret required
[logs-both-secret-and-configmap.txt](https://github.com/litmuschaos/litmus/files/3845386/logs-both-secret-and-configmap.txt)
**Which issue this …
> (feat): add ability to mount secret in executor

- utils/apps/kafka/kafka_liveness_stream.yml
- Replace hardcoded label values with variable
**Checklist**
> (fix)kafka: remove label hardcoding in liveness util

- utils/apps/kafka/kafka_liveness_stream.yml
- Change necessitated as per: https://github.com/ansible/ansible/issues/4297#issuecomment-372835664
- Uses set_fact to update ordinality instead of using registers.
**Checklist**
> (fix)set kafka ordinality variable based on ansible fact

- utils/apps/kafka/kafka_liveness_stream.yml
- fixes a typo in the kafka_liveness_stream util
**Checklist**
> (fix) kafka liveness util typo

- utils/apps/kafka/kafka_liveness_stream.yml
> (fix) typo in usage of fact name

- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-k8s-job.yml
> (refector): add kafka_instance name in kafka-disk-loss experiment

- chaoslib/pumba/pumba.j2
- extensions/v1beta1 is deprecated in latest K8s (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) 
- Litmus is tested/supported from 1.11 onwards & apps/v1 for daemonsets is available since v1.9
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # (partially addresses #949 ) 
**Checklist**
> (refactor)pumba: update apiversion of pumba daemonset

- executor/executor.yml
**What this PR does / why we need it**: 
- This PR ensures that the chaos executor monitors the experiment for the period of TOTAL_CHAOS_DURATION (adds some default period of 300s to it). 
- And the delay time is also reduced from 10s to 3s
**Checklist**
For more information you can look at PR #952
> (fix)chaos-executor: reduced the delay time for monitoring the litmus chaos job for completion

- LICENSE
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>
- Update the license Authors
**Which issue this PR fixes**: fixes https://github.com/litmuschaos/litmus/issues/950
**Checklist**
> (license): Update the license Authors

- executor/executor.yml
- This PR will help in patching experiment status in chaosengine.
- Ansible template task is not seen to support creation of `.yaml` files, but creates `.yml` successfully.  
**Checklist**
> (fix)Executor: Experiment status patching in chaosengine

- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
> refactor[yaml]: Modified the test vars name for chaos duration according to the env in target-pod-failure experiment

- .gitlab-ci.yml
- build/ansible-runner/Dockerfile
- hack/syntax-check
- Introduce Gitlab CI for litmus 
**Checklist**
> (ci)feat: introduce gitlab ci for litmus

- chaoslib/chaoskube/README.md
- chaoslib/chaoskube/chaoskube.yml
- chaoslib/chaoskube/pod_failure_by_chaoskube.yml
- experiments/generic/pod_delete/chaosutil.j2
- experiments/generic/pod_delete/pod_delete_k8s_job.yml
**What this PR does / why we need it**: The chaoskube lib is not supported with namespace-scoped SA, so it has to be fully removed from the pod-delete chaos experiment. A notice will be added to the lib under chaoslib/chaoskube.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #963 
**Checklist**
> Remove chaoskube lib from pod-delete experiment

- .gitlab-ci.yml
- Fixes the image name used in the imageTest stage of the litmus CI pipeline. 
**Checklist**
> (fix)gitlab: fix image name typo in imageTest stage

- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
- Modified the env name for chaos duration
- Added the include vars for a_label to the verify data persistence task
**Checklist**
> refactor(yaml): Modified the openebs specific chaos experiments to change the variable name

- executor/executor.yml
- Earlier there was no check for empty configmaps and empty secrets thatswhy it was executing 
multiple task and end up saying cant able to create a experiment job.
- This Pr will validate the empty configmaps and secrets and avoid execution of unwanted tasks 
inside executer.
**Checklist**
> (fix)Executor: Validating empty configmaps and secrets 

- chaoslib/litmus/kill_random_pod.yml
- Use ansible recommended var negative logic. 
**Checklist**
> (fix)revert to ansible recommended negative logic

- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_k8s_job.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_k8s_job.yml
> (fix): update pumba image

- utils/apps/kafka/kafka_cluster_health.yml
- The derived broker count is captured in a var which is re-set/initialized in a skipped block. 
- This PR fixes the above behaviour. 
**Checklist**
> (fix)kafka: ensure derived broker register var is not empty

- README.md
- chaoslib/pumba/network_chaos/pumba_netem_job.j2
- experiments/generic/pod_network_corruption/README.md
- experiments/generic/pod_network_corruption/chaosutil.j2
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_prerequisites.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_k8s_job.yml
**What this PR does / why we need it**: This PR adds the logic to do network packet corruption using the pumba chaoslib. Please test it and give me feedback, so I can continue with the chaos chart.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: partly fixes #1014 , chaos chart still missing.
**Checklist**
> Add pod network corruption experiment logic

- experiments/generic/pod_network_latency/README.md
- experiments/generic/pod_network_loss/README.md
**What this PR does / why we need it**: Minor fixes for pod-network-loss and latency experiments' README-files
**Checklist**
> Minor fixes for pod-network-loss and latency experiments

- executor/executor.yml
Namespace c_app_ns is not included in some of the tasks in ansible executor, due to which chaosengine and chaos experiment is not created other than the default namespace.
https://github.com/litmuschaos/litmus/issues/1032
**Checklist**
> (bug-fix): Adding namespace to some tasks in ansible executor

- executor/executor.yml
- experiments/generic/pod_delete/pod_delete_ansible_logic.yml
- update pod-delete experiment for support powerfulseal
**logs**
[powerfulseal.txt](https://github.com/litmuschaos/litmus/files/4009183/powerfulseal.txt)
**Checklist**
> (fix): modify pod-delete experiment for powerfulseal

- experiments/generic/pod_delete/README.md
- Added documentation link to pod delete experiment. 
**Checklist**
> (fix): update pod-delete readme - provide docs link

- chaoslib/pumba/pod_failure_by_sigkill.yaml
- experiments/generic/container_kill/README.md
- experiments/generic/container_kill/chaosutil.j2
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/container_kill/container_kill_ansible_prerequisites.yml
- experiments/generic/container_kill/container_kill_k8s_job.yml
- Added chaosutil file.
- Updated the readme - provided docs link
- Updated pumba lib (pod-failure-by-sigkill) so that it can derive the application-container name if it is not provided in chart. 
**Note**
`The priority of  var > priority of set_fact` 
**Checklist**
**Logs**
[target-container-with-null-value.txt](https://github.com/litmuschaos/litmus/files/4010312/target-container-with-null-value.txt)
[target-container-with-container-name.txt](https://github.com/litmuschaos/litmus/files/4010313 …
> (refactor): fix container kill experiment

- chaoslib/powerfulseal/powerfulseal.j2
- Changed apiversion of  powerfulseal deployment
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1046
**Checklist**
**Error message :**
```2020-01-02 16:20:39.577773 Step: Generate the powerfulseal deployment spec from template 
2020-01-02 16:20:40.505129 Step: Setup powerfulseal to initiate random pod chaos 
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "kubectl apply -f powerfulseal.yml -n default", "delta": "0:00:00.769650", "end": "2020-01-02 16:20:40.485634", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": …
```
> (fix):Changed apiversion of powerfulseal deployment

- chaoslib/powerfulseal/powerfulseal.j2
- Added selector in spec of powerfulseal deployment
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1052
**Checklist**
> (fix):Added selector in powerfulseal deployment spec

- chaoslib/litmus/platform/gke/cpu-hog-daemonset.yml
- Added selectors in daemonsets spec
- Changed apiversion of daemonsets
**Checklist**
> (fix): changed apiversion for daemonset

- chaoslib/pumba/pod_failure_by_sigkill.yaml
- experiments/coredns/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/cpu_hog/cpu_hog_ansible_logic.yml
- experiments/generic/disk_fill/disk_fill_ansible_logic.yml
- experiments/generic/disk_loss/disk_loss_ansible_logic.yml
- experiments/generic/drain_node/drain_node_ansible_logic.yml
- experiments/generic/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
- utils/apps/kafka/kafka_cluster_health.yml
- utils/common/status_app_pod.yml
-  Added pumba container health check status.
- Updated status-app-pod util because there is some conflict in variables name (same name of var,set__fact and envs)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1010 
**Checklist**
> (feat) Added pumba container health check status

- chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
- experiments/generic/cpu_hog/README.md
- experiments/generic/cpu_hog/cpu_hog_ansible_logic.yml
- experiments/generic/cpu_hog/cpu_hog_k8s_job.yml
- fixes: #1049 
- Added the cpu hog container status check in the pod_cpu-consumption lib
- Added a task to delete the cpu hog daemonset every time in the cleanup section. place this task in the rescue section of pod_cpu_consumption lib.
- Added the task to fail the whole playbook if any task is failed inside that file.
- Update cpu-hog experiment readme
**Checklist**
**Logs**
[logs-cpu-hog.txt](https://github.com/litmuschaos/litmus/files/4018366/logs-cpu-hog.txt)
> (feat): Added cpu-hog container status, delete cpu-hog ds always and failed the playbook if task failed

- chaoslib/pumba/network_chaos/network_chaos.yml
- experiments/generic/pod_network_latency/README.md
- The playbook will fail if the task is failed.
- Need: sometimes the task is failed but the chaos-result 's verdict is set to pass 
- Update readme of pod-target -network-latency experiment
- Add the ability to derive the target container name,if the container name is not provided in charts. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1055 
**Checklist**
> (feat): Ability to derive the container name, fail playbook if task fail

- experiments/generic/disk_loss/README.md
- Updated the readme of disk-loss experiment
**Checklist**
> (refactor): update readme of disk-loss experiment

- chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
- experiments/generic/disk_fill/README.md
- fixes #1024 #1050 
- Added a task to delete the disk fill daemonset every time in the cleanup section. place this task in the rescue section of disk_fill_by_litmus lib.
- Added a task to fail the whole playbook if any task is failed inside that file.
- Added the disk-fill container status check in the disk_fill_by_litmus lib
**Checklist**
> (feat): Add disk-fill container status check & delete ds

- chaoslib/litmus/cordon_drain_node.yaml
- experiments/generic/drain_node/drain_node_ansible_logic.yml
- experiments/generic/drain_node/drain_node_k8s_job.yml
- Added chaos Duration ENV in drain node experiment
**Logs**
[drain-node.txt](https://github.com/litmuschaos/litmus/files/4025452/drain-node.txt)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1067 
**Checklist**
> (feat): Added chaos duration ENV in drain node experiment

- chaoslib/litmus/cpu_hog/app_cpu_stress.j2
- chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
- experiments/generic/pod_cpu_hog/README.md
- experiments/generic/pod_cpu_hog/chaosutil.j2
- experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_logic.yml
- experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_prerequisites.yml
- experiments/generic/pod_cpu_hog/pod_cpu_hog_k8s_job.yml
- Introduces a container-level/app-level CPU chaos experiment that can take desired number of cores as input against a target container & effect nearly ~90%  CPU consumption. 
- The experiment uses a custom kubernetes job that runs a docker-in-docker container to trigger the CPU chaos on the target container for a specified duration, returning the resources once complete.
- For more info on the chaos tool used, refer:  https://github.com/litmuschaos/test-tools/pull/108
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #974 
**Checklist**
> (feat)add application level cpu chaos experiment

- experiments/generic/drain_node/README.md
- Updated the readme of drain node experiment
**Checklist**
Dependent PR in litmus-docs: https://github.com/litmuschaos/litmus-docs/pull/134
> (refactor): Update the drain node readme

- build/ansible-runner/Dockerfile
- build/plugins/default.py
- build/utils/display.py
- Improves the ansible logs for experiments to make it more pythonic. Makes following enhancements: 
- Remove PLAY start/recap to EXPERIMENT
- Removes host info & task status (we only use localhost)
- Add timestamped task banner (instead of elapsed time) & change prefix from TASK to STEP keeping with intent of the playbook
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1031 
**Checklist**
> (refactor) make the experiment logs more meaningful

- chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
- Unable to delete daemonsets after completion of task
**Checklist**
> (fix):Delete Daemonsets after completion of task

- chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
> Removed typo 

- .bettercodehub.yml
- ADOPTERS.md
- README.md
- Adds bettercodehub integration as part of quality compliance and the corresponding badge
- Adds the bettercodehub config file to ignore ansible dependencies 
**Checklist**
> (chore) add bettercodehub badge to readme

- chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
- Fixes a typo to correct the syntax in pod-cpu-experiment
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1086 
**Checklist**
> (fix)typo in pod-cpu-hog experiment

- sonar-project.properties
- Skips analysis on the modified ansible source files (plugins, utils) and restrict it to project functionality specific python code
**Checklist**
> (chore): exclude modified ansible source files from sonar analysis

- utils/cloud/aws/aws_configure.yml
- changing mount path from mnt to tmp
**Checklist**
> (fix): changing mount path from mnt to tmp

- chaoslib/chaoskube/README.md
- chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml
- chaoslib/powerfulseal/powerfulseal.j2
- executor/README.md
- experiments/kafka/kafka-broker-pod-failure/chaosutil.j2
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- utils/apps/kafka/kafka_cluster_health.yml
- Updated kafka broker pod failure experiment
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1097 
**Checklist**
> (refactor): Updating kafka broker pod failure experiment

- .bettercodehub.yml
- ADOPTERS.md
- README.md
- chaoslib/chaoskube/README.md
- chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
- chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
- chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
- chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml
- chaoslib/powerfulseal/powerfulseal.j2
- executor/README.md
- experiments/kafka/kafka-broker-pod-failure/chaosutil.j2
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- sonar-project.properties
- utils/apps/kafka/kafka_cluster_health.yml
- utils/cloud/aws/aws_configure.yml
- (Fix):Check availablity of daemonset after deletion in cpu-hog and disk-fill ( #1079 )
- (chore) add bettercodehub badge to readme (#1083)
- (fix)typo in pod-cpu-hog experiment (#1087)
- (chore): exclude modified ansible source files from sonar analysis (#1090 )
- (feat): Added rescue block in pod-delete by powerseal lib (#1085)
- (fix): changing mount path from mnt to tmp (#1093)
- (refactor): Updating kafka broker pod failure experiment (#1095) 
**Checklist**
> [Cherry Pick for RC2]

- experiments/generic/container_kill/README.md
- experiments/generic/pod_network_corruption/README.md
- experiments/openebs/openebs-pool-container-failure/README.md
- experiments/openebs/openebs-pool-pod-failure/README.md
- experiments/openebs/openebs-target-container-failure/README.md
- experiments/openebs/openebs-target-network-delay/README.md
- experiments/openebs/openebs-target-network-loss/README.md
- experiments/openebs/openebs-target-pod-failure/README.md
- Refactored readme.md for openebs experiments.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: Fixes ::https://github.com/litmuschaos/litmus/issues/1109
**Checklist**
> Refactored readme for openebs experiments

- experiments/kafka/kafka-broker-disk-failure/README.md
- experiments/kafka/kafka-broker-pod-failure/README.md
> Added readme.md for kafka experiments

- .gitlab-ci.yml
- (feat): Add the baseline stage in gitlab-ci to record the latest commit in the baseline file.
**Checklist**
> (feat): Add the baseline stage in gitlab-ci to record the latest commit in baseline file

- chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- experiments/openebs/openebs-target-container-failure/cstor_target_container_kill.yml
- experiments/openebs/openebs-target-container-failure/jiva_controller_container_kill.yml
- Fix openebs-target-container-failure experiment to support containerd runtime
- Tested for both cstor and jiva stg_classes
- Added rescue section in crictl-chaos for deletion of DS and fail the whole ansible-playbook if a single task is failed.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1141 
**Checklist**
> (refactor): fix openebs-target-container-failure experiment to support containerd runtime

- chaoslib/litmus/cpu_hog/app_cpu_stress.j2
- chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
- experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_logic.yml
- experiments/generic/pod_cpu_hog/pod_cpu_hog_k8s_job.yml
- Also refer: https://github.com/litmuschaos/test-tools/pull/110
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # (partially addresses #1152 )
**Checklist**
> (refactor) add ramp_time support for pod_cpu_hog experiment

- chaoslib/pumba/network_chaos/network_chaos.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_k8s_job.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
- experiments/generic/pod_network_latency/pod_network_latency_k8s_job.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
- experiments/generic/pod_network_loss/pod_network_loss_k8s_job.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #(partially addresses #1152 )
**Checklist**
> (refactor) ramp_time support for the network chaos experiments

- chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
- experiments/generic/cpu_hog/cpu_hog_ansible_logic.yml
- experiments/generic/cpu_hog/cpu_hog_k8s_job.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # (partially addresses #1152 ) 
**Checklist**
> (refactor) ramp_time support for node_cpu_hog experiment

- chaoslib/litmus/platform/aws/disk_loss.yml
- chaoslib/litmus/platform/gke/disk_loss.yml
- experiments/generic/disk_loss/disk_loss_ansible_logic.yml
- experiments/generic/disk_loss/disk_loss_k8s_job.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #(partially addresses #1152 )
**Checklist**
> (refactor) ramp_time support for disk-loss experiment

- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- experiments/generic/container_kill/chaosutil.j2
- experiments/generic/container_kill/container_kill_k8s_job.yml
- Added containerd runtime for container-kill experiment
**Logs**
[container-kill-containerd.txt](https://github.com/litmuschaos/litmus/files/4116256/container-kill-containerd.txt)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1174 
**Checklist**
> (feat): Added containerd runtime for container-kill experiment

- experiments/openebs/openebs-pool-network-delay/chaosutil.j2
- experiments/openebs/openebs-pool-network-delay/cstor_pool_network_delay.yml
- experiments/openebs/openebs-pool-network-delay/data_persistence.j2
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_k8s_job.yml
- Adding openEBS pool network delay experiment
**Checklist**
> (feat): adding openebs pool network delay experiment

- .gitlab-ci.yml
**Checklist**
_ Fixing the yaml format of Gitlab ci for litmus Repository
> (fix): Refactor Gitlab-ci yml for litmus repository

- experiments/generic/cpu_hog/chaosutil.j2
- Removing extra folder `cpu_hog`
**Checklist**
> (refactor): Remove extra files of cpu_hog experiment

- experiments/openebs/openebs-pool-network-delay/cstor_pool_network_delay.yml
- experiments/openebs/openebs-pool-network-loss/cstor_pool_network_loss.yml
- Fixing file extention from .yaml to .yml
**Checklist**
> (fix): Fixing file extention from .yaml to .yml

- chaoslib/litmus/platform/gke/node-cpu-hog-daemonset.j2
> (fix): Fixing label in node cpu hog experiment

- experiments/coredns/pod_delete/chaosutil.j2
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml
> (refactor): Refactor experiments to make them uniform

- chaoslib/litmus/kill_random_pod.yml
- experiments/openebs/openebs-control-plane-pod-delete/chaosutil.j2
- experiments/openebs/openebs-control-plane-pod-delete/openebs_control_plane_pod_delete_ansible_logic.yml
- experiments/openebs/openebs-control-plane-pod-delete/openebs_control_plane_pod_delete_ansible_prerequisites.yml
- experiments/openebs/openebs-control-plane-pod-delete/openebs_control_plane_pod_delete_internal_tasks.yml
- experiments/openebs/openebs-control-plane-pod-delete/openebs_control_plane_pod_delete_k8s_job.yml
- experiments/openebs/openebs_control_plane_components.yml
- Adds an OpenEBS control plane chaos experiment
**Checklist**
> (Feat): Adding openebs control plane pod delete experiment

- chaoslib/litmus/kill_random_pod.yml
- experiments/openebs/openebs-pool-pod-failure/chaosutil.j2
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_k8s_job.yml
- Tested for both cases, w/ data persistence enabled
- app-pvc provided
- app-pvc not provided
**Checklist**
> (feat): Add ability to support pool validation steps in openebs-pool-pod-failure experiment

- ADOPTERS.md
- Model the adopters structure based on the OpenEBS project with a table summarizing the adoption usecase and a folder containing details
**Checklist**
> refactor adopters format to specify table & a details folder

- ADOPTERS.md
- Change typo in Adopters file (change stateful to any application/workload) 
**Checklist**
> refactor adopters format

- ansiblelint/rules/IgnoreErrorsCheckRule.py
- ansiblelint/rules/IncludeCheckRule.py
- ansiblelint/rules/README.md
- ansiblelint/rules/RestrictCommandsCheck.py
- ansiblelint/rules/ShellModuleScalarRule.py
Addind custom ansible lint to check the ansible playbook
**Checklist**
> (feat): Adding ansible custom lint

- Roadmap.md
> Creating the Roadmap.md

- experiments/coredns/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/disk_fill/disk_fill_ansible_logic.yml
- experiments/generic/disk_loss/disk_loss_ansible_logic.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_ansible_logic.yml
- experiments/generic/node_drain/node_drain_ansible_logic.yml
- experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_logic.yml
- experiments/generic/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
- hack/chaos-result.j2
- Making instance_id as an optional variable.
- Rename the name of chaos-engine in lookvar
**Checklist**
> fix(experiment): Rename chaosengine lookup name & make instance_id optional

- experiments/coredns/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/disk_fill/disk_fill_ansible_logic.yml
- experiments/generic/disk_loss/disk_loss_ansible_logic.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_ansible_logic.yml
- experiments/generic/node_drain/node_drain_ansible_logic.yml
- experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_logic.yml
- experiments/generic/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
- utils/runtime/chaos-result.j2
- utils/runtime/getting_failure_step.yml
- utils/runtime/update_chaos_result_resource.yml
- Adding failStep attribute inside chaosresult (.status.experimentStatuses) which will tell the task-name on which playbook has failed.
- Moving chaos-result.j2 from hacks/ to utils/runtime , as runtime contains all the chaos-result related files
- chaos-result manifest after the changes
```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosResult
metadata:
name: engine-pod-delete
labels:
chaosUID: 83c439de-6082-11ea-89a5-0cc47ab587b8
spec:
engine: engien
experiment: pod-delete
status:
experimentstatus: 
phase: Completed
verdict: Pass
failStep: N/A
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when …
> feat(chaos-result): Adding failStep attribute inside chaosresult

- utils/runtime/chaos-result.j2
- If the c_result is not defined then name of the chaos-result will be same as c_experiment. It is the possible case where we ran experiment via job
**Checklist**
> update(chaos-result) Adding condition for c_result name if experiment run via job

- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
- adding chaos_uid in some experiments
**Checklist**
> fix(chaos_uid): Adding chaos_uid in some experiments

- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
- chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
- chaoslib/litmus/platform/gke/node_cpu_consumption.yml
- chaoslib/litmus/platform/gke/node_memory_consumption.yml
- chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml
- chaoslib/pumba/network_chaos/network_chaos.yml
- chaoslib/pumba/pod_failure_by_sigkill.yml
- Converting the run-id to 6 characters long instead of 10 characters as the prefix length of job is 6 characters long in k8s.
**Checklist**
> update(run_id): Make the length of run-id to 6 characters

- ADOPTERS.md
- Including openebs into llitmus adopters.
**Checklist**
> add openebs into adopters

- ADOPTERS.md
This PR is to add MayaData Organization as litmus adopters. MayaData is using litmus to introduce chaos on their production, staging and devops clusters and e2e pipelines  to make there Saas platform more reliable and robust. 
**Checklist**
> Add Mayadata as litmus adopters 

- ADOPTERS.md
Signed-off-by: ashok babu <ashok.warria@wipro.com>
**Checklist**
> Added Wipro as an adopter list

- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml
- Passing namespace variable to util file getting failure step
**Checklist**
> bug-fix(experiment): Passing namespace variable to util file getting failure step

- CODE_OF_CONDUCT.md
- MAINTAINERS
- Modifies code of conduct
- Adds an additional reviewer 
**Checklist**
> (chore)governance: update code-of-conduct and maintainers

- NOTICE.md
- fossa.md
> (chore)notice: add fossa report

- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
Adding  chaos pod name
**Checklist**
> Fix(openebs-pool-disk-loss): Adding chaos pod name

- utils/common/generate-kubernetes-chaos-events.yml
- Adding lastTimestamp in the event generation
**Checklist**
> refactor(events): Adding lastTimestamp in the event generation

- experiments/generic/node_cpu_hog/chaosutil.j2
- experiments/generic/node_cpu_hog/node_cpu_hog_k8s_job.yml
- experiments/generic/node_memory_hog/chaosutil.j2
- experiments/generic/node_memory_hog/node_memory_hog_k8s_job.yml
-  Adding EKS platform in generic experiments
**Checklist**
> feat(platform): Adding EKS platform in generic experiments

- RELEASE_GUIDELINES.md
- Fix release versions in the release_guidelines doc
**Checklist**
> (chore)release_guidelines: update release versions

- ADOPTERS.md
**What this PR does / why we need it**: Adding myself into Litmus' adopters list.
**Checklist**
> Adding Johnny into Limus's Adopters list.

- experiments/generic/disk_loss/chaosutil.j2
- experiments/generic/disk_loss/disk_loss_k8s_job.yml
- experiments/kafka/kafka-broker-disk-failure/chaosutil.j2
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-k8s-job.yml
- experiments/openebs/openebs-pool-disk-loss/chaosutil.j2
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_k8s_job.yml
- Making the  cloud_platform uniform to GKE
**Checklist**
> refactor(disk-loss-exp): Making the  cloud_platform uniform to GKE

- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-k8s-job.yml
- Adding engine_ns for events generation
**Checklist**
> fix(kafka-experiments): Adding engine_ns for events generation

- ADOPTERS.md
- adopters/Jayesh_Kumar_CloudNative_Validation.md
Signed-off-by: Jayesh Kumar <k8scncf@gmail.com>
**Checklist**
> Charting out my story of LitmusChaos journey

- .github/stale.yml
- ADOPTERS.md
- RELEASE_GUIDELINES.md
- adopters/Jayesh_Kumar_CloudNative_Validation.md
- experiments/generic/disk_loss/chaosutil.j2
- experiments/generic/disk_loss/disk_loss_k8s_job.yml
- experiments/generic/node_cpu_hog/chaosutil.j2
- experiments/generic/node_cpu_hog/node_cpu_hog_k8s_job.yml
- experiments/generic/node_memory_hog/chaosutil.j2
- experiments/generic/node_memory_hog/node_memory_hog_k8s_job.yml
- experiments/kafka/kafka-broker-disk-failure/chaosutil.j2
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-k8s-job.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-k8s-job.yml
- experiments/openebs/openebs-pool-disk-loss/chaosutil.j2
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_k8s_job.yml
- utils/common/generate-kubernetes-chaos-events.yml
Consists of the following commits:
- https://github.com/litmuschaos/litmus/pull/1334/commits/c0a1823b54cd0c87f291b3df931f33a5b24ceabc
- https://github.com/litmuschaos/litmus/pull/1334/commits/f853f44e1d164ec2dddd9ce7feb0520b77fcc2e3
- https://github.com/litmuschaos/litmus/pull/1334/commits/949a8944b81000bf7f54e80b0016251a5131e55d
- https://github.com/litmuschaos/litmus/pull/1334/commits/838f5ea0d62df27e8e495f78e3472b25936bc828
- https://github.com/litmuschaos/litmus/pull/1334/commits/eda5e17221273dee6d5ee20cac300e997033c4fd
- https://github.com/litmuschaos/litmus/pull/1334/commits/25dcfa978c6f1f86538270da5cc620d1038155ca
- https://github.com/litmuschaos/litmus/pull/1334/commits/c64908421eb771aded45c531b81310b6b7383760
- …
> [Cherry-pick for 1.2.1]

- ADOPTERS.md
- adopters/Bhaumik_Shah_Kafka_Chaos.md
- Adds Bhaumik's user story re: Kafka Chaos
**Checklist**
> (users)bhaumik: Add Bhaumik's User Story

- ADOPTERS.md
- adopters/openebs.md
- Added OpenEBS success story into litmus.
- Updated ADOPTERS file with the same and linked it to openebs adopters file
> add openebs story into litmus adopters

- fossa.md
Update fossa.md with remaining repo of litmuschaos with below repo
- Test-Tools
- Pages
- Website-LitmusChaos
**Checklist**
> (License): Update fossa.md with remaining repo of litmuschaos

- ADOPTERS.md
- adopters/jayadeep_microservices.md
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>
**Checklist**
> my story: Jayadeep

- adopters/jayadeep_microservices.md
- Fixes missing link (to project) in Jayadeep's story 
**Checklist**
> (fix)missing link to jayadeep's project

- ADOPTERS.md
- Adds link to zebrium's user story
**Checklist**
> (chore)adopters: add link to zebrium story

- ADOPTERS.md
- adopters/AppAnywhere.md
Signed-off-by: ajeshbaby <ajesh.baby@mayadata.io>
@ashokwipro Have raised PR on your request. Please review and approve.
> AppAnywhere Success Story

- chaoslib/litmus/cordon_drain_node.yml
- Adding application status for the rescheduled pod before getting the node name of the rescheduled application pod.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1186 
**Checklist**
> refactor(node-drain): Adding application status for rescheduled pod

- chaoslib/litmus/platform/gke/node_cpu_consumption.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_ansible_logic.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_k8s_job.yml
We have to take the number of cores of CPU by user to run node CPU hog experiment. It will be an optional value to be passed. If the user choose to pass an empty value then the hogging will be done by checking the node CPU capacity (current way)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/litmuschaos/litmus/issues/1355
**Checklist**
> feat(node-cpu-hog): Using custom input for number of cores in node cpu hog experiment

- chaoslib/pumba/pod_failure_by_sigkill.yml
- chaoslib/pumba/pumba.j2
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/container_kill/container_kill_k8s_job.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_k8s_job.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_k8s_job.yml
-  Enhance container kill experiment to take total _chaos_duration with an interval
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1200
**Checklist**
> feat(container-kill): Enhance container kill experiment to take total _chaos_duration with an interval

- chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- chaoslib/litmus/cpu_hog/app_cpu_stress.j2
- chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
- chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
- chaoslib/litmus/disk_fill/disk_fill_job.j2
- chaoslib/litmus/platform/gke/node-cpu-hog-job.j2
- chaoslib/litmus/platform/gke/node-memory-hog-job.j2
- chaoslib/litmus/platform/gke/node_cpu_consumption.yml
- chaoslib/litmus/platform/gke/node_memory_consumption.yml
- chaoslib/pumba/network_chaos/network_chaos.yml
- chaoslib/pumba/network_chaos/pumba_netem_job.j2
- chaoslib/pumba/pod_failure_by_sigkill.yml
- chaoslib/pumba/pumba.j2
- Using nodeName for scheduling job on specific node
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1344 
**Checklist**
> refactor(experiments): Using the derived hostname label for scheduling job on specific node via nodeSelector

- contribute/developer_guide/README.md
- contribute/developer_guide/attributes.yaml.sample
- contribute/developer_guide/generate_chart.py
- contribute/developer_guide/templates/experiment_ansible_logic.tmpl
- contribute/developer_guide/templates/experiment_custom_resource.tmpl
- contribute/developer_guide/templates/experiment_engine.tmpl
- contribute/developer_guide/templates/experiment_k8s_job.tmpl
- contribute/developer_guide/templates/experiment_rbac.tmpl
- Updating the contributor guidelines Readme
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1281 
**Checklist**
> refactor(contributor-guide): Updating the  contributor guidelines Readme

- chaoslib/litmus/platform/gke/node_cpu_consumption.yml
- chaoslib/litmus/platform/gke/node_memory_consumption.yml
- passing the correct node name variable in while getting the host name
**Checklist**
> bug(experiment): passing the correct node name variable in while getting the host name

- .travis.yml
- Makefile
Recreate PR #1359
Adding Trivy Container image security check to the Travis pipeline
https://github.com/litmuschaos/litmus/issues/322
**Checklist**
> (Recreate PR) Feat(Trivy): Adding Trivy security check to the Travis 

- experiments/generic/container_kill/container_kill_k8s_job.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_k8s_job.yml
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_k8s_job.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
- Fixing the openebs experiments with data persistence enabled
**Checklist**
> refactor(experiments): fix the openebs experiments with data persistence enabled

- experiments/coredns/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/disk_fill/disk_fill_ansible_logic.yml
- experiments/generic/disk_loss/disk_loss_ansible_logic.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_ansible_logic.yml
- experiments/generic/node_drain/node_drain_ansible_logic.yml
- experiments/generic/node_memory_hog/node_memory_hog_ansible_logic.yml
- experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_logic.yml
- experiments/generic/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
- Adding chaos_namespace to all experiments
**Checklist**
> refcator(chaos_ns): Adding chaos_namespace to all experiments

- chaoslib/pumba/pod_failure_by_sigkill.yml
- chaoslib/pumba/pumba.j2
- utils/common/create_chaos_pod.yml
- Converting pumba job to pumba pod in container-kill experiment
- It will retry three times for pod to come to running state before terminating the execution.
**Checklist**
> refactor(container-kill): Converting pumba job to pumba pod in container-kill experiment

- chaoslib/pumba/network_chaos/network_chaos.yml
- chaoslib/pumba/network_chaos/pumba_netem_job.j2
- Converting the network chaos Job to Pod
**Checklist**
> refactor(network_lib): Converting the network chaos Job to Pod

- chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- Converting containerd_chaos job to pod
**Checklist**
> refactor(containerd_chaos): Converting containerd_chaos job to pod

- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- chaoslib/litmus/cpu_hog/pod_cpu_hog.yml
- chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
- chaoslib/litmus/platform/gke/node_cpu_consumption.yml
- chaoslib/litmus/platform/gke/node_memory_consumption.yml
- chaoslib/pumba/network_chaos/network_chaos.yml
- chaoslib/pumba/pod_failure_by_sigkill.yml
- experiments/openebs/openebs-pool-container-failure/cstor_pool_kill.yml
- experiments/openebs/openebs-target-container-failure/cstor_target_container_kill.yml
- experiments/openebs/openebs-target-container-failure/jiva_controller_container_kill.yml
> fix(loop_conflict): Fixing loop conflict in openebs container failure experiments

- contribute/developer_guide/README.md
- Re-aligns the back-ticks to place yaml snippet/command outputs in proper manner. 
**Checklist**
> (fix)developer_doc: fix yaml/command snippets

- README.md
- Adds some considerations while using litmus. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1329 
**Checklist**
> (chore)readme: add considerations for using litmus

- chaoslib/pumba/pumba.j2
- experiments/generic/container_kill/container_kill_k8s_job.yml
- experiments/openebs/openebs-nfs-provisioner-kill/openebs_nfs_provisioner_kill_k8s_job.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_k8s_job.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_k8s_job.yml
upgrading pumba to 0.6.5 in all container kill experiment
https://github.com/litmuschaos/litmus/issues/1407
**Checklist**
> Upgrade(container kill): upgrading pumba to 0.6.5 in all container kill experiments

- chaoslib/litmus/pod_memory_hog/app_memory_stress.j2
- chaoslib/litmus/pod_memory_hog/pod_memory_hog.yml
- experiments/generic/pod_memory_hog/README.md
- experiments/generic/pod_memory_hog/chaosutil.j2
- experiments/generic/pod_memory_hog/pod_memory_hog_ansible_logic.yml
- experiments/generic/pod_memory_hog/pod_memory_hog_ansible_prerequisites.yml
- experiments/generic/pod_memory_hog/pod_memory_hog_k8s_job.yml
This PR is for just adding one more experiment in the generic experiment list. This experiment causes Memory resource consumption on specified application containers by using dd command which will used to consume memory of the application container for certain duration of time. It can test the application's resilience to potential slowness/unavailability of some replicas due to high Memory load.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/litmuschaos/litmus/issues/877
**Checklist**
> Add pod memory hog experiment in generic experiment

- experiments/generic/pod_cpu_hog/chaosutil.j2
This is to fix the Chaoslib path for pod CPU hog experiment.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/litmuschaos/litmus/issues/1417
**Checklist**
> fix(bug): Giving correct chaoslib path for pod CPU hog experiment

- experiments/coredns/pod_delete/pod_delete_k8s_job.yml
- experiments/generic/container_kill/container_kill_k8s_job.yml
- experiments/generic/disk_fill/disk_fill_k8s_job.yml
- experiments/generic/disk_loss/disk_loss_k8s_job.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_k8s_job.yml
- experiments/generic/node_drain/node_drain_k8s_job.yml
- experiments/generic/node_memory_hog/node_memory_hog_k8s_job.yml
- experiments/generic/pod_cpu_hog/pod_cpu_hog_k8s_job.yml
- experiments/generic/pod_delete/pod_delete_k8s_job.yml
- experiments/generic/pod_memory_hog/pod_memory_hog_k8s_job.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_k8s_job.yml
- experiments/generic/pod_network_latency/pod_network_latency_k8s_job.yml
- experiments/generic/pod_network_loss/pod_network_loss_k8s_job.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-k8s-job.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-k8s-job.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-k8s-job.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-k8s-job.yml
- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_k8s_job.yml
- experiments/openebs/openebs-nfs-provisioner-kill/openebs_nfs_provisioner_kill_k8s_job.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_k8s_job.yml
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_k8s_job.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_k8s_job.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_k8s_job.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_k8s_job.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_k8s_job.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_k8s_job.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_k8s_job.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_k8s_job.yml
- Adding chaos_ns and pod_name(powerfulseal) in experiment job
**Checklist**
> refactor(experiments): Adding chaos_ns and pod_name(powerfulseal) in experiment job

- chaoslib/litmus/node_drain/cordon_drain_node.yml
- experiments/generic/node_drain/node_drain_ansible_logic.yml
- experiments/generic/node_drain/node_drain_ansible_prerequisites.yml
- experiments/generic/node_drain/node_drain_k8s_job.yml
- Adding the task banner in the node-drain experiment
**Checklist**
> refactor(node-drain): Adding the task banner in the node-drain experiment

- chaoslib/pumba/pod_failure_by_sigkill.yml
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/container_kill/container_kill_ansible_prerequisites.yml
- experiments/generic/pod_delete/pod_delete_ansible_logic.yml
- utils/common/create_chaos_pod.yml
- Adding the task banner in the container-kill experiment.
**Checklist**
> refactor(container-kill): Adding the task banner in the container-kill experiment

- chaoslib/litmus/pod_memory_hog/pod_memory_hog.yml
- experiments/generic/pod_memory_hog/pod_memory_hog_ansible_logic.yml
- experiments/generic/pod_memory_hog/pod_memory_hog_ansible_prerequisites.yml
- Adding the task banner in the pod-memory-hog experiment
**Checklist**
> refactor(pod-memory-hog): Adding the task banner in the pod-memory-hog experiment

- chaoslib/litmus/node_memory_hog/node_memory_consumption.yml
- experiments/generic/node_memory_hog/node_memory_hog_ansible_logic.yml
- experiments/generic/node_memory_hog/node_memory_hog_ansible_prerequisites.yml
- Adding the task banner in the node-memory-hog experiment
**Checklist**
> refactor(node-memory-hog): Adding the task banner in the node-memory-hog experiment

- chaoslib/litmus/node_cpu_hog/node_cpu_consumption.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_ansible_logic.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_ansible_prerequisites.yml
- Adding the task banner in the node-cpu-hog experiment
**Checklist**
> refactor(node-cpu-hog): Adding the task banner in the node-cpu-hog experiment

- chaoslib/pumba/network_chaos/network_chaos.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_logic.yml
- experiments/generic/pod_network_corruption/pod_network_corruption_ansible_prerequisites.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml
- experiments/generic/pod_network_latency/pod_network_latency_ansible_prerequisites.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml
- experiments/generic/pod_network_loss/pod_network_loss_ansible_prerequisites.yml
- Adding the task banner in the pod network experiment
- pod network loss
- pod-network latency
- pod network corruption
**Checklist**
> refactor(network-exp): Adding the task banner in the network experiment

- chaoslib/litmus/platform/aws/disk_loss.yml
- chaoslib/litmus/platform/gke/disk_loss.yml
- experiments/generic/disk_loss/disk_loss_ansible_logic.yml
- experiments/generic/disk_loss/disk_loss_ansible_prerequisites.yml
- experiments/kafka/kafka-broker-disk-failure/disk_status_check.j2
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
- utils/cloud/aws/aws_configure.yml
- utils/cloud/aws/fetch_aws_details.yml
- utils/cloud/aws/status_disk.yml
- utils/cloud/gcp/gcloud_configure.yml
- utils/cloud/gcp/status_disk.yml
- utils/common/disk_status_check.j2
- Adding the task banner in the disk-loss experiment
**Checklist**
> refactor(disk-loss): Adding the task banner in the disk-loss experiment

- chaoslib/litmus/disk_fill/convert_fill_percentage.yml
- chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml
- chaoslib/litmus/disk_fill/file_creation.yml
- experiments/generic/disk_fill/disk_fill_ansible_logic.yml
- experiments/generic/disk_fill/disk_fill_ansible_prerequisites.yml
- Adding the task banner in the disk-fill experiment
**Checklist**
> refactor(disk-fill): Adding the task banner in the disk-fill experiment

- experiments/openebs/openebs-nfs-provisioner-kill/openebs_nfs_provisioner_kill_ansible_logic.yml
- utils/apps/nfs/external_liveness_check.yml
> adding chaos_util env and refactor external liveness check of nfs

- contribute/developer_guide/templates/experiment_ansible_logic.tmpl
- contribute/developer_guide/templates/experiment_custom_resource.tmpl
- contribute/developer_guide/templates/experiment_k8s_job.tmpl
- contribute/developer_guide/test/templates/chartserviceversion.expected
- contribute/developer_guide/test/templates/engine.expected
- contribute/developer_guide/test/templates/experiment_cr.expected
- contribute/developer_guide/test/templates/experiment_csv.expected
- contribute/developer_guide/test/templates/experiment_logic.expected
- contribute/developer_guide/test/templates/package.expected
- contribute/developer_guide/test/templates/rbac.expected
- Adding the task banner in the contributor guide
**Checklist**
> refactor(contributor-guide): Adding the task banner in the contributor guide

- experiments/cassandra/pod-delete/pod_delete_k8s_job.yml
- experiments/coredns/pod_delete/pod_delete_k8s_job.yml
- experiments/generic/pod_delete/pod_delete_ansible_logic.yml
- experiments/generic/pod_delete/pod_delete_k8s_job.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_k8s_job.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_k8s_job.yml
- Adding kill_count in all experiments
**Checklist**
> refactor(pod-delete): Adding kill_count in all experiments

- experiments/generic/pod_memory_hog/README.md
This PR contained:
-  Addition of documentation link of pod memory hog in README.md of the experiment.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/litmuschaos/litmus/issues/1426
**Checklist**
> feat(pod-memory-hog): Add documentation link of pod memory hog in README

- experiments/openebs/openebs-control-plane-chaos/README.md
- experiments/openebs/openebs-pool-disk-loss/README.md
- experiments/openebs/openebs-pool-network-delay/README.md
- experiments/openebs/openebs-pool-network-loss/README.md
> (Docs): Adding docs for the experiments

- utils/runtime/update_chaos_result_resource.yml
> Minor refactor

- experiments/openebs/openebs-pool-pod-failure/cstor_delete_and_verify_pool_deployment.yml
- experiments/openebs/openebs-pool-pod-failure/cstor_pool_health_check.yml
- experiments/openebs/openebs-pool-pod-failure/cstor_verify_pool_provisioning.yml
- experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-pod-failure/cstor_target_pod_failure.yml
- experiments/openebs/openebs-target-pod-failure/jiva_controller_pod_failure.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
- experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_prerequisites.yml
- utils/apps/openebs/fetch_cstor_target_pod.yml
- utils/apps/openebs/fetch_cvr_count_from_pv.yml
- utils/apps/openebs/fetch_jiva_controller_pod.yml
- utils/apps/openebs/fetch_podname_from_cvr.yml
- utils/apps/openebs/fetch_replica_count_from_sc.yml
- utils/apps/openebs/target_affinity_check.yml
-  Adding the task banner in the openebs pod-delete experiment
- target pod delete
- pool pod delete
**Checklist**
> refactor(openebs-exp): Adding the task banner in the openebs pod-delete experiments

- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml
- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_prerequisites.yml
- experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_internal_tasks.yml
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_prerequisites.yml
- utils/apps/busybox/busybox_data_persistence.yml
- utils/apps/mysql/check_db_connection.yml
- utils/apps/mysql/mysql_data_persistence.yml
- utils/apps/openebs/cstor_pool_health_status.yml
- utils/apps/openebs/fetch_sc_and_provisioner.yml
- Adding the task banner in the disk-loss/control-plan experiment
**Checklist**
> refactor(openebs-exp): Adding the task banner in the disk-loss/control-plan experiments

- experiments/openebs/openebs-pool-network-delay/cstor_pool_network_delay.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_logic.yml
- experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_ansible_prerequisites.yml
- experiments/openebs/openebs-pool-network-loss/cstor_pool_network_loss.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml
- experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_prerequisites.yml
- experiments/openebs/openebs-target-network-delay/cstor_target_network_delay.yml
- experiments/openebs/openebs-target-network-delay/jiva_controller_network_delay.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_logic.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_prerequisites.yml
- experiments/openebs/openebs-target-network-loss/cstor_target_network_loss.yml
- experiments/openebs/openebs-target-network-loss/jiva_controller_network_loss.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_logic.yml
- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_prerequisites.yml
- Adding the task banner in the openebs network experiment
- pool network delay
- pool network loss
- target network delay
- target network loss
**Checklist**
> refactor(openebs-exp): Adding the task banner in the openebs network experiments

- experiments/openebs/openebs-nfs-provisioner-kill/README.md
Adding nfs doc link
**Checklist**
> Adding nfs kill doc link

- experiments/openebs/openebs-pool-container-failure/cstor_kill_and_verify_pool.yml
- experiments/openebs/openebs-pool-container-failure/cstor_pool_kill.yml
- experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/cstor_target_container_kill.yml
- experiments/openebs/openebs-target-container-failure/jiva_controller_container_kill.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml
- experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_prerequisites.yml
-  Adding the task banner in the openebs container-kill experiment
- pool container failure
- target container failure
**Checklist**
> refactor(openebs-exp): Adding the task banner in the openebs container-kill experiments

- contribute/developer_guide/templates/experiment_ansible_logic.tmpl
- contribute/developer_guide/test/templates/experiment_logic.expected
- experiments/cassandra/pod-delete/README.md
- experiments/cassandra/pod-delete/pod_delete_ansible_logic.yml
- experiments/cassandra/pod-delete/pod_delete_ansible_prerequisites.yml
- utils/apps/cassandra/cassandra_liveness_check.yml
- utils/apps/cassandra/cassandra_liveness_cleanup.yml
- utils/apps/cassandra/check_load_distribution.yml
- utils/apps/cassandra/nodetool_status.yml
- Adding the task banner in the cassandra-pod-delete experiment
**Checklist**
> refactor(cassandra-exp): Adding the task banner in the cassandra-pod-delete experiment

- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-prerequisites.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-logic.yml
- experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-ansible-prerequisites.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-logic.yml
- experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-ansible-prerequisites.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml
- experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-prerequisites.yml
- utils/apps/kafka/kafka_cluster_health.yml
- utils/apps/kafka/kafka_liveness_cleanup.yml
- utils/apps/kafka/kafka_liveness_stream.yml
- utils/apps/kafka/kafka_select_broker.yml
-  Adding the task banner in the kafka-experiments
**Checklist**
> refactor(kafka-exp): Adding the task banner in the kafka-experiments

- experiments/openebs/openebs-pool-container-failure/cstor_pool_kill.yml
- experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_ansible_prerequisites.yml
> fix(openebs-exp): Fix the openebs experiments

- experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_ansible_prerequisites.yml
- utils/runtime/chaos-result.j2
> fix(cresult): update the chaos result jinja template

- chaoslib/chaostoolkit/kubernetes/pod-delete/chaostoolkit_util.yml
- chaoslib/chaostoolkit/kubernetes/pod-delete/example_test_vars.yml
- chaoslib/chaostoolkit/kubernetes/pod-delete/pod-app-kill-all.j2
- chaoslib/chaostoolkit/kubernetes/pod-delete/pod-custom-kill-all.j2
- chaoslib/chaostoolkit/kubernetes/pod-delete/pod-custom-kill-count.j2
- experiments/chaostoolkit/kubernetes/pod-delete/pod-delete_job_report.yml
New changes to support report, custom label and killing all the pods.
**Checklist**
Work in Progress
> Python package and report addition on K8 pod delete 

- RELEASES.md
> (chore)update releases doc with 1.3.0 info

- ROADMAP.md
> (chore)roadmap: update roadmap items

- README.md
Changing docker badge to litmuschaos/ansible-runner
**Checklist**
> Changing docker badge to litmuschaos/ansible-runner

- chaoslib/litmus/pod_delete/kill_random_pod.yml
- chaoslib/litmus/pod_delete/pod_failure_by_litmus.yml
- Terminating pod-delete on the basis of chaos-duration
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1482 
**Checklist**
> fix(pod-delete): Terminating pod-delete on the basis of chaos-duration

- experiments/generic/disk_loss/chaosutil.j2
- experiments/generic/disk_loss/disk_loss_ansible_logic.yml
- experiments/generic/disk_loss/disk_loss_k8s_job.yml
- Adding lib in the disk-loss experiment
**Checklist**
> update(disk-loss):Adding lib env in disk-loss experiment

- chaoslib/litmus/disk_fill/disk_fill_pod.j2
- experiments/generic/disk_fill/disk_fill_ansible_logic.yml
- experiments/generic/disk_fill/disk_fill_k8s_job.yml
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
https://github.com/litmuschaos/litmus/issues/1500
**Checklist**
> feat(disk-fill): Adding Dynamic Variable for Container Path

- chaoslib/litmus/node_cpu_hog/node-cpu-hog-pod.j2
- experiments/generic/node_cpu_hog/node_cpu_hog_k8s_job.yml
- experiments/generic/node_memory_hog/node_memory_hog_k8s_job.yml
- **What this PR does / why we need it**:
- This is for using a uniform image for stress-ng commands
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/litmuschaos/litmus/issues/1459
**Checklist**
> feat(image): Using a common image for stress-ng commands

- chaoslib/litmus/disk_fill/disk_fill_pod.j2
- chaoslib/litmus/node_cpu_hog/node-cpu-hog-pod.j2
- chaoslib/litmus/pod_delete/kill_random_pod.yml
- experiments/generic/disk_fill/disk_fill_ansible_logic.yml
- experiments/generic/disk_fill/disk_fill_k8s_job.yml
- experiments/generic/node_cpu_hog/node_cpu_hog_k8s_job.yml
- experiments/generic/node_memory_hog/node_memory_hog_k8s_job.yml
- It consists of the following commits:
- 8934763bd2072237dc9837fabb18e20ae0b9a91b
- a765a4a6b6d709ef96bbc2b37c3afc5faa5d8c94
- bb2aaf525ba6192a05e999a3bfae2dca0c309c11
**Checklist**
> [Cherry-pick for RC2] 

- contribute/developer_guide/STYLE_GUIDE.md
Add Go Style Guideline for litmuschaos
- [Introduction](#introduction)
- [Guidelines](#guidelines)
- [Defer to Clean Up](#defer-to-clean-up)
- [Channel Size is One or None](#channel-size-is-one-or-none)
- [Use `"time"` to handle time](#use-time-to-handle-time)
- [Error Wrapping](#error-wrapping)
- [Don't Panic](#dont-panic)
- [Avoid Embedding Types in Public Structs](#avoid-embedding-types-in-public-structs)
- [Performance](#performance)
- [Prefer strconv over fmt](#prefer-strconv-over-fmt)
- [Avoid string-to-byte conversion](#avoid-string-to-byte-conversion)
- [Prefer Specifying Map Capacity Hints](#prefer-specifying-map-capacity-hints)
- [Style](#style)
- [Package Naming](#package-naming)
- …
> (Enhancement): Add Go style Guide for LitmusChoos

- chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/container_kill/container_kill_k8s_job.yml
- Adding the interval & duration in container-kill
**Checklist**
> feat(containerd): Adding the interval & duration in container-kill

- chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/container_kill/container_kill_k8s_job.yml
- Adding events in the containerd helper pod
**Checklist**
> feat(containerd): Adding events in the containerd helper pod

- chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- chaoslib/litmus/pod_delete/kill_random_pod.yml
- chaoslib/litmus/pod_delete/pod-delete.j2
- chaoslib/litmus/pod_delete/pod_failure_by_litmus.yml
- contribute/developer_guide/STYLE_GUIDE.md
- experiments/generic/container_kill/container_kill_ansible_logic.yml
- experiments/generic/container_kill/container_kill_k8s_job.yml
- experiments/generic/pod_delete/pod_delete_ansible_logic.yml
- It consists of the following commits:
- 225c4e60618ebd38c7669e82b43137f8d8e845d9
- 757163200ced2868b0a76f3b38b0c6b726eff021
- 7b00ef3a853aa571f27d51d72458ee9138e32d27
- b7c776bef3eb94ea48122861516bc57253cadfb7
- e26a227152ef8a6d2d47f294e79ba6b90c37dd04
**Checklist**
> [Cherry-pick for 1.4.1]

- chaoslib/litmus/pod_delete/pod-delete.j2
- Fixing pod-delete chaoslib j2 providing custom image
**Checklist**
> fix(pod-delete): Fixing pod-delete chaolib j2 providing custom image

- ROADMAP.md
- Update roadmap items
**Checklist**
> (chore)roadmap: update roadmap status

- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- chaoslib/litmus/pod_delete/pod_failure_by_litmus.yml
> update(helper-pod): Wait till the helper pod come into running state

- ROADMAP.md
- chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- chaoslib/litmus/pod_delete/pod_failure_by_litmus.yml
- Includes: 
- https://github.com/litmuschaos/litmus/pull/1530
- https://github.com/litmuschaos/litmus/pull/1533
> [Cherry-Pick for 1.4.1] 

- chaoslib/litmus/container_kill/containerd_chaos/containerd.j2
> feat(helper-pod): Adding go-based helper pod for container kill

- chaoslib/litmus/pod_delete/pod-delete.j2
> feat(helper-pod): Adding the pod-delete go helper pod

- ROADMAP.md
> (chore)roadmap updates as of 1.4.1

- RELEASES.md
- RELEASE_GUIDELINES.md
> (chore)releases: updated release artefacts

- ROADMAP.md
- Roadmap updates
**Checklist**
> (chore)roadmap: add item for litmus portal

- experiments/generic/pod_memory_hog/pod_memory_hog_k8s_job.yml
- Add pod memory hog default memory consumption in the job spec
**Checklist**
> refactor(experiment): Add pod memory hog default memory consumption

- ROADMAP.md
> (chore)roadmap: update availability of scaffold scripts to generate experiment code

- litmus-portal/backend/graphql-server/graph/schema.resolvers.go
Signed-off-by: Raj Das <raj.das@mayadata.io>
**Checklist**
> (fix): Minor bug fixing

- .circleci/config.yml
- litmus-portal/Makefile
> chore(litmus-portal): Adding Makefile and CI setup for CircleCi

- .circleci/config.yml
- litmus-portal/Makefile
Reusing docker push script
**Checklist**
> Reusing docker push script

- ROADMAP.md
> Update the backlog in Roadmap with IO-Chaos

- ROADMAP.md
- Adds a backlog item to roadmap to include provide off-the-shelf chaos workflows that execute chaos when an application-specific benchmark run is in progress
**Checklist**
> (chore)roadmap: add backlog item on chaos workflows for application benchmarks

- README.md
Signed-off-by: Raj Das <raj.das@mayadata.io>
Adding CNCF Sandbox logo in README.md
**Checklist**
> Adding cncf sandbox logo in README.md

- .travis.yml
- Makefile
- The litmuschaos/ansible-runner docker image is now being pushed from the repo https://github.com/litmuschaos/litmus-ansible
- This PR prevents push of this image from this repo
**Checklist**
> (chore)ci: inhibit push of ansible-runner image from litmus

- RELEASES.md
> (chore)releases: update releases doc

- .betterci/ci-k8s-manifest.yml
- .betterci/config.json
- litmus-portal/backend/auth/go.sum
- litmus-portal/backend/auth/pkg/types/const.go
- litmus-portal/k8s-manifest.yml
This PR achieves following tasks
- adds the `auth-server` as a sidecar in `litmusportal-server` deployment
- connects the `auth-server` with `mongo-service`
**Checklist**
> Authdeploy

- litmus-portal/frontend/src/components/AdjustedWeights/index.tsx
- litmus-portal/frontend/src/components/VerifyCommit/index.tsx
- litmus-portal/frontend/src/config/index.ts
- litmus-portal/frontend/src/containers/app/App.tsx
- litmus-portal/frontend/src/models/analytics.ts
- litmus-portal/frontend/src/models/index.ts
- litmus-portal/frontend/src/pages/HomePage/index.tsx
- litmus-portal/frontend/src/redux/actions/analytics.ts
- litmus-portal/frontend/src/redux/reducers/analytics.ts
- litmus-portal/frontend/src/redux/reducers/index.ts
Fixed Redux Setup
**Checklist**
> chore(litmus-portal): Adding redux setup for the frontend

- litmus-portal/backend/auth/pkg/server/server.go
- litmus-portal/backend/auth/pkg/types/const.go
- litmus-portal/k8s-manifest.yml
This PR does following -
- removes the redirection that was being used for the development purposes
- changes namespace to `litmus`
**Checklist**
> (feat auth): Redirection and Namespace

- README.md
Changes has been made with this pr - 
- Updated in README.md - Community Slack url (redirection) to kubernete slack  litmus url `kubernetes.slack.com`
Signed-off-by: ashishjain <ashish.jain@mayadata.io>
**Checklist**
> fix:- Community Slack url (redirection) to kubernetes slack litmus url

- README.md
Changes has been made with this pr -
Updated in README.md - Added Slack and YouTube badges and fixed a typographical error in the community resource section
**Checklist**
> Added slack and youtube badges and fixed a typo in community resource section

- litmus-portal/frontend/src/models/analytics.ts
- litmus-portal/frontend/src/redux/reducers/analytics.ts
Updates the format of GeoCountry data for ease of use in the frontend
**Checklist**
> chore(litmus-portal): Updated redux for GeoCountry Data

- litmus-portal/backend/auth/pkg/server/server.go
This PR removes the cors error from frontend.
**Checklist**
> feat auth): handling cors error

- README.md
Changes
Tittle  - Litmus
Subtitle - Cloud-Native Chaos Engineering.
> Change multiple line Heading into Single one

- litmus-portal/backend/auth/pkg/server/server.go
This PR deals with the core issue corresponding to HTTP errors and is an extension of PR https://github.com/litmuschaos/litmus/pull/1726
**Checklist**
> (feat auth): handling cors issue for errors

- litmus-portal/README.md
- Refactoring Readme in litmus-portal
> chore(litmus-portal): Refactoring Readme in litmus-portal

- litmus-portal/README.md
- litmus-portal/k8s-manifest.yml
- Adding litmus namespace to k8s manifest
- Minor fixing in Readme.md
> chore(litmus-portal): Adding litmus namespace to k8s manifest

- litmus-portal/frontend/src/components/WelcomeModal/PasswordModal.tsx
- litmus-portal/frontend/src/components/WelcomeModal/index.tsx
- litmus-portal/frontend/src/pages/HomePage/index.tsx
Removed the button for the modal and minor refactoring
**Checklist**
> Modal refactoring

- RELEASES.md
- Updates release doc with 1.6.0 information
**Checklist**
> (chore)releases: update release doc

- MAINTAINERS
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>
Change company for MK maintainer.
> Change company for Maria Kotlyarevskaya

- docs/index.html
- docs/litmus-operator-latest.yaml
- docs/litmus-operator-namespaced-scope.yaml
- docs/litmus-operator-v1.6.0.yaml
- docs/litmus-operator-v1.6.1.yaml
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>
- sync with pages folder as part of the deprecation pages repo
- I've defined the default values for some variables
- Remove doubled empty lines
> Sync litmus docs folder  with pages docs folder

- .github/PULL_REQUEST_TEMPLATE.md
- RELEASE_GUIDELINES.md
- fossa.md
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>
- remove pages repository from litmus
**Which issue this PR fixes**: fixes #1720
> Remove pages repo from litmus

- litmus-portal/backend/graphql-server/graph/schema.graphqls
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>
**What this PR does / why we need it**: This PR will add Schema for GraphQL API.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1793 
**Checklist**
> Added the GraphQL Schema for Code Generation.

- litmus-portal/backend/auth/pkg/types/const.go
This PR fixes the connection between authentication server and mongo-server
**Checklist**
> fixing auth mongo connection

- docs/litmus-admin-rbac.yaml
- need node update permission for the node-taint experiment.
**Checklist**
> feat(admin-rbac): Adding node update permission in admin-rbac

- litmus-portal/frontend/src/components/WorkflowCluster/styles.ts
**Due to Button Size fixes some CSS were improper, This PR fix that **:
**Checklist**
> Due to Button Size fixed some CSS issues there, This PR fixed that for Buttons

- docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-ci.yaml
- docs/litmus-operator-latest.yaml
> update(crd): updating crds and add namespaced scope superset rbac

- docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-latest.yaml
- docs/litmus-operator-v1.6.2.yaml
- Update deploy manifests for 1.6.2
**Checklist**
> (chore)manifests: update litmus deploy manifests for 1.6.2

- litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
**What this PR does / why we need it**: Solves the Welcome Modal Authentication issue.
**Checklist**
> chore(litmus-portal): Updated Welcome Modal(Auth + JSON body)

- .github/PULL_REQUEST_TEMPLATE.md
> Refactoring PR template

- .betterci/ci-k8s-manifest.yml
- litmus-portal/backend/graphql-server/go.mod
- litmus-portal/backend/graphql-server/go.sum
- litmus-portal/backend/graphql-server/graph/generated/generated.go
- litmus-portal/backend/graphql-server/graph/model/models_gen.go
- litmus-portal/backend/graphql-server/graph/schema.graphqls
- litmus-portal/backend/graphql-server/graph/schema.resolvers.go
- litmus-portal/backend/graphql-server/pkg/cluster/cluster_jwt.go
- litmus-portal/backend/graphql-server/pkg/data-store/store.go
- litmus-portal/backend/graphql-server/pkg/database/mongodb/init.go
- litmus-portal/backend/graphql-server/pkg/database/mongodb/operations.go
- litmus-portal/backend/graphql-server/pkg/graphql/mutations/mutation.go
- litmus-portal/backend/graphql-server/pkg/graphql/queries/query.go
- litmus-portal/backend/graphql-server/pkg/graphql/subscriptions/subscription.go
- litmus-portal/backend/graphql-server/server.go
- litmus-portal/k8s-manifest.yml
This PR adds the required mutations, queries, subscriptions and db operations for workflow-agent
> chore(litmus-portal): Added Workflow Agent Operations to GQL Server

- litmus-portal/frontend/cypress/component/customSlider.spec.tsx
- litmus-portal/frontend/cypress/component/customStepper.spec.tsx
- litmus-portal/frontend/src/components/AdjustedWeights/styles.ts
- litmus-portal/frontend/src/components/ChooseWorkflow/index.tsx
- litmus-portal/frontend/src/components/CustomSlider/index.tsx
- litmus-portal/frontend/src/components/CustomStepper/index.tsx
- litmus-portal/frontend/src/components/CustomStepper/styles.ts
- litmus-portal/frontend/src/components/CustomText/index.tsx
- litmus-portal/frontend/src/components/PredifinedWorkflows/index.tsx
- litmus-portal/frontend/src/components/ReliabilityScore/index.tsx
- litmus-portal/frontend/src/components/ScheduleWorkflow/index.tsx
- litmus-portal/frontend/src/components/TuneWorkflow/index.tsx
- litmus-portal/frontend/src/components/VerifyCommit/index.tsx
- litmus-portal/frontend/src/components/VerifyCommit/styles.ts
- litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
- litmus-portal/frontend/src/models/workflow.ts
- litmus-portal/frontend/src/redux/actions/workflow.ts
- litmus-portal/frontend/src/redux/reducers/workflow.ts
- litmus-portal/frontend/src/utils/yamlUtils.ts
**State management for Workflow Scheduling Screens added.**
**Some refactoring of components is done.**
> State management of Workflow Scheduling Screens and Some Refactoring done. 

- litmus-portal/frontend/src/components/FinishModal/index.tsx
Signed-off-by: Saswata Mukherjee <saswataminsta@yahoo.com>
Minor typo fix in `components/FinishModal/index.tsx`.
> chore(litmus-portal): Typo fix in FinishModal

- litmus-portal/backend/graphql-server/go.mod
- litmus-portal/backend/graphql-server/go.sum
- litmus-portal/backend/graphql-server/graph/generated/generated.go
- litmus-portal/backend/graphql-server/graph/model/models_gen.go
- litmus-portal/backend/graphql-server/graph/schema.graphqls
- litmus-portal/backend/graphql-server/graph/schema.resolvers.go
- litmus-portal/backend/graphql-server/pkg/database/mongodb/operations.go
- Adding get cluster details GQL API
- Schema addition of getCluster query
> chore(litmus-portal): Adding get cluster details GQL API

- hack/push
Adding push script to the litmus
> Adding push script to the litmus

- docs/litmus-operator-v1.7.0.yaml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
> chore(1.7.0): Add crds for litmus 1.7.0

- docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- Update namespaced operator to 1.7.0
> (chore)namespaced_operator: update namespaced operator to 1.7.0

- litmus-portal/README.md
Changing the manifest file from portal to master
> Update installation file to master

- litmus-portal/backend/graphql-server/go.sum
- litmus-portal/backend/graphql-server/graph/schema.resolvers.go
- litmus-portal/backend/graphql-server/pkg/graphql/queries/query.go
- litmus-portal/backend/workflow-agent/go.mod
- litmus-portal/backend/workflow-agent/main.go
- litmus-portal/backend/workflow-agent/pkg/cluster/events/workflow.go
- litmus-portal/backend/workflow-agent/pkg/cluster/logs/pod.go
- litmus-portal/backend/workflow-agent/pkg/gql/mutation.go
- litmus-portal/backend/workflow-agent/pkg/gql/subscription.go
- litmus-portal/backend/workflow-agent/pkg/gql/util.go
- litmus-portal/backend/workflow-agent/pkg/types/log.go
- litmus-portal/frontend/src/components/Sections/Settings/UserManagementTab/EditUser/index.tsx
- Adds workflow logs to the workflow-agent
> Added Workflow Logs to workflow-agent

- ADOPTERS.md
- adopters/okteto.md
Add okteto to the list of adopters
> Add okteto to the list of adopters

- litmus-portal/backend/graphql-server/pkg/graphql/subscriptions/subscription.go
closes- https://github.com/litmuschaos/litmus/issues/1912
> Sending workflow request to the particular cluster

- litmus-portal/README.md
- litmus-portal/package-lock.json
- Removing unused things from the litmus-portal
> Removing unused things from the litmus-portal

- litmus-portal/frontend/src/components/Sections/ChaosWorkflows/BrowseWorkflow/TableData.tsx
- litmus-portal/frontend/src/components/Sections/ChaosWorkflows/BrowseWorkflow/index.tsx
- litmus-portal/frontend/src/components/Sections/WorkflowUnderground/WorkflowRepresentation/index.tsx
- litmus-portal/frontend/src/components/Sections/WorkflowUnderground/WorkflowRepresentation/styles.ts
- litmus-portal/frontend/src/containers/app/App.tsx
- litmus-portal/frontend/src/pages/WorkflowUnderground/index.tsx
* Added Workflow Sidebar
* Can display currently running nodes
* Can display executed nodes
* Updated Duration check based on UNIX time
> chore(litmus-portal): Added Workflow Sidebar

- litmus-portal/frontend/nginx/nginx.conf
- litmus-portal/frontend/src/config/index.ts
- Updated Nginx Config to handle websocket connection required for Subscriptions
Fixes #1944 
> Updated Nginx to handle Websocket Connection

- package-lock.json
- Removing package-lock.json from the root of the litmus directory
> Removing package-lock.json from the root of the litmus directory

- litmus-portal/frontend/src/components/Sections/ChaosWorkflows/BrowseWorkflow/TableData.tsx
- litmus-portal/frontend/src/components/Sections/ChaosWorkflows/BrowseWorkflow/headerSection.tsx
- litmus-portal/frontend/src/components/Sections/ChaosWorkflows/BrowseWorkflow/index.tsx
- litmus-portal/frontend/src/components/Sections/ChaosWorkflows/BrowseWorkflow/styles.ts
- litmus-portal/frontend/src/containers/app/App.tsx
This PR adds:
- Blocking the routes when the Welcome Modal is Open
- Validates the parsing of the execution_data 
- Minor CSS changes
> chore (litmus-portal): Blocking the routes when Welcome Modal is open and some minor changes

- litmus-portal/backend/graphql-server/pkg/usermanagement/create.go
> (fix): creating users with the same username

- litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
- litmus-portal/frontend/src/components/WorkflowCard/CardContent.tsx
- litmus-portal/frontend/src/utils/yamlUtils.ts
Updated predefined workflows and parsing of the same.
fixes #1999 
- None.
High priority PR.
> Updated predefined workflows and parser for the same.

- litmus-portal/backend/graphql-server/graph/generated/generated.go
- litmus-portal/backend/graphql-server/graph/model/models_gen.go
- litmus-portal/backend/graphql-server/graph/project.graphqls
- litmus-portal/backend/graphql-server/graph/schema.graphqls
- litmus-portal/backend/graphql-server/graph/schema.resolvers.go
- litmus-portal/backend/graphql-server/pkg/database/mongodb/operations/project.go
- litmus-portal/backend/graphql-server/pkg/database/mongodb/operations/usermanagement.go
- litmus-portal/backend/graphql-server/pkg/database/mongodb/schema/project.go
- litmus-portal/backend/graphql-server/pkg/project/create.go
- litmus-portal/backend/graphql-server/pkg/usermanagement/create.go
This PR contains following changes in the API layer-
- User will be able to send invitation to another user
- User will be able to accept invitation from another user
- User will be able to decline invitation from other users
- Get all users at once (will not contain project related details of any user)
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
> (feat teaming): send accept and decline invitation

- litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
- litmus-portal/frontend/src/models/CreateWorkflowData.ts
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>
**This PR:**
**- will add typing for useMutation**
> Adding typings in useMutation.

- litmus-portal/frontend/src/components/Sections/ChaosWorkflows/BrowseSchedule/TableData.tsx
- litmus-portal/frontend/src/components/Sections/ChaosWorkflows/BrowseWorkflow/TableData.tsx
- litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
added fix for workflow data fetching changed workflow_name to workflow_run_id as the unique value
Bug fix for workflow data
> added fix for workflow data

- .circleci/config.yml
- Speeds up CircleCI build by building backend and frontend images parallelly
-  previously took 20-23 mins now takes 15-17 mins
> Separating frontend and backend build to run parallel. 

- litmus-portal/backend/graphql-server/go.sum
- litmus-portal/backend/graphql-server/graph/generated/generated.go
- litmus-portal/backend/graphql-server/graph/model/models_gen.go
- litmus-portal/backend/graphql-server/graph/schema.graphqls
- litmus-portal/backend/graphql-server/graph/schema.resolvers.go
- litmus-portal/backend/graphql-server/pkg/graphql/mutations/mutation.go
> Adding get chaos workflow list

- .circleci/config.yml
Increase resource size of circleci
> Increase resource size of circleci

- litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
- litmus-portal/frontend/src/models/predefinedWorkflow.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/ExperimentDetails.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/Head.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/Recommendation.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
Signed-off-by: Oum Nivrathi kale <oum.kale@mayadata.io>
This PR has removed the dummy data from templates that were used for Experiment details.
Updated Files
-Head
-Experiment
-Recommandation
-BrowserTemplate
-Pre Define Workflow
> Updated Data - Experiment Details, Recommendation and Information for Templates. (Removed Dummy Data) 

- .circleci/config.yml
- As both frontend and backend build parallel. We can reduce the VM size of the backend build because frontend build takes more time.
- Adding docker push for master and release only
> changing backend-build machine to large

- litmus-portal/frontend/src/components/Header/ProfileDropdownItems.tsx
- litmus-portal/frontend/src/components/Header/ProfileDropdownSection.tsx
- litmus-portal/frontend/src/graphql/mutations.ts
- litmus-portal/frontend/src/graphql/quries.ts
- litmus-portal/frontend/src/models/graphql/user.ts
- litmus-portal/frontend/src/pages/Settings/index.tsx
- litmus-portal/frontend/src/pages/Settings/styles.ts
- litmus-portal/frontend/src/utils/user.ts
- litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
- litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/styles.ts
- litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/TableData.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/styles.ts
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/styles.ts
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/styles.ts
- litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/ResetModal/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/styles.ts
- litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
- litmus-portal/package-lock.json
- Added functionality to My Accounts tab
- Bug fixes for avatar
- CSS fixes
- password modal fixes: displays error on the modal if password change is unsuccessful
- tab fixes: sets to 1st tab when users log out.
> chore:(Litmus Portal) Added functionality to my-accounts tabs, and other bug fixes

- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
- litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
- litmus-portal/frontend/src/models/redux/user.ts
- litmus-portal/frontend/src/pages/Workflows/index.tsx
- litmus-portal/frontend/src/redux/reducers/user.ts
- litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/ResetModal/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
- displays error on create-user modal if username entered already exists
- displays error on my-accounts modal if current password entered is wrong
- changed skip to back button
- Name and email is prepopulated in welcome modal
- Password reset is now done in one shot
- Creating workflow will always take you to browse workflows now
- typos fixed
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …
> Bug fixes: displays error on modal for create user and change password

- litmus-portal/frontend/cypress/component/QuickActionCard.spec.tsx
- litmus-portal/frontend/package-lock.json
- litmus-portal/frontend/package.json
- litmus-portal/frontend/src/models/graphql/workflowData.ts
- litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
- litmus-portal/frontend/src/pages/AnalyticsPage/styles.ts
- litmus-portal/frontend/src/pages/LoginPage/index.tsx
- litmus-portal/frontend/src/theme/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/PopOver/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/PopOver/styles.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunsBarChart/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunsBarChart/styles.ts
Added browse workflow Analytics
fixes #2054 
- None.
Analytics PR #2
> chore(litmus-portal): Added browse workflow analytics for litmus-portal.

- litmus-portal/frontend/src/components/Button/ButtonFilled/index.tsx
- litmus-portal/frontend/src/components/Button/ButtonOutline/index.tsx
- litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
- Disabled creation of workflows for users with viewer permissions
- Changed button to take any React node
> disabled create workflow for viewers

- litmus-portal/backend/graphql-server/go.sum
- litmus-portal/backend/graphql-server/graph/generated/generated.go
- litmus-portal/backend/graphql-server/graph/model/models_gen.go
- litmus-portal/backend/graphql-server/graph/schema.graphqls
- litmus-portal/backend/graphql-server/pkg/graphql/queries/query.go
Adding cluster type in getworkflowrun API response
> Adding cluster type in getworkflowrun api

- litmus-portal/backend/subscriber/pkg/cluster/events/workflow.go
- litmus-portal/backend/subscriber/pkg/gql/mutations.go
> Fixed Workflow Status

- litmus-portal/frontend/src/graphql/quries.ts
- litmus-portal/frontend/src/models/graphql/scheduleData.ts
- litmus-portal/frontend/src/models/graphql/workflowData.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
This PR adds:
- Updated graphql schema with cluster_name and cluster_type in frontend
- Added filter functionality in browse workflow section
> chore(litmus-portal): Added filter in browse workflow section and updated the graphql schema

- ADOPTERS.md
Fill in the link to wescale adoption story in ADOPTERS.md 
> (chore)adopters: add link to wescale adoption story

- litmus-portal/frontend/src/components/Loader/index.tsx
- litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
- litmus-portal/frontend/src/models/redux/user.ts
- litmus-portal/frontend/src/pages/HomePage/index.tsx
- litmus-portal/frontend/src/pages/HomePage/style.ts
- litmus-portal/frontend/src/pages/LoginPage/index.tsx
- litmus-portal/frontend/src/pages/LoginPage/styles.ts
- litmus-portal/frontend/src/redux/reducers/user.ts
This PR modifies:
1. Buttons with Circular Progress Loader in the middle
2. Disables buttons if a request is already made to prevent unnecessary clicks/requests to the backend
3. Sets up a Loader once the Welcome Modal closes and opens up the updated Homepage for the users
> chore(litmus-portal): Updated Circular Loader and Removed User Waiting after login

- litmus-portal/cluster-agents/subscriber/pkg/gql/subscriptions.go
- Prevents subscriber from exiting on resource creation errors
> Prevent subscriber from exiting on resource creation errors

- ADOPTERS.md
Changes
- Adding wescale chaos engineering reference link 
- Add alignment for borders.
> Aligning the tables for Adopters.md

- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
Route fix for argo graph.
- None.
Minor bug fix.
> Argo route fix.

- litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/TableData.tsx
- changed the viewer's description in dropdown menu
> changed the viewer's description in dropdown menu

- .betterci/ci-k8s-manifest.yml
- litmus-portal/graphql-server/manifests/subscriber.yml
- litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
- litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
- litmus-portal/graphql-server/pkg/graphql/queries/query.go
- litmus-portal/graphql-server/pkg/k8s/custer.go
- litmus-portal/graphql-server/server.go
- litmus-portal/graphql-server/utils/misc.go
- litmus-portal/k8s-manifest.yml
- Moved Subscriber and Self-Deployer images to env-var
> Moved Subscriber and Self-Deployer images to env-var

- ROADMAP.md
- Update the ROADMAP.md based on latest developments 
> (chore)roadmap: update roadmap based on latest developments

- litmus-portal/README.md
Adding separate installation steps for portal
> Adding separate installation steps for portal

- docs/litmus-admin-rbac.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-v1.8.0.yaml
> chore(manifest-1.8.0): Adding litmus installation manifests for 1.8.0

- litmus-portal/k8s-manifest.yml
> Changing image tag to 1.8.0

- litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
fixed the bug of user details not be updated
> fixed update user bug

- litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
> fixed update user bug (#2081)

- ROADMAP.md
Changing litmus portal link in ROADMAP.md
> Changing litmus portal link in ROADMAP.md

- .github/auto-merge.yml
Adding merge bot using github action
> Changing minimum PR approvals

- README.md
- Update the docker pull count with chaos-operator instead of ansible-runner which is depreciated
> (litmus): Update the docker pull count with chaos-operator

- .circleci/config.yml
> Changing docker-build-frontend vm to large

- litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
- litmus-portal/frontend/src/components/WorkflowCard/CardContent.tsx
- litmus-portal/frontend/src/theme/index.tsx
- litmus-portal/frontend/src/utils/yamlUtils.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/ExperimentStatus/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/ExperimentStatus/styles.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunDetailsTable/TableData.tsx
- litmus-portal/frontend/src/views/Home/PassedVsFailed/styles.ts
- litmus-portal/graphql-server/server.go
Adds 1 workflow to litmus portal.
- None.
> chore(litmus-portal): Adding kube-proxy-all workflow with required parser enhancement for it.

- litmus-portal/frontend/public/index.css
- litmus-portal/frontend/src/components/Header/styles.ts
- litmus-portal/frontend/src/components/InputField/styles.ts
- litmus-portal/frontend/src/components/QuickActionCard/index.tsx
- litmus-portal/frontend/src/components/QuickActionCard/style.ts
- litmus-portal/frontend/src/components/SideBar/styles.ts
- litmus-portal/frontend/src/components/WelcomeModal/styles.ts
- litmus-portal/frontend/src/containers/app/App-styles.ts
- litmus-portal/frontend/src/containers/layouts/Scaffold/styles.ts
- litmus-portal/frontend/src/pages/HomePage/style.ts
- litmus-portal/frontend/src/theme/index.tsx
- litmus-portal/frontend/src/views/Home/AverageResilienceScore/styles.ts
- litmus-portal/frontend/src/views/Home/PassedVsFailed/styles.ts
- litmus-portal/frontend/src/views/Home/TotalWorkflows/styles.ts
- This commit will fix the CSS styling issue and make it configurable to use theme.
- Some of the extra variables are added which are an exceptional case.
> (litmus-portal): Fix the styling and css issues

- docs/litmus-operator-v1.8.1.yaml
Adds install manifests for 1.8.1 patch release
> (chore)manifests: add install manifest for v1.8.1

- litmus-portal/graphql-server/server.go
- This PR fixes the CORS issue with the GQL server
- CORS enabled on the GQL server
> CORS Fix for GraphQL Server

- litmus-portal/graphql-server/manifests/subscriber.yml
- litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
- litmus-portal/graphql-server/pkg/self-deployer/start.go
- litmus-portal/graphql-server/utils/misc.go
- litmus-portal/k8s-manifest.yml
Changing Subscriber namespace and deployer namespace to env
> Changing Subscriber namespace and deployer namespace to env

- litmus-portal/cluster-agents/subscriber/pkg/k8s/client.go
- Refactored K8S Client Util functions in subscriber 
> Refactored Subscriber K8s Client Util Functions

- .betterci/ci-k8s-manifest.yml
- .betterci/config.json
> Updated BetterCI Manifest

- docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-ci.yaml
- docs/litmus-operator-v1.8.2.yaml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
> (chore)1.8.2: Add operator yaml for 1.8.2

- litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
- litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
Signed-off-by: Sarthak Jain <sarthak.jain@mayadata.io>
- Updated User Info in the User management tab.
- Fixed search bar issue
- Changed 'name' heading to 'status' in User management table
- Bug fixes
> bug fix: User details updation in usermanagement tab

- CONTRIBUTING.md
> chore(litmus-portal): added title image , fixed a link & few typos

- demo/sample-applications/sock-shop/deploy/monitoring/02-prometheus-rbac.yaml
- docs/litmus-admin-rbac.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-ci.yaml
- docs/litmus-operator-latest.yaml
- docs/litmus-operator-v1.4.0.yaml
- docs/litmus-operator-v1.5.0.yaml
- docs/litmus-operator-v1.6.0.yaml
- docs/litmus-operator-v1.6.1.yaml
- docs/litmus-operator-v1.6.2.yaml
- docs/litmus-operator-v1.7.0.yaml
- docs/litmus-operator-v1.8.0.yaml
- docs/litmus-operator-v1.8.1.yaml
- docs/litmus-operator-v1.8.2.yaml
- litmus-portal/graphql-server/manifests/subscriber.yml
Update CR apiVersion in YAML files, resolves #1963 
Please let me know if there's anything else that needs to be done 😄
> fix: update CRs

- litmus-portal/graphql-server/go.sum
- litmus-portal/graphql-server/graph/generated/generated.go
- litmus-portal/graphql-server/graph/model/models_gen.go
- litmus-portal/graphql-server/graph/schema.graphqls
- litmus-portal/graphql-server/graph/schema.resolvers.go
- litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
- litmus-portal/graphql-server/pkg/self-deployer/start.go
Adding clusterid and clustername response in UserClusterReg Mutation
> Adding clusterid and clustername response in UserClusterReg Mutation

- docs/private_docker_setup.md
Updated private_docker_setup.md
Added bullets to private_docker_setup.md.
Improved readability of the document
> updated private_docker_setup.md

- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/graphql-server/manifests/namespace-subscriber.yml
Adds required resources in API group `litmuschaos.io` to subscriber role.
- None.
Necessary fix.
> (litmus-portal): Fixed subscriber role for getting chaosengines and chaosresults

- litmus-portal/graphql-server/graph/generated/generated.go
- litmus-portal/graphql-server/graph/model/models_gen.go
- litmus-portal/graphql-server/graph/schema.graphqls
- litmus-portal/graphql-server/pkg/database/mongodb/init.go
- litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
Saving cluster yaml token to clusters collection
> Saving cluster yaml token to clusters collection

- litmus-portal/frontend/src/components/Header/styles.ts
- litmus-portal/frontend/src/components/InfoFilled/index.tsx
- litmus-portal/frontend/src/components/InputFieldOutline/index.tsx
- litmus-portal/frontend/src/components/InputFieldOutline/styles.ts
- litmus-portal/frontend/src/components/SideBar/styles.ts
- litmus-portal/frontend/src/pages/HomePage/style.ts
- litmus-portal/frontend/src/pages/Settings/styles.ts
- litmus-portal/frontend/src/theme/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/HeaderSection.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx
- litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/styles.ts
- litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/styles.ts
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/styles.ts
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/styles.ts
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
- litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
Signed-off-by: AVRahul <a.v.rahul11@gmail.com>
Have updated the theme file new label for styles in order to get the styles generic and be used only from the `themes.tsx` file. Also modified some color strings present inside components with a defined label.
> Sync styles and themes for litmus-portal

- README-ko.md
Translate README.md file into Korean.
- Issue #2210
> Translate README.md file into Korean

- litmus-portal/graphql-server/graph/generated/generated.go
- litmus-portal/graphql-server/graph/schema.graphqls
- litmus-portal/graphql-server/graph/schema.resolvers.go
- litmus-portal/graphql-server/pkg/database/mongodb/operations/project.go
- litmus-portal/graphql-server/pkg/project/create.go
This PR contains the following feature implementations:
- User will be able to cancel the invite
- User will be able to remove a team member
- User will be able to resend the invitation 
> (feat Teaming): Cancel invite, Remove member, Resend Invitation  

- litmus-portal/local-dev-env
- litmus-portal/run.sh
- Added dev script to run auth-server and gql-server
- To run the servers you need to do `bash run.sh gql` or `bash run.sh auth`  inside `litmus-portal` dir
> Added Local Dev Script

- litmus-portal/cluster-k8s-manifest.yml
- litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
- litmus-portal/graphql-server/pkg/k8s/client.go
- litmus-portal/graphql-server/pkg/k8s/cluster.go
- litmus-portal/graphql-server/server.go
- litmus-portal/namespaced-K8s-template.yml
- Adding external cluster support for litmusportal
- Some refactors of self-deployer, file-handler functions
> Adding external cluster support for litmusportal

- litmus-portal/run.sh
- Updated run.sh with new env vars
> Updated run.sh with new env vars

- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/components/InfoFilled/index.tsx
- litmus-portal/frontend/src/components/InfoFilled/styles.ts
- litmus-portal/frontend/src/models/redux/analytics.ts
- litmus-portal/frontend/src/models/redux/index.ts
- litmus-portal/frontend/src/pages/Community/index.tsx
- litmus-portal/frontend/src/pages/Community/styles.ts
- litmus-portal/frontend/src/redux/actions/analytics.ts
- litmus-portal/frontend/src/redux/reducers/analytics.ts
- litmus-portal/frontend/src/redux/reducers/index.ts
- litmus-portal/frontend/src/views/Community/CommunityTimeSeriesPlot/index.tsx
- litmus-portal/frontend/src/views/Community/GeoMap/CityMap.tsx
- litmus-portal/frontend/src/views/Community/GeoMap/CountryMap.tsx
Signed-off-by: A4k9 <vansh.a4k9@gmail.com>
Added air-gapped network support screens on the Home and Community pages:
> Added Air-Gapped network support in Home and Community screens

- litmus-portal/README.md
Adding uninstallation steps in LitmusPortal Readme
> Adding uninstallation steps in LitmusPortal Readme

- litmus-portal/cluster-agents/subscriber/pkg/cluster/events/workflow.go
- Ignore Delete Events for Workflows
> Ignore Workflow Delete Events

- monitoring/README.md
Signed-off-by: Ritik Srivastava <ritik.srivastava@mayadata.io>
Changes in the sock-shop readme 
Change in the run command and a few instructions added for better understanding for the first time user
> sock-shop-readme-update

- README-chn.md
Chinese translation for the README document. @prithvi1307.
> Add Chinese translation of the README.md

- litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
This PR adds:
- Redux state while workflow creation
- Fetch policy in teaming section
> Added the redux state while workflow creation and fetch policy in teaming

- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunDetailsTable/styles.ts
- litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts
Signed-off-by: AVRahul <a.v.rahul11@gmail.com>
Updated a few minor / missing styles changes in order to make Kubera-litmus styles in sync.
> Adding a few minor styles changes

- README.md
> (fix)readme: remove limitation around network chaos support on containerd & crio runtime

- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
Adding namespace in argo chaos SA
> Bug-fix: Adding namespace in argo chaos SA

- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
- litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
- litmus-portal/frontend/src/components/Targets/TargetCopy/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
- litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts
This is adding endpoint to yaml link and refactoring.
> Added endpoint for yaml fetch and refactoring of targets

- litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
Fixed onKeyPressed Enter bug. If entered details in not validated the information would not be saved, it won't be possible to proceed to the next step.
> chore(litmus-portal): Fixed onKeyPressed Enter Bug

- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
- litmus-portal/frontend/src/views/Settings/TeammingTab/styles.ts
- litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
This PR add:
- Pagination in footers
- Scrollbar in tables
- Removed pollInterval in BrowseWorkflow Tables
> Added pagination in footer and scrollbar in table.

- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/styles.ts
- litmus-portal/frontend/src/views/Home/ReturningHome/index.tsx
- litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
This PR fixes bugs and adds error handlers for analytics.
- None.
High Priority bug-fix PR.
> (litmus-portal): Bug fixes and error handling related to analytics.

- litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
- litmus-portal/cluster-agents/subscriber/subscriber.go
- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/graphql-server/manifests/namespace-subscriber.yml
adding create configmap permission and few refactors in subscriber
> adding create configmap permission in subscriber manifest and few refactors in subscriber

- litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
- litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
Disabling export and analytics button.
- None.
Bugfix
> (litmus-portal): disabled export and analytics button

- litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
- litmus-portal/frontend/src/components/Targets/ConnectHome/styles.ts
- litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
- litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/styles.ts
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/TableData.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
Signed-off-by: Vansh Bhatia <vansh.bhatia@mayadata.io>
- Added "data-cy" tags required for the latest Cypress tests 
- fixed a bug in the invitation section described below:
When no project is selected (known bug, no fix yet):
The invitation/received tab crashes:
Added a check to avoid this
- Added the role being invited for in the invitation/received
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
> data-cy, invitation bug fix, Role visibility in manage team

- litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/styles.ts
This PR add:
- TimeZone generation in Cron Workflows
> chore(litmus-portal): Added timezone generation for cron workflows

- litmus-portal/namespaced-K8s-template.yml
- litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Okteto manifest update for litmus-portal.
- None.
Bug-fix / Update
> Okteto manifest update for litmus-portal.

- docs/litmus-admin-rbac.yaml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
> chore(permission): Add minimal permission for litmus-admin rbac

- litmus-portal/namespaced-K8s-template.yml
Using downward API instead of env variable for portal namespace.
- None.
Minor config change.
> (litmus-portal): using downward api for portal ns

- litmus-portal/README.md
> Changing version to 1.9.x in readme

- docs/litmus-admin-rbac.yaml
- litmus-portal/README.md
- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
- litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
- litmus-portal/frontend/src/components/Targets/ConnectHome/styles.ts
- litmus-portal/frontend/src/components/Targets/TargetCopy/styles.ts
- litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
- litmus-portal/frontend/src/pages/WorkflowDetails/TopNavButtons.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
- litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/SetTime/styles.ts
- litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
- litmus-portal/frontend/src/views/Home/ReturningHome/style.ts
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/ReceivedInvitations/styles.ts
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/TableData.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/Invitation/SentInvitations/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/InviteNew/Invite/index.tsx
- litmus-portal/frontend/src/views/Settings/TeammingTab/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/DelUser/index.tsx
- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/graphql-server/manifests/namespace-subscriber.yml
- litmus-portal/namespaced-K8s-template.yml
- litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Cherry pick from master to v1.9.x
> Cherry pick from master to v1.9.x

- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-latest.yaml
- docs/litmus-operator-v1.9.0.yaml
> chore(manifest): Adding the 1.9.0 litmus installation manifests

- docs/chaos-scheduler-v1.9.0.yaml
This PR adds a consolidatedyaml pf chaos scheduler
> adding chaos scheduler yaml

- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowRunsBarChart/index.tsx
Fixed bug in UI for bar graph extra width of failed experiments.
- None.
Minor bug-fix.
> (litmus-portal): failed experiments bar width fix for graph

- MAINTAINERS
Signed-off-by: Jayesh Kumar <k8scncf@gmail.com>
> Updating contact info

- monitoring/README.md
- monitoring/platforms/kublr/README.md
- monitoring/utils/prometheus/prometheus-scrape-configuration/01-prometheus-rbac.yaml
- monitoring/utils/prometheus/prometheus-scrape-configuration/02-prometheus-configMap.yaml
- monitoring/utils/prometheus/prometheus-scrape-configuration/prometheus-alert-rules.yaml
- monitoring/utils/prometheus/prometheus-scrape-configuration/prometheus-deployment.yaml
- monitoring/utils/prometheus/prometheus-scrape-configuration/prometheus-service.yaml
Adding prometheus config to support scrape job model.
- None.
Monitoring update for prometheus scrape jobs.
> monitoring update to support scrape jobs and minor bug-fix.

- translations/README-es.md
> Spanishtranslation2

- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/graphql-server/manifests/namespace-subscriber.yml
Chaging ImagePullPolicy to Always for workflow executor image
> Chaging ImagePullPolicy to Always for workflow executor image

- docs/litmus-operator-v1.9.1.yaml
> chore(v1.9.1): Adding manifests for v1.9.1

- litmus-portal/graphql-server/go.sum
- litmus-portal/graphql-server/graph/generated/generated.go
- litmus-portal/graphql-server/graph/model/models_gen.go
- litmus-portal/graphql-server/graph/schema.graphqls
- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/graphql-server/manifests/namespace-subscriber.yml
- litmus-portal/graphql-server/pkg/database/mongodb/init.go
- litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
- litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
- litmus-portal/graphql-server/pkg/self-deployer/start.go
- litmus-portal/graphql-server/utils/misc.go
Signed-off-by: Harsh Shekhar <harsh.shekhar@mayadata.io>
This PR intends to do the following changes:
- Add agent namespace, agent scope and serviceaccount to be used for agent registration in `UserClusterReg` schema.
> chore(update): user cluster registration schema

- CODE_OF_CONDUCT.md
> Spelling error

- translations/README-ge.md
First translation of the English README to German.
None.
I have not added the links to the German version in the Translations-file, because I did not think I should do so. Also I did not add the new "flags-symbols" because I don't know how this would work.
> German readme

- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/graphql-server/manifests/namespace-subscriber.yml
- litmus-portal/graphql-server/utils/misc.go
Refactoring manifest parser function for the fields(agent-namespace and service account)
> Refactoring manifest parser function for the fields(agent-namespace and service account)

- litmus-portal/cluster-k8s-manifest.yml
- litmus-portal/namespaced-K8s-template.yml
Agent scope env for litmus-portal frontend
> Agent scope for litmus-portal frontend

- litmus-portal/cluster-agents/subscriber/pkg/gql/mutations.go
- litmus-portal/cluster-agents/subscriber/pkg/gql/util.go
- litmus-portal/graphql-server/go.sum
- litmus-portal/graphql-server/graph/generated/generated.go
- litmus-portal/graphql-server/graph/model/models_gen.go
- litmus-portal/graphql-server/graph/schema.graphqls
- litmus-portal/graphql-server/pkg/database/mongodb/init.go
- litmus-portal/graphql-server/pkg/database/mongodb/operations.go
- litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
> Added Patch to handle duplicate workflow events

- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
- litmus-portal/frontend/src/models/graphql/clusterData.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
- litmus-portal/frontend/src/views/Home/PassedVsFailed/index.tsx
- litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
Minor bug fixes in custom worklfow section and fixed some known issues
> Bug fixes in custom workflow section and added autocomplete search for experiment selection

- ROADMAP.md
> (chore)roadmap: update roadmap

- litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
- Struct conversion for weights
- Fixing typos in document fields
- Adding workflowid in the updated manifest
> Refactoring update workflow function

- litmus-portal/graphql-server/go.mod
- litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
- litmus-portal/graphql-server/pkg/graphql/subscriptions/subscription.go
- litmus-portal/graphql-server/pkg/graphql/types.go
Replacing agent namespace with workflow manifest namespace
> Replacing agent namespace with workflow manifest namespace

- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
- litmus-portal/frontend/src/components/Targets/ClusterInfo/styles.ts
- litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
- litmus-portal/frontend/src/graphql/mutations.ts
- litmus-portal/frontend/src/graphql/quries.ts
- litmus-portal/frontend/src/models/graphql/clusterData.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
Signed-off-by: Oum Kale <oum.kale@mayadata.io>
This PR is adding a Delete cluster feature for targets. We can delete cluster from Cluster Info screens as well as Table now.
Added Delete Cluster
gql integration
Updated mutation, queries, and modal  
Back Button 
> Added Delete Cluster Feature For Targets

- litmus-portal/authentication/pkg/store/user.go
- litmus-portal/authentication/pkg/types/const.go
- litmus-portal/cluster-k8s-manifest.yml
- litmus-portal/graphql-server/pkg/database/mongodb/init.go
- litmus-portal/namespaced-K8s-template.yml
- litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
- Adding auth credentials to MongoDB deployment 
- Refactoring gql-sever and auth-server to login with credentials
- Adding env vars to the manifests (cluster, namespace, okteto)
> (litmus-portal): Adding auth credentials to MongoDB deployment and refactoring gql-sever and auth-server 

- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
This PR changes litmus-portal analytics report version from 1.9 to 1.10.
- None.
Report version update PR.
> Litmus portal analytics report version change

- litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
- litmus-portal/frontend/src/graphql/quries.ts
- litmus-portal/frontend/src/models/graphql/scheduleData.ts
- litmus-portal/frontend/src/utils/workflowTemplate.ts
> Updated graphql query in frontend and added cron support for custom workflow 

- litmus-portal/graphql-server/go.sum
- litmus-portal/graphql-server/graph/generated/generated.go
- litmus-portal/graphql-server/graph/model/models_gen.go
- litmus-portal/graphql-server/graph/myhub.graphqls
- litmus-portal/graphql-server/graph/schema.graphqls
- litmus-portal/graphql-server/graph/schema.resolvers.go
- litmus-portal/graphql-server/graph/usermanagement.graphqls
- litmus-portal/graphql-server/pkg/database/mongodb/operations/myhub.go
- litmus-portal/graphql-server/pkg/database/mongodb/operations/usermanagement.go
- litmus-portal/graphql-server/pkg/database/mongodb/schema/myhub.go
- litmus-portal/graphql-server/pkg/database/mongodb/schema/usermanagement.go
- litmus-portal/graphql-server/pkg/myhub/gitops/gitops.go
- litmus-portal/graphql-server/pkg/myhub/handler/handler.go
- litmus-portal/graphql-server/pkg/myhub/myhub.go
- litmus-portal/graphql-server/pkg/project/create.go
- litmus-portal/graphql-server/pkg/synchandler/sync-handler.go
- litmus-portal/graphql-server/pkg/usermanagement/create.go
- Moved MyHub from Users collection to MyHub collection with project ID
> Migrated MyHub from users collection to MyHub collection

- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/components/PredifinedWorkflows/index.tsx
- litmus-portal/frontend/src/graphql/mutations.ts
- litmus-portal/frontend/src/graphql/quries.ts
- litmus-portal/frontend/src/models/redux/workflow.ts
- litmus-portal/frontend/src/pages/MyHub/index.tsx
- litmus-portal/frontend/src/redux/reducers/workflow.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/Templates/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/styles.ts
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
- litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
- litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
- litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>
**This PR will:**
**- Add changes changes for myhubs, creation of custom workflows and default hub to associate them with project collection.**
> Added changes for My Hub and Custom workflows with Project ID association.

- litmus-portal/frontend/src/models/graphql/clusterData.ts
- litmus-portal/frontend/src/models/graphql/user.ts
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/index.tsx
> chore(litmus-portal): Removed unused variables from the models

- ADOPTERS.md
- adopters/users/Shantanu_Deshpande.md
> (adopters)update: add shantanu as adopter

- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/components/SideBar/index.tsx
- litmus-portal/frontend/src/components/SideBar/styles.ts
Added portal version in sidebar.
> chore(litmus-portal): Added portal version in sidebar

- litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
- litmus-portal/frontend/src/components/Targets/ConnectTarget/index.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
> Cherry picking from master to 1.10.x 

- ADOPTERS.md
- adopters/organizations/akridata.md
PR created on the basis of the following comment: https://github.com/litmuschaos/litmus/issues/2191#issuecomment-721777430  by [Keerthi Sagar](https://www.linkedin.com/in/keerthi-sagar-c-s-17809285/) 
> (adopters)update: add akridata as an adopter

- litmus-portal/README.md
- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/litmus-portal-crds.yml
> Upgrading litmus portal version and litmus crds

- docs/chaos-scheduler-v1.10.0.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
- docs/litmus-operator-ci.yaml
- docs/litmus-operator-latest.yaml
- docs/litmus-operator-v1.10.0.yaml
- docs/litmus-operator-v1.9.0.yaml
- docs/litmus-operator-v1.9.1.yaml
> update(chaosengine-crd): updating chaosengine crd

- litmus-portal/README.md
- litmus-portal/cluster-k8s-manifest.yml
- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/litmus-portal-crds.yml
- litmus-portal/namespaced-K8s-template.yml
- litmus-portal/run.sh
> Upgrading litmus-portal version and chaos crds to v1.10.0

- .circleci/config.yml
> Fixing circleci config

- .circleci/config.yml
> Cheery-pick from master

- ADOPTERS.md
- adopters/organizations/raspbernetes.md
> (adopters)update: add raspbernetes project as an adopter

- litmus-portal/graphql-server/pkg/project/create.go
Printing error instead of return in case of failed cloning
> Printing error instead of return in case of failed cloning

- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
This PR adds few changes in the custom workflow section.
1. If there is no hub available, the construct experiment from myhub option is disabled
2. If an experiment is added, the upload feature is disabled
> chore(litmus-portal): Minor fix in custom workflow creation

- litmus-portal/graphql-server/pkg/myhub/myhub.go
- litmus-portal/graphql-server/pkg/project/create.go
- litmus-portal/graphql-server/pkg/usermanagement/create.go
Adding go routine to cloning default myhub function
> Adding go routine to cloning default myhub function

- docs/litmus-operator-ci.yaml
Generated cluster rules are incorrect. 
Before:
After:
> Fix rules of the ClusterRole

- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/styles.ts
This PR adds:
1. Workflow deletion fix in which the viewer can not delete the scheduled workflow
2. AnnotationCheck in custom workflow creation.
> Added annotationCheck and fixed workflow deletion by viewer

- litmus-portal/run.sh
> Adding DB credentials to run.sh

- litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
- litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
- litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
> Added annotation and app info check and fixed the namespace issue in custom workflow creation

- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/styles.ts
Signed-off-by: oumkale <oum.kale@mayadata.io>
This PR will not allow deleting cluster and show tooltip for permission.
> Delete cluster permission fixed

- docs/chaos-scheduler-v1.11.0.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-ci.yaml
- docs/litmus-operator-latest.yaml
- docs/litmus-operator-v1.11.0.yaml
> chore(1.11.0): Adding installation manifests for the v1.11.0

- .circleci/config.yml
- litmus-portal/README.md
- litmus-portal/cluster-k8s-manifest.yml
- litmus-portal/frontend/public/locales/en/translation.yaml
- litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
- litmus-portal/graphql-server/manifests/cluster-subscriber.yml
- litmus-portal/graphql-server/manifests/namespace-subscriber.yml
- litmus-portal/litmus-portal-crds.yml
- litmus-portal/namespaced-K8s-template.yml
- litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Upgrading litmus portal to v1.11.0
Changes
- Removing Unprivileged frontend from circleci build
- Upgrading litmus portal version in UI and README.md
- Upgrading litmus operator and runner to v1.11.0
> Upgrading litmus portal to v1.11.0

- litmus-portal/cluster-k8s-manifest.yml
- litmus-portal/namespaced-K8s-template.yml
- litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Changing the image tag of litmus portal from ci to 1.11.0
> Changing the image tag of litmus portal from ci to 1.11.0

- litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
Adding minimum poll interval to get updated data constantly and to fix loading bug.
- None.
Bug-fix PR
> Analytics loading and data bug fixed

- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-v1.11.0.yaml
> (chore)chaos-runner: update chaos-runner to 1.11.1 patch version

- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-v1.11.2.yaml
> (chore)manifests: update manifests with 1.11.2 tags

- docs/api.html
> (chore)apidocs: fix api doc title

- .circleci/config.yml
> increase circleci frontend build timeout

- monitoring/utils/prometheus/prometheus-scrape-configuration/02-prometheus-configMap.yaml
- monitoring/utils/sample-application-under-test/sock-shop/user-load.yaml
Updated user-load manifest and Prometheus scrap time
> Updated user-load manifest and Prometheus scrap time

- litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
- litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
InputFields modified in Settings Page
> InputField BugFix in Settings Page

- docs/chaos-scheduler-v1.12.0.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
- docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
- docs/litmus-operator-latest.yaml
- docs/litmus-operator-v1.12.0.yaml
> (chore)manifests: update install manifests for 1.12.0

- litmus-portal/cluster-k8s-manifest.yml
- litmus-portal/namespaced-K8s-template.yml
- litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
> changing image tag to 1.12.0

- litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
Updated a minor bug in the disabling logic
> Readjusting Disabling logic

- ADOPTERS.md
- adopters/organizations/kublr.md
Adding Kubrr as Adopter 
Reference -- https://github.com/litmuschaos/litmus/issues/2191#issuecomment-767119502
> Adding Kublr as adopter reference #2191

- litmus-portal/frontend/src/components/ExperimentHeader/index.tsx
- litmus-portal/frontend/src/graphql/queries.ts
- litmus-portal/frontend/src/models/redux/myhub.ts
- litmus-portal/frontend/src/views/MyHub/MyHubCharts/chartCard.tsx
- litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
- litmus-portal/frontend/src/views/MyHub/MyHubExperiment/index.tsx
> Added private hub icons and minor fix

- .circleci/config.yml
- litmus-portal/Makefile
- litmus-portal/cluster-agents/event-tracker/build/Dockerfile
- litmus-portal/cluster-agents/event-tracker/event-tracker.go
- litmus-portal/cluster-agents/event-tracker/go.mod
- litmus-portal/cluster-k8s-manifest.yml
- litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
- litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
- litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
- litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
- litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
- litmus-portal/graphql-server/pkg/types/configurations.go
- litmus-portal/graphql-server/utils/misc.go
- litmus-portal/namespaced-K8s-template.yml
Changes
- Adding event tracker code to cluster agents
- Adding event tracker image build and push step to circleci
- Adding event tracker manifest to external cluster manifest.
> Adding event tracker as part of gitops

- litmus-portal/graphql-server/pkg/gitops/handler/handler.go
> Minor fix for Gitops Notifier
