litmuschaos/litmus

litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml

Adding configmap permission to event tracker

---

litmus-portal/cluster-agents/event-tracker/event-tracker.go

Changing logic in event-tracker for update event

Changing logic in event-tracker for update event

---

litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go

changing rbac name for event tracker and change in workflow_id access

changing rbac name for event tracker and change in workflow_id access

---

litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx

This PR adds:
- Kubera UI textfileds in Welcome Modal

chore(litmus-portal): Updated the inputfields to Kubera-UI inputfields in welcome modal

---

litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/createLabel.ts
litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts

fixed argo graph for firefox

---

litmus-portal/graphql-server/pkg/gitops/gitops.go
litmus-portal/graphql-server/pkg/gitops/handler/handler.go
litmus-portal/graphql-server/pkg/gitops/util.go

Fixed a bug for delete workflow operation when the workflow doesn't exists in git

Updated Delete Operation for Git

---

litmus-portal/graphql-server/pkg/gitops/handler/handler.go

Fixies issue in gitops workflow operation

Minor Fix GitOps

---

litmus-portal/README.md
litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseAnalytics/WorkflowComparisonTable/index.tsx
litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
litmus-portal/litmus-portal-crds.yml

Upgrading litmusportal to 1.13.0

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-K8s-template.yml

version upgrade to 1.13.0 in the k8s manifest

---

docs/chaos-scheduler-v1.13.0.yaml
docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
docs/litmus-operator-ci.yaml
docs/litmus-operator-v1.13.0.yaml

feat(v1.13.0): Adding manifests for the 1.13.0

---

docs/chaos-scheduler-v1.10.0.yaml
docs/chaos-scheduler-v1.12.0.yaml
docs/chaos-scheduler-v1.13.0.yaml

feat(image): updating image tag for scheduler

---

docs/litmus-operator-v1.13.0-crd-v1.yaml

Signed-off-by: udit <udit.gaurav@mayadata.io>

Chore(v1-crd): Update v1-crds for version 1.13.0

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml

Signed-off-by: oumkale <oum.kale@mayadata.io>
Added `deletecollection` resource for litmus-admin ClusterRole

Added `deletecollection` resource for litmus-admin ClusterRole

---

litmus-portal/frontend/package-lock.json
litmus-portal/frontend/package.json
litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
litmus-portal/frontend/src/containers/app/App.tsx
litmus-portal/frontend/src/pages/HomePage/index.tsx
litmus-portal/frontend/src/pages/LoginPage/index.tsx
litmus-portal/frontend/src/pages/Workflows/index.tsx
litmus-portal/frontend/src/react-app-env.d.ts
litmus-portal/frontend/src/testHelpers/ThemeWrapper.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
litmus-portal/frontend/src/views/MyHub/MyHubConnect/myHubInput.tsx
litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx

Updated Litmus Portal with Litmus-UI

---

litmus-portal/frontend/package-lock.json
litmus-portal/frontend/package.json
litmus-portal/frontend/src/components/Targets/ClusterInfo/index.tsx
litmus-portal/frontend/src/components/Targets/ConnectHome/index.tsx
litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
litmus-portal/frontend/src/containers/app/App.tsx
litmus-portal/frontend/src/pages/HomePage/index.tsx
litmus-portal/frontend/src/pages/LoginPage/index.tsx
litmus-portal/frontend/src/pages/Workflows/index.tsx
litmus-portal/frontend/src/react-app-env.d.ts
litmus-portal/frontend/src/testHelpers/ThemeWrapper.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowCluster/index.tsx
litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
litmus-portal/frontend/src/views/MyHub/MyHubConnect/myHubInput.tsx
litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx
litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx

Bootstrap Litmus with Litmus-UI

---

litmus-portal/frontend/package.json
litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
litmus-portal/frontend/src/containers/layouts/Row/index.tsx
litmus-portal/frontend/src/pages/SchedulePage/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/styles.ts

Added select agents screen

---

litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/model/models_gen.go
litmus-portal/graphql-server/graph/schema.graphqls
litmus-portal/graphql-server/graph/schema.resolvers.go
litmus-portal/graphql-server/pkg/gitops/handler/handler.go

- Added query to get gitops status and details

Added gql query to get GitOps details

---

litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts

Signed-off-by: oumkale <oum.kale@mayadata.io>
Custom Card for Sock-Shop Predefined Workflow

Custom Card for Sock-Shop Predefined Workflow

---

.circleci/config.yml
litmus-portal/frontend/Dockerfile
litmus-portal/frontend/src/components/SideBar/index.tsx
litmus-portal/frontend/src/components/SideBar/styles.ts

Adding {version, buildtime} to frontend ui and respective changes to {circle, Dockerfile}

(circleci/frontend): Adding {version, buildtime} to frontend ui and respective changes to {circleci, Dockerfile} 

---

litmus-portal/frontend/public/locales/en/translation.yaml

formatting translation file for the steps of connecting cluster

minor formatting translation file for the steps of connecting cluster

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/graphql/queries.ts
litmus-portal/frontend/src/models/graphql/clusterData.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseCluster/TableData.tsx
litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/model/models_gen.go
litmus-portal/graphql-server/graph/schema.graphqls
litmus-portal/graphql-server/graph/schema.resolvers.go
litmus-portal/graphql-server/pkg/cluster/handler/handler.go

(fix): Targets table workflow run time update

(fix): Targets table workflow run time update

---

MAINTAINERS

- Update the Email and Company name

Update the Maintainers email and company

---

ADOPTERS.md
adopters/organizations/orange.md

Signed-off-by: SamarSidharth <samar.sidharth89@gmail.com>

Updating ADOPTERS.md

---

litmus-portal/authentication/pkg/generates/jwt_access.go
litmus-portal/authentication/pkg/models/user.go

retriving role from mongodb in litmusportal auth server

retriving role from mongodb in litmusportal auth server

---

litmus-portal/frontend/src/components/WorkflowCard/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

https://github.com/litmuschaos/litmus/issues/2496

Removed generateName in upload YAML functionality

---

adopters/organizations/redhat.md

Signed-off-by: Jordi Gil <jgil@redhat.com>
Add Red Hat as a Litmus adopter
N/A

Add Red Hat as Litmus adopter

---

ADOPTERS.md
adopters/organizations/redhat.md

(chore)adopters: add Red Hat adoption story in ADOPTERS.md file

---

litmus-portal/frontend/src/components/QuickActionCard/index.tsx
litmus-portal/frontend/src/views/AnalyticsDashboard/DataSource/Forms/prometheus.tsx

* Basic auth disabled for data source
* Added complete path for API docs
- None.
Bug fix PR

Basic auth disabled for data source and added complete path for API docs

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts

* Added Workflow Settings Details Modification
* Added Navigation and Alerts

Added Workflow Settings Details Modification + Navigation

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/styles.ts

This PR adds the Add Probe modal which will be used in the Tune Workflow screens.

chore(litmus-portal): Add Add Probe modal

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddExperimentModal.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

This PR adds:
- MyHub Option in select workflow
- Queries to fetch ChaosEngine and Experiment YAML

Added Myhub option and gql queries to fetch the chaosengine and experiment YAML

---

litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/model/models_gen.go
litmus-portal/graphql-server/graph/project.graphqls
litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go
litmus-portal/graphql-server/pkg/project/create.go

Signed-off-by: SarthakJain26 <sarthak.jain@mayadata.io>
- Updated MemberInput interface (replaced username with userID)
- Updated mongo queries to fetch details using UID

Updated mongo queries to use UID as unique identifier

---

litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
litmus-portal/frontend/src/components/WorkflowCard/styles.ts

Signed-off-by: oumkale <oum.kale@mayadata.io>
Update card styles for Infra-Chaos tag

Update card styles for Infra-Chaos tag

---

litmus-portal/README.md
litmus-portal/cluster-agents/event-tracker/build/Dockerfile
litmus-portal/cluster-agents/event-tracker/event-tracker.go
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
litmus-portal/namespaced-K8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

Converting mongodb deployment to statefulset

Converting mongodb deployment to statefulset

---

litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx
litmus-portal/frontend/src/utils/auth.ts

- minor fixes in stepper conditions of the welcome modal
- updated return statements of auth-utility function to avoid the crashing of the site in case of empty name and email field in jwt token

welcome modal bug fix

---

litmus-portal/frontend/src/models/graphql/user.ts
litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/index.tsx

Signed-off-by: SarthakJain26 <sarthak.jain@mayadata.io>
- Admin won't be able to edit user details of the created user.
- Code refactor

Revoking admin's privileges to edit created user's fullname and email

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/SideBar/index.tsx
litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx

This PR adds:
- Fixed the My Hub typo
- Updated the GitOps section to show the input fields on only when the Git repository option is selected

chore(litmus-portal): Fixed the MyHubs typo and updated the Gitops section

---

litmus-portal/frontend/src/components/InfoFilled/index.tsx
litmus-portal/frontend/src/pages/Community/index.tsx
litmus-portal/frontend/src/pages/Community/styles.ts

* updated dev.to link
* updated text on the card

Minor text and link fixes for community page.

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/models/dashboardsData.ts
litmus-portal/frontend/src/pages/MonitoringDashboardPage/index.tsx
litmus-portal/frontend/src/pages/MonitoringDashboardPage/styles.ts
litmus-portal/frontend/src/pages/SelectAndConfigureDashboards/Configure.tsx
litmus-portal/frontend/src/utils/promUtils.ts
litmus-portal/frontend/src/utils/timeDifferenceString.tsx
litmus-portal/frontend/src/views/AnalyticsDashboard/KubernetesDashboards/Table/TableData.tsx
litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/PanelContent.tsx
litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/OverviewQuickActionCard/index.tsx
litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dashboardData.tsx
litmus-portal/frontend/src/views/AnalyticsDashboard/Overview/Tables/dataSource.tsx

* makes the dashboard smooth and fast for browsing.
* optimized memory usage and high processing overhead while viewing
* hard refresh bug fixed
* multiple metrics bug fixed
PR for bug fix (2.0 beta 1)

link, state management fix for reducing computational cost for analytics dashboard.

---

docs/2.0.0-Beta1/litmus-2.0.0-Beta1.yaml
docs/2.0.0-beta1/litmus-2.0.0-beta1.yaml
litmus-portal/README.md

Adding litmus-2.0.0-beta1 manifest

Adding litmus-2.0.0-Beta1 manifest

---

docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
docs/litmus-operator-ci.yaml
docs/litmus-operator-latest.yaml
docs/litmus-operator-v1.13.2.yaml

Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
- Adding manifests for the 1.13.2

feat(v1.13.2): Adding manifests for the 1.13.2

---

litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/index.tsx

fixed issue of workflow table dropdown not working, made the workflow name clickable

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/models/graphql/invite.ts
litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx
litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/styles.ts
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts

Signed-off-by: SarthakJain26 <sarthak.jain@mayadata.io>
- Removed delete button in sent invitation tab for the users having invitation status as `exited` or `declined`
- minor style changes
- Updated text in translation

minor bug fix in settings tab

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

Updated the YAML generation utility

---

litmus-portal/frontend/src/components/WorkflowStepper/index.tsx

This PR adds:
- Loader in the finish button of verify and commit screen
Fixes the issue #2549 

chore(litmus-portal): Added loader in verify and commit finish button

---

litmus-portal/frontend/src/pages/MyHub/customMyHubCard.tsx
litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/CreateWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx

This PR adds:
- Changed the fetchPolicy while getting the ChaosEngine and Experiment YAMLs
- Added a check to disable a viewer to update MyHub details

Updated the fetch policy for getting experiment and engine yaml from MyHub

---

litmus-portal/README.md

[chore] - Update Beta link Docs

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

Populating Custom Chaos Table

---

litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts

* Fixes the data adding bug with custom experiments
* Fixes UI layout style issues

chore(litmus-v2): Fixed Adding Experiment data to Table Bug 🐛

---

litmus-portal/frontend/src/models/localforage/workflow.ts
litmus-portal/frontend/src/models/redux/workflow.ts
litmus-portal/frontend/src/redux/actions/workflow.ts
litmus-portal/frontend/src/redux/reducers/index.ts
litmus-portal/frontend/src/redux/reducers/workflow.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

* Added Redux state for Manifest only
* Fixed Roll back local forage persistance

Added Redux state for Manifest only + Fixed Roll back local forage persistance ❤🩹

---

litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/models/redux/workflow.ts
litmus-portal/frontend/src/redux/reducers/workflow.ts
litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/WeightSlider/index.tsx

This PR adds:
- Updated the table component
- Added vertical stepper for Custom and Pre-defined workflows
- Added logic to add ChaosEngine changes to main workflow YAML
- Added probe details pop-over
- Updated the weight slider component

chore(litmus-portal): Added vertical stepper, logic to add ChaosEngine changes and updated weight slider component

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ExtractSteps.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/UpdateCRD.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

* Extracted Experiment details 💻
* Fixed workflow preview render 🛠️

chore(v2): Extracted Experiment details and Fixed workflow preview render 🛠️

---

litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

This PR adds:
- Probes deletion logic
- Updated the weight slider
- Minor Bug fix

Added probe deletion logic and minor fix

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

* Workflow Table changes would be saved in Table
* Works for both Custom Workflow and Pre-Defined Workflows

chore(litmus-v2): Updated manifest saving logic to save updated ChaosEngine and reflect on Table 🌻

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
litmus-portal/frontend/src/components/Header/styles.ts
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/styles.ts
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/styles.ts
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/styles.ts

- Enhanced UI for teaming
- Fixed Leave Project Bug

UI enhancements in teaming

---

.github/workflows/push.yml

Adding build time and version args to docker build of frontend

Adding buildtime and version args to docker build of frontend

---

litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/pkg/database/mongodb/workflow/operations.go

This PR fixes the issue with workflow run last_updated field. The last_updated field for some older workflows were overwritten when a new workflow run of the same schedule is executed.

Fixed workflow run update bug

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/AdjustedWeights/index.tsx
litmus-portal/frontend/src/components/AdjustedWeights/styles.ts
litmus-portal/frontend/src/components/ProgressBar/AnalyticsLinearProgressBar/index.tsx
litmus-portal/frontend/src/components/ProgressBar/AnalyticsLinearProgressBar/styles.ts
litmus-portal/frontend/src/components/ProgressBar/LinearProgressBar/index.tsx
litmus-portal/frontend/src/components/ProgressBar/LinearProgressBar/styles.ts
litmus-portal/frontend/src/pages/MyHub/index.tsx
litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowRunDetailsTable/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/ExperimentPoints.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/ScheduleWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/ResultTable.tsx

This PR adds:
- Updated LinearProgressBar Component
- Fixed Argo graph not rendering issue
- Changed the RR score for workflow in running phase
- Updated permissions to re-run and delete workflow

chore(litmus-portal): Updated the Linear ProgressBar component and some minor bug fixes

---

litmus-portal/frontend/src/containers/app/App.tsx

Signed-off-by: Vansh Bhatia <vansh@chaosnative.com>
Added checks to avoid frontend URL manipulation, conditions tested:
Both project ID and Role removed :heavy_check_mark: 
- Ex:  `http://localhost:3001/home`
Self project + Role change (random role) :heavy_check_mark: 
- Ex: `http://localhost:3001/home?projectID=541f2cc2-fbf2-4e74-95db-ad4397b1856e&projectRole=sdljkdhfaslkd`
Self project + Role removal  :heavy_check_mark: 
- Ex: `http://localhost:3001/home?projectID=541f2cc2-fbf2-4e74-95db-ad4397b1856e` / `http://localhost:3001/home?projectID=541f2cc2-fbf2-4e74-95db-ad4397b1856e&projectRole=`
Non existent project + any Role :heavy_check_mark: 
- Ex: `http://localhost:3001/home?projectID=sakjdhdashdkjashkld&projectRole=Owner`
Existing project (Not a member) + any Role :heavy_check_mark: 
- …

Added checks to avoid frontend URL manipulation

---

GoogleSeasonOfDocs.md

(chore)GSoD: Project Proposal Page

---

litmus-portal/frontend/src/views/GetStarted/ProjectSet/index.tsx
litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/index.tsx

- Fixed the translation 
- added error for `create` user API
- added conditional rendering for `go to projects` based on user role in project

Added beta2 fixes for auth and teaming

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/README.md

Upgrading litmusportal image tags, docs to v2.0.0-Beta1

---

litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

This PR adds:
- Integration of Probes Modal
- Updated the Vertical Stepper
- Minor fixes

chore(litmus-portal): Integrated the Probes modal and updated the vertical stepper

---

litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/models/localforage/workflow.ts
litmus-portal/frontend/src/pages/SchedulePage/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts

* Added Workflow Scheduling for both Pre defined and Custom Workflows
* Fixed UI layout of v2 workflow screens

chore(v2): Added Workflow Scheduling and UI Fixes 📆

---

litmus-portal/frontend/src/utils/auth.ts
litmus-portal/frontend/src/views/GetStarted/ProjectSet/index.tsx

Adding user to litmusDB at time of login, if user exists in authDB but not in litmusDB to prevent data inconsistency.

Adding user to litmusDB at the time of login

---

litmus-portal/frontend/src/components/Tabs/index.tsx
litmus-portal/frontend/src/models/graphql/workflowData.ts
litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx

**This PR will** 
- remove the Resiliency score calculation and local tab component from dagre graph screen.
- made the tab component more generic so that it can be used in other places. ( In components directory )

Removed the Resiliency score calculation and local tab component from dagre graph screen

---

.github/workflows/build.yml

**Filter for the litmus-portal directory wasn't allowing the status for jobs to be reported as skipped/failed/succeeded that are marked as required in GitHub settings of Litmus Repository.**

Fixed Github Action 

---

.github/workflows/push.yml
litmus-portal/cluster-agents/subscriber/pkg/cluster/objects/objects.go
litmus-portal/cluster-agents/subscriber/pkg/gql/subscriptions.go
litmus-portal/cluster-agents/subscriber/pkg/gql/util.go

- Fix failing CI tests
- Remove go imports check from push.yml
- This change was requested in #2632 

Fix failing CI tests and remove go imports check from push.yml

---

.bettercodehub.yml

chore(bch): Updating BCH config 🤯

---

.bettercodehub.yml

chore(bch): Updating bch path in config

---

litmus-portal/frontend/package-lock.json
litmus-portal/frontend/package.json
litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/pages/LoginPage/index.tsx
litmus-portal/frontend/src/views/AnalyticsDashboard/LitmusDashboard/WorkflowComparisonPlot/index.tsx
litmus-portal/frontend/src/views/GetStarted/PasswordSet/index.tsx
litmus-portal/frontend/src/views/GetStarted/PasswordSet/styles.ts
litmus-portal/frontend/src/views/GetStarted/ProjectSet/index.tsx
litmus-portal/frontend/src/views/GetStarted/ProjectSet/styles.ts
litmus-portal/frontend/src/views/Home/ReturningHome/WorkFlowCard/index.tsx

- Added translations for login and getStarted page
- Added inputField from litmus-UI for login and getStarted page

Added translations and InputField from litmus-ui in login and get started pages

---

litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml

This PR adds:
- Permissions required for Kubernetes Object API

Added permission required for kubernetes obj api

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/Status.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/workflowConstants.ts

**This PR will add fixes for handling edge cases given below -** 
- When a workflow fails due to the failure of a node or nodes -> show the workflow graph and all details.
- When a workflow fails to start -> Show a prompt `Please check the configuration, the workflow was not able to start`, as there will be no visualization graph and any other details
- **When workflow Succeeds, Now the status will be `Completed` instead of `Succeeded` for both workflow and nodes.**
- fixed the issue of the blank screen when clicked on show application details ( Due to network delay, component wasn't getting manifest, fixed now by adding loading as a dependency in query).
Summarize your changes here to communicate with the maintainers and make sure …

Added fixes for handling edge cases in Workflow Visualisation Screen

---

litmus-portal/graphql-server/pkg/self-deployer/start.go

Renaming self cluster to self agentRenaming self cluster to self agent

Renaming self cluster to self agent

---

ADOPTERS.md

This PR adds VMWare as an adopter of LitmusChaos and is based on this [comment](https://github.com/litmuschaos/litmus/issues/2191#issuecomment-815913143) by [Bomin Nie](https://cn.linkedin.com/in/bomin-nie-21470526). 
The usecase details will be added soon. 
- Please add the links to the dependent …

(chore)adopters: add VMWare as an adopter

---

litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx

**This PR will add a minor fix for embedded YAML parsing logic for application details.**

Added Minor fix for embedded YAML parsing logic for Applications details. 

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

* Fixes custom step addition in manifest
* Fixes pre-populating already saved data from manifest while rolling back
* Adds schedule form template feature

chore(scheduling): Adding scheduling through template + Schedule Fixes ☑️☑️

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

* Workflow and a sub-workflow radio button has to be selected to move forward
* Minimum one experiment has to be selected to move forward after selecting custom workflow

chore(validation): ⚠️ Fixing Alerts and Validation 📟

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

chore(scheduling): Added revert chaos 👾👾

---

litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts

Added Predefined workflow template for podtato-head

Added Predefined workflow template for podtato-head

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/styles.ts

This PR will add a fix for handling one edge case for app info ( when chaosengine doesn't have appinfo ) and removed the Hosted On Option.

Added fix for handling one edge case for appinfo and removed the Hosted On Option.

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/LitmusStepper/styles.ts
litmus-portal/frontend/src/constants.ts
litmus-portal/frontend/src/graphql/mutations.ts
litmus-portal/frontend/src/graphql/queries.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

This PR adds:
- Save functionality feature with editor.
- Creation of workflows with template
- Delete a saved template
- Workflow Stepper fix

chore(litmus-portal): Added save template functionality, delete template and minor fixes

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/LitmusStepper/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

* Revert chaos engine names fixed
* Add Experiment would only be possible for custom workflows
* Back button won't be present for first stepper's step

chore(bugfix): Fixed Revert ChaosEngine names + Removed Back button from stepper's first step + Conditional Experiment Addition

---

litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx

chore(bugfix): Minor Alert Fix

---

litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts

Name modification for sock-shop Predefined Workflow Card. 
```sock-shop-chaos```

Name modify "sock-shop-chaos"

---

litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx

* Fixed Scheduling Bug on Close Modal

chore(scheduling): Fixed Scheduling Bug on Close Modal

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx

Fixed probes modal for https/probes

---

ADOPTERS.md

(chore)adopters: link vmware adoption story to adopters table

---

litmus-portal/frontend/public/icons/calendarBlank.svg
litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/Header/styles.ts
litmus-portal/frontend/src/components/SideBar/index.tsx
litmus-portal/frontend/src/models/graphql/user.ts
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/AgentInfoContainer/index.tsx
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/AgentInfoContainer/styles.ts
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/index.tsx
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/WorkflowRunCard/styles.ts
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/index.tsx
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/RecentWorkflowRuns/styles.ts
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
litmus-portal/frontend/src/views/Home/LandingHome/AgentDeployModal/index.tsx
litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
litmus-portal/frontend/src/views/Home/MainInfoContainer/styles.ts
litmus-portal/frontend/src/views/Home/ProjectInfoContainer/index.tsx
litmus-portal/frontend/src/views/Home/ProjectInfoContainer/styles.ts

…anslations/reviews added/addressed
Signed-off-by: Vansh Bhatia <vansh@chaosnative.com>
- Added CTA to home page cards
- Added appropriate color feedbacks to workflow states
- Addressed translation/constants addition
- Better alignments on home page cards

UI improvements

---

litmus-portal/frontend/src/components/WorkflowCard/styles.ts

This PR will fix Cards Styling for Pre-Defined Workflow

chore(Workflow Cards): Styling fix

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/Button/BackButton/styles.ts
litmus-portal/frontend/src/components/Tabs/index.tsx
litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
litmus-portal/frontend/src/pages/Workflows/index.tsx
litmus-portal/frontend/src/views/Targets/BrowseCluster/HeaderSection.tsx
litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/styles.ts

**This PR will -** 
**- Change Cluster to Agent in Targets page**
**- Tab color fix for  https://github.com/litmuschaos/litmus-ui/issues/45**
**- Made the text aligned for https://github.com/litmuschaos/litmus-ui/issues/51**
**- Made the "Overall workflow description" hidden by default.**
**- Removed the workflow description line as it wasn't required for https://github.com/litmuschaos/litmus-ui/issues/56.** 
**- Changed the color of backbutton to hint.**
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate …

Added minor translations and style fixes

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts

This PR adds:
- Fix for editor crashing issues
- Confirmation modal 
- Translation fixes

chore(v2): Fixed editor crashing issues and minor translation fixes

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/pages/GetStartedPage/styles.ts
litmus-portal/frontend/src/pages/LoginPage/index.tsx
litmus-portal/frontend/src/pages/LoginPage/styles.ts
litmus-portal/frontend/src/pages/Settings/index.tsx
litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/GetStarted/PasswordSet/index.tsx
litmus-portal/frontend/src/views/GetStarted/PasswordSet/styles.ts
litmus-portal/frontend/src/views/GetStarted/ProjectSet/index.tsx
litmus-portal/frontend/src/views/GetStarted/ProjectSet/styles.ts
litmus-portal/frontend/src/views/Home/ProjectInfoContainer/index.tsx
litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts
litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx

- Made the Tabs UI consistent 
- minor translation fix
Issue link: https://github.com/litmuschaos/litmus-ui/issues/50

Made the tabs consistent, minor translation fix

---

litmus-portal/cluster-agents/event-tracker/controllers/eventtrackerpolicy_controller.go
litmus-portal/cluster-agents/event-tracker/pkg/utils/informers.go

(event-tracker): Adding few error checks

---

docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
docs/litmus-operator-latest.yaml
docs/litmus-operator-v1.13.3.yaml

Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>

chore(1.13.3): Adding litmus-operator manifests

---

litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx

* Fixed Revert Chaos 
* Fixed Edit Schedule Icon Not able to render while routing

chore(bug-fix): Fixing Revert Chaos + Edit Schedule Icon

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml

- Updates the chaos operator, runner and exporter images to the latest version

Updated chaos operator and runner images in manifest

---

litmus-portal/cluster-agents/subscriber/go.mod
litmus-portal/cluster-agents/subscriber/go.sum
litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go

- Updated chaos operator pkg, fixes the chaos result shown in portal
- Update  experiment verdict to use chaos result data
- Ref: [Backend Issuess](https://github.com/litmuschaos/litmus-e2e/issues/254)

Updated chaos operator dependency

---

docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
docs/litmus-operator-ci.yaml
docs/litmus-operator-latest.yaml
docs/litmus-operator-v1.13.3.yaml
litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
litmus-portal/litmus-portal-crds.yml

Ref: 
- [runnerAnnotations](https://github.com/litmuschaos/chaos-operator/blob/e74fffdeac4cc5a0d24374990ce1c208b50530fe/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go#L143)
- [experimenAnnotations](https://github.com/litmuschaos/chaos-operator/blob/e74fffdeac4cc5a0d24374990ce1c208b50530fe/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go#L318)
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what …

(fix)annotation-injector-validation: fix the validation flags in CRD …as per new names in chaosengine API

---

litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/schema.graphqls
litmus-portal/graphql-server/graph/schema.resolvers.go
litmus-portal/graphql-server/pkg/database/mongodb/cluster/operations.go
litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
litmus-portal/graphql-server/pkg/project/create.go

Added mutation to update project name

Added mutation to update project name

---

litmus-portal/graphql-server/pkg/project/create.go

Refactored teaming code
- Removed conditions that are already being handled by RBAC
- Replaced if-else ladder with switch case

Refactored teaming code

---

litmus-portal/frontend/src/pages/WorkflowDetails/styles.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/TableData.tsx
litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowInfo/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowNodeInfo/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowStatus/styles.ts

This PR will add color fixes for Argo-graph,fix button alignment issue, and fix workflow status issue.

Added minor style fixes

---

litmus-portal/frontend/package-lock.json
litmus-portal/frontend/package.json
litmus-portal/frontend/src/pages/GetStartedPage/styles.ts
litmus-portal/frontend/src/pages/LoginPage/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ExtractSteps.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx

* Adding CronWorkflow BugFix
* Taking color from litmus-ui 1.1.3

chore(bugfix): Adding CronWorkflow Bug Fix + Taking login Background from litmus-ui

---

docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/README.md
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

* Updated GVRs for namespaced manifest's Role
* Litmus 2.0 beta helm installation steps for Okteto.

Updated GVRs for namespaced manifest's Role and litmus 2.0 beta helm installation steps for Okteto.

---

.github/workflows/push.yml
docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/frontend/Dockerfile
litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/graphql-server/pkg/authorization/middleware.go
litmus-portal/graphql-server/pkg/myhub/ops/gitops.go
litmus-portal/graphql-server/pkg/project/create.go
litmus-portal/graphql-server/server.go
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
litmus-portal/run.sh

This PR adds:
- Branch and Tag clone functionality
- Env to get the latest hub version

Added branch and tag clone functionality and env for branch/tag for MyHub

---

litmus-portal/platforms/okteto/README.md

* Minor readme fix for Okteto platform helm installation steps

Minor readme fix for Okteto platform helm installation steps

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/README.md

(chore)version-update: update versions of portal components to 2.0.0Beta4

---

litmus-portal/platforms/okteto/README.md
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

* Updating pns to k8sapi as the CRE for argo on Okteto

Updating pns to k8sapi as the CRE for argo on Okteto

---

litmus-portal/README.md
litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
litmus-portal/platforms/okteto/README.md

Adding argument for forcing the CNE to user given value instead of docker/default for workflow controller.

Adding argument for forcing the CNE to user given value instead of docker/default for workflow controller.

---

litmus-portal/frontend/src/views/AnalyticsDashboard/MonitoringDashboardPage/Panel/styles.ts

Signed-off-by: Ritik Srivastava <ritik@chaosnative.com>
1. one style change for immediate bug fix of the expand and shrink of the graph

shrink and expand bug fix

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

Based on sequence edited the preview would change dynamically

<feature>: Updating Sequence Visualization

---

litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts

* Minor Kube Proxy Chaos Icon fix

type(bugfix): Minor Icon Fix

---

litmus-portal/frontend/src/utils/promUtils.ts

Signed-off-by: Ritik Srivastava <ritik@chaosnative.com>
Prom util file bug fix

appinfo undefined bug fix

---

litmus-portal/cluster-agents/subscriber/go.sum
litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go
litmus-portal/cluster-agents/subscriber/pkg/cluster/events/workflow.go
litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/manifests/cluster/1c_argo_meta.yaml
litmus-portal/graphql-server/manifests/namespace/1b_argo_meta.yaml
litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go

This PR solves 2 issues:
1. Fixes #2735 
2. Discards older chaosengine logs and results in case the current engine creation has failed

Added argo instanceid, discard older results with same engine name

---

litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ExtractSteps.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx

* Improved workflow visualization

type(visualization): 🩹 Fixing edit sequence 🩹

---

litmus-portal/frontend/.eslintrc.json
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/__tests__/ChooseWorkflow.test.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx

Adding Unit Tests for ChooseWorkflow

chore(testing): Adding Unit Tests for ChooseWorkflow

---

litmus-portal/frontend/src/components/LitmusStepper/index.tsx
litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx

…ton wait loader
* Fixed Edit and Schedule navigation
* Added Finish Button loading state

type: bugfix -- Fixed Edit and Schedule navigation + Added finish button loading

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
litmus-portal/frontend/src/constants.ts
litmus-portal/frontend/src/graphql/queries.ts
litmus-portal/frontend/src/models/redux/customyaml.ts
litmus-portal/frontend/src/redux/reducers/workflow.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts

This PR adds:
- Subject field in the workflow maninfest
- Context field for chaos engines
- Fixed name and description change bug in verify and commit page
- Minor bug fixes

chore(litmus-portal): Added subject and context fields while workflow creation and fixed some minor bugs

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

This PR adds:
- Argo graph crashing issue while sequencing
- Workflow persistence for MyHub 
- Added context for pre-defined workflows

chore(litmus-portal) : Fixed the argo graph crashing issue, workflow persistence for MyHub and added context for pre-defined workflows

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts

* Minor style fix in Add Exp Modal

type(style-fix): 🎨 Minor style fix in Add Experiment Modal 🎨

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/__tests__/ChooseAWorkflowAgent.test.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx

Added Viewer permission + Fixed Alert when no cluster is available

type(validation): 🔧 Added Viewer permission + Fixed Alert when no cluster is available ✨

---

litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

(bug-fix): Created utility for dynamic namespace while workflow creation

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx

type(bugfix): 🔨 Fixed Breaking Upload YAML 🔨

---

litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml

Subscriber permissions for namespace mode

---

docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/graphql-server/utils/misc.go
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

* Added a condition to the check for ns install step addition.
* Added "*" for admin permissions in a namespace for the graphql server to enable successful self agent creation.

Fixes for ns scope permissions and handling an edge case.

---

litmus-portal/graphql-server/utils/misc.go

Minor fix for ns mode- agent scope to be taken from cluster registration request (currently its taking from hardcoded os env)

Minor fix for ns mode- agent scope to be taken from cluster registration request

---

litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml

Minor SA fix  in eventtracker (namespace)

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/README.md

Upgrading LitmusPortal manifests to Beta5

Upgrading LitmusPortal manifests to Beta5

---

docs/2.0.0-Beta4/litmus-2.0.0-Beta4.yaml
docs/2.0.0-Beta4/litmus-namespaced-2.0.0-Beta4.yaml

- Add a separate Beta4 manifest of litmus-portal.

Chore(Beta4): Add litmus-portal manifest for Beta4 version

---

ADOPTERS.md
adopters/organizations/kitopi.md

Adding Kitopi to Adopters file including the short description of our implementation

add kitopi to ADOPTERS.md

---

docs/litmus-operator-ci.yaml
docs/litmus-operator-v1.13.4.yaml

Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
- Adding manifests for litmus 1.13.4 release
- updated the crds for the ci and latest versions

chore(manifests): Adding manifests for 1.13.4

---

litmus-portal/frontend/package-lock.json
litmus-portal/frontend/package.json
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts

* Fixed Verify & Commit page issue with updated Editable Text

Fixed Verify & Commit page issue with updated Editable Text

---

litmus-portal/frontend/package.json
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/schema.graphqls
litmus-portal/graphql-server/graph/schema.resolvers.go
litmus-portal/graphql-server/pkg/myhub/handler/handler.go
litmus-portal/graphql-server/pkg/myhub/myhub.go

This PR adds:
- Updated workflow generation logic
- Fixed re-run issue if revert-chaos not present
- Added pre-defined myhub apis
- Added jobCleanupPolicy as retain by default
- Minor fixes

chore(litmus-portal): Updated workflow generation logic and added predefined myhub api

---

litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts

This PR will removed kube-proxy pre-defined workflow 

chore(workflow):Removed kube-proxy pre-defined workflow

---

litmus-portal/frontend/src/pages/EditSchedule/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts

* Fixed Workflow Name not populating for Predefined Workflows bug
* Cleansed Verify & Commit page

type(bugfix): ⚡ Fixed Predefined Workflow Name population issue + Cleansed Verify & Commit Page 🎨

---

litmus-portal/frontend/src/views/MyHub/MyHubConnect/index.tsx
litmus-portal/frontend/src/views/MyHub/MyHubEdit/index.tsx

This PR fixes `MyHubEdit` and `MyHubConnect` input issue where even wrong git URL and branch gets saved for later use(input fields show errors, but the user can still save) as mentioned [here](https://github.com/litmuschaos/litmus-e2e/issues/254#issue-859032615). Submit button now remains disabled until correct input is provided.
Also fixes broken copy icon image in MyHubEdit.

type(bugfix): Fix MyHub input validation

---

monitoring/grafana-dashboards/sock-shop/Sock-Shop-Performance-Under-Chaos.json

* Fixing count of (passed/failed/awaited) experiments 
* Fixing Events query for sock shop dashboard

(monitoring): Fixing count of experiments & event query for sock shop dashboard

---

litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go

This PR prevents the existing workflow labels from being overwritten by the backend

Fix for overridden workflow labels

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/constants.ts
litmus-portal/frontend/src/graphql/mutations.ts
litmus-portal/frontend/src/graphql/queries.ts
litmus-portal/frontend/src/pages/Settings/index.tsx
litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts

This PR adds:
- Image registry frontend integration

chore(litmus-portal): Added image registry frontend integration

---

litmus-portal/frontend/src/components/YamlEditor/Editor.tsx

Currently, the `Editor` uses [Ubuntu Mono](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/src/components/YamlEditor/Editor.tsx#L477) font family but this causes issues when typing as it introduces extra spacing between cursor and actual text. This occurs for any custom font. Changing this to simply `monospace` rectifies the issue. 
Also, currently, page down seems to lead to the end of the file and not the end of the page. This is due to the `maxLines` prop which causes Aceditor to interpret 12000 lines as a page. It does not restrict the number of lines that can be entered (tested with `maxLines`=1) but rather restricts how many lines the editor shows and what it considers to be a "page". 
Thus removing it causes aceditor to set the "page" size automatically …

type(bugfix): Fix Editor typing & pagedown issues

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts

* Fixes overflowing experiment bug in Edit Sequence
* Increases Table height for better visualisation

type(fix): Fixes overflowing experiment bug in Edit Sequence + Increases Table height for better visualisation

---

litmus-portal/frontend/src/models/graphql/createWorkflowData.ts
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

This PR adds:
- Image-Registry changes in workflow manifest

chore(litmus-portal): Added image-registry changes in workflow manifest

---

litmus-portal/frontend/src/utils/validate.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx

* Solving context issues for experiments
* Fixing workflow name length

type(bugfix 🐛): Solving context issues for experiments + Fixing workflow name length 👷

---

litmus-portal/frontend/src/pages/ApplicationDashboard/styles.ts

* fixing on hover and focused styles for dropdown

(portal - analytics / monitoring): Fixing a minor style issue on app. dashboard page

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
docs/2.0.0-Beta4/litmus-2.0.0-Beta4.yaml
docs/2.0.0-Beta4/litmus-namespaced-2.0.0-Beta4.yaml
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

change all docker image repo name to litmuschaos

changing all docker image repo name to litmuschaos

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts

Fixed workflow name issue, added info popover for private image registry

---

litmus-portal/frontend/src/components/YamlEditor/Editor.tsx

* Adding back maxLines parameter to resolve highlighting and validation error position issues. PageDown bug fix broke the validation feature.

(portal- workflows): Bug fix for editor

---

litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
litmus-portal/cluster-agents/subscriber/subscriber.go
litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml

This PR enables the subscriber to check for agent component status before posting an active status to the gql server.
Fixes #2798 

Added agent component live check

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/graphql/mutations.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
litmus-portal/frontend/src/views/Settings/ImageRegistry/styles.ts

chore(litmus-portal): Handled edge case when no image registry is present

---

litmus-portal/frontend/src/models/graphql/createWorkflowData.ts
litmus-portal/frontend/src/models/redux/image_registry.ts
litmus-portal/frontend/src/redux/actions/image_registry.ts
litmus-portal/frontend/src/redux/reducers/image_registry.ts
litmus-portal/frontend/src/redux/reducers/index.ts
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

Fixed the query race conditions and handled few edge cases

---

litmus-portal/frontend/src/views/WorkflowDetails/WorkflowTable/TableData.tsx

Added one minor UI fix for Node table

---

docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
docs/litmus-operator-ci.yaml
docs/litmus-operator-latest.yaml
docs/litmus-operator-v1.13.3.yaml
docs/litmus-operator-v1.13.4.yaml
docs/litmus-operator-v1.13.5.yaml
litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
litmus-portal/litmus-portal-crds.yml

Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>

chore(1.13.5): Adding manifests for 1.13.5 & crds updation

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/README.md

upgrading litmusportal manifest to 2.0.0-Beta6

---

litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml

This PR will add CRD for Event-tracker.

Added CRD for Event-tracker

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/README.md

Upgrading manifest to Litmus-2.0.0-Beta7

---

litmus-portal/frontend/src/models/redux/customyaml.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

Fixed revert chaos not working after returning to tune worklfow and adding a new experiment

type(bugfix): 🐛 Fixed revert chaos not working after returning to tune worklfow and adding a new experiment 🐛

---

resources/README.md

Adding a beginner-friendly resource section 🚀

type(community): 📝 Adding a beginner friendly resource section 🚀🎉

---

litmus-portal/frontend/src/views/WorkflowDetails/LogsModal/index.tsx

Added Fix for Icon in Workflow Name

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowSequence/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts

Fixed
* Edit Sequence , There is no gap between experiment name if the name is long
* Description width is not 100%  in Summary Page
* Back button on workflow template description, Its only available at bottom of the page

type(ux): Fixed UX Issue 3, 4 and 10 🔨 🔨

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

Fixed revert chaos deletion issue for Pre-Defined Workflows

type(bugfix): Fixed revert chaos deletion issue for Pre-Defined Workflows

---

litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/Status.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/CustomStatus/__tests__/CustomStatus.test.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/__tests__/WorkflowSetting.test.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

This PR adds:
- Tests for workflow name length validation
- Custom Status tests

Added unit-test cases for workflow name and custom status

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

This PR adds:
- Updating serviceaccount of chaosengine before patching in workflow manifest

type(bug): Updating serviceaccount of chaosengine before patching in workflow manifest for custom workflows

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/containers/app/App.tsx
litmus-portal/frontend/src/pages/MyHub/MyHubConnectDrawer/index.tsx
litmus-portal/frontend/src/pages/MyHub/MyHubConnectDrawer/styles.ts
litmus-portal/frontend/src/pages/MyHub/customMyHubCard.tsx
litmus-portal/frontend/src/pages/MyHub/index.tsx
litmus-portal/frontend/src/pages/MyHub/styles.ts

This PR adds:
- Updated MyHub UI
- Added connect myhub drawer
- Code clean-up

type(ui-refactor): Updated MyHub UI and added connect myhub drawer

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseTemplate/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseWorkflow/HeaderSection.tsx

* Adding enable schedule (ux-issue 14)
* Fixing ux issue 7 and 11

type(ux): Adding enable schedule (ux-issue 14) + fixing ux issue 7 and 11

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/styles.ts

Fixed ux-issue 
* 16
* 38
* 39

type(ux): Fixed ux-issue 16, 38 and 39

---

resources/README.md

- [ x ] Documentation Update (if none of the other choices applies)
- [ x ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc

Update resources section

---

litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
litmus-portal/frontend/src/components/YamlEditor/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts

* Making Graph Visualization Green
* Fixing Editor UI

type(ux): 🔨 Making Graph Visualization Green + Fixing Editor UI

---

litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/components/WorkflowStepper/styles.ts
litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
litmus-portal/frontend/src/components/YamlEditor/styles.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts

* Fixing Save template editor
* Fixing Finish button CSS
* Vertically aligning Save alert

type(bugfix): Fixing Save template editor and fixing Finish button CSS + Vertically aligning Save alert

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/YamlEditor/Editor.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/styles.ts

* Fixing editor save issue when nothing is changes
* Removing Kubernetes Conformance Test Header

type(bugfix): Fixing editor save issue when nothing is changes + Removing Kubernetes Conformance Test Header

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

This PR adds:
- MyHub selection for pre-defined experiments

type(ux): Added myhub selection for pre-defined workflows

---

README.md
litmus-portal/frontend/README.md

Remove circleci badge from README.md

Remove circleci badge from README.md

---

litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx

This PR adds the following change:
- Added localforage for default hub (`Chaos Hub`) if it is available

Minor fix for pre-defined workflows

---

litmus-portal/graphql-server/pkg/authorization/middleware.go
litmus-portal/graphql-server/pkg/database/mongodb/cluster/operations.go
litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go
litmus-portal/graphql-server/pkg/stat/status.go
litmus-portal/graphql-server/pkg/usermanagement/create.go
litmus-portal/graphql-server/server.go

This PR adds endpoint to fetch aggregated portal stats.

Added endpoint for portal stats

---

litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
litmus-portal/graphql-server/utils/misc.go

**This PR will**
- fix edge cases while calculating Resilience Score when chaos data doesn't come for experiments.
- Also will fix the namespace getting overridden while registering an agent in namespaced mode. 
**Tested by** 
- connecting multiple agents in different namespaces in the namespaced mode in the same cluster
- Connecting in Cluster Mode
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …

Added Minor Fix for Resilience Score Calculation Logic and Namespaced mode agent registration.

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/1b_argo_rbac.yaml
litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/1a_argo_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
litmus-portal/graphql-server/pkg/types/configurations.go
litmus-portal/graphql-server/server.go
litmus-portal/graphql-server/utils/misc.go
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
litmus-portal/run.sh

Removing Argo server deployment from the agent list

Removing Argo server deployment from the agent list

---

litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/TopNavButtons/index.tsx
litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/TableData.tsx
litmus-portal/frontend/src/views/Analytics/Overview/index.tsx

* Fixing icon path
* Fixing text on button

Minor fixes for analytics

---

litmus-portal/cluster-agents/subscriber/pkg/events/util.go

This PR fails workflows with stopped chaosengines and no experiments

Added fail check for stopped engine with no experiments

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/README.md

**This PR will** 
**- upgrade the Control plane version to 2.0.0-Beta8.**
**- Upgrade the operator,exporter and runner to v1.13.5.**

Updated the Control plane to version 2.0.0-Beta8.

---

.github/workflows/push.yml

**This PR will fix the image push Step for the event-tracker in GitHub Action workflow.**

Fixed the image push Step for event-tracker.

---

litmus-portal/graphql-server/go.mod
litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/graph/analytics.graphqls
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/model/models_gen.go
litmus-portal/graphql-server/graph/schema.graphqls
litmus-portal/graphql-server/graph/schema.resolvers.go
litmus-portal/graphql-server/pkg/analytics/handler/handler.go
litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
litmus-portal/graphql-server/pkg/database/mongodb/analytics/schema.go

Signed-off-by: arkajyotiMukherjee <arko@chaosnative.com>
- Includes workflow run stats for all or specified workflows

WorkflowRun stats in workflow details page for analytics

---

litmus-portal/frontend/src/graphql/queries.ts

Signed-off-by: arkajyotiMukherjee <arko@chaosnative.com>
Minor bug fix for workflow stats

Bug fix: changed project_id from String to ID

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts

This PR adds:
- Error texts for agent and myhub
- Fixed probes table width
- Made chaos hub default for custom experiments

type(ux): Added error texts and fixed the probes table

---

litmus-portal/cluster-agents/subscriber/pkg/events/util.go

This PR adds error log for time discrepancy between workflow and engine resource when parsing workflow events.

Added error log for time discrepancy between workflow and engine resource

---

adopters/organizations/lenskart.md

- [x ] New feature (non-breaking change which adds functionality)
- [ x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ x] I have signed the commit for DCO to be passed.
- [ x] Lint and unit tests pass locally with my changes
- [ x] I have added tests that prove my fix is effective or …

Created lenskart.md

---

ADOPTERS.md

- [ x] Documentation Update (if none of the other choices applies)
- [ x ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ x] I have signed the commit for DCO to be passed.
- [ x] Lint and unit tests pass locally with my changes
- [ x] I have added tests that prove my fix is effective or …

Added lenskart to the adaptors.md

---

MAINTAINERS

Update Uma's information in the MAINTAINERS file

---

litmus-portal/frontend/src/components/Loader/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddExperimentModal.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

* Fixing Radio Button selection issue (@amityt)
* Adding data-cy for Smoke Test
* Fixing Loader Alignment

type(bug): Fixing Radio Button selection issue + Adding data-cy for Smoke Test + Fixing Loader Alignment

---

adopters/organizations/halodoc.md

- [x ] Documentation Update (if none of the other choices applies)
- [ x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc

Created halodoc.md

---

ADOPTERS.md

Adds the line for Halodoc in ADOPTERS.md based on https://github.com/litmuschaos/litmus/pull/2915

(chore)adoption: add entry for halodoc in adopters.md file

---

litmus-portal/graphql-server/pkg/usage/status.go

This PR updates the project owner sort option in usage query to use owner username instead of name

Updated project owner sort to username field

---

litmus-portal/README.md

**This PR will add AKS and K3S as supported platforms.**

Updating the supported platforms list

---

docs/litmus-namespaced-scope/litmus-ns-rbac.yaml

Chore(RBAC): Add service account for ns mode

---

docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml

Chore(RBAC): Add RBAC for ns scope experiments

---

README.md

Update README.md (Add Maveric Systems blog)

---

litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/graph/schema.resolvers.go
litmus-portal/graphql-server/pkg/authorization/validate.go

Moving rbac to authorization package

Moving rbac to authorization package

---

litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx

API doc url fix

---

litmus-portal/graphql-server/pkg/usage/status.go

This PR updates the usage query to exclude removed agents from total count

Exclude removed agents from usage data

---

litmus-portal/authentication/api/handlers/user_handlers.go
litmus-portal/authentication/api/main.go
litmus-portal/authentication/go.mod
litmus-portal/authentication/go.sum
litmus-portal/authentication/pkg/entities/user.go
litmus-portal/authentication/pkg/user/repository.go
litmus-portal/authentication/pkg/utils/configs.go

Adding backward compatibility fix for auth server

---

litmus-portal/frontend/src/components/LitmusStepper/index.tsx
litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

Fixed Radio Button selection issue at Choose Workflow Screen 🐛

type(bugfix): Fixed Radio Button selection issue at Choose Workflow Screen 🐛

---

litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
litmus-portal/frontend/src/pages/EditSchedule/index.tsx
litmus-portal/frontend/src/pages/EditSchedule/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowPreview/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

* Fixed Accordion width problem
* Added Edit Sequence Button render for No Visualizaed Graphs
* Minor CSS Fixes for Edit Schedule Page

type(ux-bugfix): Fixed Accordion width problem and Edit Sequence Button render for No Visualizaed Graphs

---

litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

This PR adds:
- Hubs with available status will be displayed in workflow creation step
- Updated table head styles
- Added checks in save template modal

type(ux): Fixed portal ux issues and minor style changes

---

litmus-portal/frontend/src/models/graphql/workflowListData.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/model/models_gen.go
litmus-portal/graphql-server/graph/workflow.graphqls
litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go

- Fixes pagination issue on the table footer
- Fixes default sort issue (Default sort will be on the basis of last updated time)

Bug fixes in browse workflow table

---

litmus-portal/graphql-server/manifests/cluster/1c_argo_meta.yaml
litmus-portal/graphql-server/manifests/namespace/1b_argo_meta.yaml

This PR updates argo executor image pull policy in configmap

Updated argo executor image pull policy

---

litmus-portal/cluster-agents/event-tracker/main.go
litmus-portal/cluster-agents/subscriber/subscriber.go

adding environment vars check condition in event tracker and subscriber

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/UserDetails/index.tsx
litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/TableToolbar.tsx
litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Table/styles.ts
litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/index.tsx
litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowGraphs/styles.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/styles.ts
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/HeaderSection.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
litmus-portal/frontend/src/views/Targets/BrowseCluster/HeaderSection.tsx
litmus-portal/frontend/src/views/Targets/BrowseCluster/styles.ts

Fixes Issue:
[86] - Editing a Workflow Name : Issue in Error message
[90] - Need to update the workflow status with new icons and colors at the Browse Workflow Page
[96] - Need to remove the Edit Profile Picture in Settings
[103] - The dropdown in Browse Workflow tabs have a purple border color which seems like its activated

type(ux-fix): ⚡️ Fixed Table FormControl active colors + 📝 updated workflow pills + minor UX fixes 🎨

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/General.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/data.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/UsageStatistics/UsageTable/index.tsx

This PR adds:
- Updated exp runs in usage section
- Refactored target application section (label selection)
- Fixed workflow name issue
- Updated context and subject for workflow

type(ux): Updated exp runs in usage section and refactored the target application code

---

litmus-portal/frontend/src/models/redux/tabs.ts
litmus-portal/frontend/src/pages/ChaosHub/customMyHubCard.tsx
litmus-portal/frontend/src/pages/ChaosHub/index.tsx
litmus-portal/frontend/src/redux/actions/tabs.ts
litmus-portal/frontend/src/redux/reducers/tabs.ts
litmus-portal/frontend/src/views/Analytics/Overview/index.tsx
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
litmus-portal/frontend/src/views/MyHub/MyHubCharts/index.tsx
litmus-portal/frontend/src/views/UsageStatistics/UsageStats/index.tsx
litmus-portal/frontend/src/views/UsageStatistics/UsageTable/index.tsx

This PR adds:
- Fixed usage statistics page
- Added redux state for MyHub tabs
- Added data-cy for MyHub e2e

type(ux): Fixed usage statistics page with LazyQuery and added redux state for Myhub tabs

---

litmus-portal/cluster-agents/subscriber/go.mod
litmus-portal/cluster-agents/subscriber/pkg/events/util.go
litmus-portal/cluster-agents/subscriber/pkg/types/event.go
litmus-portal/frontend/src/models/graphql/workflowData.ts
litmus-portal/graphql-server/pkg/chaos-workflow/types.go

Added engine context in chaos data
- Required in experiments table in analytics

Added engine context in chaos data

---

litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/model/models_gen.go
litmus-portal/graphql-server/graph/usage.graphqls
litmus-portal/graphql-server/pkg/usage/status.go
litmus-portal/graphql-server/pkg/usage/types.go

This PR adds the active agent count to the usage stats

Added active agent count to usage stats

---

litmus-portal/authentication/api/handlers/user_handlers.go
litmus-portal/authentication/go.mod
litmus-portal/authentication/pkg/user/repository.go
litmus-portal/authentication/pkg/user/service.go
litmus-portal/run.sh

- UID will be taken from context for update user handler 
- Added condition to hash password before updating it in update/details API
- Updated bash script

Fixed bug in update/details api

---

litmus-portal/frontend/package-lock.json
litmus-portal/frontend/package.json
litmus-portal/frontend/src/models/dashboardsData.ts
litmus-portal/frontend/src/pages/ApplicationDashboard/index.tsx
litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/Panel/PanelContent.tsx
litmus-portal/frontend/src/views/Analytics/ApplicationDashboard/Panel/PanelGroupContent.tsx

1. Update litmus-ui version to 1.3.1
2. Multiple zooming enabled for Application dashboards in Analytics section

Litmus UI version update 1.3.1

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/pages/UsageStatistics/datePicker.tsx
litmus-portal/frontend/src/pages/UsageStatistics/index.tsx
litmus-portal/frontend/src/pages/UsageStatistics/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/ConfigurationStepper/ConfigurationStepper.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/EnvironmentVariables.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/styles.ts
litmus-portal/frontend/src/views/UsageStatistics/UsageStats/index.tsx
litmus-portal/frontend/src/views/UsageStatistics/UsageTable/index.tsx
litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx

This PR adds:
- Tune Experiment step to edit the env variables
- Added date range filter for usage page
- Fixed logs issue

chore(litmus-portal): Added env tunables, date range for usage stats and fixed logs issue

---

ADOPTERS.md

Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>
- [] New feature (non-breaking change which adds functionality)

add KubeSphere to ADOPTERS.md

---

ADOPTERS.md

Signed-off-by: ajeshbaby <ajesh@chaosnative.com>
Chore updating the latest additions in chronological order.

[chore] Updating latest addition in Chronological order

---

MAINTAINERS

(chore)maintainers: update maintainers email id

---

GOVERNANCE.md
MAINTAINERS

Signed-off-by: ksatchit <karthik@chaosnative.com>
Updates the governance doc to reflect Github PRs as a way to propose maintainers (there is no dedicated slack channel for maintainers as originally planned. Maintainers like @Jasstkn were added via PR).
Changes the role of @ispeakc0de, @rajdas98 & @uditgaurav to maintainers for their awesome contributions to the growth of the litmuschaos project over the past year. 
While @ispeakc0de & @uditgaurav have been instrumental in increasing the experiment suite & the e2e framework, @rajdas98 has been instrumental in the development of the Litmus control plane & orchestration. 
Adds newer reviewers that have contributed significantly over the past year to the various sub-projects within Litmus and continue to build the community! 
Summarize your …

(chore)governance: add newer maintainers and reviewers

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

**This PR will update the image tags for the workflow controller and executor to v2.11.0 for multiarch support.**

Updated the image tags for workflow controller and executor to v2.11.0.

---

litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml

typo in 3a_agent_rbac

---

litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
litmus-portal/frontend/src/pages/EditSchedule/index.tsx
litmus-portal/frontend/src/pages/EditSchedule/styles.ts
litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
litmus-portal/frontend/src/views/WorkflowDetails/LogsSwitcher/index.tsx

* Adding data-cy for E2E
* Fixing Edit Scheduile View YAML

type(update): Adding data-cy for E2E and fixing Edit Scheduile View YAML

---

litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
litmus-portal/frontend/src/components/SuspenseLoader/index.tsx
litmus-portal/frontend/src/components/UnconfiguredAgent/index.tsx
litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/containers/app/App.tsx
litmus-portal/frontend/src/pages/AnalyticsPage/index.tsx
litmus-portal/frontend/src/pages/ChaosHub/index.tsx
litmus-portal/frontend/src/pages/ConfigureDataSources/index.tsx
litmus-portal/frontend/src/pages/EditSchedule/index.tsx
litmus-portal/frontend/src/pages/HomePage/index.tsx
litmus-portal/frontend/src/pages/Settings/index.tsx
litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
litmus-portal/frontend/src/pages/Workflows/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/WorkflowRunCard/index.tsx
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
litmus-portal/frontend/src/views/Home/LandingHome/index.tsx
litmus-portal/frontend/src/views/Home/ProjectInfoContainer/index.tsx

**This PR will add code-splitting at the components level, by lazy loading the required components. This will help in making more chunks in a production build and required chunks will be downloaded on the client side parallely.**
**One custom component (`<SuspenseLoader />`) for using suspense is added, which can be used as a HOC wherever required.**
- Please add the links to the dependent PR …

Added Code-splitting at components level.

---

ADOPTERS.md

Added Omar Hanafi

---

litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml

**This PR will add minimal RBAC for Agents in Namespace Mode.**

Added minimal RBAC for agents in Namespace Mode.

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/graphql/mutations.ts
litmus-portal/frontend/src/graphql/queries.ts
litmus-portal/frontend/src/models/redux/image_registry.ts
litmus-portal/frontend/src/redux/reducers/image_registry.ts
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/SaveTemplateModal.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbesMenu.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/comparatorTypes.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/styles.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/TargetApplication.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/styles.ts
litmus-portal/frontend/src/views/Settings/ImageRegistry/index.tsx
litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/image_registry.graphqls
litmus-portal/graphql-server/graph/model/models_gen.go
litmus-portal/graphql-server/pkg/database/mongodb/image_registry/schema.go
litmus-portal/graphql-server/pkg/image_registry/ops/image_registry.go
litmus-portal/graphql-server/pkg/project/create.go

This PR adds:
- Updated probes UI and made some functionality dynamic
- Fixed the node selector issue in chaos engine
- Fixed image registry issue (image registry change will not be available in upload functionality)

chore(litmus-portal): Updated probes ui, fixed node selector issue in chaos engine and fixed image registry issue

---

litmus-portal/authentication/Dockerfile
litmus-portal/cluster-agents/event-tracker/Dockerfile
litmus-portal/cluster-agents/subscriber/Dockerfile
litmus-portal/cluster-agents/subscriber/go.mod
litmus-portal/graphql-server/Dockerfile
litmus-portal/graphql-server/go.mod

upgrading goversion to 1.16

---

litmus-portal/authentication/api/main.go

Signed-off-by: DarthBenro008 <hkpdev008@gmail.com>
Fixes CORS issue in litmus-portal auth server when run locally for development

fix: auth server: cors issue

---

litmus-portal/frontend/src/ReduxRoot.tsx
litmus-portal/frontend/src/config/index.ts
litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
litmus-portal/graphql-server/go.mod
litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/pkg/myhub/myhub.go
litmus-portal/graphql-server/pkg/myhub/ops/gitops.go
litmus-portal/graphql-server/server.go

This PR adds:
- Updated myhub package from src-d/go-git to go-git/go-git
- Fixed charts icons url issue
- Updated myhub api to save the hub details in db before cloning it

Upgraded myhub package to latest and minor change in myhub api

---

litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml

Adding rbac permissions for predefined workflow

Adding rbac permissions for predefined workflow

---

litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml

**This PR will update the version labels to v1.13.6 in rbac and deployment for litmus.**

Updated version labels to v1.13.6 in RBAC and Deployment for litmus.

---

.github/BUILD_IMAGE.md
.github/filter_and_build.sh
.github/workflows/e2e.yml

**This PR will update the Github Action workflow for e2e for on-demand command.**
> Now, we are using an action for filtering the changed directories, so it will be more scalable with respect to component directories.
**Current command - `/run-e2e-all`**
Latest Test run - https://github.com/Jonsy13/test-e2e-build/pull/6
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to …

chore (Litmus-Portal) : Updated E2E GitHub Action Worflow

---

ADOPTERS.md
adopters/organizations/mercedes.md

Signed-off-by: ajeshbaby <ajesh@chaosnative.com>
Raising this PR based on the [comment](https://github.com/litmuschaos/litmus/issues/2191#issuecomment-876115729) 
@asibece Can you review this ?

Add Mercedes as Adopter

---

monitoring/portal-dashboards/node_metrics.json
monitoring/portal-dashboards/pod_metrics.json
monitoring/portal-dashboards/sock-shop.json

* Updating event queries to filter out events with nil injection time
* Updating verdict queries to filter out `Awaited` experiments
* Fixes for the node metrics dashboard.
- To be merged before release.

Bug fixes for portal dashboards

---

litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/ChooseADashboardType/index.tsx
litmus-portal/frontend/src/views/Analytics/WorkflowDashboard/WorkflowComparisonTable/index.tsx

* Adding back changes that did not get committed from workflow query optimization PR for comparison table
* Bug fix for dashboard listing on error
To be merged before release

(portal-analytics): Bug fix for dashboard list and workflow comparison table

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

This PR will fix issue for bank-of-anthos pre-defined workflow secrests
Updating permissions(rbac) for pre-defined workflow

Updating chaos-cluster-role and chaos-role permissions(rbac) for pre-defined workflow

---

docs/litmus-operator-ci.yaml
docs/litmus-operator-latest.yaml

updating rbac permissions for the operator

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/README.md

**This PR will update the control-plane to Beta-9.**

(Litmus-Portal): Updated the control-plane to Beta-9.

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml

chore(rbac-fix): Fixing rbac for ingress

---

ADOPTERS.md
adopters/organizations/redhat_kraken.md

Updating the adopters section to encompass all of Red Hat OpenShift as we are using Litmus, in addition to Kraken, for chaos testing 

Adding Openshift platform adopter

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go
litmus-portal/graphql-server/pkg/types/configurations.go
litmus-portal/graphql-server/server.go
litmus-portal/graphql-server/utils/misc.go
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

This PR moves the agent dependency list to the server env making it configurable from the server deployment manifest.

Shifted agent dependency list to server env

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
litmus-portal/frontend/src/views/Targets/TargetCopy/index.tsx

Renaming "litmusctl agent connect" to "litmusctl create agent" in the UI

Renaming "litmusctl agent connect" to "litmusctl create agent" in the UI

---

litmus-portal/graphql-server/pkg/k8s/cluster.go

This change fix the logic to get the IP or Hostname from ingress.
The current logic do not work with traefik
- [ X] Bugfix (non-breaking change which fixes an issue)
- [ X] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ X] I have signed the commit for DCO to be passed.
fix …

Fix ingress logic

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/Header/index.tsx
litmus-portal/frontend/src/components/Header/styles.ts
litmus-portal/frontend/src/components/SideBar/index.tsx
litmus-portal/frontend/src/pages/GetStartedPage/index.tsx
litmus-portal/frontend/src/pages/GetStartedPage/styles.ts
litmus-portal/frontend/src/pages/LoginPage/index.tsx
litmus-portal/frontend/src/pages/LoginPage/styles.ts
litmus-portal/frontend/src/pages/Targets/index.tsx
litmus-portal/frontend/src/pages/Workflows/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/SelectMyHub.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ReliabilityScore/index.tsx

* Updated LoginPage and workflow content

type(rebranding): Updated LoginPage and workflow content

---

.betterci/README.md
litmus-portal/namespaced-k8s-template.yml

Removing resource limits from namespace manifests

Removing resource limits from namespace manifests

---

docs/api.html
docs/config.yml

This PR adds:
- Cluster APIs
- Workflow APIs
- ChaosHub APIs
- User Management APIs
- Workflow Management APIs
- Updated the Favicon for docs tab
**Above changes can be viewed here:** https://amityt.github.io/litmus/api.html

type(api-docs): Added API docs with the updated Litmus Portal apis

---

litmus-portal/frontend/src/components/Header/index.tsx
litmus-portal/frontend/src/components/Header/styles.ts

type(fix): Updated Chaos Center header

---

litmus-portal/frontend/src/views/WorkflowDetails/ArgoWorkflow/styles.ts

Update Argo colors to take from Theme

type(color-fix): Update Argo colors to take from Theme

---

.github/workflows/codeql-analysis.yml

Adding vulnerability scanner in the github workflows (codeql-analysis)

Adding vulnerability scanner in the github workflows (codeql-analysis)

---

litmus-portal/authentication/api/handlers/user_handlers.go
litmus-portal/authentication/pkg/entities/user.go
litmus-portal/authentication/pkg/user/repository.go
litmus-portal/authentication/pkg/user/service.go
litmus-portal/frontend/src/pages/GetStartedPage/index.tsx
litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx

- Added a separate struct for /update/details API
- remove LoggedIn filed from user struct 

Added separate struct to for /update/details API

---

ADOPTERS.md
adopters/organizations/klanik.md

Add Klanik as adopter and a brief of our story to reference us

Add Klanik as adopter and a brief of our story

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/views/Analytics/ApplicationDashboards/Steps/TuneTheQueries/EditPanelsWizard/index.tsx

1. Text corrections for the analytics/application dashboard creations 
2.   key="tab-addMetric" has been removed as the component was not being mapped. Key not required here.

Text corrections and unneeded key removal

---

monitoring/portal-dashboards/schema.json

This PR adds the schema for app. / infra monitoring dashboards on chaos center.

Schema for app. / infra monitoring dashboards on chaos center

---

litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
litmus-portal/graphql-server/pkg/usage/status.go

This PR optimizes the usage state database query to reduce the amount of data being handled in the query pipeline.

Optimized the usage stats db query

---

litmus-portal/frontend/public/index.html
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
litmus-portal/graphql-server/pkg/analytics/handler/handler.go

Signed-off-by: arkajyotiMukherjee <arko@chaosnative.com>

removed terminated and in-complete workflows from workflow analytics

---

litmus-portal/frontend/package-lock.json
litmus-portal/frontend/package.json

Signed-off-by: Ritik Srivastava <ritik@chaosnative.com>
1. Litmus UI version updated to 1.4.3

litmus ui version update

---

litmus-portal/cluster-agents/event-tracker/config/example_cr/eventtracker_policy.yaml
litmus-portal/cluster-agents/event-tracker/main.go
litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go

Adding a condition-based selection of controller manager and Kubernetes  informers scope

Adding namespace scope support for eventtracker controller

---

.github/workflows/gh-pages.yaml

adding docs to the github pages

---

monitoring/README.md
monitoring/platforms/kublr/README.md
monitoring/utils/metrics-exporters-with-service-monitors/kube-state-metrics/deployment.yaml
monitoring/utils/metrics-exporters-with-service-monitors/kube-state-metrics/service-monitor.yaml
monitoring/utils/metrics-exporters-with-service-monitors/litmus-metrics/chaos-exporter/chaos-exporter.yaml
monitoring/utils/metrics-exporters-with-service-monitors/litmus-metrics/chaos-exporter/service-monitor.yaml
monitoring/utils/metrics-exporters-with-service-monitors/mysqld-exporter/deployment.yaml
monitoring/utils/metrics-exporters-with-service-monitors/mysqld-exporter/service-monitor.yaml
monitoring/utils/metrics-exporters-with-service-monitors/node-exporter/daemonset.yaml
monitoring/utils/metrics-exporters-with-service-monitors/node-exporter/service-monitor.yaml
monitoring/utils/metrics-exporters-with-service-monitors/prometheus-blackbox-exporter-metrics/configmap.yaml
monitoring/utils/metrics-exporters-with-service-monitors/prometheus-blackbox-exporter-metrics/deployment.yaml
monitoring/utils/metrics-exporters-with-service-monitors/prometheus-blackbox-exporter-metrics/service-monitor.yaml
monitoring/utils/metrics-exporters-with-service-monitors/prometheus-blackbox-exporter-metrics/service.yaml
monitoring/utils/metrics-exporters/kube-state-metrics/deployment.yaml
monitoring/utils/metrics-exporters/litmus-metrics/chaos-exporter/chaos-exporter.yaml
monitoring/utils/metrics-exporters/mysqld-exporter/deployment.yaml
monitoring/utils/metrics-exporters/node-exporter/daemonset.yaml
monitoring/utils/metrics-exporters/prometheus-blackbox-exporter-metrics/configmap.yaml
monitoring/utils/metrics-exporters/prometheus-blackbox-exporter-metrics/deployment.yaml
monitoring/utils/metrics-exporters/prometheus-blackbox-exporter-metrics/service.yaml
monitoring/utils/prometheus/prometheus-configuration/prometheus.yaml
monitoring/utils/prometheus/prometheus-scrape-configuration/02-prometheus-configMap.yaml

* adding black-box exporter and scrape job, service monitor 
* updates to litmus version and exporter manifests

Adding black-box exporter and scrape job, service monitor with updates to litmus version and exporter manifests

---

litmus-portal/cluster-agents/event-tracker/main.go
litmus-portal/cluster-agents/event-tracker/pkg/utils/informers.go
litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go

Fixing logs of event tracker

---

docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
docs/litmus-operator-ci.yaml
docs/litmus-operator-latest.yaml
docs/litmus-operator-v1.13.8.yaml

adding pod-namespace in operator manifest

---

litmus-portal/authentication/api/handlers/user_handlers.go
litmus-portal/authentication/api/routes/user_router.go
litmus-portal/authentication/pkg/user/repository.go
litmus-portal/authentication/pkg/user/service.go
litmus-portal/frontend/src/pages/GetStartedPage/index.tsx

- Added a new route `/GetUser/:uid` that fetches the user details based on `uid`.
- Added checks to prevent Database inconsistencies due to caching. 

Added checks to prevent DB inconsistency

---

litmus-portal/README.md

**This PR will update the links in Readme.md, so that they will point to Beta9 manifests from 2.0.0-Beta9 branch.**

(Litmus-Portal): Updated the Readme.md raw links for Beta to Branch specific links.

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml

**This PR will fix the RBAC for k8s-manifests in the Beta9 branch (These were fixed in master).** 
**This raw url to these manifests will be given in Readme.md in master.**

(Litmus-Portal): Fixed RBAC in Beta9 branch

---

litmus-portal/cluster-agents/event-tracker/main.go
litmus-portal/graphql-server/server.go

Adds version env check in event-tracker

added version env check in event-tracker

---

docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
docs/2.0.0/litmus-2.0.0.yaml
docs/2.0.0/litmus-namespaced-2.0.0.yaml

…s to Beta9.
**This PR will add Manifests for 2.0.0-RC1.**

Added Manifests for 2.0.0-RC1 & downgraded the Beta Manifest to Beta9

---

docs/2.0.0-Beta/litmus-2.0.0-Beta.yaml
docs/2.0.0-Beta/litmus-namespaced-2.0.0-Beta.yaml
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
litmus-portal/graphql-server/pkg/cluster/handler/handler.go
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

Adding delete permission to the manifest for deleting the subscriber

Adding delete permission to the manifest for deleting the subscriber

---

docs/2.0.0/litmus-2.0.0.yaml
docs/2.0.0/litmus-namespaced-2.0.0.yaml

Permission fix in docs/2.0.0-manifests

Permission fix in docs/2.0.0-manifests

---

litmus-portal/README.md
mkdocs/docs/2.0.0/litmus-2.0.0.yaml
mkdocs/docs/2.0.0/litmus-namespaced-2.0.0.yaml

**This PR adds Installation manifests for 2.0.0.**

(Litmus-Portal): Added Installation Manifests for 2.0.0

---

docs/2.0.0/litmus-2.0.0.yaml
docs/2.0.0/litmus-namespaced-2.0.0.yaml
litmus-portal/README.md

Added Updated Installation Manifests in 2.0.0 branch.

---

litmus-portal/README.md

Updating the chaos center readme

Updating the chaoscenter readme

---

mkdocs/docs/experiments/faq/portal.md

Faq added for bank of anthos workflow

Faq for bank of anthos workflow

---

mkdocs/docs/experiments/categories/pods/container-kill.md
mkdocs/docs/experiments/categories/pods/pod-cpu-hog-exec.md
mkdocs/docs/experiments/categories/pods/pod-cpu-hog.md
mkdocs/docs/experiments/categories/pods/pod-delete.md
mkdocs/docs/experiments/categories/pods/pod-dns-error.md
mkdocs/docs/experiments/categories/pods/pod-dns-spoof.md
mkdocs/docs/experiments/categories/pods/pod-io-stress.md
mkdocs/docs/experiments/categories/pods/pod-memory-hog-exec.md
mkdocs/docs/experiments/categories/pods/pod-memory-hog.md
mkdocs/docs/experiments/categories/pods/pod-network-corruption.md
mkdocs/docs/experiments/categories/pods/pod-network-duplication.md
mkdocs/docs/experiments/categories/pods/pod-network-latency.md
mkdocs/docs/experiments/categories/pods/pod-network-loss.md
mkdocs/docs/experiments/chaos-resources/chaos-engine/application-details.md
mkdocs/docs/experiments/chaos-resources/chaos-engine/experiment-components.md
mkdocs/docs/experiments/chaos-resources/chaos-engine/runner-components.md
mkdocs/docs/experiments/faq/portal.md
mkdocs/docs/experiments/troubleshooting/portal.md

(docs): fixing the list items rendering issue

---

mkdocs/docs/experiments/chaos-resources/chaos-scheduler/contents.md
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/engine-specification.md
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/once/immediate.yaml
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/once/specific-time.yaml
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/basic-schema.yaml
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/just-endtime.yaml
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/just-starttime.yaml
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/time-range.yaml
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/work-days.yaml
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/repeat/work-hours.yaml
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/schedule-once.md
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/schedule-repeat.md
mkdocs/docs/experiments/chaos-resources/chaos-scheduler/state.md
mkdocs/mkdocs.yml

Adding the chaos-scheduler docs and examples

(docs): Adding the chaos-scheduler docs and examples

---

mkdocs/docs/chaos-scheduler-v2.0.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.0.0.yaml

(docs): Adding manifest for 2.0.0 operator and scheduler

---

CONTRIBUTING.md

Updated CONTRIBUTING Docs

---

litmus-portal/frontend/src/components/AdjustedWeights/index.tsx
litmus-portal/frontend/src/components/AdjustedWeights/styles.ts
litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
litmus-portal/frontend/src/components/AgentDeployModal/styles.ts
litmus-portal/frontend/src/components/Button/BackButton/index.tsx
litmus-portal/frontend/src/components/DeveloperGuide/index.tsx
litmus-portal/frontend/src/components/DeveloperGuide/styles.ts
litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
litmus-portal/frontend/src/pages/EditSchedule/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx

* Updated AdjustedWeights component
* Updated Icons for Components
* AgentDeployModal
* BackButton
* DeveloperGuide

type(Icon): Updating Icons to LitmusUI for a few components

---

mkdocs/docs/experiments/categories/azure/azure-instance-stop.md
mkdocs/docs/experiments/categories/azure/azure-instance-stop/azure-instance.yaml
mkdocs/docs/experiments/categories/azure/azure-instance-stop/azure-scale-set-instance.yaml
mkdocs/docs/experiments/categories/azure/azure-instance-stop/chaos-interval.yaml

Signed-off-by: Akash Shrivastava <akash@chaosnative.com>
Adds SCALE_SET env in the docs 

Add Azure Scale Set support mention in Docs

---

.github/workflows/build.yml
.github/workflows/push.yml
README.md
litmus-portal/Makefile
litmus-portal/upgrade-agents/control-plane/main.go

This PR adds the upgrade agent build steps to the ci workflows.

added upgrade agent build to ci

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

Fixed Configuration Wizard Open Alert Issue

area(ConfigurationStepper): Fixed Configuration Wizard Open Alert Issue

---

litmus-portal/cluster-k8s-manifest.yml

**This PR will ad initContainer in server deployment to wait for MongoDB**

Added initContainer in server deployment to wait for MongoDB.

---

litmus-portal/README.md

Signed-off-by: ajeshbaby <ajesh@chaosnative.com>
Update uninstall section to docs link

Update un-installation section

---

litmus-portal/README.md

Updated Uninstallation Doc link

area(Uninstall): Updated Uninstallation Doc link

---

litmus-portal/graphql-server/server.go

fixed db version nil issue

---

litmus-portal/frontend/src/components/InstallChaos/index.tsx

This PR adds:
- Prompt while copying in myhub section

type(ux): Added prompt while copying in myhub section

---

litmus-portal/graphql-server/pkg/gitops/handler/handler.go

removing few gitops logs

---

mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/repeat/basic-schema-per-hour-at-specific-minute.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/repeat/basic-schema-per-hour.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/repeat/basic-schema-per-mins.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/repeat/just-starttime.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/repeat/time-range.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/repeat/work-days.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/repeat/work-hours.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-scheduler/schedule-repeat.md

(scheduler): adding minchaosinterval details

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

**This PR will litmuschaos/curl image in all dev/ci manifests for initContainers.**

Added litmuschaos/curl image in all dev/ci manifests for initContainers

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

type(ux): Fixed fetch policy issue in tune workflow page

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
mkdocs/docs/2.1.0/litmus-2.1.0.yaml
mkdocs/docs/2.1.0/litmus-namespaced-2.1.0.yaml

Final Upgrade of litmuschaos 2.1.0

---

litmus-portal/README.md

Updating readme

---

litmus-portal/frontend/package-lock.json
litmus-portal/frontend/package.json
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/TuneWorkflowSteps/SteadyState.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx

updated litmus-ui version to `1.6.0` for fixing analytics bugs

updated litmus-ui version to 1.6.0 for fixing analytics bugs

---

monitoring/utils/sample-application-under-test/percona/README.md

fixed grafana dashboard links for percona

fixed grafana dashboard links for percona

---

mkdocs/docs/experiments/concepts/awsIamIntegration.md
mkdocs/mkdocs.yml

- Add docs for AWS IAM integration for litmus service accounts

docs(AWS): Add docs for AWS IAM integration for litmus service accounts

---

litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

removing harcoded namepsace from nginx config

---

SECURITY.md

Signed-off-by: ksatchit <karthik@chaosnative.com>

(chore)security: add security disclosure process for litmuschaos

---

mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-operator-ci.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v2.0.0.yaml

Adding valueForm field for the ENVs inside chaosexperiment CRD 

chore(crd): adding valueFrom field inside env

---

mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-operator-ci.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v2.0.0.yaml
mkdocs/docs/litmus-operator-v2.1.0.yaml

chore(manifest): adding valueFrom field

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/1b_argo_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/1a_argo_rbac.yaml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

removing some unnecessary argo rbacs

removing some unnecessary argo rbacs

---

litmus-portal/authentication/api/main.go
litmus-portal/authentication/go.mod
litmus-portal/authentication/go.sum
litmus-portal/cluster-agents/event-tracker/go.mod
litmus-portal/cluster-agents/event-tracker/go.sum
litmus-portal/cluster-agents/event-tracker/main.go
litmus-portal/cluster-agents/subscriber/go.mod
litmus-portal/cluster-agents/subscriber/go.sum
litmus-portal/cluster-agents/subscriber/subscriber.go
litmus-portal/graphql-server/go.mod
litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/server.go
litmus-portal/upgrade-agents/control-plane/go.mod
litmus-portal/upgrade-agents/control-plane/go.sum
litmus-portal/upgrade-agents/control-plane/main.go

Signed-off-by: Vivek R <123vivekr@gmail.com>
Currently, we have a lot of env vars in the litmusportal, so this PR uses envconfig pkg to validate and process the env vars.
PKG- https://github.com/kelseyhightower/envconfig
Modules changed: 
- graphql-server
- event-tracker
- subscriber
- authentication-serve
Closes #2659

Use kelseyhightower/envconfig pkg to validate the environment variables

---

litmus-portal/cluster-agents/event-tracker/main.go

Fixed CLUSTER_ID typo in event-tracker

---

litmus-portal/graphql-server/server.go

**- Made PORT env optional**
**- Fixed ARGOWORKFLOWCONTROLLERIMAGE env typo**

Added ENVs fix for gql-server

---

mkdocs/docs/chaos-scheduler-v2.1.1.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.1.1.yaml

chore(2.1.1): adding manifest for 2.1.1 version

---

litmus-portal/cluster-agents/subscriber/subscriber.go

Minor fix in subscriber regarding start time

Minor fix in subscriber

---

ADOPTERS.md
adopters/organizations/pole_emploi.md

Add Pôle Emploi as an adopter.
Signed-off-by: Remi Ziolkowski <remi.ziolkowski-ext@pole-emploi.fr>

Add Pôle Emploi as an adopter.

---

litmus-portal/graphql-server/utils/misc.go

minor logic-fix in subscriber manifest generation

---

litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx
litmus-portal/frontend/src/pages/WorkflowInfoStats/StackedBar/index.tsx
litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/Observability/Overview/WorkflowStatisticsCard/index.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableData.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx

Added parameters to required components for workflow statistics test suite (litmus-e2e).

Add cypress parameters for workflow stats test suite

---

litmus-portal/frontend/src/utils/auth.ts
litmus-portal/graphql-server/pkg/authorization/middleware.go
litmus-portal/graphql-server/pkg/database/mongodb/project/operations.go
litmus-portal/graphql-server/pkg/database/mongodb/usermanagement/operations.go

- Updated jwt-token name from `token` to `litmus-cc-token`
- Removed unwanted logs from graphql server

Updated token name

---

litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx

Fixed an edge case for saving template for a basic argo workflow

---

litmus-portal/README.md
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
mkdocs/docs/2.3.0/litmus-2.3.0.yaml
mkdocs/docs/2.3.0/litmus-namespaced-2.3.0.yaml

Adding manifests for v2.3.0 ChaosCenter

---

mkdocs/docs/chaos-scheduler-v2.3.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.3.0.yaml

chore(2.3.0): Adding manifests for the 2.3.0 release

---

mkdocs/docs/litmus-admin-rbac.yaml

chore(admin-rbac): Adding networking policies permissions for the network partition experiment

---

litmus-portal/frontend/src/pages/WorkflowInfoStats/StackedBar/index.tsx
litmus-portal/frontend/src/pages/WorkflowInfoStats/index.tsx

Added cypress parameters for workflow stats loader

Add parameters for workflow stats loader

---

litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
litmus-portal/frontend/src/views/Observability/Overview/WorkflowStatisticsCard/index.tsx

This PR adds:
- Error logs while uploading yaml
- Edit schedule functionality
- Updated terminated icon in observability

chore(chaos-center): Added error logs while uploading yaml and fixed edit schedule functionality

---

litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx

Add cypress parameters for deleting schedule confirmation modal.

Add cy-parameters for deleting schedule

---

litmus-portal/frontend/src/components/Header/ProfileDropDown.tsx
litmus-portal/frontend/src/components/Header/ProjectDropDownItems.tsx
litmus-portal/frontend/src/components/SideBar/index.tsx
litmus-portal/frontend/src/pages/Targets/index.tsx
litmus-portal/frontend/src/pages/Workflows/index.tsx
litmus-portal/frontend/src/utils/auth.ts
litmus-portal/frontend/src/views/Home/AgentConfiguredHome/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/TableData.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/removeMemberModal.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx

**This PR will add required data-cy identifiers for Teaming tests & fixes the non-unique key issue for recent workflow runs in case when a workflow is ran twice.**

Adding Cypress identifiers for project details validation.

---

litmus-portal/frontend/src/views/Targets/BrowseCluster/TableData.tsx

Removed the condition for checking `isActive` data of a cluster in the upgrade agent button

Removed isActive condition from upgrade button

---

litmus-portal/frontend/src/pages/ConfigureDataSources/index.tsx
litmus-portal/frontend/src/views/Observability/DataSources/Forms/prometheus.tsx
litmus-portal/frontend/src/views/Observability/DataSources/Table/TableData.tsx
litmus-portal/frontend/src/views/Observability/DataSources/Table/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/TableData.tsx

Add cypress parameters for data source creation, configuration, and deletion

Add cypress parameters for data source

---

litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/WorkflowStats/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/ExperimentPoints.tsx

Add cypress parameters for workflow stats graph (Experiment radial chart, Resilience score chart &  Pass-Fail bar)

Add cypress parameters for workflow stats graph

---

litmus-portal/authentication/api/presenter/protos/authentication.pb.go
litmus-portal/authentication/api/presenter/protos/authentication_grpc.pb.go
litmus-portal/authentication/api/presenter/protos/project.pb.go
litmus-portal/authentication/api/presenter/protos/project_grpc.pb.go
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/protos/authentication.pb.go
litmus-portal/graphql-server/protos/authentication_grpc.pb.go
litmus-portal/graphql-server/protos/project.pb.go
litmus-portal/graphql-server/protos/project_grpc.pb.go
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

- Added grpc endpoints in cluster manifest
- Fixed go import issues in generated files

Updated cluster manifest and fixed go import issues

---

litmus-portal/graphql-server/pkg/authorization/validate.go
litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
litmus-portal/graphql-server/pkg/gitops/handler/handler.go

**This PR will close the unclosed connection for grpc client in graphql-server.**

Closing the unclosed connections for grpc client in graphql-server

---

litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml

**This PR will disable Leader election for workflow controller in Namespaced mode**

Disabling Leader election for workflow controller in Namespaced mode

---

litmus-portal/dex-server/dex-deployment.yaml

Fixed typo of `ClusterRole` resource

Fixed typo of clusterrole

---

litmus-portal/Makefile

**Depcheck has started giving false alerts. This PR will add chages for ignoring depcheck temporary. https://github.com/depcheck/depcheck/issues/687**

(Temporary-removal): Ignoring depcheck due to false alerts

---

mkdocs/docs/2.4.0/litmus-2.4.0.yaml
mkdocs/docs/2.4.0/litmus-namespaced-2.4.0.yaml

**This PR will add manifests for 2.4.0 ChaosCenter Installation**

Adding manifests for 2.4.0 ChaosCenter

---

mkdocs/docs/chaos-scheduler-v2.4.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.4.0.yaml

chore(2.4.0): Adding manifests for the 2.4.0 release

---

litmus-portal/README.md

**This PR will add changes in Readme.md for v2.4.0 manifests changes.**

Chore(2.4.0): Updating Readme.md for v2.4.0 manifests changes.

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx

Add cy param for revert-chaos button

Add cy param for revert-chaos button

---

litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
litmus-portal/cluster-agents/subscriber/subscriber.go

fixes- https://github.com/litmuschaos/litmus/issues/3245#issuecomment-997934195

Change fatal error to standard error for some logs

---

litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go

Adding fatal error for the connections in subscriber

Adding fatal error for the connections in subscriber

---

litmus-portal/frontend/src/components/LitmusStepper/index.tsx
litmus-portal/frontend/src/pages/ObservabilityPage/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboard/InfoDropdown/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboard/TopNavButtons/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Stepper/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/ConfigureDashboardMetadata/Form/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/TableData.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/index.tsx

Added cypress params for monitoring dashboard

Add cy-params for monitoring dashboard

---

litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/AcceptedInvitations/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/ReceivedInvitations/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Invitation/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/index.tsx

- Fixed the project details updation issue in teaming: now the details will be updated without any reload after accepting/declining the invitation.

Bug Fix: Fixed the project details updation issue in teaming

---

mkdocs/docs/auth/v2.0.0/api.html
mkdocs/docs/auth/v2.0.0/swagger.yml
mkdocs/docs/graphql/v2.0.0/api.html
mkdocs/docs/graphql/v2.0.0/config.yml

- Updated API docs with updated project APIs in auth server
- Removed unused user management queries and mutations from graphql API docs

Updated Auth API documentation

---

litmus-portal/authentication/api/handlers/grpc/grpc_handler.go
litmus-portal/authentication/api/handlers/rest/project_handler.go
litmus-portal/authentication/api/types/project_types.go
litmus-portal/authentication/pkg/entities/project.go
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx

- Updated project schema to remove redundant fields: now the member details will be fetched from user collection instead of duplicating the data in project collection.
- updated FE accordingly

Updated project schema to remove redundant fields

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

**This PR will update litmus core images to v2.4.0 in CI manifests.**

Updating litmus core images to v2.4.0 in CI manifests

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

**This PR will Update the grpc endpoints to localhost & upgrade manager.**

Updated the grpc endpoints to localhost & upgrade manager

---

mkdocs/docs/experiments/categories/pods/pod-io-stress/mount-path.yaml

Fix pod IO stress docs example for mount path

---

MAINTAINERS

Pending action item :-)
- Please add the links to the dependent PR needs to be merged before this (if any).

Update Email address

---

litmus-portal/ingress.yml
mkdocs/docs/2.4.0/litmus-2.4.0.yaml
mkdocs/docs/2.5.0/litmus-2.5.0.yaml
mkdocs/docs/2.5.0/litmus-namespaced-2.5.0.yaml

**This PR will -** 
- Add manifests for v2.5.0 ChaosCenter Installation
- ChaosCenter components - v2.5.0
- Litmus Core components - v2.4.0
- ChaosHub Branch - v2.4.x
- Update the Ingress manifests to use `networking.k8s.io/v1` apiVersion.
**Note - We have deprecated support for `extensions/v1beta1` apiVersion for Ingress.** 
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going …

Adding Manifests for v2.5.0 & updated Ingress Manifest

---

litmus-portal/README.md

Updating litmus version to 2.5.0

---

litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

(ChaosCenter): Fixed Upgrade Agent

---

mkdocs/docs/chaos-scheduler-v2.5.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.5.0.yaml

Chore(2.5.0): Add manifest for 2.5.0 litmus backend

---

litmus-portal/frontend/Dockerfile

Due to some CVE in the base of the frontend(nginxinc/nginx-unprivileged), upgrading it to the latest possible version

Updating base image of frontend to nginxinc/nginx-unprivileged:1.21-alpine 

---

mkdocs/overrides/home.html

Signed-off-by: neelanjan00 <neelanjan@chaosnative.com>
Updates the Sandbox status to Incubating status in Experiment Docs.

Updated Sandbox to Incubating Project Status in Experiment Docs

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

**This PR will update the core images & chaoscharts branch to v2.5.x.**

(Chaos-Center): Upgraded Core Images to v2.5.0 in master manifests

---

litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/index.tsx
litmus-portal/upgrade-agents/control-plane/go.mod
litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go
litmus-portal/upgrade-agents/control-plane/versions/v2.6.0/manager.go
litmus-portal/upgrade-agents/control-plane/versions/v2.6.0/workflow.go

This PR adds:
- Control Plane upgrade script
- Minor UI fix in runs and schedule table

Added control-plane upgrade script and minor UI fix

---

litmus-portal/README.md

**This will update the Readme.md with instructions for v2.6.0 Installation/Uninstallation & Upgrade.**

Updated Readme.md with 2.6.0 changes

---

mkdocs/docs/experiments/categories/pods/common-tunables-for-pod-experiments.md
mkdocs/docs/experiments/categories/pods/common/default-app-health-check.yaml
mkdocs/docs/experiments/categories/pods/pod-network-latency.md
mkdocs/docs/experiments/categories/pods/pod-network-latency/network-latency-jitter.yaml

Docs(examples): Add some example docs for jitter and default app check tunable

---

mkdocs/docs/chaos-scheduler-v2.6.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.6.0.yaml

Chore(2.6.0): Add manifest for 2.6.0

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml

* adding mongo headless svc 
* Replacing mongo-sts serviceName with mongo-headless
Refer- https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations

Adding mongo headless service to mongo sts

---

litmus-portal/authentication/go.mod
litmus-portal/authentication/go.sum

This PR updates gin-gonic to v1.7.7 

fix: updated gin version

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
litmus-portal/namespaced-k8s-template.yml

Adding security contexts to all litmus resources
except- mongo because it uses a root user in the docker image

Adding security contexts to all litmus resouces

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

**This PR will Update litmus-core images to 2.6.0 and add tagged image for curl**

Updated litmus-core images and added tagged image for curl

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml
litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/1c_argo_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

Adding resources requests and limits

---

litmus-portal/authentication/pkg/utils/configs.go
litmus-portal/authentication/pkg/utils/grpc.go
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

**This PR will disable auto mounting of default SA token for Frontend & MongoDB deployments.**

Disabled auto mounting of default SA token for Frontend & MongoDB deployments

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespaced-k8s-template.yml

fixing auth server endpoints in the frontend NGINX config

---

litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/graph/schema.resolvers.go
litmus-portal/graphql-server/pkg/cluster/handler/handler.go

This PR adds:
- mountPath fix for hub
- minor label fix in subscriber

chore(chaos-center): Updated hub mountPath and minor fix in deleteAgent mutation

---

litmus-portal/authentication/pkg/utils/configs.go

Added minor Fix for RPC endpoint in Authentication server

---

litmus-portal/frontend/src/graphql/mutations.ts
litmus-portal/frontend/src/graphql/queries.ts
litmus-portal/frontend/src/models/graphql/clusterData.ts
litmus-portal/frontend/src/models/graphql/dashboardsDetails.ts
litmus-portal/frontend/src/models/graphql/dataSourceDetails.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/ChooseWorkflowFromExisting.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/WorkflowSettings/index.tsx
litmus-portal/frontend/src/views/Observability/DataSources/Table/TableData.tsx
litmus-portal/frontend/src/views/Observability/DataSources/Table/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboard/ChaosAnnotationsEditor/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/TuneTheQueries/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/TableData.tsx
litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
litmus-portal/graphql-server/graph/generated/generated.go
litmus-portal/graphql-server/graph/schema.graphqls
litmus-portal/graphql-server/graph/schema.resolvers.go
litmus-portal/graphql-server/pkg/analytics/handler/handler.go
litmus-portal/graphql-server/pkg/authorization/roles.go
litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
litmus-portal/graphql-server/pkg/cluster/handler/handler.go

- Added RBAC checks for the following APIs:
DeleteClusterReg, DeleteChaosWorkflow, GeneraterSSHKey, UpdateDashboard, DeleteDashboard, DeleteDataSource, DeleteManifestTemplate, CreateImageRegistry, UpdateImageRegistry, DeleteImageRegistry, ListDataSource, GetPromSeriesList, ListDashboard, GetGitOpsDetails, ListManifestTemplate, GetTemplateManifestByID, ListImageRegistry, GetImageRegistry, TerminateChaosWorkflow, SyncWorkflow, SyncHub
- Only users with assigned roles will have privilage to access these APIs through UI, litmusctl, postman or any other platform.
- Malicious users trying to access these APIs by spoofing roles will get error response
Put an `x` in the boxes that apply. You can also fill …

Rbac validation

---

litmus-portal/namespaced-k8s-template.yml

**This PR will fix manifest for namespaced scope.**
Issue found in pipeline - 

Fixing manifest for namespaced scope

---

litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

This PR will add a upgrade path for 2.6.0->2.7.0.

Added minor fix for upgrade agent for 2.7.0

---

litmus-portal/authentication/pkg/project/repository.go
litmus-portal/frontend/src/containers/app/App.tsx

Signed-off-by: arkajyotiMukherjee <arko@chaosnative.com>

added the new APIs in frontend for RBAC and fixed associated security issues

---

litmus-portal/README.md
litmus-portal/namespaced-k8s-template.yml
mkdocs/docs/2.7.0/litmus-2.7.0.yaml
mkdocs/docs/2.7.0/litmus-namespaced-2.7.0.yaml

**This PR will update readme.md for 2.7 release.**

chore(ChaosCenter): Updated Readme for 2.7.0 ChaosCenter

---

mkdocs/docs/chaos-scheduler-v2.7.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.7.0.yaml

Release(2.7.0): Adds manifest for litmus backend 2.7.0

---

litmus-portal/Makefile
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/pkg/projects/project_handler.go
litmus-portal/graphql-server/pkg/self-deployer/start.go
litmus-portal/graphql-server/server.go
litmus-portal/namespaced-k8s-template.yml

This PR :
1. adds env var to configure self-agent component's node selector and tolerations. 
2. updates SELF_CLUSTER env var to SELF_AGENT
Related to #3526 
@rajdas98 @Jonsy13 will need to expose the env vars in helm after which the issue can be closed

feat: ability to configure self-agent component's node selector and tolerations

---

litmus-portal/authentication/api/handlers/rest/project_handler.go
litmus-portal/authentication/api/handlers/rest/user_handlers.go
litmus-portal/authentication/pkg/entities/user.go
litmus-portal/authentication/pkg/utils/errors.go
litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/styles.ts
litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/tableData.tsx

- Added email validation and added rbac in get_user_with_project API
- Fixes issues 1 and 7 under authentication APIs in https://github.com/litmuschaos/litmus-e2e/issues/362 

Added email validation and added rbac in get_user_with_project API

---

litmus-portal/authentication/api/handlers/rest/dex_auth_handler.go

- Adds created_at field while creating a user via dex
- Fixes https://github.com/litmuschaos/litmus/issues/3516

Added created_at field while creating user via dex

---

litmus-portal/cluster-agents/subscriber/go.mod
litmus-portal/cluster-agents/subscriber/go.sum
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/go.mod
litmus-portal/graphql-server/go.sum
litmus-portal/namespaced-k8s-template.yml

**This PR will** 
- Upgrade argo go pkgs to v3.2.9 in graphql-server & Subscriber
- Upgrade Litmus-Core to 2.7.0 in manifests
- Upgrade Argo workflow-controller & executor images to v3.2.9 (Fixing some of the vulnerabilities)
**This PR depends on https://github.com/litmuschaos/test-tools/pull/272**
- Please add the links to the dependent PR need …

(ChaosCenter): Upgrading workflow-controller & Executor to v3.2.9 & Litmus-Core to 2.7.0

---

litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/uploadYAML.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

- Added fix for workflow failure issue while adding experiments with the same name in a workflow [#11](https://github.com/chaosnative/cn-project-c1/issues/11), [#2500](https://github.com/litmuschaos/litmus/issues/2500), [3511](https://github.com/litmuschaos/litmus/issues/3511)

Added fix for workflow failure issue while adding experiments with same name( issue #11)

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/LocalQuickActionCard/index.tsx
litmus-portal/frontend/src/components/SideBar/index.tsx
litmus-portal/frontend/src/containers/app/App.tsx
litmus-portal/frontend/src/pages/ConfigureDataSources/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/index.tsx
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/TableData.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/styles.ts
litmus-portal/frontend/src/views/Observability/DataSources/Table/TableData.tsx
litmus-portal/frontend/src/views/Observability/DataSources/Table/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboard/DataSourceInactiveModal/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboard/PanelAndGroup/Panel.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboard/TopNavButtons/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/TuneTheQueries/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/TableData.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Table/index.tsx
litmus-portal/frontend/src/views/Observability/Overview/MonitoringDashboardCard/index.tsx
litmus-portal/frontend/src/views/Observability/Overview/WorkflowStatisticsCard/index.tsx
litmus-portal/frontend/src/views/Observability/Overview/index.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableData.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/TableToolbar.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/styles.ts

This PR adds:
- Workflow type filter in schedules and analytics tab
- Pre-define workflow redirect URL
- Changed from `observability` to `analytics` and updated the routes

chore(chaos-center): Added workflow type filter, pre-defined workflow redirect link and updated analytics routes

---

mkdocs/docs/experiments/categories/aws-ssm/aws-ssm-chaos-by-id.md
mkdocs/docs/experiments/categories/aws-ssm/aws-ssm-chaos-by-tag.md
mkdocs/docs/experiments/categories/aws/ebs-loss-by-id.md
mkdocs/docs/experiments/categories/aws/ebs-loss-by-tag.md
mkdocs/docs/experiments/categories/aws/ec2-terminate-by-id.md
mkdocs/docs/experiments/categories/aws/ec2-terminate-by-tag.md

Signed-off-by: Adarshkumar14 <adarsh@chaosnative.com>

Adding aws region in mandateory field

---

litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/choosePreDefinedExperiments.tsx

This PR updates the redirect URL of pre-defined workflows

Updated pre-defined workflows route

---

litmus-portal/cluster-agents/subscriber/pkg/events/workflow.go
litmus-portal/cluster-agents/subscriber/pkg/k8s/log.go
litmus-portal/cluster-agents/subscriber/pkg/k8s/objects.go
litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
litmus-portal/cluster-agents/subscriber/pkg/requests/webhook.go
litmus-portal/cluster-agents/subscriber/pkg/utils/workflow.go
litmus-portal/cluster-agents/subscriber/subscriber.go
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
litmus-portal/namespaced-k8s-template.yml

The subscriber was updating CLUSTER_ID and ACCESS_KEY in the agent-config map. This PR fixed the logic of the subscriber to update it in agent-secret.
Signed-off-by: Raj Babu Das <raj@chaosnative.com>

Fixing subscriber to update CLUSTER_ID and ACCESS_KEY to the agent-secret

---

mkdocs/docs/2.8.0/litmus-2.8.0.yaml
mkdocs/docs/2.8.0/litmus-namespaced-2.8.0.yaml
mkdocs/docs/2.8.0/upgrade-agent.yaml

Adding ChaosCenter 2.8.0 installation manifests

Adding ChaosCenter 2.8.0 installation manifests

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
litmus-portal/namespaced-k8s-template.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
mkdocs/docs/2.8.0/litmus-2.8.0.yaml
mkdocs/docs/2.8.0/litmus-namespaced-2.8.0.yaml

adding list secrets permission to eventtracker RBAC

adding list secrets permission to eventtracker RBAC

---

litmus-portal/README.md
litmus-portal/run.sh

Updating chaoscenter readme with 2.8.0 installation links

Updating chaoscenter readme with 2.8.0 installation links

---

mkdocs/docs/experiments/categories/pods/common-tunables-for-pod-experiments.md
mkdocs/docs/experiments/categories/pods/common/node-label-filter.yaml

- This PR adds docs for the NODE_LABEL feature in pod-level experiments.

Chore(docs): Add docs for NODE_LABEL feature in pod level experiments

---

litmus-portal/README.md
litmus-portal/namespace-k8s-manifest.yml

* Reducing the  complexity of installing namespace scope manifest
```yaml
#Create a namespace eg: litmus
kubectl create ns litmus
#Install CRDs, if SELF_AGENT env is set to TRUE
kubectl apply -f https://raw.githubusercontent.com/litmuschaos/litmus/2.8.0/litmus-portal/litmus-portal-crds.yml
#Install ChaosCenter
kubectl apply -f https://raw.githubusercontent.com/litmuschaos/litmus/master/litmus-portal/namespace-k8s-manifest.yml -n litmus
```
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're …

Reducing the  complexity of installing namespace scope manifest

---

MAINTAINERS

Updated contact details in maintainers file

chore: update contact details for gdsoumya 

---

litmus-portal/graphql-server/go.mod
litmus-portal/graphql-server/go.sum
litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml

**This PR will fix RBAC for namespaced scope.** 

Fixing RBAC in namespaced scope

---

litmus-portal/upgrade-agents/control-plane/go.mod
litmus-portal/upgrade-agents/control-plane/go.sum
litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

**This PR will add version upgrade for 2.8.0 in upgrade-agent.**

fixing upgrade-agent

---

monitoring/utils/prometheus/prometheus-scrape-configuration/01-prometheus-rbac.yaml

Prometheus k8s version update from beta1 to v1

update: Prometheus k8s version update from beta1 to v1

---

mkdocs/docs/graphql/v2.9.0/api.html
mkdocs/docs/graphql/v2.9.0/config.yml

- Added API documentation for analytics

Added API documentation for analytics

---

litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go
litmus-portal/cluster-k8s-manifest.yml
litmus-portal/namespace-k8s-manifest.yml
litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml

**This PR will fix error log in subscriber & update the litmus-core components to 2.8.0.** 

Fixed error logs in Subscriber & updated Litmus core components

---

mkdocs/docs/chaos-scheduler-v2.9.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.9.0.yaml

Chore(2.9.0): Add core component release manifest for 2.9.0

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/frontend/src/components/Header/index.tsx
litmus-portal/frontend/src/graphql/mutations/chaosHub.ts
litmus-portal/frontend/src/graphql/mutations/gitOps.ts
litmus-portal/frontend/src/models/graphql/chaoshub.ts
litmus-portal/frontend/src/models/graphql/prometheus.ts
litmus-portal/frontend/src/models/redux/workflow.ts
litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
litmus-portal/frontend/src/pages/MonitoringDashboard/index.tsx
litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
litmus-portal/frontend/src/redux/actions/workflow.ts
litmus-portal/frontend/src/redux/reducers/index.ts
litmus-portal/frontend/src/redux/reducers/workflow.ts
litmus-portal/frontend/src/utils/promUtils.ts
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/ChooseAWorkflowAgent/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/Observability/MonitoringDashboards/Steps/TuneTheQueries/EditPanelsWizard/index.tsx
litmus-portal/frontend/src/views/Settings/GitOpsTab/index.tsx
litmus-portal/frontend/src/views/Targets/BrowseCluster/index.tsx
litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go
litmus-portal/graphql-server/pkg/database/mongodb/analytics/schema.go
litmus-portal/graphql-server/pkg/handlers/core_version_handler.go
litmus-portal/graphql-server/server.go
litmus-portal/namespace-k8s-manifest.yml
litmus-portal/run.sh

This PR fixes:
- Dashboard creation and view dashboard issues
- Updated gitops schema in FE
- Minor changes

Fixed analytics dashboard and gitops related issues

---

litmus-portal/upgrade-agents/control-plane/main.go
litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Signed-off-by: Saranya-jena <saranya.jena@harness.io>
- Added info msg in upgrade manager when current and desired versions are the same. [(issue 3551)](https://github.com/litmuschaos/litmus/issues/3551)
- Added upgrade path for 2.9.0

Added info msg in upgrade manager when current and desired version are same

---

litmus-portal/cluster-agents/event-tracker/go.mod
litmus-portal/cluster-agents/event-tracker/go.sum
litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go

Fixing GitOps API in event tracker

---

litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx
litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/graphql-server/pkg/chaos-workflow/ops/operations.go

This PR adds:
- Updated logic to map weightages wrt to ChaosEngine name
- Fixes workflow stats table

Updated weightage logic and fixed workflow stats page

---

litmus-portal/frontend/src/pages/WorkflowInfoStats/WorkflowRunTable/index.tsx

Minor fix in workflow stats

---

mkdocs/docs/2.9.0/litmus-2.9.0.yaml
mkdocs/docs/2.9.0/litmus-namespaced-2.9.0.yaml
mkdocs/docs/2.9.0/litmus-portal-crds-2.9.0.yml
mkdocs/docs/2.9.0/upgrade-agent.yaml

**This PR will add manifests for 2.9.0 release of ChaosCenter.**

Added manifests for 2.9.0 release

---

.github/workflows/build.yml

**This PR will remove the ignore-path filter from workflow-level.**

Removed ignore-path filter from workflow level

---

mkdocs/docs/experiments/concepts/IAM/awsIamIntegration.md

EKS AWS IAM SA command fix in the [doc](https://litmuschaos.github.io/litmus/experiments/concepts/IAM/awsIamIntegration/).
NA
NA

Fix: AWS EKS IAM SA command

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/frontend/nginx/nginx.conf
litmus-portal/namespace-k8s-manifest.yml

**This PR will update the nginx.conf in manifests as well as local copy in frontend for supporting envoy proxy.**
**Tested with Istio as well as nginx-controller.**

Updated local nginx.conf as well as in manifests for supporting envoy proxy

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx

This PR fixes the following issue https://github.com/litmuschaos/litmus/issues/3633

Fixed issues with httpProbe and promProbe in tune workflow section

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/WorkflowStepper/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/ScheduleWorkflow/index.tsx

This PR fixes:
- Alert for invalid schedule type

fix(workflow-schedule): Added check for invalid schedule type

---

litmus-portal/cluster-k8s-manifest.yml
litmus-portal/graphql-server/pkg/gitops/handler/handler.go

This PR will fix updateGitOps functionality as reported [here](https://github.com/litmuschaos/litmus/issues/3642)
The issue was due to directory in path `/tmp/gitops_test` not getting mounted and as we have made the file-system as read-only, it was giving error. With this change both `/tmp/gitops` and `/tmp/gitops_test` will be mounted as emptyDir.
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …

Fixed updateGitOps functionality

---

mkdocs/docs/chaos-scheduler-v2.10.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.10.0.yaml

Relase(2.10.0): Adds release manifest for 2.10.0

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/components/AgentDeployModal/index.tsx
litmus-portal/frontend/src/views/Targets/TargetCopy/index.tsx

Signed-off-by: Sarthak Jain <sarthak.jain@harness.io>
Updated litmuctl command to connect agent

Updated litmuctl command to connect agent

---

litmus-portal/frontend/public/locales/en/translation.yaml
litmus-portal/frontend/src/pages/WorkflowInfoStats/InfoSection/index.tsx

Signed-off-by: Saranya-jena <saranya.jena@harness.io>

UI Fixes: Removed the duplicate words

---

litmus-portal/README.md

Updating readme for 2.11.0 release

Updating readme for 2.11.0

---

mkdocs/docs/chaos-scheduler-v2.11.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v2.11.0.yaml

chore(2.11.0): Adding release manifests for the litmus 2.11.0

---

README.md

Added a few more links
added a few links to the installation section of the Getting Started page

links to docs

---

litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
litmus-portal/manifests/cluster-k8s-manifest.yml
litmus-portal/manifests/namespace-k8s-manifest.yml

- Adding cluster roles and roles, required for the chaos-operator:2.11.0 .
- permission is required in openshift platform to run experiments.

Adding cluster roles and roles  required for the deployment in openshift

---

litmus-portal/frontend/src/utils/validate.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx

Schedules UI crashed when a workflow is created using API, due to invalid cron syntax.
This PR fixes the following issue https://github.com/litmuschaos/litmus/issues/3699

Fixed ui crashing issue for invalid cron syntax

---

litmus-portal/graphql-server/graph/resolver.go
litmus-portal/graphql-server/pkg/handlers/request_logger.go
litmus-portal/graphql-server/pkg/handlers/status_handler.go
litmus-portal/graphql-server/server.go

Adding graphql request logger middleware

Adding request logger middleware

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
litmus-portal/graphql-server/server.go

Added optional fields in cmdProbe and minor fixes

---

litmus-portal/frontend/src/containers/app/App.tsx
litmus-portal/frontend/src/pages/EditSchedule/Schedule.tsx
litmus-portal/frontend/src/pages/EditSchedule/index.tsx

Fixed edit schedule option

---

litmus-portal/frontend/src/containers/app/App.tsx
litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/index.tsx
litmus-portal/frontend/src/pages/WorkflowDetails/index.tsx
litmus-portal/frontend/src/pages/WorkflowDetails/styles.ts
litmus-portal/frontend/src/views/ChaosWorkflows/BrowseSchedule/TableData.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
litmus-portal/frontend/src/views/CreateWorkflow/VerifyCommit/index.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonPlot/index.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonPlot/style.ts
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/index.tsx
litmus-portal/frontend/src/views/Observability/WorkflowStatistics/WorkflowComparisonTable/styles.ts

**This PR will add changes for -** 
- Fixing Workflows comparison plot
- Fixing Workflow comparion report
- Fixing Logs for install experiment step
[chaos-center-statistics …

Added fixes for comparison plot & logs for install experiments step & data-cy parameters for ChaosHub

---

litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/connectGit.tsx
litmus-portal/manifests/cluster-k8s-manifest.yml
litmus-portal/manifests/namespace-k8s-manifest.yml

Minor fix in ChaosHub auth

---

litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/connectRemote.tsx
litmus-portal/frontend/src/pages/ChaosHub/MyHubConnectDrawer/styles.ts
litmus-portal/graphql-server/manifests/namespace/1b_argo_meta.yaml
litmus-portal/manifests/namespace-k8s-manifest.yml

Added warning text for remote chaos hub

---

litmus-portal/frontend/src/models/graphql/invite.ts
litmus-portal/frontend/src/models/graphql/user.ts
litmus-portal/frontend/src/views/ChaosWorkflows/Runs/styles.ts
litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/index.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/invitedTableData.tsx
litmus-portal/frontend/src/views/Settings/TeamingTab/Team/tableData.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/index.tsx
litmus-portal/frontend/src/views/Settings/UserManagementTab/UserManagement/tableData.tsx
litmus-portal/graphql-server/graph/cluster.graphqls

Signed-off-by: Saranya-jena <saranya.jena@harness.io>
- Fixed issue in deactivate user and created_at showing `invalid date`

Fixed issue in deactivate user and created_at showing `invalid date`

---

litmus-portal/cluster-agents/subscriber/pkg/events/util.go
litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

This PR adds:
- Fixed issue with executed_by label in subscriber
- Updated upgrade agent

Fixed issue with executed_by label in subscriber and updated upgrade agent

---

litmus-portal/README.md

Updating readme for 2.12.0

---

mkdocs/docs/experiments/concepts/chaos-resources/probes/cmdProbe.md
mkdocs/docs/experiments/concepts/chaos-resources/probes/litmus-probes.md

docs(cmdProbe): Adding docs for source attributes

---

ADOPTERS.md

Update ADOPTERS.md with HCL Cloud Native Labs entry

---

ADOPTERS.md
adopters/organizations/abinbev.md
adopters/organizations/ci&t.md

- [ x ] Documentation Update (if none of the other choices applies)
- [ x ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x  ] I have signed the commit for DCO to be passed.
- [ x ] Lint and unit tests pass locally with my changes
- [ x ] I have added necessary documentation (if …

Update Adopters (AbInbev, CI&T)

---

litmus-portal/frontend/src/utils/yamlUtils.ts
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx
litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx

This PR adds:
- Removal of instance_id in chaosEngines
- Added workflow.ui lable in chaosEngines

Added workflow.uid label in chaosengine

---

litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
litmus-portal/manifests/cluster-k8s-manifest.yml
litmus-portal/manifests/litmus-portal-crds.yml
litmus-portal/manifests/namespace-k8s-manifest.yml
mkdocs/docs/2.12.0/litmus-portal-crds-2.12.0.yml

**This PR will updates CRDs with new changes & update core components to 2.12.0 for CI manifests.**

Updated litmus CRDs & updated litmus-core components to 2.12.0 in CI manifests

---

litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
litmus-portal/manifests/litmus-portal-crds.yml

Minor fix in CRDs

---

litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Updated upgrade agent version to 2.13.0

---

litmus-portal/README.md
litmus-portal/manifests/cluster-k8s-manifest.yml
litmus-portal/manifests/namespace-k8s-manifest.yml
mkdocs/docs/2.13.0/litmus-2.13.0-without-resources.yaml
mkdocs/docs/2.13.0/litmus-2.13.0.yaml
mkdocs/docs/2.13.0/litmus-namespaced-2.13.0.yaml
mkdocs/docs/2.13.0/litmus-portal-crds-2.13.0.yml
mkdocs/docs/2.13.0/upgrade-agent.yaml

Adding manifests of 2.13.0

---

mkdocs/docs/experiments/concepts/security/openshift-scc.md

Update SCC docs with comments

---

mkdocs/docs/2.13.0/litmus-2.13.0-without-resources.yaml
mkdocs/docs/2.13.0/litmus-2.13.0.yaml
mkdocs/docs/experiments/categories/pods/pod-network-partition.md
mkdocs/docs/experiments/categories/pods/pod-network-partition/ports.yaml

**This PR will update docs for pod-network-partition experiment & also add minor fix in 2.13.0 manifests.**

Updated Ports example/docs for pod network partition experiment & minor fix in installation manifest

---

mkdocs/docs/chaos-scheduler-v2.12.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-ci.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v2.12.0.yaml

Chore(2.12.0): Add Core Component Manifest for Litmus 2.12.0

---

litmus-portal/graphql-server/pkg/myhub/ops/gitops.go

Adding depth=1 in the git clone options

---

mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v2.13.1.yaml

chore(2.13.1): Adding 2.13.1 release manifests

---

mkdocs/docs/experiments/categories/gcp/gcp-vm-disk-loss-by-label.md
mkdocs/docs/experiments/categories/gcp/gcp-vm-disk-loss-by-label/chaos-interval.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-disk-loss-by-label/gcp-disk-loss.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-disk-loss.md
mkdocs/docs/experiments/categories/gcp/gcp-vm-disk-loss/chaos-interval.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-disk-loss/gcp-disk-loss.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop-by-label.md
mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop-by-label/chaos-interval.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop-by-label/gcp-instance.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop-by-label/managed-instance-group.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop.md
mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop/chaos-interval.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop/gcp-instance.yaml
mkdocs/docs/experiments/categories/gcp/gcp-vm-instance-stop/managed-instance-group.yaml

Signed-off-by: Neelanjan Manna <neelanjan.manna@harness.io>
- Renamed GCP ZONES ENV in all experiments

chore(GCP Docs): Renamed GCP ZONES ENV

---

mkdocs/docs/experiments/concepts/security/psp.md

Signed-off-by: Udit Gaurav <udit.gaurav@harness.io>
Update the psp docs with adding the missing fields and comments on each field

Chore(docs): Update the psp docs with adding the missing fields and comments on each field

---

mkdocs/docs/chaos-scheduler-v2.14.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v2.14.0.yaml

- Adds core component manifest for 2.14.0

Release(2.14.0): Adds core component manifest for 2.14.0

---

mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml

Added changes for crd fix in namespaced scope for cmdProbes

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml
litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml

upgrade(litmus): updating graphql manifests

---

litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Added changes for upgrade-agent for 2.14.0 release

---

litmus-portal/README.md
litmus-portal/manifests/cluster-k8s-manifest.yml
litmus-portal/manifests/litmus-portal-crds.yml
litmus-portal/manifests/namespace-k8s-manifest.yml
mkdocs/docs/2.14.0/litmus-2.14.0-without-resources.yaml
mkdocs/docs/2.14.0/litmus-2.14.0.yaml
mkdocs/docs/2.14.0/litmus-namespaced-2.14.0.yaml
mkdocs/docs/2.14.0/litmus-portal-crds-2.14.0.yml
mkdocs/docs/2.14.0/upgrade-agent.yaml

Signed-off-by: avaakash <as86414@gmail.com>
Adding manifests of 2.14.0

Adding manifests of 2.14.0

---

litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Co-authored-by: Vedant <vedant.srotria@harness.io>

Added changes for upgrade 2.14.0 (#3794)

---

litmus-portal/README.md

Adding manifests of 2.14.0 (#3799)

---

demo/litmus-sdk/litmus-sdk.md

demo(litmu-sdk): Adding litmus-sdk demo

---

demo/boutique-chaos-on-load/boutique-chaos-on-load.md

Signed-off-by: Udit Gaurav <udit.gaurav@harness.io>

Demo(boutique): Adds demo docs for boutique application under load

---

mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/application-details.md
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/annotation-check.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/app-info.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/auxiliary-appinfo.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/engine-state.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/jobcleanup-policy.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/service-account.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-spec/terminationGracePeriod.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/engine-state.md
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components.md
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-annotations.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-configmaps-and-secrets.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-image.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-imagePullSecrets.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-nodeSelectors.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-resources.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-statusCheckTimeout.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/experiment-components/experiment-tolerations.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/rbac-details.md
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components.md
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-annotations.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-args-and-command.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-configmaps-and-secrets.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-image-and-pullPolicy.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-imagePullSecrets.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-nodeSelectors.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-resources.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runner-components/runner-tolerations.yaml
mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/runtime-details.md

Signed-off-by: avaakash <as86414@gmail.com>
1. Fixed Aux App docs with the correct format
2. Removed trailing whitespaces in chaos-engine specs
3. Removed newline from manifests in chaos-engine specs

Chore(Fix): Fixed Aux App docs

---

litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Signed-off-by: Adarsh kumar <adarsh.kumar@harness.io>

Adding upgrade agent for 3.0-beta1

---

litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Ignoring semantic versioning 

---

mkdocs/docs/chaos-scheduler-v3.0-beta1.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-ci.yaml
mkdocs/docs/litmus-operator-v3.0-beta1.yaml

chore(3.0-beta1): adding core manifests for 3.0-beta1 release

---

litmus-portal/graphql-server/server.go
litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Updated upgrade agent for 3.0.0-beta2 and minor fix with version checks

---

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
litmus-portal/graphql-server/pkg/analytics/handler/handler.go
litmus-portal/graphql-server/pkg/analytics/ops/operations.go

This PR fixes:
- Fixed analytics graph for monthly details
- Fixed empty retry option in probes (Fixes https://github.com/litmuschaos/litmus/issues/3843)

Fixed analytics graph and empty retry option in probes

---

litmus-portal/manifests/cluster-k8s-manifest.yml
litmus-portal/manifests/namespace-k8s-manifest.yml

Signed-off-by: Jonsy13 <vedant.shrotria@harness.io>

Updating core components to 3.0.0-beta2 in master manifests

---

mkdocs/docs/3.0.0-beta2/litmus-3.0.0-beta2-without-resources.yaml
mkdocs/docs/3.0.0-beta2/litmus-3.0.0-beta2.yaml
mkdocs/docs/3.0.0-beta2/litmus-namespaced-3.0.0-beta2.yaml
mkdocs/docs/3.0.0-beta2/litmus-portal-crds-3.0.0-beta2.yml
mkdocs/docs/3.0.0-beta2/upgrade-agent.yaml

Signed-off-by: Jonsy13 <vedant.shrotria@harness.io>

Added manifests for 3.0.0-beta2 ChaosCenter

---

mkdocs/docs/chaos-scheduler-v3.0.0-beta2.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.0.0-beta2.yaml

feat(3.0.0-beta2): adding release manifests for 3.0.0-beta2

---

MAINTAINERS.md

Signed-off-by: ksatchit <karthik.s@harness.io>

(fix)maintainers: fix typos in maintainers file

---

MAINTAINERS.md

Updating Raj Das username and emil in Maintainer.md

---

mkdocs/docs/chaos-scheduler-v3.0.0-beta4.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-ci.yaml
mkdocs/docs/litmus-operator-v3.0.0-beta4.yaml

chore(3.0.0-beta4): adding manifest for 3.0.0-beta4

---

mkdocs/docs/experiments/categories/pods/disk-fill.md
mkdocs/docs/experiments/categories/pods/disk-fill/container-path.yaml

Changed container path to socket path and runtime

---

litmus-portal/graphql-server/pkg/cluster/util.go

Replacing ArgoWorkflowControllerImage environment variable

---

litmus-portal/graphql-server/manifests/cluster/1b_argo_rbac.yaml
litmus-portal/graphql-server/manifests/cluster/1c_argo_deployment.yaml
litmus-portal/graphql-server/manifests/cluster/2b_litmus_rbac.yaml
litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml
litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/cluster/3b_agents_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/1a_argo_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/1b_argo_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/2a_litmus_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml
litmus-portal/graphql-server/manifests/namespace/3b_agents_deployment.yaml
litmus-portal/graphql-server/pkg/cluster/util.go
litmus-portal/graphql-server/pkg/database/mongodb/cluster/schema.go

Fixing node selector and toleration issue while generating the delegate manifest

---

litmus-portal/README.md
litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Added version changes in upgrade agent and updated readme with 3.0.0-beta5

---

litmus-portal/manifests/cluster-k8s-manifest.yml
mkdocs/docs/3.0.0-beta5/litmus-3.0.0-beta5-without-resources.yaml
mkdocs/docs/3.0.0-beta5/litmus-3.0.0-beta5.yaml
mkdocs/docs/3.0.0-beta5/litmus-namespaced-3.0.0-beta5.yaml
mkdocs/docs/3.0.0-beta5/litmus-portal-crds-3.0.0-beta5.yml
mkdocs/docs/3.0.0-beta5/upgrade-agent.yaml

Added manifests for `3.0.0-beta5` ChaosCenter release

---

mkdocs/docs/chaos-scheduler-v3.0.0-beta6.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-ci.yaml
mkdocs/docs/litmus-operator-v3.0.0-beta6.yaml

chore(3.0.0-beta6): Adding the manifests for 3.0.0-beta6

---

litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go

Added upgrade agent changes for 3.0.0-beta6

---

mkdocs/docs/chaos-scheduler-v3.0.0-beta7.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v3.0.0-beta7.yaml

chore(3.0.0-beta7): Adding the manifests for 3.0.0-beta7

---

ADOPTERS.md
adopters/organizations/apisix.md
adopters/organizations/infracloud.md

- [x ] Documentation Update (if none of the other choices applies)
- [ x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x ] I have signed the commit for DCO to be passed.
- [ x] Lint and unit tests pass locally with my changes
- [ x] I have added tests that prove my fix is effective or …

Adding Adopters

---

chaoscenter/graphql/server/pkg/database/mongodb/chaos_experiment/operations.go
chaoscenter/graphql/server/pkg/database/mongodb/chaos_experiment/schema.go
chaoscenter/graphql/server/pkg/database/mongodb/chaos_experiment_run/operations.go
chaoscenter/graphql/server/pkg/database/mongodb/chaos_experiment_run/schema.go
chaoscenter/graphql/server/pkg/database/mongodb/chaos_hub/schema.go
chaoscenter/graphql/server/pkg/database/mongodb/chaos_infrastructure/schema.go
chaoscenter/graphql/server/pkg/database/mongodb/environments/schema.go
chaoscenter/graphql/server/pkg/database/mongodb/image_registry/schema.go

- Added mongo schema and operations for chaos experiment and runs
- Added mongo schema for hub, infrastructure, environments and image registry

chore: Litmus 3.0: Added Mongo schema and operations

---

mkdocs/docs/chaos-scheduler-v3.0.0-beta8.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-ci.yaml
mkdocs/docs/litmus-operator-v3.0.0-beta8.yaml

chore(3.0.0-beta8): Adding the manifests for 3.0.0-beta8

---

chaoscenter/web/src/components/InputSlider/InputSlider.module.scss
chaoscenter/web/src/controllers/ChaosStudioClone/ChaosStudioClone.tsx
chaoscenter/web/src/controllers/ChaosStudioEdit/ChaosStudioEdit.tsx
chaoscenter/web/src/controllers/TargetApplicationTab/TargetApplicationTab.tsx
chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/TargetApplication/TargetApplication.tsx

fix: Fixed target application state not preserving issue

---

chaoscenter/Readme.md
chaoscenter/web/Dockerfile
chaoscenter/web/nginx/nginx.conf
mkdocs/docs/3.0.0-beta9/litmus-3.0.0-beta9-without-resources.yaml
mkdocs/docs/3.0.0-beta9/litmus-3.0.0-beta9.yaml
mkdocs/docs/3.0.0-beta9/litmus-namespaced-3.0.0-beta9.yaml
mkdocs/docs/3.0.0-beta9/litmus-portal-crds-3.0.0-beta9.yml
mkdocs/docs/3.0.0-beta9/upgrade-agent.yaml

Added installation manifests and readme for litmus 3.0.0-beta9

---

chaoscenter/web/config/webpack.dev.js
chaoscenter/web/src/config/index.ts
mkdocs/docs/3.0.0-beta9/litmus-3.0.0-beta9-without-resources.yaml
mkdocs/docs/3.0.0-beta9/litmus-3.0.0-beta9.yaml
mkdocs/docs/3.0.0-beta9/litmus-namespaced-3.0.0-beta9.yaml

Added changes for fixing beta9 issues

---

chaoscenter/subscriber/pkg/events/chaosengine.go
chaoscenter/subscriber/pkg/events/workflow.go

fix: fixed subscriber startTime issue

---

chaoscenter/web/src/models/chaosInfrastructure.ts
mkdocs/docs/3.0.0-beta10/litmus-3.0.0-beta10-without-resources.yaml
mkdocs/docs/3.0.0-beta10/litmus-3.0.0-beta10.yaml
mkdocs/docs/3.0.0-beta10/litmus-namespaced-3.0.0-beta10.yaml
mkdocs/docs/3.0.0-beta10/litmus-portal-crds-3.0.0-beta10.yml
mkdocs/docs/3.0.0-beta10/upgrade-agent.yaml

Updated CRD link and added manifests for beta10

---

mkdocs/docs/3.0.0-beta10/litmus-3.0.0-beta10-without-resources.yaml
mkdocs/docs/3.0.0-beta10/litmus-namespaced-3.0.0-beta10.yaml

updated default hub branch name

---

chaoscenter/graphql/server/pkg/chaos_experiment/types.go
chaoscenter/subscriber/pkg/types/event.go

Fixed chaosdata schema

---

chaoscenter/web/nginx/nginx.conf
mkdocs/docs/3.0.0-beta10/litmus-3.0.0-beta10-without-resources.yaml
mkdocs/docs/3.0.0-beta10/litmus-3.0.0-beta10.yaml
mkdocs/docs/3.0.0-beta10/litmus-namespaced-3.0.0-beta10.yaml

Fix: Added fix for nginx issue upon page refresh

---

chaoscenter/Readme.md

Updated installation step in readme for 3.0.0-beta10

---

chaoscenter/authentication/api/handlers/rest/project_handler.go
chaoscenter/authentication/api/routes/project_router.go
chaoscenter/authentication/pkg/project/repository.go
chaoscenter/authentication/pkg/services/project_service.go
mkdocs/docs/auth/v3.0.0/auth-api.json

- updated API to accept invitation state in path

Updated list_invitations API to make it generic 

---

mkdocs/docs/chaos-scheduler-v3.0.0-beta10.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.0.0-beta10.yaml

chore(3.0.0-beta10): Adding the manifests for 3.0.0-beta10

---

.gitattributes

Update .gitattributes to show golang language 

---

chaoscenter/web/src/components/MainNav/MainNav.module.scss
chaoscenter/web/src/components/MainNav/MainNav.module.scss.d.ts
chaoscenter/web/src/components/MainNav/MainNav.tsx
chaoscenter/web/src/components/SettingsWrapper/SettingsWrapper.module.scss
chaoscenter/web/src/components/SettingsWrapper/SettingsWrapper.tsx
chaoscenter/web/src/components/SideNav/SideNav.module.scss
chaoscenter/web/src/components/SideNav/SideNav.module.scss.d.ts
chaoscenter/web/src/components/SideNav/SideNav.tsx

feat: Updated SideBar Component

---

mkdocs/docs/chaos-scheduler-v3.0.0-beta11.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.0.0-beta11.yaml

chore(3.0.0-beta11): Adding the manifests for 3.0.0-beta11

---

chaoscenter/web/src/strings/strings.en.yaml
chaoscenter/web/src/strings/types.ts
chaoscenter/web/src/views/InviteNewMembers/InviteNewMemberListColumns.tsx
chaoscenter/web/src/views/InviteNewMembers/InviteNewMemberTable.module.scss
chaoscenter/web/src/views/InviteNewMembers/InviteNewMemberTable.module.scss.d.ts
chaoscenter/web/src/views/InviteNewMembers/InviteNewMembers.tsx
chaoscenter/web/src/views/InviteNewMembers/InviteUsersTable.tsx
chaoscenter/web/src/views/ProjectMembers/PendingMembersTable.tsx
chaoscenter/web/src/views/ProjectMembers/ProjectMember.module.scss
chaoscenter/web/src/views/ProjectMembers/ProjectMember.module.scss.d.ts

fix: Fixed UI issues found in teaming page

---

chaoscenter/graphql/server/graph/resolver.go
chaoscenter/graphql/server/pkg/chaos_experiment/ops/service.go

fix: Added experiment run operator for NewChaosExperimentService

---

chaoscenter/web/src/views/Environments/EnvironmentList/CreateEnvironment.tsx

fix: Fixed issue where create/edit environment API was being called twice

---

chaoscenter/web/src/strings/strings.en.yaml
chaoscenter/web/src/strings/types.ts
chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/Probes.tsx

Updated select probe button text

---

mkdocs/docs/chaos-scheduler-v3.0.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.0.0.yaml

chore(3.0.0): Adding the manifests for 3.0.0

---

chaoscenter/web/src/components/PipelineDiagram/Nodes/ChaosExecutionNode/ChaosExecutionNode.tsx

Fixed issue with fault node popover not showing probe results

---

chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go
chaoscenter/web/src/models/chaosInfrastructure.ts
chaoscenter/web/src/strings/strings.en.yaml

fixed duplicate experiment name issue

---

mkdocs/docs/3.0.0/litmus-3.0.0-without-resources.yaml
mkdocs/docs/3.0.0/litmus-cluster-scope-3.0.0.yaml
mkdocs/docs/3.0.0/litmus-namespaced-3.0.0.yaml

Updated Default Branch Name for ChaosHub

---

mkdocs/docs/3.0.0/litmus-3.0.0-without-resources.yaml
mkdocs/docs/3.0.0/litmus-cluster-scope-3.0.0.yaml
mkdocs/docs/3.0.0/litmus-namespaced-3.0.0.yaml

Updated chaoshub branch in 3.0.0 manifest

---

chaoscenter/web/src/views/Environments/EnvironmentList/CreateEnvironment.tsx

fix: fixed update environment submit button issue

---

mkdocs/docs/experiments/categories/pods/pod-network-corruption.md
mkdocs/docs/experiments/categories/pods/pod-network-corruption/blacklist-source-and-destination-ports.yaml
mkdocs/docs/experiments/categories/pods/pod-network-duplication.md
mkdocs/docs/experiments/categories/pods/pod-network-duplication/blacklist-source-and-destination-ports.yaml
mkdocs/docs/experiments/categories/pods/pod-network-latency.md
mkdocs/docs/experiments/categories/pods/pod-network-latency/blacklist-source-and-destination-ports.yaml
mkdocs/docs/experiments/categories/pods/pod-network-loss.md
mkdocs/docs/experiments/categories/pods/pod-network-loss/blacklist-source-and-destination-ports.yaml

Add port blacklisting in the pod-network faults

---

chaoscenter/README.md

Updated the installation manifest broken link in readme

---

mkdocs/docs/chaos-scheduler-v3.1.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.1.0.yaml

chore(3.1.0): Adding the manifests for 3.1.0

---

chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go

This change introduces a map to uniquely identify each mode with the probe name as its key. Mitigating the mode overriding bug.

chore: Updating GetProbesInExperimentRun API

---

.github/dependabot.yml

Added dependabot configuration to configure scanning of only required directories

---

chaoscenter/web/src/components/ExperimentActionButtons/ExperimentActionButtons.tsx
chaoscenter/web/src/strings/strings.en.yaml
chaoscenter/web/src/strings/types.ts
chaoscenter/web/src/views/ChaosProbes/AddProbeModal.tsx
chaoscenter/web/src/views/ExperimentBuilderTemplateSelection/UploadYAML.tsx
chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/SelectProbesTab/NoProbes.tsx
chaoscenter/web/src/views/ExperimentDashboardV2/ExperimentDashboardV2TableMenu.tsx
chaoscenter/web/src/views/ProjectMembers/ProjectMembers.tsx

fix: Fixed RBAC issue and updated upload YAML function

---

chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go

fix: Fixed duplicate probe issue in enable/disable cron API

---

mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-operator-ci.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v3.1.0.yaml

Integrate the operator image with scarf gateway

---

chaoscenter/web/.eslintrc.yml
chaoscenter/web/src/api/ReactQueryProvider.tsx
chaoscenter/web/src/utils/testUtils.tsx
chaoscenter/web/src/views/ErrorCheck/__tests__/ErrorCheck.test.tsx
chaoscenter/web/src/views/Overview/Overview.tsx
chaoscenter/web/src/views/Overview/__tests__/Overview.test.tsx
chaoscenter/web/src/views/ResetPassword/__tests__/ResetPassword.test.tsx

Added test cases for views in chaoscenter web 
- ErrorCheck.tsx
- ResestPassowrd.tsx
- Overview.tsx

feat: add tests cases for  chaoscenter web views

---

MAINTAINERS.md

Updated Codeowners

---

MAINTAINERS.md

Update Maintainer email

---

mkdocs/docs/chaos-scheduler-v3.2.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.2.0.yaml

chore(3.2.0): Adding the manifests for 3.2.0

---

chaoscenter/web/src/services/experiment/KubernetesYamlService.ts

chore(chaoscenter): Added node selector in chaos engine spec

---

mkdocs/docs/3.3.0/litmus-3.3.0-without-resources.yaml
mkdocs/docs/3.3.0/litmus-cluster-scope-3.3.0.yaml
mkdocs/docs/3.3.0/litmus-namespaced-3.3.0.yaml
mkdocs/docs/3.3.0/litmus-portal-crds-3.3.0.yml

Added installation manifests for 3.3.0

---

chaoscenter/web/src/controllers/APITokens/APITokens.tsx
chaoscenter/web/src/views/ApiTokens/ApiTokens.tsx

fix: Fixed issue with API tokens refetch and copy button

---

mkdocs/docs/chaos-scheduler-v3.3.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v3.3.0.yaml

chore(3.3.0): Adding the installation manifests for 3.3.0

---

chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go
chaoscenter/subscriber/pkg/k8s/operations.go

Fixed issue infra config map and secret patch

---

chaoscenter/graphql/server/pkg/database/mongodb/init.go

updated the environment_id index to be a partial index

---

chaoscenter/graphql/server/server.go
mkdocs/docs/3.4.0/litmus-3.4.0-without-resources.yaml
mkdocs/docs/3.4.0/litmus-cluster-scope-3.4.0.yaml
mkdocs/docs/3.4.0/litmus-namespaced-3.4.0.yaml
mkdocs/docs/3.4.0/litmus-portal-crds-3.4.0.yml

Added 3.4.0 installation files

---

mkdocs/docs/chaos-scheduler-v3.4.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.4.0.yaml

chore(3.4.0): Adding the installation manifests for 3.4.0

---

.github/workflows/cifuzz.yml

Reference: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

Added required manifest integrate OSS-Fuzz in CI

---

chaoscenter/README.md

- [ x] Documentation Update (if none of the other choices applies)
- [x ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [ x] I have signed the commit for DCO to be passed.

Updated litmus installation through kubectl in the README.md with latest version of litmus

---

mkdocs/docs/experiments/concepts/chaos-resources/probes/cmdProbe.md

Add docs for tolerations in source cmdProbe.
Fixes: [#482](https://github.com/litmuschaos/chaos-operator/issues/482)
Part of PR: [PR](https://github.com/litmuschaos/chaos-operator/pull/483)

Adds docs for toleratios in source cmdProbe

---

chaoscenter/web/src/controllers/Environments/Environment.tsx

Fixed #4462 
Pagination is now working as expected.

Added pagination control in environment list

---

chaoscenter/web/.husky/pre-commit
chaoscenter/web/.husky/pre-push

closes #4468
Modified `pre-commit` and `pre-push` hook scripts to `POSIX-compilant`.
Now they can run on any environment and most shells like `bash`, `dash`, `sh`, `zsh`.
Result of commit after changes.

Husky hook fix.

---

chaoscenter/web/package.json
chaoscenter/web/yarn.lock

While fixing CSS conflict between UICore V3 (from harness-core-ui) and UICore V4, I accidentally unpublished `4.0.0-beta.1`. This action is unrecoverable per NPMJS Support team.
This leads to packages that depends on `4.0.0-beta.1` (Limus and Gitness) fail to build.
To fix this issue, a change from `4.0.0-beta.1` to `4.0.0-beta.1a` is needed. `4.0.0-beta.1a` is exact the same as `4.0.0-beta.1`.
- Please add the links to the dependent PR need to be …

chore(deps): Update package.json to use UICore 4.0.0-beta.1a

---

mkdocs/docs/3.5.0/litmus-3.5.0-without-resources.yaml
mkdocs/docs/3.5.0/litmus-cluster-scope-3.5.0.yaml
mkdocs/docs/3.5.0/litmus-namespaced-3.5.0.yaml
mkdocs/docs/3.5.0/litmus-portal-crds-3.5.0.yml

Added installation manifest for 3.5.0

---

mkdocs/docs/chaos-scheduler-v3.5.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-latest.yaml
mkdocs/docs/litmus-operator-v3.5.0.yaml

chore(3.5.0): Adding the installation manifest for 3.5.0

---

chaoscenter/graphql/server/go.mod
chaoscenter/graphql/server/go.sum
chaoscenter/graphql/server/pkg/chaoshub/handler/handler.go

addded path sanitisation for hub repo URL

---

chaoscenter/graphql/server/pkg/chaos_experiment/ops/service.go

Remove unused variable 
Closes #4386 

Remove unused variable

---

.github/workflows/cifuzz.yml

Updated ci-fuzz github workflow to run on specific paths and fuzz duration

---

mkdocs/docs/chaos-scheduler-v3.6.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.6.0.yaml

chore(3.6.0): Adding the installation manifest for 3.6.0

---

mkdocs/docs/3.6.1/litmus-3.6.1-without-resources.yaml
mkdocs/docs/3.6.1/litmus-cluster-scope-3.6.1.yaml
mkdocs/docs/3.6.1/litmus-namespaced-3.6.1.yaml
mkdocs/docs/3.6.1/litmus-portal-crds-3.6.1.yml

Added installation manifests for 3.6.1

---

chaoscenter/web/src/models/chaosInfrastructure.ts

chore: Updated CRD version in Infrastructure installation

---

chaoscenter/event-tracker/main.go
chaoscenter/subscriber/subscriber.go

chore(tls): Fix the subscriber & event-tracker to add CUSTOM_TLS_CERT to root cert pool instead of override

---

RELEASE_GUIDELINES.md

docs(k8s-version): update the litmus & k8s version compatibility metrics

---

chaoscenter/manifests/litmus-cluster-scope.yaml
mkdocs/docs/3.7.0/litmus-3.7.0-without-resources.yaml
mkdocs/docs/3.7.0/litmus-cluster-scope-3.7.0.yaml

Added permissions to get secrets for graphql server

---

mkdocs/docs/chaos-scheduler-v3.7.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.7.0.yaml

chore(3.7.0): Adding the installation manifest for 3.7.0

---

MAINTAINERS.md

Updating email id

---

chaoscenter/graphql/server/pkg/chaoshub/service.go

Fixed nil pointer issue with default chaoshubs

---

chaoscenter/graphql/server/server.go

Temporarily removing version check for Database in 3.x

---

mkdocs/docs/chaos-scheduler-v3.8.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.8.0.yaml

chore(3.8.0): Adding the installation manifest for 3.8.0

---

mkdocs/docs/chaos-scheduler-v3.8.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-scheduler-namespaced-crd.yaml

chore(schedule): update the scheduler crd

---

chaoscenter/authentication/api/handlers/rest/project_handler.go
chaoscenter/authentication/api/handlers/rest/user_handlers.go
chaoscenter/authentication/api/handlers/rest/user_handlers_test.go
chaoscenter/authentication/api/handlers/rest/validations.go
chaoscenter/authentication/pkg/entities/session.go
chaoscenter/authentication/pkg/entities/user.go
chaoscenter/authentication/pkg/user/repository.go
chaoscenter/authentication/pkg/utils/errors.go

Added mandatory checks for default password reset

---

chaoscenter/authentication/api/main.go
chaoscenter/authentication/api/middleware/cors.go
chaoscenter/authentication/go.mod
chaoscenter/authentication/go.sum
chaoscenter/graphql/server/api/middleware/cors.go
chaoscenter/graphql/server/go.mod
chaoscenter/graphql/server/go.sum
chaoscenter/graphql/server/server.go
chaoscenter/graphql/server/utils/variables.go

add cors check

---

chaoscenter/authentication/api/handlers/grpc/grpc_handler.go

Added nil check for token validation

---

chaoscenter/dex-server/dex-deployment.yaml
chaoscenter/manifests/litmus-getting-started.yaml
chaoscenter/manifests/litmus-installation.yaml
chaoscenter/manifests/litmus-without-resources.yaml

updated dex deployment yaml

---

mkdocs/docs/chaos-scheduler-v3.9.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.9.0.yaml

chore(3.9.0): Adding the installation manifest for 3.9.0

---

.github/workflows/build.yml
chaoscenter/authentication/Dockerfile
chaoscenter/event-tracker/Dockerfile
chaoscenter/graphql/server/Dockerfile
chaoscenter/subscriber/Dockerfile

We migrated the base image of the dockerfile in choascenter to UBI. Changing the exit-code to 1 only for the changed image to check if there are any vulnerabilities. 

Changing trivy exit code to 1

---

mkdocs/docs/3.9.2/litmus-getting-started.yaml
mkdocs/docs/3.9.2/litmus-installation.yaml
mkdocs/docs/3.9.2/litmus-portal-crds.yml
mkdocs/docs/3.9.2/litmus-without-resources.yaml

Added installation manifest for 3.9.2

---

chaoscenter/web/src/components/ProjectDashboardCardContainer/ProjectDashboardCardContainer.tsx

fix: Fixed routing issues with project switcher

---

mkdocs/docs/3.10.0/litmus-getting-started.yaml
mkdocs/docs/3.10.0/litmus-installation.yaml
mkdocs/docs/3.10.0/litmus-portal-crds.yml
mkdocs/docs/3.10.0/litmus-without-resources.yaml

Added installation manifests for 3.10.0

---

mkdocs/docs/chaos-scheduler-v3.10.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.10.0.yaml

chore(3.10.0): Adding the installation manifest for 3.10.0

---

mkdocs/docs/auth/v3.0.0/auth-api.json
mkdocs/docs/auth/v3.9.0/auth-api.json

Correct swagger.json file versions
- v3.0.0
- v3.9.0

fix: Correct swagger.json file versions

---

chaoscenter/graphql/definitions/shared/chaoshub.graphqls
chaoscenter/graphql/server/graph/generated/generated.go
chaoscenter/graphql/server/graph/model/models_gen.go
chaoscenter/graphql/server/pkg/chaoshub/models_factory.go
chaoscenter/graphql/server/pkg/chaoshub/service.go
chaoscenter/graphql/server/pkg/database/mongodb/chaos_hub/schema.go

Added remoteHub field in chaosHub backend

---

chaoscenter/authentication/api/handlers/rest/user_handlers.go

response invalidCredentials status that does not match has changed from 400 to 401
https://github.com/litmuschaos/litmus/blob/37fae3a4577ef80fb7d8ab26b67fd6059b75c702/chaoscenter/authentication/api/handlers/rest/user_handlers.go#L266
https://github.com/litmuschaos/litmus/blob/37fae3a4577ef80fb7d8ab26b67fd6059b75c702/chaoscenter/authentication/pkg/utils/errors.go#L32

Comment response invalidcredentails status has changed from 400 to 401

---

mkdocs/docs/chaos-scheduler-v3.11.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.11.0.yaml

chore(3.11.0): Add the installation manifest for 3.11.0 version

---

.github/workflows/push.yml

Fixed deprecated upload/download artefact github action in push.yml

---

ADOPTERS.md

ADOPTERS.md updated.

---

chaoscenter/web/src/views/ExperimentDashboardV2/ExperimentDashboardV2Table.tsx
chaoscenter/web/src/views/ExperimentDashboardV2/ExperimentDashboardV2TableMenu.tsx

Closes #4679 
Running experiments can be stopped now even if stuck in Queued state and then the experiment can be deleted.
When there are running experiments, delete option is disabled
When there are no running experiments when stuck in queued state, delete option is enabled
- [ x] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md) doc
- [x ] I have signed the commit for DCO to be passed.
- [x ] Lint and …

Support for delete/abort when experiment is stuck in Queued state 

---

README.md

Removed 3 broken links in the community blogs section as the corresponding pages appear to have been removed from the websites. No suitable replacements were found.

Remove invalid links in README.md

---

chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go

when update ChaosExperiment log can't know what is problem. so change error to log message for better debugging

Add error msg to the log on UpdateChaosExperiment

---

mkdocs/docs/chaos-scheduler-v3.12.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.12.0.yaml

chore(3.12.0): Add the installation manifest for 3.12.0 version

---

mkdocs/docs/3.10.0/litmus-getting-started.yaml
mkdocs/docs/3.10.0/litmus-without-resources.yaml
mkdocs/docs/3.11.0/litmus-getting-started.yaml
mkdocs/docs/3.11.0/litmus-installation.yaml
mkdocs/docs/3.11.0/litmus-without-resources.yaml
mkdocs/docs/3.12.0/litmus-getting-started.yaml
mkdocs/docs/3.12.0/litmus-installation.yaml
mkdocs/docs/3.12.0/litmus-without-resources.yaml
mkdocs/docs/3.13.0/litmus-getting-started.yaml
mkdocs/docs/3.13.0/litmus-installation.yaml
mkdocs/docs/3.13.0/litmus-portal-crds.yml
mkdocs/docs/3.13.0/litmus-without-resources.yaml
mkdocs/docs/3.9.0/litmus-getting-started.yaml
mkdocs/docs/3.9.0/litmus-installation.yaml
mkdocs/docs/3.9.0/litmus-without-resources.yaml
mkdocs/docs/3.9.1/litmus-getting-started.yaml
mkdocs/docs/3.9.1/litmus-installation.yaml
mkdocs/docs/3.9.1/litmus-without-resources.yaml
mkdocs/docs/3.9.2/litmus-getting-started.yaml
mkdocs/docs/3.9.2/litmus-installation.yaml
mkdocs/docs/3.9.2/litmus-without-resources.yaml

Added installation manifest for 3.13.0

---

mkdocs/docs/chaos-scheduler-v3.13.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.13.0.yaml

chore(3.13.0): Add the installation manifest for 3.13.0 version

---

ADOPTERS.md
adopters/organizations/emirates-nbd.md
adopters/organizations/outsystems.md

Add Emirates NBD and OutSystems as adopters

Add Emirates NBD and OutSystems as adopters

---

ADOPTERS.md

Updating Emirates NBD Our Story Link

chore: Updating Emirates NBD story link

---

README.md

I updated the recent LitmusChaos videos on CNCF in the README.

Update recent videos in README

---

MAINTAINERS.md

Sahil, Ajesh & Hrishav have been at the forefront of maintaining the Litmus website and its associated artifacts. Proposing their elevation as maintainers of the website-related repositories 

(chore)maintainers: add newer maintainers for the Litmus websites

---

ROADMAP.md

(chore)roadmap: update the litmus roadmap

---

MAINTAINERS.md

chore: Updated Hrishav's name in maintainer's list

---

translations/README-ko.md

I updated the recent LitmusChaos videos on CNCF in the README-ko.

Update recent videos in README-ko

---

mkdocs/docs/3.14.0/litmus-getting-started.yaml
mkdocs/docs/3.14.0/litmus-installation.yaml
mkdocs/docs/3.14.0/litmus-portal-crds.yml
mkdocs/docs/3.14.0/litmus-without-resources.yaml

Added installation manifest for 3.14.0

---

mkdocs/docs/chaos-scheduler-v3.14.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.14.0.yaml

chore(3.14.0): Add the installation manifest for 3.14.0 version

---

.github/ISSUE_TEMPLATE/maintainer.md
.github/ISSUE_TEMPLATE/member.md
.github/ISSUE_TEMPLATE/reviewer.md
GOVERNANCE.md
MAINTAINERS.md
community-roles.md

Updates Governance policy and Memebership roles

chore: Updating Governance policy and Memebership roles

---

MAINTAINERS.md

Fixing MAINTAINER.md formatting

chore: Fixing MAINTAINER.md formatting

---

.github/ISSUE_TEMPLATE/maintainer.md
.github/ISSUE_TEMPLATE/member.md
.github/ISSUE_TEMPLATE/reviewer.md

chore: Fixing ISSUE_TEMPLATE naming

---

chaoscenter/authentication/api/handlers/rest/project_handler.go

Fixes inconsistent response of `/list_projects` API when no projects are found
Fixes #5010 
No dependent PR's

fix: return only message when no projects are found

---

mkdocs/docs/chaos-scheduler-v3.15.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.15.0.yaml

chore(3.15.0): Add the installation manifests for 3.15.0 version

---

mkdocs/docs/3.16.0/litmus-getting-started.yaml
mkdocs/docs/3.16.0/litmus-installation.yaml
mkdocs/docs/3.16.0/litmus-portal-crds.yml
mkdocs/docs/3.16.0/litmus-without-resources.yaml

Adding LitmusChaos Install manifest for 3.16.0

chore: Adding LitmusChaos Install manifest for 3.16.0

---

mkdocs/docs/chaos-scheduler-v3.16.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.16.0.yaml

chore(3.16.0): Add the installation manifests for 3.16.0 version

---

mkdocs/docs/chaos-scheduler-v3.17.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.17.0.yaml

chore(3.17.0): Adding the installation charts for 3.17.0 version

---

proposals/python-sdk.md

Add Litmus Python SDK proposal docs

[Proposal] Support a LitmusChaos Python SDK

---

.github/workflows/cifuzz.yml
.github/workflows/e2e.yml

Some of the ci workflows are using deprecated version of artifacts for upload/download. I've updated their versions.

ci: update artifact version

---

mkdocs/docs/3.18.0/litmus-getting-started.yaml
mkdocs/docs/3.18.0/litmus-installation.yaml
mkdocs/docs/3.18.0/litmus-portal-crds.yml
mkdocs/docs/3.18.0/litmus-without-resources.yaml

Adding Litmus install manifest for 3.18.0

chore: Adding Litmus install manifest for 3.18.0

---

mkdocs/docs/chaos-scheduler-v3.18.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.18.0.yaml

chore(3.18.0): Adding the installation charts for 3.18.0 version

---

mkdocs/docs/3.19.0/litmus-getting-started.yaml
mkdocs/docs/3.19.0/litmus-installation.yaml
mkdocs/docs/3.19.0/litmus-portal-crds.yml
mkdocs/docs/3.19.0/litmus-without-resources.yaml

Adding Litmus install manifest for 3.19.0

chore: Adding Litmus install manifest for 3.19.0

---

mkdocs/docs/chaos-scheduler-v3.19.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.19.0.yaml

chore(3.19.0): Adding the installation charts for 3.19.0 version

---

.github/workflows/build.yml
.github/workflows/push.yml
chaoscenter/dex-server/Dockerfile
chaoscenter/dex-server/web/web.go

Enable Dex Server builds in PR checks and Push pipelines

---

.github/workflows/push.yml

fixed push.yml having issue with duplicate IDs

---

ADOPTERS.md
adopters/organizations/amadeus.md

Add Amadeus in the list of organization

Add Amadeus in the list of adopters

---

mkdocs/docs/3.20.0/litmus-getting-started.yaml
mkdocs/docs/3.20.0/litmus-installation.yaml
mkdocs/docs/3.20.0/litmus-portal-crds.yml
mkdocs/docs/3.20.0/litmus-without-resources.yaml

chore: Adding install manifest for 3.20.0

---

mkdocs/docs/chaos-scheduler-v3.21.0.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-operator.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-namespaced-scheduler.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-experiment-rbac.yaml
mkdocs/docs/litmus-namespaced-scope/litmus-ns-rbac.yaml
mkdocs/docs/litmus-operator-v3.21.0.yaml

release(3.21.0): Add the installation manifest for the 3.21.0
