vdbench/bench_runner.sh
Usage : 
```
docket -v /mnt/testdir:/datadir1 run openebs/test-storage <template> <duration>
```
=> add options to specify template and duration

Makefile, mysql-client/Dockerfile, mysql-client/MySQLLoadGenerate.sh, mysql-client/buildscripts/push
Code changes: 
----------------
- Why is this change necessary?
We need a client to generate sql load for DB servers deployed on kubernetes
- How does this change address the issue?
Creates a client container that runs some simple insert/select queries repeatedly with increased data chunks each time to generate load on the sql server pod
- What side effects does this change have?
No impact to the product itself
Changes tested on: 
---------------------
Container tested after building locally on ubuntu 16.04 64 bit Baremetal boxes/ESX VM
=> Include container to run database load for mysql (mysql-client)

Makefile, custom-percona/Dockerfile, custom-percona/buildscripts/push, custom-percona/docker-entrypoint.sh
Code changes: 
----------------
- PMM (Percona monitoring & management) is a free and open-source solution that provides thorough time-based analysis for MySQL servers.
It consists of :
a) pmm-client : Which is installed on every database host that you want to monitor. It collects server metrics, general system metrics, and query analytics data for a complete performance overview.
b) pmm-server : The central part of PMM that aggregates collected data and presents it in the form of tables, dashboards, and graphs in a web interface.
- While the pmm-server is available as a standalone docker image, the pmm-client installation on the DB server is a manual process. While acceptable for a bare-metal DB installation, it is not optimal for a percona server container, as the packages in a …
=> Create a custom percona server container image integrated with pmm-client

Makefile, mysql-master/Dockerfile, mysql-master/buildscripts/push, mysql-master/docker-entrypoint.sh, mysql-slave/Dockerfile, mysql-slave/buildscripts/push, mysql-slave/docker-entrypoint.sh
- Contains custom images for mysql master and slave, which can be used in kubernetes application deployments when setting up mysql replication clusters.
Fixes : https://github.com/openebs/test-storage/issues/20
=> Added test container images for mysql replication cluster

mysql-slave/Dockerfile
Code Changes : 
----------------
The mysql-slave dockerfile uses the same server-id as the mysql-master in the following error during replication:
"Fatal error: The slave I/O thread stops because master and slave have equal MySQL server ids; these ids must be different for replication to work "
This commit removes that line & retains one that generates a random server-id
Fixes #23
=> Generate random server-id for mysql-slave 

Makefile, custom-percona/Dockerfile, logger/Dockerfile, logger/README.md, logger/buildscripts/push, logger/debugjob.yaml, logger/logger.sh, mysql-master/Dockerfile, mysql-slave/Dockerfile
- The logger container and debugjob K8s job have been created to aid troubleshoot/debugging on the kubernetes cluster by capturing the pod logs
- Logger uses a tool called "stern" to collect the pod logs.
- It is also capable of executing kubectl commands to extract cluster state.
Capabilities that need to be added (being worked currently) to the debug container to increase its effectiveness/utility include: 
- Collect node logs  (kubelet) 
- Capture kube-system logs (this can be obtained by passing --namespace arg to stern. However, this may need to be an optional param)
=> Initial commit to create stern-based debug container and kubernetes job 

.travis.yml, Makefile, README.md, docs/litmus_deep_dive.md, docs/running_test_suite.md
Litmus can be used by various teams & end users to
test their kubernetes deployments. Hence, the tone of
the content has been made generic.
A docs folder with 2 topics has been added. This was
separated from readme as readme will focus more on
building a test case & running it versus how to run
the entire test suite.
A simple readme will enable contributors to understand
fast and hence make contributions. Running test suite
is seen as a step that should be taught later once the
initial hurdle is passed.
In future, the readme will have build the test logic,
containerizing & running the same. There is also a plan
to have a video to build, containerize & run a test case.
Signed-off-by: AmitKumarDas <amit.das@openebs.io>
=> makes the contents inside readme more generic

tests/mysql/mysql_storage_benchmark/mysql.yaml, tests/mysql/mysql_storage_benchmark/run_litmus_test.yaml, tools/tpcc-client/tpcc-mysql/tpcc-runner.sh
Changes: 
- Improve tpcc-runner to check mysql server connectivity & perform fixed retries
- Removed the default wait time in the tpcc-bench sidecar of percona-mysql pod
- Replaced the litmus ansible-runner image
Notes for reviewers: 
- The MySQL DB initialization sequence (at the end of which the mysqld is ready to take connections) is seen to take different amount on time on : 
- Different platforms 
- Different storage backends 
- The existing mysql pod runs the tpcc-bench container as a sidecar, which waits for a fixed period of 60s before attempting database creation as part of the benchmark preparation. This was seen to error out on the OpenEBS volume, on which the init took > 60s (values ranged from 80-100s based on nature of underlying disks) 
- The PR uses an improved method as …
=> Implement retry logic based on mysql server state in tpcc-runner (mysql-benchmark test) 

tests/fio/fio.yaml, tests/fio/run_litmus_test.yaml, tests/fio/test.yaml, tests/fio/test_cleanup.yaml, tests/fio/test_vars.yaml, tools/fio/fio_runner.sh, tools/fio/templates/file/basic-rw, tools/fio/templates/file/standard-ssd
- Creates a litmus test for fio-based benchmarks for storage evaluation
- Updates the openebs/tests-fio workload generator container, with respect to: 
- Additional template based on user request
- Improvements to fio_runner bash script
- The fio profiles checked into the tools/fio/templates are based on user definitions. While the core IO parameters are retained unchanged during a test, options have been provided in the test job to run with desired size and duration.
- The fio run has been configured to …
=> Include litmus test for fio-based benchmark

tests/mysql/mysql_persistence_on_pod_eviction/README.md, tests/mysql/mysql_persistence_on_pod_eviction/mysql.yaml, tests/mysql/mysql_persistence_on_pod_eviction/run_litmus_test.yaml, tests/mysql/mysql_persistence_on_pod_eviction/test.yaml, tests/mysql/mysql_persistence_on_pod_eviction/test_cleanup.yaml, tests/mysql/mysql_persistence_on_pod_eviction/test_vars.yaml
- This litmus test verifies persistence of MySQL data upon forced reschedule of all pods on the application node due to resource constraints (disk-pressure) 
- The eviction/resource constraint is applied by the test on the application node via a kubernetes node taint `node.kubernetes.io/out-of-disk` with action `NoExecute`. This belongs to a group of taints for which the `tolerationSeconds` is 0, i.e., the pods are immediately evicted. Typically, these are applied by node-controller when certain system conditions are true.
- The data persistence is checked by validating the presence of table content written prior to the reschedule
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, …
=> Add litmus test to check mysql data persistence upon forced reschedule (via pod evictions)

tests/fio/run_litmus_test.yaml, tests/mysql/mysql_persistence_on_pod_eviction/README.md, tests/mysql/mysql_persistence_on_pod_eviction/run_litmus_test.yaml, tests/mysql/mysql_storage_benchmark/run_litmus_test.yaml
- The current litmus test jobs uses "/mnt" as the log-location for placing the pod, cluster and ansible playbook logs. The tarball created after compression is based on timestamp and not intuitive for user to relate to test executed. This PR adds a log directory named after the test in /mnt to store the same logs. 
- Until a better log visualization approach is identified, the following steps will have to be performed: 
- Append test-name to hostPath volume.
- Obtain the logs from *wherever* (node) litmus pod …
=> Add dedicated log directory to each test

README.md
- Adds a missing test pre-requisite to create a configmap out of the cluster's kubeconfig file. This will be mounted into the litmus pod to aid stern-based logging.
=> Add step in README to create configmap from the in-cluster-config 

executor/ansible/plugins/callback/actionable.py, tests/mysql/mysql_data_persistence/chaos/pumba/pod_failure_by_sigkill.yaml, tests/mysql/mysql_data_persistence/run_litmus_test.yaml, tools/ansible-runner/Dockerfile
- Include custom ansible stdout callback plugin "actionable"
- Minor updates to chaos type and duration for MySQL data persistence test
The callback plugin displays the test playbook run output similar to the following : 
```
TASK [Check whether the provider storageclass is applied] **********************
TASK [Replace the pvc placeholder with test param] *****************************
TASK [Replace the storageclass placeholder …
```
=> Include custom ansible stdout callback plugin "actionable"

Providers/OpenEBS/Installers/Operator/0.6/ansible/openebs.yaml, Providers/OpenEBS/Installers/Operator/0.6/ansible/vars.yaml, Providers/OpenEBS/Installers/Operator/0.6/litmusbook/setup_openebs.yaml, tools/ansible-runner/Dockerfile
- This PR adds litmusbook for installing openebs v0.6 in kubernetes cluster .
- This book has been tested on both AWS and GCP cluster .
- Logs for litmus pod running this book in GCP cluster :
```
kubectl log -n litmus litmus-openebs-qk9bd
log is DEPRECATED and will be removed in a future version. Use logs instead.
TASK [Applying openebs operator] ***********************************************
TASK [Applying openebs storageclass] *******************************************
FAILED - RETRYING: Checking Maya-API-Server is running (100 retries left).
TASK [Checking Maya-API-Server is running] …
```
=> Adds litmus book to install openebs 0.6

providers/openebs/installers/operator/0.6/ansible/sc.yaml
This PR fixes invalid storage pool name in storage class on openebs 0.6 litmus book.
=> Fixes invalid storage pool name in storage class of openebs 0.6

Makefile
- Some recent changes to the gometalinter is seen to break the CI. This PR excludes gosec linter (suspected lint tool)
```
2.07s$ make
------------------
--> Running go fmt
------------------
------------------
--> Running metalinter
------------------
pkg/exec/exec.go:49::warning: Subprocess launched with variable,MEDIUM,HIGH (gosec)
make: *** [metalint] Error 1
```
- There is no new go-libraries being added into litmus at this point, so adding the above exclude until active go development resumes.
=> Fix broken travis builds/CI

hack/litmus-result.yaml, hack/rbac.yaml, tools/ansible-runner/Dockerfile
- The litmus test results are currently maintained in a result.json file that is stored inside the "logdir" specified in the litmus job, which is a host path on the node. For any CI system, executing the litmus tests, extracting the test results would mean fetching the file content from the node OR parsing the ansible runner pod logs to the result strings.  It would be desirable to have a better/simpler means of getting the results. This PR addresses this need, and makes a provision for the test status  to be stored in a custom resource  (thanks @kmova ). This way the test results can also be obtained via a kubectl command (the CI stage/job executing the test can perform this step) 
**Which issue this PR fixes** *(optional, in `fixes #<issue …
=> Initial commit for Litmus result CRD & CR spec 

tools/ansible-runner/Dockerfile
-> This PR removes add test operation from tools/docker file as there is no more test directory present.
-> Changed  ADD **providers/openebs/installers/operator/** to  ADD **providers/openebs/installers/operator/** so that storageclass litmus job can also get packed to the ansible runner image .
-> New expected directory structure:
```
providers
└── openebs
└── installers
├── operator
│   └── 0.6
│       ├── ansible
│       └── litmusbook
└── storageclass
└── 0.6
├── ansible
└── litmusbook
```
=> Fixes docker error of no test directory present

k8s/aws/ebs-volumes/README.md, k8s/aws/ebs-volumes/create-ebs-volume.yml, k8s/aws/ebs-volumes/delete-ebs-volume.yml, k8s/aws/ebs-volumes/vars.yml
- Add `create-ebs-volume.yml` playbook will create, attach and mount ebs-volume.
- Add `delete-ebs-volume.yml` playbook will unmount, detach and delete ebs-volume.
- Add `vars.yml` will store all variable data.
- O/P for create-ebs-volume.yml
```
$ ansible-playbook create-ebs-volume.yml --extra-vars "cluster_name=nodes.k8s-compassionate-babbage.k8s.local"
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
PLAY [localhost] ********************************************************************************************************************************************************
TASK [Gathering Facts] …
```
=> Add playbook for create ebs-volume in aws

providers/openebs/installers/operator/0.6/README.md, providers/openebs/installers/operator/0.6/ansible/openebs_cleanup.yaml, providers/openebs/installers/operator/0.6/ansible/openebs_setup.yaml, providers/openebs/installers/operator/0.6/litmusbook/openebs_cleanup.yaml, providers/openebs/installers/operator/0.6/litmusbook/openebs_setup.yaml
-> This PR adds cleanup code for openebs.
-> Applying cleanup code will perform ```kubectl delete -f openebs-oprator.yaml```
-> Adds following environment variable to pass image name explicitly.
```
- OPENEBS_IO_JIVA_CONTROLLER_IMAGE  
- OPENEBS_IO_JIVA_REPLICA_IMAGE  
- OPENEBS_IO_VOLUME_MONITOR_IMAGE  
- OPENEBS_IO_JIVA_REPLICA_COUNT 
```
-> This PR has been tested on a GCP cluster anf found working .
=> Add cleanup code for removal of openebs v0.6 and exposes more environment variable

README.md, apps/fio/tests/run_litmus_test.yaml, apps/percona/tests/mysql_data_persistence/run_litmus_test.yaml, apps/percona/tests/mysql_storage_benchmark/README.md, apps/percona/tests/mysql_storage_benchmark/run_litmus_test.yaml
- Currently, all tests have job name as "litmus"  (The tests cleanup all the resources created as part of the test, with the litmus job itself stays behind). 
- The job does not identify with the test being performed
- Re-running these tests errors out & can be executed only if the completed job instance is removed/deleted. It is possible for users to forget this step. 
- CI systems using litmus jobs in their pipelines will have the additional step of deletion of completed job in each stage, whereas a bulk removal at the end of the pipeline may be more desirable. 
- This PR addresses the above issue by : 
a) Prefixing test names to litmus test jobs (`litmus-<test-name>`)
b) Adding metadata.generateName …
=> Update tests to generate unique test-specific job names

master.yaml
**What this PR does**:
This PR makes it easy to marshal `master.yaml` and create patch for litmus tests.
`op`, `path`, `value` are the fields needed to parse JSONPointer, rest of the fields are just for informative purpose.
possible values for `op` (operation) are `"add"`, `"remove"`, `"replace"`, `"move"`, `"test"` and `"copy"`.
**Assumptions:**
- It is assumed in JSONPointer that `ansibletest` container is the first one in YAML when it is parsed.
- Parameters represented in current `master.yaml` is not already present in the litmus test spec. (since I have used `add` in `op` field of each param)
Note: All the above assumptions are met in this PR
Signed-off-by: Abhishek Kashyap <abhishek.kashyap@mayadata.io>
=> `master.yaml` uses JSONPointer instead of JSONPath

apps/percona/chaos/openebs_target_network_delay/run_litmus_test.yaml, apps/percona/chaos/openebs_volume_replica_failure/run_litmus_test.yaml
- Currently, the stern-based logger runs for a pre-defined period, regardless of completion of the test container execution, thereby keeping the test job alive for much longer than necessary. The other case, i.e., completion of log collection before test end (esp on slower systems where image pulls take a long time) is also observed
- This PR fixes the above behaviour by running the log collection process until the test container is terminated. The logger waits upon test completion, following which the node (systemd) logs are collected & test job ends
- This involves passing the test container name in the logger's command along with certain cluster data (pod name, namespace) to the logger in the form of …
=> Updates to logger spec to capture logs for duration of litmus test container

k8s/gcp/k8s-installer/check-cluster-availability.yml, k8s/gcp/k8s-installer/create-k8s-cluster.yml, k8s/utils/health/cluster_health_check.py
- Separate cluster availability check from `create-k8s-cluster.yml`
playbook for GCP
- Add `check-cluster-availability.yml` playbook, that runs independently
and checks for readiness of cluster
- Separating these playbooks helps in calling cleanup/rollback process, in case of
non-availability/failure of the cluster due to any reason
=> Seperate Cluster availability check playbook

providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Without the retry check added to the task (to check whether ndm ds is running) , ansible performs a default retry check 3 times before failing. 
=> Add retries flag to ndm run check in openebs installer litmusbook (master) 

apps/percona/deployers/percona-installer.yaml, providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- The openebs operator installer litmusbook tries to identify node count by performing a `grep <none>` operation with reference to lack of role definitions for the nodes in the cluster. However, this behaviour may change across providers and kubernetes versions. In AWS, for 1.10.x the node roles are explicitly defined causing failure of this step. A more generic approach that checks for taints with 'master' key are used to determine the 'schedulable nodes' of the cluster - thereby getting a more realistic count.
- Simplified a namespace existence check in percona app deployer that was failing due to lack of quotes while performing a string compare within the kubectl jsonpath filter.
**Which issue this …
=> Updates to litmus openebs installer & percona app-deployer jobs

providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
**What this PR does / why we need it**: 
- Refer #124 (The taint based check to discount the master during a node count, while being a good method is seen to fail when executed over a kubeconfig from inside a pod). 
- Using a simpler check involving `grep -v master` directly from the `kubectl get nodes` o/p. This is seen to work from pods mounted w/ kubeconfig - and is verified on vagrant, GKE and kops-based AWS clusters. 
=> Obtain node count w/o master across kubernetes distros 

apps/percona/chaos/openebs_target_network_delay/test.yaml, apps/percona/chaos/openebs_volume_replica_failure/test.yaml
- In cases where a chaos test is repeated multiple times, or multiple applications undergo same type of chaos, there is a necessity to use a distinct result CR. Currently, the CR derives its name from the chaos testname.  This PR allows for provisioning a instance ID/run ID as ENV, which, if present will be appended to the chaos testname, thereby rendering the CR unique.
- An environment variable "RUN_ID" needs to be added to the ansibletest container in the run_litmus_test.yaml job spec to use the above.
=> Append custom string to litmus result CR name indicative of instance_id/run_id of chaos

chaoslib/openebs/jiva_controller_network_delay.yaml, chaoslib/openebs/jiva_replica_pod_failure.yaml
Change label from `openebs/replica=jiva-replica` to `openebs.io/replica=jiva-replica`
Change label from `openebs/controller` to `openebs.io/controller`
Signed-off-by: Akash Srivastava <akash.srivastava@openebs.io>
=> Update label for fetching jiva controller and replica pods

apps/cassandra/deployers/cassandra-installer.yml, apps/cassandra/deployers/cassandra_vars.yml, apps/cassandra/deployers/deploy_cassandra_litmus.yml
- Update litmus job to refer to openebs-standard storage class by default.
- Fix litmus cr result job to use test name (lower case alphanumeric characters, '-' or '.')
- Added a check to verify successful creation of statefulset replicas as specified in statefulset spec.
@shashank855 Can you review this PR?
=> Update cassandra litmus book to verify successful creation of statefulset replicas.

apps/cockroachdb/deployers/cockroachdb-installer.yaml, apps/cockroachdb/deployers/cockroachdb-sts.yaml, apps/cockroachdb/deployers/cockroachdb-svc.yaml, apps/cockroachdb/deployers/cockroachdb-vars.yaml, apps/cockroachdb/deployers/deploy-app-litmus.yaml
- In K8s cluster, deploys cockroachdb application as statefulset with 3 replicas.
- Using new variable in cockroachdb litmusbook for the application deployment type(statefulset/deployment)
- If the deployment is statefulset, verifying if all the replicas are created and running.
=> Deploy cockroachdb as k8s statefulset

apps/cassandra/workload/cassandra-loadgen.yml, apps/cassandra/workload/run_cassandra_loadgen.yml, apps/cassandra/workload/test.yml, apps/cassandra/workload/test_vars.yml
- Include litmus book to run workload on cassandra statefulset.
- Runs loadgen for specified duration.
- Verify the data written by fetching keyspaces inside the pod.
=> Include litmus book to run workload on cassandra statefulset.

common/utils/app-deploy.yml, common/utils/deploy-check.yml, common/utils/litmus-result.yml, common/utils/sts-check.yml
- Include litmus app-deploy util to deploy any application by passing application spec.
- Include litmus deploy-check util to check the phase of the application pod by using application specs.
- Include litmus sts-check util to verify successful creation of statefulset replica's creation by validation with the number of replica's specified in the sts spec.
- Include litmus result-cr util to set litmus book (Start Of Test) and (End Of Test) state as a CR.
=> Litmus common utils for re-usable tasks to add new litmus books.

providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Include CAS Templates creation check as part of setup_openebs.
- Verifies CAS templates creation by kubectl command  `kubectl get cast -n <namespace>` with retry count of 3.
=> Include CAS Templates creation check as part of setup_openebs.

hack/litmus-prerequisites.sh
Simplifies the process of setting up litmus pre-requisites before running the test jobs. 
- Take kubeconfig path as user input, with defaults specified
- Setup litmus RBAC and create kubeconfig configmap (after renaming to admin.conf) 
=> feat(install): setup litmus-prerequisites on cluster

apps/percona/tests/mysql_data_persistence/test.yaml, chaoslib/kubectl/cordon_drain_node.yaml, chaoslib/kubectl/pod_evict_by_taint.yaml, chaoslib/pumba/pod_failure_by_sigkill.yaml
- Standardizes the params taken by the chaoslib modules
- Passes `app_ns` to chaoslib instead of hardcoding to litmus
=> fix(yaml): pass application namespace to pumba & kubectl chaoslib utils

apps/cassandra/deployers/run_litmus_test.yml, apps/cassandra/workload/run_litmus_test.yml, apps/fio/tests/run_litmus_test.yml, apps/mongodb/deployers/run_litmus_test.yml, apps/percona/tests/mysql_data_persistence/run_litmus_test.yml, apps/percona/tests/mysql_storage_benchmark/run_litmus_test.yml
- As we use litmus pod logs for debugging, we need to use default plugin for dumping the stdout.
- Changed the plugin to 'default' wherever 'actionable' and 'log_plays' were used.
=> Using default ansible stdout plugin in the deployers litmusbooks

k8s/packet/k8s-installer/README.md, k8s/packet/k8s-installer/create_packet_cluster.yml, k8s/packet/k8s-installer/pre_requisite.sh, k8s/packet/k8s-installer/vars.yml
Add k8s version support for packet cloud
- Modify `create_packet_cluster.yml` for add k8s_version support and pass
it to bash script
- Modify `vars.yml` for provide maximum resourses for nodes
```
$ kubectl get nodes
NAME                   STATUS    ROLES     AGE       VERSION
master-nervous-nobel   Ready     master    30m       v1.10.0
node-nervous-nobel01   Ready     <none>    27m       v1.10.0
node-nervous-nobel02   Ready     <none>    28m       v1.10.0
node-nervous-nobel03   Ready     <none>    29m       v1.10.0
```
=> Add k8s version support for packet cloud

providers/openebs/installers/operator/master/ansible/openebs_setup.yaml
- Due to liveness probe addition to the maya-apiserver deployment in openebs operator, the container
takes requests after the initialDelaySeconds of 300s. 
- During this period the pod.status.phase check returns 'Running'
- The new check verifies container 'ready' status instead of the above
=> Update provider litmusbook to check maya-apiserver container status instead of pod status 

k8s/gcp/k8s-installer/create-k8s-cluster.yml, k8s/gcp/k8s-installer/create-vpc.yml, k8s/gcp/k8s-installer/delete-vpc.yml
- Modify create-vpc.yml to create random vpc instead to hardcoding and
store the vpc name in a log file
- This allows the playbook to support multiple cluster creation
simultaneously.
- Modify create-k8s-cluster.yml to read the vpc name from log file and
use it per se in kops
- Modify delete-vpc.yml to fetch the vpc name from the log file
=> Modify GCP playbook for random VPC name support

apps/percona/chaos/openebs_target_failure/test_vars.yml
- Removes reference to cstor in the target failure test (as it can invoke both openebs-cstor & openebs-jiva related chaoslib utils) 
=> refactor(yaml): remove cstor references in the target failure test

tools/ansible-runner/Dockerfile, tools/godog-runner/Dockerfile
Update the kubectl binary in the ansible-runner & godog-runner images
* Why was this change necessary?
ansible-runner, godog-runners Dockerfile have older version of kubectl
* Are there any side effects?
No
https://github.com/openebs/litmus/issues/193
On branch 193-kubectl
Changes to be committed:
modified:   ansible-runner/Dockerfile
modified:   godog-runner/Dockerfile
=> Update the kubectl binary in the ansible-runner & godog-runner images

apps/cassandra/workload/test_vars.yml, apps/mongodb/deployers/test.yml, apps/percona/deployers/test.yml
- Corrected the namespace variable name in cassandra workload litmusbook.
- Corrected typo in percona and mongodb deployers.
=> Modified namespace variable name in cassandra workload litmusbook

apps/percona/chaos/openebs_target_failure/test.yml, apps/percona/deployers/test.yml
- CI pipelines that use deployers and chaos with multiple providers (storage-classes) OR with different image versions etc.,  the result CRs from which the test status is derived need to be differentiated from one-another. Currently the result CR name is taken from the test-name which is constant. The runID, if available is appended to the test-name to make it unique, and thereby traceable (refer: https://github.com/openebs/litmus/pull/131)
=> fix(yaml): update the percona deployer and network-delay chaos to us run metadata ENV/runID

apps/percona/chaos/openebs_replica_network_delay/run_litmus_test.yml, apps/percona/chaos/openebs_target_failure/run_litmus_test.yml, apps/percona/chaos/openebs_target_network_delay/run_litmus_test.yml, apps/percona/chaos/openebs_volume_replica_failure/run_litmus_test.yml
- There may be user wrapper scripts that have been templatized & serve the purpose of replacing env values in the existing jobs. This requires that the litmus jobs follow a certain standard/convention with respect to the way in which the values of the env are specified. For ex: wrapping them with `""` v/s `' '` v/s `not-quoting` them at all etc,. 
- This may cease to be an issue when there are tools that inherently understand the K8s spec. But it cannot be assumed that the users will use only such tools while …
=> refactor(yaml): make env values across chaos jobs consistent 

README.md
Fix indentation of code blocks in README.
<details>
<summary>DCO</summary>
Signed-off by: StrikerRUS < nekit94-08 at mail.ru >
</details>
=> fix indentation of code blocks in README

apps/percona/workload/test.yml
Add a task to check the running status of application before triggering the workload.
=> Add a task to check for running status of percona-application

apps/cassandra/workload/run_litmus_test.yml, apps/cassandra/workload/test.yml, apps/cassandra/workload/test_vars.yml
- Add a task in test.yml to ensure that application is running before running the workloads.
=> Add a task to ensure application running status of cassandra.

apps/cassandra/deployers/test.yml, apps/cockroachdb/deployers/test.yml, apps/crunchy-postgres/deployers/test.yml, apps/jenkins/deployers/test.yml, apps/jupyter/deployers/test.yml, apps/mongodb/deployers/test.yml
- Updates deployer (apart from percona) litmusbooks to use RUN_ID env
=> refactor(yaml): add logic to append run/instance id/metadata to result  CR name for deployers

apps/crunchy-postgres/deployers/test.yml
- Fix an indentation error on the postgres deployer playbook
=> fix(yaml): fix an indentation error in postgres deployer playbook

apps/cassandra/deployers/test.yml, apps/cockroachdb/deployers/test.yml, apps/crunchy-postgres/deployers/test.yml, apps/mongodb/deployers/test.yml
- Litmus job success for deployment of statefulsets with multiple replicas may take time. Increasing retry count before declaring failure.
=> refactor(yaml): increase retries for successful bringup of multi-replica statefulset

apps/crunchy-postgres/deployers/run_litmus_test.yml, apps/mongodb/deployers/run_litmus_test.yml, chaoslib/openebs/jiva_controller_pod_failure.yaml
- use jsonpath to derive the controller pod name (w/ vsm label) 
- use consistent default namespace values and pvc naming convention in deployer jobs 
=> refactor(yaml): use jsonpath to derive the controller pod name (w/ vsm label) 

apps/mongodb/workload/test.yml
Signed-off-by: manjunathd <manjunath.imagin@gmail.com>
- Added litmus block to include RUN_ID/Instance metadata to mongodb workload litmus book
=> Add RUN_ID/Instance metadata to mongodb workload litmus book

apps/cassandra/liveness/run_litmus_test.yml, apps/cassandra/workload/run_litmus_test.yml, apps/cockroachdb/workload/run_litmus_test.yml, apps/crunchy-postgres/liveness/run_litmus_test.yml, apps/crunchy-postgres/workloads/run_litmus_test.yml, apps/jenkins/job-simulator/run_litmus_test.yml, apps/minio/tests/deploy_minio/run_litmus_test.yml, apps/mongodb/liveness/run_litmus_test.yml, apps/mongodb/workload/run_litmus_test.yml, apps/percona/liveness/run_litmus_test.yml, apps/percona/workload/run_litmus_test.yml
Signed-off-by: Roshan <roshanjossey@gmail.com>
Previously, some of them were using only name. This prevents from
running the job again.
With generateName, a hash is attached to the end of name to make it
unique
**Which issue this PR fixes** : fixes #259
=> Use K8s generateName API for litmusbooks

chaoslib/openebs/jiva_controller_pod_failure.yaml
- The presence of spaces around jinja template in a shell (kubectl) command that used -o jsonpath args
was causing the register variable to be unassigned. This PR removes it. 
=> refactor(yaml): remove additional spaces for jinja template used in kubectl cmd w/ jsonpath

Makefile, apps/jupyter/deployers/test.yml, apps/mongodb/workload/test.yml, apps/percona/tests/mysql_storage_benchmark/test.yml, apps/percona/workload/test.yml
This PR would enable ansible playbook syntax checks on Travis
**Which issue this PR fixes**: 
fixes #207
~~Not entirely sure if there is a way to generate a list of playbooks to check~~
=> Check ansible syntax in Travis

apps/jenkins/deployers/jenkins.yml, chaoslib/openebs/jiva_controller_pod_failure.yaml
- Uses `storageClassName` attribute in PVC spec in jenkins 
- Updates the jiva controller failure chaoslib to use latest PV label check
=> refactor(yaml): update jenkins deployment PVC spec to change storagelass def mechanism

apps/cassandra/deployers/run_litmus_test.yml, apps/cassandra/functional/scale_replicas/run_litmus_test.yml, apps/cassandra/functional/scale_replicas/test.yml, apps/cassandra/functional/scale_replicas/test_vars.yml
- It can scale up the application replicas by taking the replica count as input.
- Using application label and namespace to find out the app name.
- Uses scale_replica.yml from funclib.
Modified the default replica count in cassandra deployer to 2. Therefore, cassandra statefulset is deployed with two replicas and scaling up to 3 replicas using this litmusbook.
Here is the sample test run output:
```
skipping: [127.0.0.1] => {"changed": …
```
=> Implemented litmusbook for scaling up application replicas

apps/cassandra/deployers/run_litmus_test.yml
- Reduce characters in namespace to help keep openebs pv/svc names under 63 char
=> refactor(yaml): reduce characters in namespace to help keep openebs k8s resource names under 63 char

apps/crunchy-postgres/workload/crunchy_postgres_loadgen.yml, apps/crunchy-postgres/workload/run_litmus_test.yml, apps/crunchy-postgres/workload/test.yml, apps/crunchy-postgres/workload/test_vars.yml
**This PR does the following**:
- Adds a litmusbook which trigers a crunchy-postgres-loadgen job.
- The litmusbook checks for the following after deploying the loadgen:
1. Weather the loadgen pod is in running state.
2. Weather the loadgen has perfomed a write operation on database or not.
- Accordingly ansible task updates the result in result CR.
**Special note for Reviewers**
- The stateful set for the mongodb deployment is also modified to make the mongo workload work properly
refer:https://github.com/openebs/test-tools/pull/12
**Following is the output acheived after deploying the loadgen:**
```
TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
TASK [Apply the litmus result …
```
=> Add a litmusbook for crunchy-workload

apps/cassandra/functional/scale_replicas/run_litmus_test.yml, apps/cassandra/workload/run_litmus_test.yml, apps/cockroachdb/deployers/run_litmus_test.yml, apps/cockroachdb/workload/run_litmus_test.yml, apps/crunchy-postgres/workload/run_litmus_test.yml
- Using same namespace where application is deployed for cassandra and postgres loadgen jobs.
=> Changed the namespace for cassandra and postgres loadgen jobs

apps/cassandra/deployers/run_litmus_test.yml, apps/cassandra/functional/scale_replicas/test.yml, apps/cassandra/workload/test.yml, apps/cockroachdb/deployers/run_litmus_test.yml, apps/cockroachdb/deployers/test.yml, apps/cockroachdb/workload/test.yml, apps/crunchy-postgres/deployers/run_litmus_test.yml, apps/crunchy-postgres/deployers/test.yml, apps/crunchy-postgres/workload/run_litmus_test.yml, apps/crunchy-postgres/workload/test.yml, apps/crunchy-postgres/workload/test_vars.yml, apps/mongodb/deployers/test.yml, apps/mongodb/workload/run_litmus_test.yml, apps/mongodb/workload/test.yml, apps/mongodb/workload/test_vars.yml, apps/percona/deployers/test.yml, apps/percona/workload/test.yml
- Using 'openebs-standalone' provider for statefulset deployment.
- Checking if the application is deployed successfully before starting load generation.
- Added application label env in mongo workload litmus book.
- Removed hard-coded namespace value in litmusbooks.
- Removed whitespaces and blank lines in litmusbooks.
=> Checking the application's existence before starting load generation

apps/crunchy-postgres/workload/crunchy_postgres_loadgen.yml
- The litmus loadgen job deploys the loadgen in the app's namespace per the playbook. 
=> refactor(yaml): remove use of litmus namespace in crunchy-postgres loadgen YAML

apps/cockroachdb/workload/test.yml, apps/crunchy-postgres/workload/test.yml, apps/percona/workload/test.yml
- Uses `kubectl create` in postgres workload litmusbook the loadgen uses generateName
- Updates run_id check in crunchy-postgres & percona workload/loadgen litmusbooks
=> refactor(yaml): add checks for run_id & use kubectl create cmd in postgres workload 

apps/percona/deployers/test.yml
- Add initcheck tasks for successful db init in percona deployer litmusbook
- Verifies db init status by searching 'ready for connections' log messages in application pod logs.
=> refactor(yaml): Add initcheck tasks for successful db init in percona deployer litmusbook

k8s/aws/k8s-installer/vars.yml
- Change master and nodes instance type from `t2.large` to `t2.xlarge`
=> Change master and nodes type of aws cluster

k8s/gcp/k8s-installer/create-k8s-cluster.yml
- Add option to set the size of underlying CPUs of VMs(master and
nodes), for the Kubernetes cluster in gce
- Set `n1-standard-4 (4 vCPUs, 15 GB memory)` as the default value if
none cpu size provided whatsoever.
- To set size of VMs, pass variable in extra vars:
e.g: `--extra-var "master-size=n1-standard-4 node_size=n1-standard-4"`
=> Add option to set underlying CPU size in GCE

k8s/azure/k8s-installer/README.md, k8s/azure/k8s-installer/create-k8s-cluster.yml
- remove hardcoded node vm size and make it generic
- pass node vm size in extra-vars, i.e,
`--extra-vars "node_vm-size=Standard_D3"`
An extra variable is required while executing the cluster creation playbook.
=> Make azure k8s(AKS) node size generic while creation

chaoslib/kubectl/cordon_drain_node.yaml, chaoslib/kubectl/pod_evict_by_taint.yaml
- This PR enhances the current chaoslib utils for drain and taint nodes.
- Included a block to trigger the drain/uncordon operations based on the action(var) passed.
- Included a block to trigger the taint/untaint operations based on the action(var) passed.
=> refactor(yaml): Include block to drain/taint based chaoslib

apps/cassandra/chaos/openebs_single_replica_failure/run_litmus_test.yml, apps/cassandra/chaos/openebs_single_replica_failure/test.yml, apps/cassandra/chaos/openebs_single_replica_failure/test_vars.yml, chaoslib/openebs/jiva_replica_pod_failure.yaml
-  This litmusbook kills the replica pod in a deployment and checks if the application is alive post rescheduling
-  This book accepts application label and its namespace as env. Derives the PVC name and the replica deployment name using the label and namespace.
- Included a condition in the chaoslib utility task file that checks if all the pods in the deployment are running after scheduling again.
Test-run execution sample result:
```
PLAYBOOK: test.yml *************************************************************
1 plays in ./cassandra/chaos/openebs_single_replica_failure/test.yml
TASK [Gathering Facts] …
```
=> test(yaml)Litmusbook for single replica failure.

k8s/aws/k8s-installer/README.md, k8s/aws/k8s-installer/create-aws-cluster.yml
- Node taint task only execute only when taint_value is passed in
extra_vars
```
TASK [Getting nodes name] ***********************************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": "kubectl get nodes -o jsonpath='{.items[?(@.metadata.labels.kubernetes\\.io/role==\"node\")].metadata.name}' | awk '{print $1}'", "delta": "0:00:00.855251", "end": "2018-10-29 15:15:23.405501", "rc": 0, "start": "2018-10-29 15:15:22.550250", "stderr": "", "stderr_lines": [], "stdout": "ip-10-0-1-119.eu-west-2.compute.internal", "stdout_lines": …
```
=> Add task for taint node with specified value

apps/percona/liveness/db-cred.cnf, apps/percona/liveness/run_litmus_test.yml, apps/percona/liveness/test.yml, apps/percona/liveness/test_vars.yml
The liveness jobs need to be enhanced in order to aid launch/monitor from CI tools such as gitlab & made consistent with other "test" job types in litmus (deploy/workload/functional/chaos) 
- Replace a plain K8s job with a litmus job
- Use env vars to accept database cred info (remove conf files, as this necessitates users to run an additional step to create configmap before they can execute the liveness job) 
- Launch liveness container as a sidecar to ansible runner
- Monitor liveness status via ansible runner & update result CRs
- Use placeholders for nodeselector & add taint-toleration to aid infra-chaos tests, where the liveness pod can be isolated by running them on non-participating nodes. …
=> feat(yaml)(liveness): Add external liveness litmus job for percona application

apps/percona/liveness/run_litmus_test.yml, apps/percona/liveness/test.yml
- Additional checks in the percona-liveness container monitor task
- Include activeDeadlineSeconds to self-kill job after a certain period
=> refactor(yaml)(liveness): enhance failsafe steps in percona liveness job

apps/jenkins/liveness/run_litmus_test.yml, apps/jenkins/liveness/test.yml, apps/jenkins/liveness/test_vars.yml
**Following is the log of the ansible-test container:**
```
TASK [Construct testname appended with runID] **********************************
included: /common/utils/update_litmus_result_resource.yml for 127.0.0.1
TASK [Generate the litmus result CR to reflect SOT (Start of …
```
=> Add a litmusbook for jenkins liveness

apps/percona/deployers/run_litmus_test.yml, apps/percona/functional/scale_jiva_replica/run_litmus_test.yml, apps/percona/functional/scale_jiva_replica/test.yml, apps/percona/functional/scale_jiva_replica/vars.yml, funclib/openebs/access-mode-check.yml
- Add a Litmusbook for jiva-replica-scaleup.
- Add a **access-mode-check.yml** in funclib to checking the replica-access mode.
**Following is the output for the litmus job log:**
```
TASK [Generate the litmus result CR to reflect SOT (Start of Test)] ************
changed: [127.0.0.1] => {"changed": true, "checksum": "1df2d431d14527432a66738db78b77fd3695e86b", "dest": "./litmus-result.yaml", "gid": 0, "group": "root", "md5sum": "64d3375040c2b0cfa197b3dd9adf5745", "mode": "0644", "owner": "root", "size": 421, "src": "/root/.ansible/tmp/ansible-tmp-1540549875.76-121244277305473/ …
```
=> Add a litmusbook for jiva-replica-scaleup

apps/percona/chaos/cstor_pool_failure/test.yml, apps/percona/chaos/openebs_replica_network_delay/test.yml, apps/percona/chaos/openebs_target_failure/run_litmus_test.yml, apps/percona/chaos/openebs_target_failure/test.yml, apps/percona/chaos/openebs_target_network_delay/test.yml, apps/percona/chaos/openebs_volume_replica_failure/test.yml, apps/percona/tests/mysql_data_persistence/test.yml, common/utils/mysql_data_persistence.yml
- Add a util for data persistence.
- Include data-persistence check in the following chaos:
1. cstor-pool failure
2. target-failure
3. target-network delay
4. volume-replica failure
5. replica-network delay
- Use for **mysqlcheck** command is been included for checking the data-persistence. It check for all the corrupted tables in the database. 
**Following is the log for target_network_delay:**
```
task path: /percona/chaos/openebs_target_network_delay/test.yml:2
META: ran handlers
TASK [Checking status of liveness pod] …
```
=> Add a util for Data Persistence

apps/percona/deployers/run_litmus_test.yml, apps/percona/deployers/test.yml, apps/percona/deployers/test_vars.yml
- Adds a litmusbook for percona deprovisioning.
- This litmubook uses the common util for deprovisioning.
- Deprovision of is done based on the **ACTION**(env-variable) in litmusbook.
- When actions is defined(ACTION: 'deprovision') then apllication deprovisioner block is executed.
- When action is not defined(ACTION: ' ') then application deployment block is executed. 
**Following is the log of ansible-test container:**
```
included: …
```
=> Litmusbook for percona deprovisioning

apps/percona/chaos/cstor_pool_failure/run_litmus_test.yml, apps/percona/chaos/cstor_pool_failure/test_vars.yml
- More than one chaoslib/test can be invoked via the pool chaos litmusbook. 
- Use a `CHAOS_TYPE` env to select the type of pool chaos
=> (refactor)(yaml): update the pool chaos litmus book w/ env for chaos type

apps/crunchy-postgres/deployers/test.yml, apps/jenkins/chaos/app_pod_failure/run_litmus_test.yml, apps/jenkins/chaos/app_pod_failure/test.yml, chaoslib/pumba/pod_failure_by_sigkill.yaml, common/utils/check_deployment_status.yml
- Updated application pod kill using pumba util to perform app container kill bot deployment and statefulset applications 
- performed this test against mongo statefulset
@dargasudarshan  @gprasath  can you please review this PR
```
ansible-playbook 2.7.2
/etc/ansible/hosts did not meet host_list requirements, check plugin …
```
=> refactor(yaml): Updated application pod failure litmus book for statefulset applicaions (xfs)

apps/percona/deployers/percona.yml
In Litmus, currently, all stateful applications (i.e., databases) have a corresponding : 
a) "external liveness" check which will verify whether an application is accessible from a client-like end-application
b) "workload/loadgen" jobs which will ensure that application specific data is pumped into the stateful applications. They are being used in litmus/e2e for:
i) Relative BM measurements
ii) Fill apps with some data before running functional/chaos tests
However, (b) is short-lived - doesn't run through duration of test. To have active I/Os during chaos, we need "probes" on the application which can keep performing I/O & will accelerate RO conditions. 
**Which issue this PR fixes** *(optional, in …
=> (refactor)(yaml): update percona deployment template to include liveness probe

apps/custom/tests/memcheck/run_litmus_test.yml, apps/custom/tests/memcheck/test-mem.py, apps/custom/tests/memcheck/test.yml, apps/custom/tests/memcheck/test_vars.yml, providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
- Update Openebs operator tag to CI 
- Set memory consumption for jiva's benchmark value via litmus job ENV
=> refactor(yaml) Update Openebs operator tag to CI and set memory benchmark as job ENV

k8s/eks/k8s-installer/create-eks-cluster.yml, k8s/eks/k8s-installer/vars.yml
- Updates the node size to m4.xlarge to avoid pod evictions.
- Updates the ami image to use Ubuntu1804.
- Remove code that performs ISCSI installation on nodes.
- Add the limit for the max number of pods per node.(Ref:https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/amazon-eks-nodegroup.yaml)
=> perf(yaml):Updates to the vars and cluster creation process.

apps/percona/workload/run_litmus_test.yml, apps/percona/workload/test.yml, apps/percona/workload/test_vars.yml, apps/percona/workload/tpcc.conf
- Make the workload duration configurable
- Update the placeholders in tpcc.conf to ensure they aren't used as is
=> (refactor)(percona workload): make tpcc run duration configurable

apps/percona/chaos/openebs_app_svc_chaos/chaosutil.j2, apps/percona/chaos/openebs_app_svc_chaos/run_litmus_test.yml, apps/percona/chaos/openebs_app_svc_chaos/test.yml, apps/percona/chaos/openebs_app_svc_chaos/test_prerequisites.yml, apps/percona/chaos/openebs_app_svc_chaos/test_vars.yml, chaoslib/service_chaos/svc_chaos.yml, chaoslib/service_chaos/svc_chaos_kube.yml
This PR contains util to restart node level services using a daemonset, and, have an env to set the chaos duration.
Also, this PR have litmus job to restart docker service in the node where application pod resides.
=> testcase(svc_chaos): util for restarting kubelet/docker services, and, job for app pod to use this util

chaoslib/service_chaos/svc_chaos.yml
- The svc chaos util uses app label to select the pod whose node will be injected w/ the svc chaos. Currently it is built for stateful deployments (which will always be single replica)
- This PR introduces a minor workaround to make this chaos util work (in its current state) for statefulsets 
- Will always use ordinality `-0` for pod selection (mostly master pods). It is a quick fix to ensure CD scripts can use this chaos test against statefulset apps. Future enhancements will be made to include better …
=> (fix)(yaml): make svc_chaos util compatible w/ statefulset pods

chaoslib/openebs/cstor_pool_network.yml
This PR is to pick the pool pod for doing network chaos which is on the node where application resides.
=> fix(pool_chaos): selecting the pool pod on node where app resides

apps/percona/chaos/cstor_pool_failure/run_litmus_test.yml, chaoslib/openebs/cstor_verify_pool_provisioning.yml
This PR is to have default application namespace as app-percona-ns.
This also fixes the CVR status change from "Online" to "Healthy"
=> fix(status): pool chaos status lookup change from Online to Healthy

apps/percona/deployers/percona.yml, apps/percona/deployers/run_litmus_test.yml, common/utils/pre_create_app_deploy.yml
- Liveness probes in percona deployment should be a configurable param
- `blockinfile` & `lineinfile` were sub-optimal in this case/or needed undesired additions to job spec. Since the job is a one-time playbook-run - sed's lack of idempotency should not matter.
=> (refactor)(yaml): convert liveness probe as a configurable in percona deploy litmus job 

providers/openebs/installers/operator/master/ansible/openebs_setup.yaml, providers/openebs/installers/operator/master/ansible/vars.yaml
- kubectl set env steps for maya-apiserver in this litmusbook triggers multiple/parallel rolling updates. The subsequent task to get pod name can get a spurious/dying pod.
- Introduce a task before pod name check to ensure rolling update is completed
- Include a task to check successful sparse pool 
- Update delays & retry values for faster completion
=> (fix)(yaml): include check to verify maya-apiserver rolling update is completed before install verification

apps/percona/chaos/drain_node/run_litmus_test.yml, apps/percona/chaos/drain_node/test.yml, apps/percona/chaos/drain_node/test_vars.yml, apps/percona/deployers/run_litmus_test.yml, apps/percona/liveness/run_litmus_test.yml, chaoslib/kubectl/cordon_drain_node.yaml
- Include a litmus book to perform node maintenance
- This test requires a cluster with 4 nodes and one node tainted to run only liveness and litmus pods.
- Pre-chaos and post chaos will verify the application pod status by verifying the liveness pod status
=> [openebs/litmus] (test): Include a litmus book to perform node maintenance (via kubectl drain).

apps/cassandra/deployers/run_litmus_test.yml, apps/cassandra/functional/scale_replicas/run_litmus_test.yml, apps/crunchy-postgres/deployers/test.yml, apps/mongodb/deployers/mongo_statefulset.yml
- Increased the retry count. Within the specified time interval, the application failed to start.
- Reduced the app replica count in mongo and cassandra statefulset deployers.
- Reduced the replica count in cassandra-scale test.
=> Increased the retry count after deploying application

apps/percona/chaos/cstor_pool_failure/run_litmus_test.yml, apps/percona/chaos/drain_node/run_litmus_test.yml
- These placeholders refer to default liveness labels present in the percona liveness litmus job
- They will be replaced by desired values in the gitlab runner scripts 
- Enable data persistence checks on node drain chaos book
=> (refactor)(yaml): adding liveness placeholders and enable data persistence check in infra chaos books 

apps/percona/chaos/taint_node/run_litmus_test.yml, apps/percona/chaos/taint_node/test.yml, apps/percona/chaos/taint_node/test_vars.yml
- Include litmus book to perform node eviction via kubectl taint.
- Pre-chaos and post chaos will verify the application pod status by verifying the liveness pod status
=> [Openebs/litmus] (test): Include litmus book to perform node eviction(via kubectl taint)

chaoslib/openebs/cstor_verify_pool_provisioning.yml
- It fixes the failing task derive-rep-count task in *chaoslib/openebs/verify_pool_provision.yml*.
*Following is the output after the fix:*
```
TASK [Derive PV from application PVC] ********************************************************************************************************************************
task path: /test.yml:6
changed: [localhost] => {"changed": true, "cmd": "kubectl get pvc percona-claim -o custom-columns=:spec.volumeName -n app-percona-ns --no-headers", "delta": "0:00:00.486980", "end": "2018-11-30 13:22:18.995685", "rc": 0, "start": "2018-11-30 13:22:18.508705", "stderr": "", "stderr_lines": [], "stdout": "pvc-18264d99-f3de-11e8-92f5-005056ba22b1", "stdout_lines": ["pvc-18264d99-f3de-11e8-92f5-005056ba22b1"]}
TASK [Derive SC …
```
=> fix for failing replica-count task in cstor-verify-pool-provision.yaml

chaoslib/packet/node_chaos.yml
- Packet, being a baremetal cloud allows for native/self-managed clusters (brought up via kubeadm/kubespray)
- This PR adds a util that can be used to perform ungraceful node failure (power-off) 
- Node chaos tests are sub-categorized into graceful/ungraceful/node-replace/node-resource constraints/kubernetes-induced reschedule etc., 
- Depends on #421
=> (feat)(yaml): add util for packet node chaos

apps/percona/functional/snapshot_rebuild/run_litmus_test.yml, apps/percona/functional/snapshot_rebuild/test.yml, apps/percona/functional/snapshot_rebuild/test_vars.yml, common/utils/inject_packet_loss_tc.yml
- This litmusbook is capable of testing snapshot rebuild functionality.
- Included an util which induces packet drop in the provided replica and remove the packet drop role based on the condition.
Tasks included:
- Bringing down one of the pool pods using tc( above said util).
- Creating snapshot if the consistency factor is lesser than or equal to healthy replicas.
- Checking if the snapshot is not present in the degraded replica.
- Bringing up the pool pod.
- Using 'zfs stats' command, checking if the snapshot is rebuilt successfully.
=> (feat)(yaml)The litmusbook to test snapshot rebuilding.

k8s/packet/k8s-installer/vars.yml
Upgrade default kubernetes version of packet cluster
- From 1.10.0-00 to 1.12.3-00
=> (update)(yml):Upgrade kubernetes version of packet cluster

apps/percona/chaos/openebs_target_failure/test.yml, apps/percona/chaos/openebs_target_failure/test_vars.yml, apps/percona/deployers/percona.yml, apps/percona/deployers/test.yml, apps/percona/deployers/test_vars.yml, common/utils/openebs/target_affinity_check.yml
- Verify target pod is always scheduled on app node
- Include checks in deployer and target pod failure tests
- Add I/O soak time post chaos before checking app status 
(we are seeing some belated failures in chaos tests which are missed by the chaos e2e tests) 
- TODO: Add this util in infra (node) chaos tests
=> (feat)(yaml): add target pod affinity check to deployer & target pod failure chaos

apps/percona/chaos/app_node_failure_ups_diff_name/run_litmus_test.yml, apps/percona/chaos/app_node_failure_ups_diff_name/test.yml, apps/percona/chaos/app_node_failure_ups_diff_name/test_vars.yml, chaoslib/aws_chaos/chaosutil_aws.yml, chaoslib/aws_chaos/ebs_volume_operations.yml, chaoslib/aws_chaos/prerequisites_aws.yml, common/utils/application_liveness_check.yml, common/utils/aws/fetch_aws_details.yml, common/utils/check_no_of_nodes.yml
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
- Include a litmus book to perform application node replacement. (by shutting down the application node)
- This test requires AWS kops cluster and by shutting down the node kops will create another node(with a different name).
- Pre-chaos and post chaos will verify the application pod status by verifying the liveness pod status.
**Test logs:**:
```
ansible-playbook 2.7.4
python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC …
```
=> [openebs/litmus] (test): Include a litmus book to perform application node name replacement (via ansible ec2 shutdown module).

apps/fio/tests/data-integrity/commands.sh, apps/fio/tests/data-integrity/fio-read.yml, apps/fio/tests/data-integrity/fio-write.yml, apps/fio/tests/data-integrity/pvc.yml, apps/fio/tests/data-integrity/run_litmus_test.yml, apps/fio/tests/data-integrity/test.yml, apps/fio/tests/data-integrity/test_vars.yml, common/utils/disable_compression_on_pools.yml
1) This litmusbook is capable of filling the ~97% of volume by setting DATA_CHECK env to data_accessibility.
2) Include a util which will disable the compression at zfs side.
3) Using fio read job verfies written data and also performs RW operations after filling 95% of volume capacity.
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
**Logs:**
```
kubectl logs -f litmus-di-fio-pdgv7-lq4mf -n litmus …
```
=> (Functionality) Fill the volume capacity upto 97% to check the behaviour of application.

apps/percona/chaos/app_node_failure_ups_diff_name/test.yml, apps/percona/chaos/cstor_verify_rebuild/test.yml, apps/percona/chaos/drain_node/test.yml, apps/percona/chaos/node_freeze/test.yml, apps/percona/chaos/node_freeze/test_vars.yml, apps/percona/chaos/openebs_app_svc_chaos/test.yml, apps/percona/chaos/openebs_pool_failure/test.yml, apps/percona/chaos/openebs_pool_network/test.yml, apps/percona/chaos/openebs_replica_network_delay/test.yml, apps/percona/chaos/openebs_target_failure/test.yml, apps/percona/chaos/openebs_target_network_delay/test.yml, apps/percona/chaos/openebs_target_network_loss/test.yml, apps/percona/chaos/openebs_volume_replica_failure/test.yml, apps/percona/chaos/taint_node/test.yml, chaoslib/kubectl/cordon_drain_node.yaml, common/utils/status_app_pod.yml
1) Application under test name fetch tasks at the beginning of test to check container-status.
2) Check rescheduled pod container statuses after the test.
**Special notes for your reviewer**: util file is tested on drain-node and taint_node for now.
@dargasudarshan @ksatchit @nsathyaseelan 
**test-logs**
```[0;34mansible-playbook 2.7.5[0m
[0;34m  config file = None[0m
[0;34m  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules'][0m
[0;34m  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible[0m
[0;34m  executable location = /usr/local/bin/ansible-playbook[0m
[0;34m  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0][0m
[0;34mNo config …
```
=> Modified:containerStatus with restarts over pod status check in utils file

apps/percona/functional/snapshot_rebuild/snap_rebuild_multiple_rep/test.yml, apps/percona/functional/snapshot_rebuild/snap_rebuild_single_rep/test.yml, chaoslib/openebs/cstor_replica_network_delay.yaml, funclib/kubectl/k8s_snapshot_clone/snap_rebuild_prerequesites.yml
There is change in istgtcontrol output format. Below is new one:
```istgtcontrol -q replica | json_pp 
{
"volumeStatus" : [
{
"status" : "Healthy",
"name" : "vol1",
"replicaStatus" : [
{
"inflightWrite" : "0",
"Mode" : "Healthy",
"checkpointedIOSeq" : "1000",
"inflightSync" : "0",
"upTime" : 4422,
"Address" : "127.0.0.1",
"inflightRead" : "0",
"replicaId" : "6161"
},
{
"checkpointedIOSeq" : "1000",
"inflightSync" : "0",
"upTime" : 4418,
"inflightWrite" : "0",
"Mode" : "Healthy",
"replicaId" : "6162",
"inflightRead" : "0",
"Address" : "127.0.0.1"
}
]
}
]
}
```
Replica status is changed from 'status' to 'Mode'.
This PR is in accordance with istgtcontrol output change.
=> fix(istgtcontrol): istgtcontrol output change from 'status' to 'Mode'

apps/percona/chaos/openebs_pool_failure/test.yml
@nsathyaseelan 
logs:
```+ kubectl logs -f openebs-pool-failure-nwh8g-fwwq8 -n litmus -c ansibletest
[0;34mansible-playbook 2.7.6[0m
[0;34m  config file = None[0m
[0;34m  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules'][0m
[0;34m  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible[0m
[0;34m  executable location = /usr/local/bin/ansible-playbook[0m
[0;34m  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0][0m
[0;34mNo config file found; using defaults[0m
[0;34m/etc/ansible/hosts did not meet host_list requirements, check plugin documentation …
```
=> Changed chaostype value in update_litmus_resource_result task

apps/percona/chaos/disk_failure/test.yml, chaoslib/aws_chaos/disk_failure.yml
Signed-off-by: giri <giridhara.prasad@cloudbyte.com>
- When a volume is created on cstor pool , the corresponding spc name should be passed as label to find out the pod.
- Fails to derive pod name if is created on pool other than 'cstor-disk-pool'
#478 
-  Finding out spc name and passing it as label for deriving pool name.
-  Sleeping for 60 seconds as AWS requires some time in between detaching and attaching drives to update. Attaching disk fails upon trying immediately as the disk status remains in detaching for some time.
=> refactor(yaml): Using spc name as cstor pool pod's label in disk failure litmusbook

chaoslib/openebs/jiva_replica_pod_failure.yaml
- Obtaining the second row of the resourceversion object.
- It was impacting the single replica failure where we compare the earlier resourceversion with the one after restart.
=> Obtaining the resource version and checking it after restart

common/utils/openebs/openebs_upgrade.yml, common/utils/openebs/upgrade/run_litmus_test.yml, common/utils/openebs/upgrade/test.yml, common/utils/openebs/upgrade/test_prerequisites.yml, common/utils/openebs/upgrade/test_vars.yml
Signed-off-by: Ubuntu <vibhor.kumar@mayadata.io>
1) This PR consist of automation of cstor volume and jiva volume upgrade with necessary pre and post checks.
2) Available 0.8.1-RC1 release tag is used here for upgrade.
3) Using a svn module to get the upgrade script from git with specified 0.8.0-0.8.1 upgrade script folder.
**Special notes for your reviewer**: This test is performed on percona deployment 
@dargasudarshan @nsathyaseelan @gprasath @vishnuitta @mittachaitu
FOR JIVA UPGRADE LOGS 
```ansible-playbook 2.7.6
executable location = …
```
=> Litmusbook for upgrading cstor and jiva volume from 0.8.0 to 0.8.1

apps/percona/deployers/run_litmus_test.yml, apps/percona/functional/k8s_snapshot/run_litmus_test.yml, apps/percona/functional/k8s_snapshot/test.yml, apps/percona/functional/k8s_snapshot/test_vars.yml
- Creating snapshot and clone based on the pvc provided.
- Checking if the parent volume can be deleted when the clone is present.
- Removed unused variables.
```
2019-03-07T09:12:01.837543 (delta: 0.058754)         elapsed: 0.058754 ********
===============================================================================
task path: /percona/functional/k8s_snapshot/test.yml:19
2019-03-07T09:12:01.852934 (delta: 0.015324)         elapsed: 0.074145 ********
META: ran handlers
TASK [Record test instance/run ID] …
```
=> feat(test): Attempting to delete the parent volume which has clone

apps/percona/chaos/openebs_replica_network_delay/run_litmus_test.yml, apps/percona/chaos/openebs_target_network_delay/run_litmus_test.yml, chaoslib/openebs/jiva_controller_network_delay.yaml, chaoslib/openebs/jiva_replica_network_delay.yaml
- Modified network delay until for controller and replica.
- The included tasks are check the replica getting disconnected after inducing delay in controller in controller network delay util. The same task added in the replica network delay util also.
ctrl.log
```
ansible-playbook 2.7.8
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation …
```
=> refactor[yaml]: Modified network delay utils to check the replica status

experiments/functional/snapshot-creation/run_litmus_test.yml, experiments/functional/snapshot-creation/test.yml, experiments/functional/snapshot-creation/test_vars.yml, tools/ansible-runner/Dockerfile
- Added a directory named experiment in which we can add functional and chaos litmusbooks.
- Implemented litmusbook which is capable of creating snapshot using pvc name as input.
```
PLAYBOOK: test.yml *************************************************************
1 plays in ./experiments/functional/snapshot-creation/test.yml
2019-03-20T10:02:22.227388 (delta: 0.061742)         elapsed: 0.061742 ******** 
task path: …
```
=> feat(litmus):Implementing snapshot creation litmus book.

experiments/functional/snapshot-creation/run_litmus_test.yml, experiments/functional/snapshot-creation/test_vars.yml, funclib/kubectl/k8s_snapshot_clone/create_snapshot.yml
- Rather than generating random name for snapshot, passing it as an environmental variable.
```
PLAYBOOK: test.yml *************************************************************
1 plays in ./experiments/functional/snapshot-creation/test.yml
2019-03-21T08:08:07.475116 (delta: 0.061173)         elapsed: 0.061173 ******** 
task path: /experiments/functional/snapshot-creation/test.yml:14
2019-03-21T08:08:07.490201 (delta: 0.015033)         elapsed: 0.076258 …
```
=> Passing snapshot name as env in snapshot creation litmusbook

experiments/functional/clone-creation/run_litmus_test.yml, experiments/functional/clone-creation/test.yml, experiments/functional/clone-creation/test_vars.yml, experiments/functional/restrict-parent-volume-deletion/run_litmus_test.yml, experiments/functional/restrict-parent-volume-deletion/test.yml, experiments/functional/restrict-parent-volume-deletion/test_vars.yml, funclib/kubectl/k8s_snapshot_clone/create_clone.yml
- Implemented two litmusbooks to create clone and check if the parent volume can be deleted successfully.
- Passing snapshot name, namespace as env in clone creation litmusbook.
- Passing parent volume name, namespace as env in parent volume deletion playbook.
```
2019-03-22T07:15:20.777129 (delta: 0.062306)         elapsed: 0.062306 ******** 
task path: /experiments/functional/clone-creation/test.yml:12
2019-03-22T07:15:20.791387 (delta: 0.014201) …
```
=> Including clone and parent volume deletion litmusbooks

providers/openebs/installers/operator/master/ansible/openebs_setup.yaml, providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
- Refactor openebs-deployment litmusbook to use cstor pool-exporter image
** Following is the logs of litmus-test-container**
```
TASK [Updating openebs cstor volume management image] **************************
task path: /operator/master/ansible/openebs_setup.yaml:129
2019-03-22T09:22:13.253225 (delta: 1.766535)         elapsed: 37.006856 ******* 
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl --kubeconfig /root/admin.conf set env deployment maya-apiserver \"OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE=openebs/cstor-volume-mgmt:0.8.2-RC1\" -n openebs", "delta": "0:00:01.356426", "end": "2019-03-22 09:22:14.986127", "rc": 0, "start": "2019-03-22 09:22:13.629701", "stderr": "", "stderr_lines": [], "stdout": "deployment.extensions/maya-apiserver env …
```
=> Refactor openebs-deployment litmusbook to use cstor pool-exporter image

apps/elasticsearch/deployers/es-statefulset.yaml, apps/elasticsearch/workload/elasticsearch_loadgen.yml, apps/elasticsearch/workload/run_litmus_test.yml, apps/elasticsearch/workload/test.yml, apps/elasticsearch/workload/test_vars.yml, apps/percona/chaos/node_freeze/run_litmus_test.yml
1) This Pr consist of litmus-book for generating load (I/O) on elasticsearch statefulset using elasticsearch-stress-test tool.
2) This PR also consists of small changes of other files .
PR for elasticsearch-stress-tool: https://github.com/openebs/test-tools/pull/81
@dargasudarshan @gprasath @nsathyaseelan 
logs
```+ kubectl logs -f elasticsearch-loadgen-wjbpd-pghgm -n litmus …
```
=> Litmusbook for generating load on elasticsearch statefulset.

experiments/functional/clone-creation/run_litmus_test.yml, experiments/functional/clone-creation/test.yml, experiments/functional/clone-creation/test_vars.yml, funclib/kubectl/k8s_snapshot_clone/snapshot-claim.j2
- Updated clone creation util with a variable for volume capacity.
- Included variable for the same in test_vars.
- Updating the variable while executing clone creation.
- Included this variable in the job file.
- Litmusbook can validate the functionality of admission-server by providing more capacity.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #553 
Here is the stdout snippet:
```
[root@master-1552853078 clone-creation]# kubectl logs -f litmus-clone-qr487-nfwtf -n litmus
ansible-playbook 2.7.6
configured module search path = [u'/root/.ansible/plugins/modules', …
```
=>  refactor(yaml):Obtaining volume capacity as env in clone creation util.

apps/busybox/liveness/run_litmus_test.yml, apps/busybox/liveness/test.yml, apps/busybox/liveness/vars.yml
- Adds a litmusbook for busybox liveness.
- LitmusBook takes **LIVENESS_TIMEOUT**, **POD_NAME**, **LIVENESS_RETRY_COUNT** as environment variable.
- It performs **CRUD** operation on busybox using **dd-command** and for each successful iteration of CRUD-operation it sets liveness status as running. 
- The liveness client for busybox is part of PR in `openebs/test-tools`(link: https://github.com/openebs/test-tools/pull/82)
**Following is the log of the liveness-container**:
```
10240+0 records in
10240+0 records out
41943040 bytes (40.0MB) copied, 0.431196 seconds, 92.8MB/s
liveness-running
Unable to use a TTY - input is not a terminal or the right kind of file
10240+0 records in
10240+0 records out
41943040 bytes …
```
=> Add a litmusbook for busybox-liveness

experiments/functional/clone-snapshot-rebuild/busybox.j2, experiments/functional/clone-snapshot-rebuild/chaosutil.j2, experiments/functional/clone-snapshot-rebuild/run_litmus_test.yml, experiments/functional/clone-snapshot-rebuild/test.yml, experiments/functional/clone-snapshot-rebuild/test_vars.yml, funclib/kubectl/k8s_snapshot_clone/clone_during_rebuild.yml, funclib/kubectl/k8s_snapshot_clone/clone_post_rebuild.yml, funclib/kubectl/k8s_snapshot_clone/clone_pre_rebuild.yml
- Litmusbook for taking clone in various snapshot rebuild scenarios.
```
ansible-playbook 2.7.8
[DEPRECATION WARNING]: Specifying include variables at the top-level …
```
=> feat[litmus]: LitmusBook for clone in snapshot rebuild scenarios

providers/openebs/installers/openebs_helm/run_litmus_test.yml, providers/openebs/installers/openebs_helm/test.yml, providers/openebs/installers/openebs_helm/test_vars.yml
- This litmusbook will deploy openebs using stable helm chart.
- It deploys helm client and tiller in the cluster before attempting to install openebs.
- Checks if the openebs components are running after installation.
Here is the test output snippets:
```
2019-04-03T06:57:31.324988 (delta: 0.064232)         elapsed: 0.064232 ******** …
```
=> feat(yaml):Include litmusbook for helm based openebs deployment.

apps/elasticsearch/deployers/es-statefulset.yaml
* The file is changed that tells don't pull the image if the docker image of the elasticsearch is already present.
=> changed imagePullPolicy from Always to IfNotPresent

providers/openebs/installers/operator/master/ansible/openebs_psp.yaml, providers/openebs/installers/operator/master/ansible/openebs_setup.yaml, providers/openebs/installers/operator/master/ansible/vars.yaml
- Creating pod security policy before installing openebs.
- Associated the PSP created to a ClusterRole.
- Associated the Privileged ClusterRole to OpenEBS Service Account.
- After this task, triggering openebs installation.
```
PLAYBOOK: openebs_setup.yaml ***************************************************
1 plays in ./operator/master/ansible/openebs_setup.yaml
2019-04-11T12:43:08.583981 (delta: 0.070186)         elapsed: 0.070186 ******** 
TASK [Gathering Facts] …
```
=> Creating pod security policy and clusterrole before deploying openebs

apps/elasticsearch/deployers/es-statefulset.yaml, apps/elasticsearch/deployers/run_litmus_test.yml
* In specification of es-statefulset.yml replaced runAsUser:1000 with fsGroup:1000 .
* Sometimes the pod may get restarted again and again and application pod thus goes to CrashLoopBackOff.
* Replacing solves the issue.
* More volume capacity may sometimes lead to some issues in openShift cluster , so reducing the capacity to 8G may not lead to such issues.
=> Replaced runAsUser with fsGroup in spec and reduced the volume capacity from 25G to 8G

apps/prometheus/deployers/prometheus.yml, apps/prometheus/deployers/run_litmus_test.yml, apps/prometheus/deployers/test.yml
Added a prometheus deployment litmus test script.
This script:
- creates service account,cluster role,cluster role binding,configmap,prometheus deployment , 
prometheus service, and persistent volume claim
Below is the litmus job log for reference:
```
2019-04-22T12:07:23.696509 (delta: 0.062586)         elapsed: 0.062586 ******** 
2019-04-22T12:07:23.712275 (delta: 0.015709)         elapsed: 0.078352 ******** 
2019-04-22T12:07:32.293189 (delta: 8.580887) …
```
=> Added prometheus provisioning litmus test script

apps/custom/tests/memcheck/run_litmus_test.yml, apps/custom/tests/memcheck/test.yml
- Included deprovisoning task in memcheck-jiva test. 
**following is the log of ansible-test container**:
```
TASK [set_fact] ****************************************************************
2019-04-24T10:26:55.380094 (delta: 206.308258)         elapsed: 295.409565 **** 
ok: [127.0.0.1] => {"ansible_facts": {"flag": "Pass"}, "changed": false}
TASK [Deprovisioning test related resources] ***********************************
2019-04-24T10:26:55.515045 (delta: 0.134849)         elapsed: 295.544516 ****** 
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl delete -f memleak.yml -n memleak", "delta": "0:00:33.782076", "end": "2019-04-24 10:27:29.633426", "rc": 0, "start": "2019-04-24 10:26:55.851350", "stderr": "", "stderr_lines": [], "stdout": …
```
=> [Refactor] Included deprovision task in memcheck-test

funclib/kubectl/k8s_snapshot_clone/create_clone.yml
- This util can create clone based on snapshot name, namespace and the capacity provided.
- If the capacity of cloned volume is not equal to the actual capacity of PVC, the clone creation fails.
- It succeeds only if the given cloned volume's capacity is equal to PVC's capacity.
=> feat(yaml):Test clone creation with different capacity.

apps/busybox/liveness/busybox_liveness.yml, apps/busybox/liveness/run_litmus_test.yml, apps/busybox/liveness/test.yml, apps/busybox/liveness/vars.yml
- Creates a separate liveness job for busybox in application specific namespace.
**Following is the ansible log**:
```
2019-04-09T09:41:27.076566 (delta: 0.062682)         elapsed: 0.062682 ******** 
2019-04-09T09:41:27.090948 (delta: 0.014325)         elapsed: 0.077064 ******** 
2019-04-09T09:41:36.526562 (delta: 9.435593)         elapsed: 9.512678 ******** 
skipping: [127.0.0.1] => {"changed": false, …
```
=> Created a external liveness for busybox

apps/fio/tests/capacity/fio.yml, apps/fio/tests/capacity/run_litmus_test.yml, apps/fio/tests/capacity/test.yml, apps/fio/tests/capacity/test_capacity.yml, apps/fio/tests/capacity/test_cleanup.yml, apps/fio/tests/capacity/test_vars.yml, apps/fio/tests/capacity/testclaim-pvc.yml
This commit add following test cases:
- Volume creation of 25GB
- Bringing one of the replicas down multiple times randomly
to create autogenerated snapshots and writing data randomly.
- Ensure the replicas getting connected after and volume is
in RW mode.
* As per the current build of jiva >= 0.7.0 this test will be failing due to bug in jiva (for random writes).
Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>
=> feat(litmus): Add capacity test cases

providers/cstor/cstor-disk-pool/cstor-spc.j2
- Commented the annotations where we overriding the default images
- Using default images for cstor pool and volumes
=> refactor(yaml): Using default images for cstor pool and volumes

providers/cstor-storage-policies/local-pv-hostpath.j2, providers/cstor-storage-policies/run_litmus_test.yml, providers/cstor-storage-policies/test.yml, providers/cstor-storage-policies/test_vars.yml
- Keeping storage class template for local pv provisoning
- Updating the host path value in template
- Checking if the storage class is created.
```
included: /utils/fcm/create_testname.yml for 127.0.0.1
TASK [Construct testname appended with runID] …
```
=> feat(yaml):Creating storage class for local pv provisioning

providers/cstor/cstor-disk-pool/run_litmus_test.yml, providers/cstor/cstor-disk-pool/test.yml, providers/cstor/cstor-disk-pool/test_vars.yml
- This litmusbook now takes CSTOR_POOL_COUNT as env-var and consumes its value to validate number of pool pods created.
**Following is the log of ansible-test container:**
```
TASK [Getting list of unused disks attached] ***********************************
changed: [127.0.0.1] => {"changed": true, "cmd": "sort used_disks > a1\n sort all_disks > a2\n diff a2 a1 | grep -e \"<\" -e \">\" | awk '{print $2}'", "delta": "0:00:01.161429", "end": "2019-05-10 09:36:26.719681", "rc": 0, "start": "2019-05-10 09:36:25.558252", "stderr": "", "stderr_lines": [], "stdout": "disk-592f162914abf0c392bea480845d8422\ndisk-6911d32fb9e9d958966e09b373fd679c\ndisk-6d77e19f09d49a1b9395779f150e8de5", "stdout_lines": ["disk-592f162914abf0c392bea480845d8422", …
```
=> Refactor litmusbook for cstor-pool provision to take pool-count as env

experiments/functional/app-target-affinity/functional_util.j2, experiments/functional/app-target-affinity/run_litmus_test.yml, experiments/functional/app-target-affinity/test.yml, experiments/functional/app-target-affinity/test_vars.yml, utils/scm/openebs/sts_target_affinity_check.yml
- Created util for statefulset target affinity check
- Modified the target affinity check litmubook to use the utils based on env
```
ansible-playbook 2.7.8 …
```
=> feat[litmusbook]: Included litmusbook for statefulset target affinity check

providers/cstor-storage-policies/cstor-perf-parameters.j2, providers/cstor-storage-policies/run_litmus_test.yml, providers/cstor-storage-policies/test.yml, providers/cstor-storage-policies/test_vars.yml
- Included storage class spec with performance tunables.
- Create a storage class (cstor-performance-config)  in storage policies playbook.
- Check if such storage class is created.
```
included: /utils/fcm/create_testname.yml for 127.0.0.1
TASK [Construct testname …
```
=> feat(yaml):Including a storage class with performance tunable parameters

apps/busybox/deployers/test.yml
- Modified the busybox deploy litmusbook for deprovision.
```
[WARNING]: Found variable using reserved name: action
included: /utils/fcm/create_testname.yml for 127.0.0.1
TASK [Record test instance/run ID] …
```
=> refactor(yaml): Updated the task for busybox deployer litmusbook

experiments/chaos/app_pod_failure/test.yml, providers/cstor/cstor-disk-pool/run_litmus_test.yml
- When Application deployment is there with multiple replica then this test should pick random pods name to perform chaos.
**Following is the log of ansible test container:**
```
TASK [Obtain the ready replica count and compare with the replica count.] ******
task path: /utils/k8s/check_deployment_status.yml:29
TASK [Get application pod name] ************************************************
task path: /experiments/chaos/app_pod_failure/test.yml:68
changed: [127.0.0.1] => {"changed": true, "cmd": "kubectl get pods -n default -l app=gitaly  --no-headers -o=custom-columns=NAME:\".metadata.name\" | shuf -n 1", "delta": "0:00:01.403197", "end": "2019-05-15 11:56:27.338847", "rc": 0, "start": "2019-05-15 …
```
=> Refactor(App_kill) litmusbook to pick random pod name

apps/busybox/liveness/busybox_liveness.yml, apps/busybox/liveness/run_litmus_test.yml, apps/busybox/liveness/test.yml, apps/busybox/liveness/vars.yml
**Following is the log of ansible-test containter:**
```
TASK [Construct testname appended with runID] **********************************
included: /utils/fcm/update_litmus_result_resource.yml for 127.0.0.1
TASK [Generate the litmus result CR to reflect SOT (Start of Test)] …
```
=> Includes deprovision in busybox-loadgen limusbook

apps/prometheus/liveness/prometheus_liveness.yml, apps/prometheus/liveness/run_litmus_test.yml, apps/prometheus/liveness/test.yml, apps/prometheus/liveness/vars.yml
Added following prometheus-liveness litmus job scripts
- apps/prometheus/liveness/prometheus_liveness.yml
- apps/prometheus/liveness/run_litmus_test.yml
- apps/prometheus/liveness/test.yml
- apps/prometheus/liveness/vars.yml
Here are litmus job logs for your reference:
```
TASK [Construct testname appended with runID] ********************************** …
```
=> Adds prometheus-liveness litmus job script

chaoslib/chaoskube/pod_failure_by_chaoskube.yaml, chaoslib/pumba/pod_failure_by_sigkill.yaml, executor/README.md, executor/chaos_executor.yml, executor/executor.yml, executor/test.yml, experiments/chaos/kubernetes/container_kill/run_litmus_test.yml, experiments/chaos/kubernetes/container_kill/test.yml, experiments/chaos/kubernetes/pod_delete/run_litmus_test.yml, experiments/chaos/kubernetes/pod_delete/test.yml, hack/chaos-result.j2, hack/crds.yaml, hack/litmus-prerequisites.sh, hack/rbac.yaml, tools/ansible-runner/Dockerfile, utils/fcm/update_chaos_result_resource.yml
Litmus is being enhanced to function as a generic chaos framework that developers can use both in their CI pipelines as well as in their deploy environments (staging/pre-prod/prod).  A [Chaos Operator](https://github.com/litmuschaos/chaos-operator) project has been created to that effect, with the aim of enhancing the current framework to include: 
- Scheduled batch Run of Chaos (ref: [chaosengine](https://github.com/litmuschaos/chaos-operator/blob/master/deploy/crds/chaosengine.yaml))
- Intuitive monitoring (ref: [chaos-exporter](https://github.com/litmuschaos/chaos-exporter/pull/1)) 
- Standardised chaos experiment spec (ref: [chaos-charts](https://github.com/litmuschaos/chaos-charts))
- Categorized …
=> (feat)(chaos executor): add an executor to run chaos experiments

experiments/functional/jiva-pods-openebs-ns/run_litmus_test.yml, experiments/functional/jiva-pods-openebs-ns/test.yml, experiments/functional/jiva-pods-openebs-ns/test_vars.yml, providers/cstor-storage-policies/jiva-openebs-ns.yml, providers/cstor-storage-policies/test.yml, providers/cstor-storage-policies/test_vars.yml
- Included litmusbook to check the jiva pods scheduled on openebs namespace
- created storage class to deploy jiva in openebs namespace 
```
ansible-playbook 2.7.8 …
```
=> feat[litmusbook]: Included litmusbook to check the jiva pods scheduled on openebs namespace

chaoslib/pumba/pod_failure_by_sigkill.yaml
- Refactor litmusbook of cstor-pool-delete to include conditional check for getting the pod name.
**Following is log of ansible-test container:**
```
ansible-playbook 2.7.9
[DEPRECATION WARNING]: Specifying include …
```
=> Refactor litmusbook of cstor-pool-delete to include conditional check.

providers/openebs/installers/openebs_helm/test.yml
- Refactor litmusbook for OpenEBS installation using HELM
**Following is the log of ansible-test container:**
```
included: /utils/fcm/create_testname.yml for 127.0.0.1
TASK [Construct testname appended with runID] **********************************
TASK [include_tasks] …
```
=> Refactor litmusbook for OpenEBS installation using HELM

apps/cassandra/deployers/cassandra_statefulset.yml, apps/cassandra/deployers/run_litmus_test.yml, apps/cassandra/deployers/test.yml, apps/cassandra/deployers/test_vars.yml
* Volume capacity is taken as environmental variable.
* Target affinity is added in order to schedule both target pod and application pod in same node
* These files are modified
* apps/cassandra/deployers/cassandra_statefulset.yml  
* apps/cassandra/deployers/run_litmus_test.yml
* apps/cassandra/deployers/test.yml
* apps/cassandra/deployers/test_vars.yml
Here are the logs
```
[root@master-1554817485 deployers]# kubectl logs litmus-cassandra-z5jj2-smqqb -n litmus -f
[WARNING]: Found variable using reserved name: action …
```
=> Refactored litmus books for deployment of cassandra to take capacity as env and added target affinity in playbooks

apps/crunchy-postgres/deployers/postgres_statefulset.yml, apps/crunchy-postgres/deployers/run_litmus_test.yml, apps/crunchy-postgres/deployers/test.yml, apps/crunchy-postgres/deployers/test_vars.yml
* Volume capacity is taken as environmental variable.
* Target affinity is added in order to schedule both target pod and application pod in same node
* These files are modified
modified:   apps/crunchy-postgres/deployers/postgres_statefulset.yml
modified:   apps/crunchy-postgres/deployers/run_litmus_test.yml
modified:   apps/crunchy-postgres/deployers/test.yml
modified:   apps/crunchy-postgres/deployers/test_vars.yml
Here are the logs :
```
[root@master-1554817485 deployers]# kubectl logs litmus-pgset-l7qzq-42jpf -n litmus
[WARNING]: Found variable …
```
=> Refactored litmus books for deployment of Postgres to take capacity as env and added target affinity in playbooks

experiments/functional/volume-capacity/run_litmus_test.yml, experiments/functional/volume-capacity/test.yml, experiments/functional/volume-capacity/test_vars.yml
- LitmusBook to fill the volume capacity
```
2019-06-04T14:33:32.014478 (delta: 0.06487)         elapsed: 0.06487 ********** 
2019-06-04T14:33:32.032854 (delta: 0.018314)         elapsed: 0.083246 ******** 
TASK [include_tasks] …
```
=> feat[yaml]: Implemeted a LitmusBook to fill the volume capacity

providers/cstor/cstor-block-device-pool/block_device_claim.yml, providers/cstor/cstor-block-device-pool/run_litmus_test.yml, providers/cstor/cstor-block-device-pool/spc.yml, providers/cstor/cstor-block-device-pool/test.yml, providers/cstor/cstor-block-device-pool/test_vars.yml
Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>
- Includes litmusbook `run_litmus_test.yml` which takes *POOL_NAME*(name of pool to be provisioned), *OPERATOR_NS*(namespace in which openebs gets deployed) and *DEVICE_CAPACITY*(storage capacity of disk attached to each node) as env-var.
- This litmusbook filters unclaimed disks present in the cluster and creates corresponding BDC(Block-device claim), then creates the storage pool using the unused(i.e: which have not participated in cstor-pool provision) **block-devices**.
- Currently this litmusbook is designed to work for striped pool-type only.
**Following is the log of ansible test container:**
``` …
```
=> Add litmus for cstor-pool provision using BD(block device)

apps/elasticsearch/deployers/es-statefulset.yaml, apps/elasticsearch/deployers/run_litmus_test.yml, apps/elasticsearch/deployers/test.yml, apps/elasticsearch/deployers/test_vars.yml
* Volume capacity is taken as environmental variable.
* Target affinity is added in order to schedule both target pod and application pod in same node
Here are the logs:
```
[root@master-1554817485 apps]# kubectl logs litmus-elasticsearch-lsjks-ndkrt -n litmus
[WARNING]: Found variable using reserved name: action
2019-06-04T14:01:23.930038 (delta: 0.133463)         elapsed: 0.133463 ******** 
=============================================================================== …
```
=> Refactored litmus books for deployment of Elasticsearch to schedule application pod and target pod in same node

experiments/chaos/node_storage_fill/busybox_deployment.yml, experiments/chaos/node_storage_fill/run_litmus_test.yml, experiments/chaos/node_storage_fill/test.yml, experiments/chaos/node_storage_fill/test_vars.yml
- Deploying an application which consumes the node space completely.
- Obtaining SPC as env. Through SPC label, finding out a csp. Based on csp label, getting the corresponding pool pod. Scheduled the above application on the node where pool pod is running.
- Filling the node space using fallocate.
- Once the application pod is evicted, checking the corresponding pool pod's status. If it is unknown/evicted , failing the test.
```
PLAYBOOK: test.yml *************************************************************
1 plays in ./experiments/chaos/node_storage_fill/test.yml
2019-06-06T04:36:25.019689 (delta: 0.040919) …
```
=> test(yaml):Implement litmusbook to check pool pod behavior when the node is running out of space

experiments/chaos/node_storage_fill/run_litmus_test.yml, experiments/chaos/node_storage_fill/test.yml
- Included infra-chaos specific toleration content in litmusbook.
- Included namespace creation task.
- Deprovisioning the rogue application
=> refactor(yaml):Include infra-chaos specific toleration in node-fill litmusbook

chaoslib/openebs/cstor_verify_pool_provisioning.yml
- Fix-(cstor-verify-pool-provisioning) to get number of replica count
**Following is the output**
```
kubectl get sc openebs-cstor-disk -n openebs --no-headers -o jsonpath='{.metadata.annotations}' | grep  -A 2 "name: ReplicaCount" | head -2 | grep -v ReplicaCount | awk '{print $2}' | cut -d '"' -f2
3
```
```
kubectl get sc openebs-cstor-sparse -n openebs --no-headers -o jsonpath='{.metadata.annotations}' | grep  -A 2 "name: ReplicaCount" | head -2 | grep -v ReplicaCount | awk '{print $2}' | cut -d '"' -f2
3
```
=> Fix-(cstor-verify-pool-provisioning) to get number of replica count

k8s/packet/packet-storage/README.md, k8s/packet/packet-storage/create-volume.yml, k8s/packet/packet-storage/vars.yml
- Include disk format and mount task in packet cluster setup script.
- Define a variable called `mount_path`(the path where disk will be mounted) in vars.yml, by default it is `/var/openebs`.
- Include a task in `create-volume.yml` to format the disk in **ext4**.
**Following is the log:**
```
PLAY [localhost] **************************************************************************************************************************************************
TASK [Gathering Facts] ********************************************************************************************************************************************
ok: [localhost]
TASK [Create a volume in packet cloud] *************************************************************************************************************************** …
```
=> Include disk format and mount task in packet cluster setup script

apps/jenkins/deployers/run_litmus_test.yml, providers/openebs/installers/operator/master/ansible/openebs_setup.yaml, providers/openebs/installers/operator/master/ansible/vars.yaml, providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
* Sparse file count is taken as env.
* Following files are modified :
* ansible/openebs_setup.yaml
* ansible/vars.yaml
* litmusbook/openebs_setup.yaml
The playbooks are tested in openshift cluster. After deleting all the contents of openebs namespace, openebs namespace is also deleted. Later,  openebs_setup.yaml is applied. It pulls the docker image and creates openebs namespace with all its resources.  Here are the logs 
```
[root@master-1554817485 litmusbook]# kubectl logs litmus-openebs-setup-cgf47 -n litmus -f
executable location = …
```
=> Refactored the litmus books to take sparse file count as env

experiments/functional/deprovision-multiple-volumes/pvc.yml, experiments/functional/deprovision-multiple-volumes/pvc_provision.yaml, experiments/functional/deprovision-multiple-volumes/run_litmus_test.yml, experiments/functional/deprovision-multiple-volumes/test.yml, experiments/functional/deprovision-multiple-volumes/test_vars.yml
- Included a litmusbook to check whether the stale pv details not present in cstor pool pods
- Deployed Multiple PVs in the same namespace
- Delete the pool pod and all the pvcs together
- Wait until pool pods are up and running
- Exed into the cstor-pool pod container and check if the pv is not present in the pool pods.
```
[root@master-1554817485 sathya]# kubectl logs -f litmus-pvc-deprovision-7dfgs-d4f7z -n litmus …
```
=> feat[litmusbook]: Created a litmusbook to check the status deleted pv stale lists in pool pods

providers/openebs/installers/operator/master/ansible/openebs_setup.yaml, providers/openebs/installers/operator/master/ansible/vars.yaml, providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
* Modified ansible playbooks to take analytics value as env.
* Following files modified:
modified:   ansible/openebs_setup.yaml
modified:   ansible/vars.yaml
modified:   litmusbook/openebs_setup.yaml
Here are the logs when  ANALYTICS_VALUE is not null
```
[root@master-1554817485 litmusbook]# kubectl logs litmus-openebs-setup-24dtf -n litmus -f
/etc/ansible/hosts did not meet host_list requirements, check …
```
=> Refactored ansible playbooks to take analytics val as env

experiments/functional/sts-volume-distribution/test.yml
* Added timeout in sts-volume-distribution.
* Wait for 60 seconds
* Following file is modified:
experiments/functional/sts-volume-distribution/test.yml
Here are the logs of litmus pod:
```
[root@master-1554817485 sts-volume-distribution]# kubectl logs litmus-sts-replica-distribution-g8m4n-996tc -n litmus -f
[WARNING]: Found variable using reserved name: action
2019-06-19T11:53:43.340408 (delta: 0.066902)         elapsed: 0.066902 ******** …
```
=> refactor[yaml]: Added timeout task in statefulset volume distribution litmusbook

experiments/chaos/node_storage_fill/test.yml
* If availabe size if 50 GB and if we try to fill the disk with more than 50GB, we get and error message 
' fallocate: fallocate '/test.img': No space left on device'
* If we fill with 50GB , along with error message, we can observe that the pod is evicted from that node and    gets scheduled on some other node.
* The following file is modified :
/litmus/experiments/chaos/node_storage_fill/test.yml
=> Changed the amount of data to be filled in disks in order to evict the application pod

experiments/chaos/app_node_failure_diff_aws/run_litmus_test.yml, providers/cstor/cstor-block-device-pool/run_litmus_test.yml, providers/cstor/cstor-block-device-pool/spc.yml, providers/cstor/cstor-block-device-pool/test.yml, providers/cstor/cstor-block-device-pool/test_vars.yml
* Pool type is taken as environmental variable. It can take the value striped, mirrored, raidz, raidz2.
* The pool type value is replaced in spc.yml and when this yaml is applied, a spc is created which uses  
unclaimed bds to create csps.
* The following files are modified :
providers/cstor/cstor-block-device-pool/run_litmus_test.yml
providers/cstor/cstor-block-device-pool/spc.yml
providers/cstor/cstor-block-device-pool/test.yml
providers/cstor/cstor-block-device-pool/test_vars.yml
Here are the logs for reference :
1. Striped pool
```
[root@gitlab-master cstor-block-device-pool]# kubectl logs cstor-block-device-pool-provision-vbk8g-2rkwz -n litmus -f
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is …
```
=> Refactored litmus books to take pool type as environmental variable

providers/cstor/cstor-block-device-pool/run_litmus_test.yml, providers/cstor/cstor-block-device-pool/spc.yml, providers/cstor/cstor-block-device-pool/test.yml, providers/cstor/cstor-block-device-pool/test_vars.yml
* Storage class name is taken as environmental variable.
* The storage class with name specified in run_litmus_test ( specified value in STORAGE_CLASS) will be created along with csps when run_litmus_test.yml is applied.
* The following files are modified.
modified:   providers/cstor/cstor-block-device-pool/run_litmus_test.yml
modified:   providers/cstor/cstor-block-device-pool/spc.yml
modified:   providers/cstor/cstor-block-device-pool/test.yml
modified:   providers/cstor/cstor-block-device-pool/test_vars.yml
The litmus books are tested for by creating striped pool and corresponding storage class by applying run_litmus_test.yml. Here is the log:
```
[root@master-1558702621 cstor-block-device-pool]# kubectl logs cstor-block-device-pool-provision-2xt7f-dcjvk -n litmus -f
No config file …
```
=> Refactored litmus books to take storage class name as env

apps/percona/workload/run_litmus_test.yml, apps/percona/workload/test.yml, apps/percona/workload/test_vars.yml, apps/percona/workload/tpcc.conf
- Included tasks to replace the parameters in tpcc.conf file
```
2019-07-09T15:22:19.228843 (delta: 0.074773)         elapsed: 0.074773 ******** 
2019-07-09T15:22:19.248779 (delta: 0.019883)         elapsed: 0.094709 ******** 
TASK …
```
=> Modified the percona workload litmusbook to replace the default values in config file

experiments/functional/schedule-target-pod/busybox_deployment.yml, experiments/functional/schedule-target-pod/run_litmus_test.yml, experiments/functional/schedule-target-pod/storage_class.j2, experiments/functional/schedule-target-pod/storage_class.yml, experiments/functional/schedule-target-pod/test.yml, experiments/functional/schedule-target-pod/test_vars.yml
* The target pod is scheduled on the node specified in run_litmus_test.yml
* In storage class , we use TargetNodeSelector to schedule target pod in particular node which has the label.
* Below steps are followed to do the scheduling of target pod on node.
1. Node where target pod has to be scheduled is given a label.
2. Jinja template is converted into storage class yaml file.
3. Storage class yaml file which contains TargetNodeSelector is applied and hence a storage class is 
created.
4. Deployment of busybox is done.
5. Whether target pod is scheduled in the specified node or not is verified.
6. The label given to node is erased.
7. Storage class is deleted.
Here are the logs :
1. When target pod is scheduled …
=> feat[yaml]: Litmus book for scheduling target pod on specified node

experiments/functional/schedule-target-pod/run_litmus_test.yml
* In run_litmus_test.yml by mistake it was written as task.yml. It is corrected to test.yml
=> fix[yaml]: Correct the typo in file 

k8s/packet/k8s-installer/vars.yml
- Modified the default cluster region for Packet cluster creation has to support t1.small.x86 VM's
=> refactor[LitmusBook]: Changed the default cluster region for Packet cluster

experiments/chaos/openebs_target_failure/run_litmus_test.yml, experiments/chaos/openebs_target_failure/test.yml, experiments/chaos/openebs_target_failure/test_vars.yml
- Included util of statefulset target affinity in openebs target failure litmusbook 
- This change is needed for this PR has to perform both deployment and statefulset applications based on the ENV parameters given in the run_litmus_test.yml
litmusbook log in caseof deployment
```
[root@master-1558702621 openebs_target_failure]# kubectl logs -f openebs-target-failure-89dnb-lnpp4 -n litmus …
```
=> refactor[yaml]: Modified openebs target failure litmusbook for statefulset and deployment

providers/csi-provisioner/README.md, providers/csi-provisioner/csi-cstor-sc.j2, providers/csi-provisioner/run_litmus_test.yml, providers/csi-provisioner/test.yml, providers/csi-provisioner/test_vars.yml
- Deploy csi driver based on host operating system in kubernetes cluster.
- Verify the existence of csi controller and csi-node components.
- Populate the storageclass template with the variables.
- Create storage class.
- check if the desired pods and storageclass are created.
Resources created are as follows;
```
openebs-csi-controller-0                      4/4       Running   0          3m51s
openebs-csi-node-kpx4l                        2/2       Running   0          3m51s
openebs-csi-node-nflqq                        2/2       Running   0          3m51s
openebs-csi-node-srx24                        2/2       Running   0          3m51s
```
Test-result:
``` …
```
=> test(litmus): implement csi driver deployment litmus experiment

k8s/packet/k8s-installer/README.md, k8s/packet/k8s-installer/create_packet_cluster.yml
- Create packet cluster for kubernetes version 1.14 and above.
- Update `README.md` for packet cluster deletion command
**Following is the log of ansible test container**
```
PLAY [localhost] *****************************************************************************************************************************************************
TASK [Gathering Facts] ***********************************************************************************************************************************************
task path: /home/shashank/Desktop/workspace/litmus/k8s/packet/k8s-installer/create_packet_cluster.yml:19
ok: [localhost]
META: ran handlers
TASK [Generate ssh key for packet] **************************************************************************** …
```
=> fix(packet cluster setup): Refactor script to setup cluster for version k8s-1.14 & above

apps/percona/functional/k8s_snapshot/test.yml, chaoslib/openebs/jiva_controller_network_delay.yaml, chaoslib/openebs/jiva_replica_network_delay.yaml, experiments/functional/fio/data-integrity/fio-read.yml, experiments/functional/fio/data-integrity/run_litmus_test.yml, experiments/functional/fio/data-integrity/test.yml, experiments/functional/fio/data-integrity/test_vars.yml
- This PR is modifying the below LitmusBook/Utils
- k8s-snapshot clone litmusbook
- FIO data integrity check LitmusBook
- Jiva Controller network delay Util
- Jiva replica network delay Util
- The Changes in LitmusBook is needed because they are already covered as part of different LitmuBook for ex: Delete parent volume has separate LitmusBook and the Volume capacity fill using FIO also covered by different LitmusBook.
- The Changes in the Utils is needed as part of accommodating for Statefulset and deployment. 
data integrity LitmusBook log:-
```
'No config file found; using defaults
/etc/ansible/hosts did not meet script …
```
=> refactor[litmusbook]: Modified and removed the tasks in litmusbook

k8s/packet/k8s-installer/create_packet_cluster.yml
- Increased timeout for waiting for ssh into each instance
=> Increased timeout for ssh into instances task in packet cluster creation playbook

providers/cstor/cstor-block-device-pool/run_litmus_test.yml, providers/cstor/cstor-block-device-pool/spc.yml, providers/cstor/cstor-block-device-pool/test.yml, providers/cstor/cstor-block-device-pool/test_vars.yml, providers/cstor/cstor-cspc-pool/run_litmus_test.yml, providers/cstor/cstor-cspc-pool/test.yml, providers/openebs/installers/operator/master/ansible/openebs_setup.yaml, providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml
- Modified the pool pod and SPC creation LitmusBook using blockDevices 
- Included a task to delete the SPC and verify the status
- Modified the SPC spec by including the maxPool count as a variable
LitmusBook log for pool creation
```
2019-08-26T18:54:13.946518 (delta: 0.041925)         elapsed: 0.041925 ******** 
TASK [Gathering …
```
=> refactor[yaml]: Modified a Pool creation LitmusBook to check the pool status

utils/scm/applications/mysql/mysql_data_persistence.yml
- Included a task to delete the application pod to verify the data persistence.
- Verified this with target network delay chaos experiment.
``` …
```
=> refactor[util]: Included a task to restart the application pod in mysql data persistence util

providers/cstor/cstor-cspc-pool/test.yml
- changed the label selector to get the cspc pool pod status task in litmusbook. As per new label schema changes.
=> refactor[yaml]: Changed the label selector for cspc provision litmusbook

ci/gitlab/templates/pod-delete/chaosengine.yaml, ci/gitlab/templates/pod-delete/pod-failure-template.yml
- This enables app developers to use extend ready chaos templates for their environments
=> (feat)remote-templates: add gitlab template for pod-delete chaos

tools/ansible-runner/Dockerfile
- Included path for parameters file in docker image
**Checklist**
=> Included a path for the application parameters in docker file

experiments/chaos/openebs_target_failure/data_persistence.j2, experiments/chaos/openebs_target_failure/run_litmus_test.yml, experiments/chaos/openebs_target_failure/test.yml, experiments/chaos/openebs_target_failure/test_prerequisites.yml, experiments/chaos/openebs_target_failure/test_vars.yml, experiments/chaos/openebs_target_network_delay/test.yml, utils/scm/applications/busybox/busybox_data_persistence.yml
- Included a jinja template to get the data consistency util for based on the application
- Modified busybox-data-persistence util
- In case of busybox application, the configmap values will be
```
parameters.yml: |
blocksize: 4k
blockcount: 1024
testfile: difiletest
```
**Checklist**
```
/etc/ansible/hosts did …
```
=> refactor[litmusbook]: include data consistency checks in target-failure scenario

providers/cstor/cstor-cspc-pool/test.yml
- This PR will have the task to get the device count to check the cspc container status
**Checklist**
```
2019-09-04T10:52:42.395840 (delta: 0.064127)         elapsed: 0.064127 ******** 
2019-09-04T10:52:42.414540 …
```
=> fix[cspc-litmusbook]: Included a task to get the device count

experiments/functional/snapshot_deletion/jiva/snapshot_delete_verify_test.yml
Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>
**Following is the log of ansible-test container:**
```
2019-09-11T06:36:56.750375 (delta: 0.060316)         elapsed: 0.060316 ******** 
2019-09-11T06:36:56.765387 (delta: 0.014957)         elapsed: 0.075328 ******** 
2019-09-11T06:37:06.865854 (delta: 10.100434)         elapsed: 10.175795 ****** 
TASK …
```
=> Refactor litmusbook for jiva-snapshot-delete

experiments/chaos/openebs_volume_replica_failure/README.md, experiments/chaos/openebs_volume_replica_failure/data_persistence.j2, experiments/chaos/openebs_volume_replica_failure/run_litmus_test.yml, experiments/chaos/openebs_volume_replica_failure/test.yml, experiments/chaos/openebs_volume_replica_failure/test_prerequisites.yml, experiments/chaos/openebs_volume_replica_failure/test_vars.yml
Signed-off-by: Saksham Katiyar <saksham.katiyar@mayadata.io>
- Included changes to get the data consistency util for based on the application.
**Checklist**
**MYSQL LOGS**:
```
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this …
```
=> refactor[litmusbook]: Updated the volume replica failure litmusbook to check the data consistency

chaoslib/openebs/jiva_controller_pod_failure.yaml
- Changed the until condition to get the status of replica in controller kill util
**Checklist**
```
[root@master-1558702621 openebs_target_failure]# kubectl logs -f openebs-target-failure-mlh6t-9jdk5 -n litmus
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is …
```
=> refactor[ctrl-kill]: Modified the controller pod kill util to get the replica status

providers/openebs/installers/operator/master/litmusbook/test.yaml
Signed-off-by: somesh kumar <somesh.kumar@mayadata.io>
updated the task to check pool pod status in openebs deployer litmusbook
**Checklist**
``` …
```
=> refactor(yaml): updated task to check pool pod status

experiments/chaos/openebs_target_network_loss/README.md, experiments/chaos/openebs_target_network_loss/data_persistence.j2, experiments/chaos/openebs_target_network_loss/run_litmus_test.yml, experiments/chaos/openebs_target_network_loss/test.yml, experiments/chaos/openebs_target_network_loss/test_prerequisites.yml, experiments/chaos/openebs_target_network_loss/test_vars.yml
1. Updated the target_network_loss litmusbook to check the data consistency.
python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
statically imported: /experiments/chaos/openebs_target_network_loss/test_prerequisites.yml …
=> refactor[litmusbook]: Updated target_network_loss litmusbook to check the data consistency

experiments/chaos/openebs_target_network_delay/README.md, experiments/chaos/openebs_target_network_delay/data_persistence.j2, experiments/chaos/openebs_target_network_delay/run_litmus_test.yml, experiments/chaos/openebs_target_network_delay/test.yml, experiments/chaos/openebs_target_network_delay/test_prerequisites.yml, experiments/chaos/openebs_target_network_delay/test_vars.yml
Signed-off-by: somesh kumar <somesh.kumar@mayadata.io>
1. Updated the target_network_delay litmusbook to check the data consistency.
Logs for data consistency check against percona --->
```
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is …
```
=> refactor(yaml): Updated target_network_delay litmusbook to check the data consistency

providers/cstor-storage-policies/jiva-xfs-sc.j2, providers/cstor-storage-policies/test.yml, providers/cstor-storage-policies/test_vars.yml
Signed-off-by: somesh kumar <somesh.kumar@mayadata.io>
**What this PR does**:
1. added openebs-jiva-xfs storage class with xfs file system
**Checklist**
=> refactor[yaml]: Added openebs-jiva-xfs storage class with xfs file system

experiments/chaos/openebs_pool_failure/README.md, experiments/chaos/openebs_pool_failure/data_persistence.j2, experiments/chaos/openebs_pool_failure/run_litmus_test.yml, experiments/chaos/openebs_pool_failure/test.yml, experiments/chaos/openebs_pool_failure/test_vars.yml, experiments/chaos/openebs_pool_network/README.md, experiments/chaos/openebs_pool_network/data_persistence.j2, experiments/chaos/openebs_pool_network/run_litmus_test.yml, experiments/chaos/openebs_pool_network/test.yml, experiments/chaos/openebs_pool_network/test_vars.yml, experiments/chaos/openebs_target_network_loss/test.yml
##
1. Added data consistency check in openebs_pool_failure litmusbook.
2. Added data consistency check in openebs_pool_network litmusbook.
3. Resolved typo in target_network_loss litmusbook.
-  new_pod_name variable changed to app_pod_name.
##
1. [openebs pool failure logs against busybox.txt](https://github.com/litmuschaos/litmus/files/3629653/openebs.pool.failure.logs.against.busybox.txt)
2. [openebs_pool_failure logs against percona.txt](https://github.com/litmuschaos/litmus/files/3629656/openebs_pool_failure.logs.against.percona.txt)
3. [openebs_pool_network logs against busybox.txt](https://github.com/litmuschaos/litmus/files/3629657/openebs_pool_network.logs.against.busybox.txt)
4. [openebs_pool_network logs against …
=> refactor[yaml]: Updated pool_failure and pool_network litmusbook to check data consistency

executor/executor.yml
-  combine appinfo (chaosengine.spec) to the dictionary of Env variables of job. 
**Checklist**
=> Refactor[executor]: combine appinfo to envDictionary

build/ansible-runner/Dockerfile, chaoslib/litmus/kill_random_pod.yml, chaoslib/litmus/pod_failure_by_litmus.yml
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>
Many of of the ansible modules are using shell commands using kubectl to access kubernetes resources. This PR would be contributing towards #808 and #703 in converting them to k8s and k8s_facts module provided by ansible
**Checklist**
Could not change the kill_pod task to k8s module, as the module doesn't support --grace-period parameter. Also I have moved the pod kill logic to separate file as ansible doesn't support looping over blocks.
Tested locally in minikube by invoking the following playbook with various parameters
```yaml
- hosts: localhost
connection: local
gather_facts: no
vars:
c_experiment: "pod-delete"
c_duration: "15"
c_interval: "5"
c_force: …
```
=> [Refactor] pod_failure_by_litmus to use ansible k8s module

chaoslib/pumba/network_chaos/induce_latency.yml, chaoslib/pumba/network_chaos/induce_packet_loss.yml, chaoslib/pumba/network_chaos/network_chaos.yml, experiments/generic/pod_network_latency/README.md, experiments/generic/pod_network_latency/chaosutil.j2, experiments/generic/pod_network_latency/pod_network_latency_ansible_logic.yml, experiments/generic/pod_network_latency/pod_network_latency_ansible_prerequisites.yml, experiments/generic/pod_network_latency/pod_network_latency_k8s_job.yml, experiments/generic/pod_network_loss/README.md, experiments/generic/pod_network_loss/chaosutil.j2, experiments/generic/pod_network_loss/pod_network_loss_ansible_logic.yml, experiments/generic/pod_network_loss/pod_network_loss_ansible_prerequisites.yml, experiments/generic/pod_network_loss/pod_network_loss_k8s_job.yml
- Introduces network chaos on Kubernetes pods using Pumba (network latency/delays & percentage-based packet loss)
**Checklist**
[network-latency.log](https://github.com/litmuschaos/litmus/files/3710846/network-latency.log)
[network-packet-loss.log](https://github.com/litmuschaos/litmus/files/3710847/network-packet-loss.log)
- Further optimizations (to reduce repeated execution of some tasks, such as pumba setup/teardown for example will be placed as separate utils owned by the lib). These will be considered in …
=> (feat)experiment: add generic network chaos experiments on k8s pods

CONTRIBUTING.md
- Consists of updates to contribution guide on sync-up meeting & release planning sheet
**Checklist**
=> (community) contributing_guide: include sync up meeting details

executor/README.md
-  update readme - add Steps to get executor and monitor image from the engine spec
**Checklist**
=> update(README): steps to add monitor and executor image added

hack/chaos-result.j2, utils/runtime/update_chaos_result_resource.yml
- This introduces a way for the executors (in its current form or any custom executors) to propagate an (execution) instance_id of the experiment to its chaos result resource. It could be passed as an ENV, or as an ansible playbook extra var.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #914 
**Checklist**
- The if blocks in the templating logic introduces indentation by default, to avoid which the flag `lstrip_blocks` has been used in the template task. This needs the python package jinja2>2.7. The current ansible-runner uses jinja2 vers 2.10.3.
- The …
=> (enhancement) executor: add capability to append an instance_id to chaos result

chaoslib/litmus/kill_random_pod.yml, experiments/kafka/kafka-broker-pod-failure/chaosutil.j2, experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml, experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-prerequisites.yml, experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-k8s-job.yml, utils/apps/kafka/display_kafka_broker_info.yml, utils/apps/kafka/kafka_cluster_health.yml, utils/apps/kafka/kafka_launch_stream_derive_leader_broker.yml, utils/apps/kafka/kafka_liveness.j2, utils/apps/kafka/kafka_liveness_cleanup.yml, utils/apps/kafka/kafka_liveness_stream.yml, utils/apps/kafka/kafka_select_broker.yml
- Introduces a kafka chaos experiment to  kill kafka-broker pod while a message stream is being published/consumed. The experiment aims to test the deployment sanity of the kafka cluster, by checking that the data stream consumption is un-interrupted upon kill of either the leader broker (for a specified topic partition) or its in-sync replicas (ISRs)
- The experiment can be performed in three different modes, where the broker under test (to be killed) is determined in the following ways:
- Select a specific kafka-broker pod which is known to maintain known data partitions
- Allow a custom kafka liveness client that simulates the producer/consumer nodes to create a topic with desired replication factor …
=> (feat) kafka: include kafka broker kill experiment

experiments/kafka/kafka-broker-pod-failure/README.md
-  Add sample chaosengine manifest for the kafka broker pod failure experiment
**Checklist**
=> (feat): add readme for kafka broker pod failure experiment

experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml, experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-k8s-job.yml, utils/apps/kafka/kafka_liveness.j2
- Existing kafka liveness checks fail on kudo-based kafka clusters due to the difference in zookeeper uri used by the kafka cli scripts.
- kudo: ${ZOOKEEPER_SERVICE}:${ZOOKEEPER_PORT}/${KAFKA_INSTANCE_NAME}
- confluent: ${ZOOKEEPER_SERVICE}:${ZOOKEEPER_PORT} 
**Checklist**
=> (refactor)kafka: support liveness checks on kudo kafka cluster

utils/apps/kafka/kafka_liveness_stream.yml
- Fix the zookeeper URI used in the liveness util (determine topic/partition leader) 
**Checklist**
=> (refactor)kafka-liveness: use correct zookeeper uri for kudo kafka cluster

experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-ansible-logic.yml, experiments/kafka/kafka-broker-disk-failure/kafka-broker-disk-failure-k8s-job.yml, experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-ansible-logic.yml, experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure-k8s-job.yml, utils/apps/kafka/kafka_liveness.j2, utils/common/status_app_pod.yml
- Adds a new ENV for kafka consumer timeouts
- Optimizes app pod status check util
**Checklist**
=> (refactor)kafka: add updated liveness checks

executor/executor.yml
- This PR ensures that the chaos executor monitors the experiment for the period of  ```TOTAL_CHAOS_DURATION``` (adds some default period of 500s to it) 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #953 
**Checklist**
=> (fix)chaos_executor: ensure executor waits for the experiment chaos duration before completion

chaoslib/pumba/pumba.j2
The apiVersion of pumba daemonset was changed, and it now needs a selector field to work properly, otherwise it gives an error when running experiments using the pumba chaoslib.
**Which issue this PR fixes *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #**
Related to my issue #949 .
**Checklist**
=> Added missing selector to DaemonSet

chaoslib/pumba/pod_failure_by_sigkill.yaml
On slow machines the container-kill experiments fails just because the restartCount is only 30 and the pod could take longer to restart its killed container. Increasing it lets the experiment pass successfully.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: related to discussion in #949 
**Checklist**
=> Changed restartCount 30 -> 60

executor/experiment_volumes.yml
- This PR will validate the configMaps which are defined in chaos experiment .
- This PR ensures that the configmaps which are given in chaos experiment should 
present inside cluster.
- If the configMap are not present inside cluster then the experiment job will not be 
created
**Checklist**
=> executer: Validating  configMaps present inside cluster or not

executor/experiment_volumes.yml
- This PR will validate the secrets which are defined in chaos experiment .
- This PR ensures that the secrets which are given in chaos experiment should
present inside cluster.
- If the secrets are not present inside cluster then the experiment job will not be
created
**Checklist**
=> executer: Validating secrets present inside cluster or not 

.gitignore, .gitlab-ci.yml, contribute/developer_guide/templates/package.tmpl, contribute/developer_guide/test/templates/chartserviceversion.expected, contribute/developer_guide/test/templates/experiment_cr.expected, contribute/developer_guide/test/templates/experiment_csv.expected, contribute/developer_guide/test/templates/experiment_logic.expected, contribute/developer_guide/test/templates/package.expected, contribute/developer_guide/test_generate_chart.py, hack/pytest-suite
- Adds a pytest suite to test whether experiment artefacts (csv, package, custom resource, ansible logic yaml) are generated successfully using the `generate_chart.py` script
- A function mimicking the scaffold generation in actual script is created & tests created against it to bring out an initial suite that validates whether the artefacts are generated without errors. 
- The tests will be carried out in a separate gitlab stage (gitlab executor VM has been patched with the dependencies) 
**Checklist**
- Path …
=> Add pytest suite to verify successful scaffolding of experiment artefacts

experiments/openebs/openebs-target-container-failure/openebs_target_container_failure_ansible_logic.yml, experiments/openebs/openebs-target-pod-failure/openebs_target_pod_failure_ansible_logic.yml
-   Update the chaos result name in openebs target pod/container failure experiments
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1003 
**Checklist**
=> (fix): update the chaos-result name

build/ansible-runner/Dockerfile, build/plugins/default.py, build/utils/display.py
**What this PR does / why we need it**: 
- The experiments (and executor) consist of multiple conditional tasks (using `when` operator) which causes multiple "skipped" log entries causing the output to be clustered, especially with verbose mode. This PR suppresses the skipped tasks by default by a configuration param. If however, this needs to enabled for debug purposes, it can be achieved via the ENV "DISPLAY_SKIPPED_HOSTS" set to "True".
- The ansible tasks by default mention the "hostname" performing the task along with a task result "status" param depending on whether the task was indeed executed to modify state (`changed`) or the desired state is already achieved, hence not needing a modification (idempotence) (`ok`). Considering …
=> (feat) modify ansible stdout log

executor/executor.yml, executor/test.yml
-  Get the auxiliaryAppInfo variable from runner pod Env
-  Add auxiliaryAppInfo variable as a job env so that we can use this for multiple app health check status in infra chaos experiments.
- auxiliaryAppinfo contains namespaces and labels of all the dependent jobs.
**Checklist**
=> (feat): Add auxiliaryAppInfo Env variable in job

experiments/generic/pod_network_loss/README.md, experiments/generic/pod_network_loss/pod_network_loss_k8s_job.yml
- Update readme of pod network loss experiment
-  Change lib-image in job
**Checklist**
=> (refactor): update readme & change pumba image

chaoslib/litmus/disk_fill/disk_fill_ds.yaml
-  Changed ApiVersion of daemonset from extensions/v1beta1 to apps/v1
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1056
**Checklist**
=> (fix):Changed apiVersion of daemonset for disk-fill

chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml, chaoslib/litmus/platform/gke/pod_cpu_consumption.yml
- Unable to confirm that the Disk Fill DaemonSet is deleted successfully.
- Unable to confirm that the Cpu-Hog DaemonSet is deleted successfully.
- Removed typo
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/litmuschaos/litmus/issues/1080
**Checklist**
=> (Fix):Check availablity of daemonset after deletion in cpu-hog and disk-fill

chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml
- Adding rescue block in powefulseal lib so that it will always delete the powerfulseal deployment
- The playbook will fail if any task inside that playbook fails
**Logs for all possible conditions**
[powerfulseal-pass.txt](https://github.com/litmuschaos/litmus/files/4039164/powerfulseal-pass.txt)
[powerfulseal-fail-before-deployment-creation.txt](https://github.com/litmuschaos/litmus/files/4039165/powerfulseal-fail-before-deployment-creation.txt)
[powerfulseal-fail-after-deployment-creation.txt](https://github.com/litmuschaos/litmus/files/4039166/powerfulseal-fail-after-deployment-creation.txt)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
=> (feat): Adding rescue block in pod-delete by powerseal lib

executor/engine_configmap_getter.yml, executor/engine_env_getter.yml, executor/engine_secret_getter.yml, executor/executor.yml, executor/experiment_configmap_getter.yml, executor/experiment_secret_getter.yml, executor/experiment_volumes.yml
- Add the ability to provide ENV, ConfigMap and secrets in chaosengine.
- Tested by providing multiple ENV, configmaps and secrets. It is able to override ENV, configmaps and secrets from the engine. If the ENV, configmaps or secrets not present inside chaos experiment then it will append them.
**Job-pod description**
[drain-node-job-pod.txt](https://github.com/litmuschaos/litmus/files/4076647/drain-node-job-pod.txt)
**engine and experiment yaml**
[drain-node.txt](https://github.com/litmuschaos/litmus/files/4076648/drain-node.txt)
[chaosengine.txt](https://github.com/litmuschaos/litmus/files/4076650/chaosengine.txt)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, …
=> (feat): Add ability to provide cmap/secret in engine

chaoslib/pumba/pod_failure_by_sigkill.yaml, experiments/generic/container_kill/container_kill_ansible_logic.yml, experiments/openebs/openebs-pool-container-failure/cstor_kill_and_verify_pool.yml
- Adding rescue block in pod-failure-by-sigkill lib so that it will always delete the Pumba DS
- The playbook will fail if any task inside that playbook fails
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1140 
**Checklist**
=> (feat): Adding rescue block in pod-failure-by sigkill  lib

experiments/openebs/openebs-pool-container-failure/cstor_kill_and_verify_pool.yml, experiments/openebs/openebs-pool-container-failure/openebs_pool_container_failure_ansible_logic.yml, experiments/openebs/openebs-pool-pod-failure/openebs_pool_pod_failure_ansible_logic.yml
- Previously the name of chaos-result for `openebs-pool-container-failure` experiment is only the name of c_experiment. It will update the name of  chaos-result to `<engine-name>-<c_experiment>`
- Previously the name of chaos-result for `openebs-pool-pod-failure` experiment is only the name of c_experiment. It will update the name of  chaos-result to `<engine-name>-<c_experiment>`
- Remove the action field from the `cstor_kill_and_verify_pool`. As we already removed the action field from `pod_failure_by_sigkill` Lib 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1149 …
=> (refactor): Update the name of chaos-result in openebs pool container/pod failure experiment

chaoslib/litmus/cordon_drain_node.yaml, experiments/generic/node_drain/node_drain_ansible_logic.yml, experiments/generic/node_drain/node_drain_k8s_job.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #(partially addresses #1152 )
**Checklist**
=> (refactor) ramp_time support for node_drain experiment

chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml, experiments/generic/disk_fill/disk_fill_ansible_logic.yml, experiments/generic/disk_fill/disk_fill_k8s_job.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #(partially addresses #1152 )
**Checklist**
=> (refactor) ramp_time support for disk_fill experiment

chaoslib/litmus/container_kill/containerd_chaos/containerd.j2, chaoslib/litmus/cpu_hog/app_cpu_stress.j2, chaoslib/litmus/disk_fill/disk_fill_ds.j2, chaoslib/litmus/platform/gke/node-cpu-hog-daemonset.j2, chaoslib/powerfulseal/powerfulseal.j2, chaoslib/pumba/network_chaos/pumba_netem_job.j2, chaoslib/pumba/pumba.j2
- The abort workflow identifies the k8s resources with the chaos lineage (via engine UID) and deletes them.  
- Right now, only the children (pod) of higher level controllers (job/deploy/daemonset) are passed the chaos UID labels. Deleting them can cause the pods to be recreated, thereby not completely achieving the abort functionality. 
- This PR fixes this by adding the chaos UID labels at parent resource level.
**Checklist**
=> (fix) add chaos lineage via labels to parent k8s resources

chaoslib/litmus/platform/gke/node_cpu_consumption.yml
- Fixing the hardcoded async value to sum of chaos duration and grace period (30s) 
**Checklist**
=> (fix): Fixing the hardcoded async value to sum of chaos duration and graceperiod (30s) 

chaoslib/litmus/kill_random_pod.yml
- Add ability to select only the running pods.
- Add the AUT running status check after the deletion of replica in each iteration. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/litmuschaos/litmus/issues/1258
**Checklist**
=> feat(pod-delete): Add ability to select only running pods

chaoslib/litmus/cpu_hog/app_cpu_stress.j2, chaoslib/litmus/cpu_hog/pod_cpu_hog.yml, chaoslib/pumba/network_chaos/network_chaos.yml, chaoslib/pumba/network_chaos/pumba_netem_job.j2, experiments/generic/pod_cpu_hog/pod_cpu_hog_k8s_job.yml, experiments/generic/pod_network_corruption/pod_network_corruption_k8s_job.yml, experiments/generic/pod_network_latency/pod_network_latency_k8s_job.yml, experiments/generic/pod_network_loss/pod_network_loss_k8s_job.yml, experiments/kafka/kafka-broker-network-latency/kafka-broker-network-latency-k8s-job.yml, experiments/kafka/kafka-broker-network-loss/kafka-broker-network-loss-k8s-job.yml, experiments/openebs/openebs-pool-network-delay/openebs_pool_network_delay_k8s_job.yml, experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_ansible_logic.yml, experiments/openebs/openebs-pool-network-loss/openebs_pool_network_loss_k8s_job.yml, experiments/openebs/openebs-target-network-delay/openebs_target_network_delay_k8s_job.yml, experiments/openebs/openebs-target-network-loss/openebs_target_network_loss_k8s_job.yml
- Make the total-time-duration consistent in all experiments. It should be in seconds
**Checklist**
=> refactor(experiments): Make the time-duration consistent(in seconds) in all experiments

chaoslib/pumba/pod_failure_by_sigkill.yml
- Adding record restart count step before chaosInjection because container-kill experiment was failing due to the presence of restartCountBef and restartCountAfter both after the chaos injection. Hence this condintion `restartCountAfter > restartCountBef` fails
**Checklist**
=> fix(container-kill): Adding record restart count step before chaosInjection

chaoslib/litmus/container_kill/containerd_chaos/containerd.j2, chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml, chaoslib/litmus/disk_fill/disk_fill_by_litmus.yml, chaoslib/litmus/disk_fill/disk_fill_job.j2, chaoslib/litmus/platform/gke/node-cpu-hog-job.j2, chaoslib/litmus/platform/gke/node-memory-hog-job.j2, chaoslib/litmus/platform/gke/node_cpu_consumption.yml, chaoslib/litmus/platform/gke/node_memory_consumption.yml, chaoslib/pumba/pod_failure_by_sigkill.yml, chaoslib/pumba/pumba.j2
- Adding run-id support for the chaoslibs. This helps in unique identification of the chaos job in a given namespace for the same engine. 
**Checklist**
=> Feat(Chaos-lib): Adding run-id support for the chaos libs

experiments/openebs/openebs-pool-disk-loss/openebs_pool_disk_loss_ansible_logic.yml
- Adding event support for openebs pool disk loss experiment
**Checklist**
=> Feat(Openebs-pool-disk-loss): Adding event support for openebs pool disk loss experiment

chaoslib/litmus/container_kill/containerd_chaos/containerd.j2, chaoslib/litmus/cpu_hog/app_cpu_stress.j2, chaoslib/litmus/disk_fill/disk_fill_job.j2, chaoslib/litmus/platform/gke/node-cpu-hog-job.j2, chaoslib/litmus/platform/gke/node-memory-hog-job.j2, chaoslib/litmus/platform/gke/node_cpu_consumption.yml, chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml, chaoslib/powerfulseal/powerfulseal.j2, chaoslib/pumba/network_chaos/pumba_netem_job.j2, chaoslib/pumba/pod_failure_by_sigkill.yml, chaoslib/pumba/pumba.j2, experiments/coredns/pod_delete/liveness-app.j2, experiments/coredns/pod_delete/nginx.j2
Issue it resolve: https://github.com/litmuschaos/litmus/issues/1292
**_This PR is for:_**
- Adding checks for chaos-uid in all jinja templates
**Checklist**
=> bug-fix(jinja-template): Adding checks for chaos-uid in all jinja templates

utils/runtime/getting_failure_step.yml
- set the offset on the basis of verbosity level to get the failure step
**Checklist**
=> feat(ansible-verbosity):  Getting failure step on the basis of verbosity level

experiments/generic/node_memory_hog/README.md
**_This PR contains:_**
- Addition of docs link for node memory experiment
**Checklist**
=> docs(experiment): Add docs link in node memory hog experiments

experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_ansible_logic.yml, experiments/openebs/openebs-control-plane-chaos/openebs_control_plane_chaos_internal_tasks.yml
- fix the namespace issue of openebs-control-plane-chaos 
**Checklist**
=> fix(experiment): fix the namespace issue of openebs-control-plane-chaos

experiments/coredns/pod_delete/pod_delete_ansible_logic.yml
=> (bug): Removing misplaced command

chaoslib/litmus/kill_random_pod.yml
- If we want to kill the pod once then there is no need for the app status check there as we already have app status check in the post chaos check. Second point, when we are including kill_random_pod_kill from openebs experiments we are not passing app_label we are directly passing app_pod_name so status util may fail as it need app_label.
- If we want to kill the application pod multiple times ( having c_iterations) then we have to check the application status before going for next iteration for killing
**Checklist**
**Special …
=> fix(kill-random-pod): check status only if c_iterations is defined

.github/stale.yml
- Integrate stale bot maintain the stale issue
More info: https://probot.github.io/apps/stale/
**Checklist**
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>
=> (stale-bot): Add template for stale bot

ROADMAP.md
- Updates the roadmap completed items based on 1.2/1.2.1/1.2.2 deliverables. 
**Checklist**
=> (chore)roadmap: move features from in-progress to completed items

chaoslib/powerfulseal/pod_failure_by_powerfulseal.yml, chaoslib/powerfulseal/powerfulseal.j2
-  Deriving svc_acc_name in powerfulseal experiment
**Checklist**
=> fix(powerfulseal): Deriving svc_acc_name in powerfulseal experiment

experiments/openebs/openebs-pool-pod-failure/cstor_delete_and_verify_pool_deployment.yml
- Giving correct chaoslib path to kill random pod. For more details - https://gitlab.mayadata.io/litmuschaos/litmus-e2e/-/jobs/81564
**Checklist**
=> fix(bug): Giving correct chaoslib path to kill random pod

experiments/openebs/openebs-pool-pod-failure/cstor_delete_and_verify_pool_deployment.yml
- Typo in chaoslib path of openebs pool pod failure experiment.
**Checklist**
=> (fix): Typo in chaoslib path of openebs pool pod failure experiment

chaoslib/litmus/pod_cpu_hog/pod_cpu_hog.yml, experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_logic.yml, experiments/generic/pod_cpu_hog/pod_cpu_hog_ansible_prerequisites.yml
- Adding the task banner in the pod-cpu-hog experiment
**Checklist**
=> refactor(pod-cpu-hog): Adding the task banner in the pod-cpu-hog experiment

utils/runtime/chaos-result.j2, utils/runtime/update_chaos_result_resource.yml
- Adds a user-defined string to the chaosresult name and also the CR spec to enable users to define an "instance" of chaos. 
- Useful in cases where existing chaosresult resources are not to be overwritten
- The instance info is taken as an env var INSTANCE_ID in the chaosengine 
**Note**: This change also necessitates an update to the chaos-runner to process the INSTANCE_ID info and pass it to the experiment job. 
**Checklist**
=> (enhancement)chaosresult: add an instance_id to chaosresult name and spec

ADOPTERS.md
Sumit has presented the demo of how Argo-Litmus is used to do chaos engineering at Intuit at the community syncup meeting on 15th April. Updating Adopters.md for the same.
=> Update Adopters.md with Argo-Litmus demo link

MAINTAINERS
- The litmus governance is being updated to a SIG model where each area (comprising one or more sub-projects / repos) will be maintained by a SIG lead, who will maintain those repos
- While this revamp will be made soon via a series of upcoming PRs (the SIGs formation is in progress at this point), this PR adds Maria Kotlyarevskaya who is keenly interested in leading the "Deployment SIG"  and maintaining the associated repos, into the existing maintainers list. 
- Maria has multiple useful PRs on the helm repos and is an active community member on the litmus slack channel and is committed to the long-term success of Litmus chaos engineering project. 
**Which issue this PR fixes** *(optional, in `fixes …
=> (chore)governance: add maria as a maintainer (litmus deployment focused)

chaoslib/litmus/pod_delete/kill_random_pod.yml
- Adding type casting in pod-delete experiment
**Checklist**
=> update(pod-delete): Adding type casting in pod-delete experiment

chaoslib/litmus/pod_delete/kill_random_pod.yml
Signed-off-by: xkbarkar kristin.barkardottir@gmail.com 
The current FORCE flag in pod_delete experiment is pointless as pods will be force deleted either way 
**Which issue this PR fixes** *
#1507
**Checklist**
=> Remove the force flag from pod_delete job that should not force delete

chaoslib/litmus/container_kill/containerd_chaos/crictl-chaos.yml
- This PR is for adding some grace period in the retires for checking the contained chaos-pod. For shorter chaos duration in the clusters like KinD the chaos pod takes time to get in completed/succeeded state.
**Checklist**
=> fix(experiment): Adding some grace period in the retries for containerd chaos-pod

.github/auto-merge.yml, .github/workflows/main.yml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
- This PR is for adding label `merge` for `/merge` on a PR comment further reading this label Github pro-bot will check if 1 approval is there or label merge is there or not. If all the requirements are fulfilled then pro-bot will merge the  Pull  Request.
- This PR also fixes the issue related to running container-kill experiment BDDs.
**Workflow:**
- for `/merge` in PR comment, it will add a merge label ref: [this-merge-example](https://github.com/uditgaurav/litmus-run-e2e/pull/6#issuecomment-645061238)
**Which issue this PR fixes** 
- fixes https://github.com/litmuschaos/litmus/issues/1557
**Checklist**
- Please install …
=> feat(actions): Add merge label and auto-merge feature in GitHub Actions

experiments/generic/pod_network_corruption/README.md
- Add more details in pod network corruption readme
**Checklist**
=> refactor(readme): Add more details in pod network corruption readme

chaoslib/litmus/kubelet_service_kill/kubelet-service-kill.j2
- This pull request is for fixing the indentation in the kubelet-service-kill experiment j2 file.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/litmuschaos/litmus/pull/1582
**Checklist**
=> Bug(indentation): Fix the indentation in kubelet service kill experiment j2 file

MAINTAINERS
- Updates email IDs of maintainers'
**Checklist**
=> (chore)governance: update maintainer email IDs

.circleci/config.yml
Signed-off-by: gdsoumya <gdsoumya@gmail.com>
This PR stops the Litmus Portal CI builds on master branch
**Checklist**
=> Stopped CircleCi Build for master branch

litmus-portal/backend/subscriber/pkg/types/types.go, litmus-portal/backend/subscriber/subscriber.go
Changes:
1. Adding flag.Parse() (Now it will work both as incluster and outcluster)
2. Adding a struct for the response of `clusterconfirm` mutation
Issue- https://github.com/litmuschaos/litmus/issues/1903
=> Adding flag.Parse() and struct for clusteconfim mutation response

litmus-portal/backend/subscriber/pkg/cluster/events/workflow.go, litmus-portal/backend/subscriber/pkg/types/event.go
- Added message field to the workflow-run execution data
- This field will contain messages regarding the workflow status (required for workflow errors)
=> Added Message field to Workflow-Run execution data

litmus-portal/backend/graphql-server/pkg/database/mongodb/operations.go
Currently, workflow-collection inserts duplicate `workflow_run_id`. This commit will do a custom upsert operation.
=> Changing MongoDB operation for a unique update of workflow collection

litmus-portal/backend/graphql-server/pkg/graphql/mutations/mutation.go
Bug: Earlier it was not JSON marshalling the experiment name in weightage.
Fix: using copy struct is able to fix the bug
=> Bug-fix: using copier to copy the weightages struct

litmus-portal/frontend/src/components/PredifinedWorkflows/data.ts, litmus-portal/frontend/src/components/WorkflowCard/CardContent.tsx, litmus-portal/frontend/src/components/WorkflowCard/styles.ts, litmus-portal/frontend/src/components/WorkflowStepper/index.tsx, litmus-portal/frontend/src/models/predefinedWorkflow.ts, litmus-portal/frontend/src/models/redux/template.ts, litmus-portal/frontend/src/pages/HomePage/index.tsx, litmus-portal/frontend/src/redux/actions/template.ts, litmus-portal/frontend/src/redux/reducers/index.ts, litmus-portal/frontend/src/redux/reducers/template.ts, litmus-portal/frontend/src/theme/index.tsx, litmus-portal/frontend/src/views/ChaosWorkflows/Templates/index.tsx, litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
This PR:
1. Fixes pre selection of workflow card when returning back from template
2. Adds a button toggle er global state
3. Doesn't tamper with workflow ID when creating a new schedule
4. Adds few colors to themes that were not earlier included
=> chore(litmus-portal): Fixed pre-selection from Template & toggling button for initial workflow selection

litmus-portal/graphql-server/pkg/cluster/cluster_jwt.go
- Previously the cluster registration token was set to expire after 12hrs
- Updated it to never expire until the cluster is registered
=> Removed expiration from cluster-registration jwt

litmus-portal/frontend/src/components/Header/index.tsx, litmus-portal/frontend/src/containers/app/App.tsx
Signed-off-by: Vedant Shrotria <vedant.shrotria@mayadata.io>
**This PR will fix:**
**- User who is not an owner won't be allowed to go to settings route.**
**- If User who is not an editor or owner of a project is on settings page, will be redirected to homepage while project switching.**
- Please add the links to the dependent PR need to be …
=> Fix for Settings route for different users with different roles.

litmus-portal/cluster-agents/subscriber/pkg/gql/util.go
Subscriber is not able to parse an error string
eg: 			
```
"message": "pods \"argowf-chaos-pod-delete-1602350414-2208157228\" is forbidden: error looking up service account litmus/argo-chaos: serviceaccount \"argo-chaos\" not found"
```
Replacing it with space
=> Bug-fix: Replacing string to space in error condition

litmus-portal/graphql-server/pkg/graphql/mutations/mutation.go
=> Adding is_cluster_confimed to true, once it got confirmed

monitoring/grafana-dashboards/sock-shop/Sock-Shop-Performance-Under-Chaos.json
Solves issue for decimal gauge values.
When Instant if off it uses the query API endpoint rather than the query_range API endpoint on Prometheus, which is more efficient if we only care about the end of the time range and don't want to pull in data that Grafana is going to give away again. Making instant as true on the gauge solves the issue of decimal numbers for the count.
- None.
=> Minor fix for gauge count errors on sock-shop dashboard.

litmus-portal/frontend/src/views/Home/PassedVsFailed/index.tsx, litmus-portal/frontend/src/views/Home/ResilienceScoreComparisonPlot/index.tsx, litmus-portal/frontend/src/views/Home/ReturningHome/index.tsx
Minor analytics bug fix.
The bugs:
1. Icons showing on passed vs failed component beyond 10% too which was to be removed as per @ajeshbaby 's review.
2. Due to fetch policy sometimes the query for analytics data was not getting triggered.
3. Red and green colour are reserved for use after only 2 lines available on workflow comparison graph on the home screen with other theme colours.
The fix:
1. Updated condition for the conditional rendering of icons.
2. Removed fetch policy override to default to network query rather than Apollo cache.
3. Changed order of colours on comparison graph colour array, pushing red and green colours to the end.
Put …
=> (litmus-portal): Minor bug fixes for analytics on litmus portal.

litmus-portal/frontend/src/components/YamlEditor/Editor.tsx, litmus-portal/frontend/src/views/CreateWorkflow/CustomWorkflow/TuneWorkflow/index.tsx
Fixed an edge case where appinfo is not present in custom workflows like ec2-terminate experiment and display the default value of annotationCheck from the YAML in UI.
=> Fixed an edge case where appinfo is not present in custom workflows

litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go, litmus-portal/cluster-agents/subscriber/pkg/types/event.go
This PR adds a new field called `chaosResult` in the `chaosData` section of the workflow nodes(chaos steps) which contains the complete chaos result cr for the particular experiment
=> Added complete chaos result to workflow data

docs/chaos-scheduler-v1.13.0.yaml, docs/litmus-namespaced-scope/litmus-namespaced-crds.yaml, docs/litmus-operator-ci.yaml, docs/litmus-operator-latest.yaml, docs/litmus-operator-v1.13.0-crd-v1.yaml, docs/litmus-operator-v1.13.0.yaml, litmus-portal/graphql-server/manifests/cluster/2a_litmus_crds.yaml, litmus-portal/litmus-portal-crds.yml
-  Removing maxProperties field from the openapi validator of chaosengine crd. 
=> fix(crds): Removing maxProperties field from openapi validator for chaosengine

litmus-portal/graphql-server/graph/generated/generated.go, litmus-portal/graphql-server/graph/schema.graphqls, litmus-portal/graphql-server/graph/schema.resolvers.go, litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
Added workflow re-run feature in backend, that allows running a one-time workflow again without re-creating a new schedule manually.
closes #2467 
=> Added workflow re-run feature

litmus-portal/frontend/public/locales/en/translation.yaml, litmus-portal/frontend/src/components/WelcomeModal/Stepper.tsx, litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/index.tsx, litmus-portal/frontend/src/views/Settings/AccountsTab/AccountSettings/styles.ts, litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx, litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/styles.ts, litmus-portal/frontend/src/views/Settings/TeamingTab/InviteNew/Invite/styles.ts, litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/NewUserModal/styles.ts, litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/UserDetails/index.tsx, litmus-portal/frontend/src/views/Settings/UserManagementTab/CreateUser/index.tsx, litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/ResetModal/styles.ts, litmus-portal/frontend/src/views/Settings/UserManagementTab/EditUser/index.tsx
Signed-off-by: SarthakJain26 <sarthak.jain@mayadata.io>
- Removed Default Error state from Password Fields in Settings Tab and Welcome Modal
- Fixed Modal Padding in Settings Tab
- [ x] Bugfix (non-breaking change which fixes an issue)
=> Fixed default error state for password fields and fixed modal padding

litmus-portal/cluster-agents/subscriber/pkg/cluster/events/util.go, litmus-portal/cluster-agents/subscriber/pkg/cluster/events/workflow.go
This PR modifies the subscriber to update the workflow and experiment status to `failed` when the chaos engine status is `stopped`
=> Updated workflow status to failed for stopped chaosengines

litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml, litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
* removed hardcoded litmus namespace from chaos exporter deployment
* removed space at the start of the filename
=> (litmus-portal): removed hardcoded litmus namespace from chaos exporter deployment and removed space at the start of the filename.

litmus-portal/frontend/src/views/CreateWorkflow/ChooseWorkflow/index.tsx
This PR fixes the issue where, on closing the customize workflow modal, the new workflow name is shown despite not saving.
=> chore(litmus-portal): Fix workflow name issue

litmus-portal/frontend/public/locales/en/translation.yaml, litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx, litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx, litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/styles.ts
This PR adds in units in the `AddProbe` modal for the required fields. Ref: [Unit issue](https://github.com/litmuschaos/litmus-e2e/issues/254)
=> chore(litmus-portal): Add units to AddProbe modal

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddExperimentModal.tsx, litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/styles.ts
This PR changes `AddExperimentModal` to use RadioButton instead of Select and also adds in search for easier selection.
=> chore(litmus-portal): Change AddExperimentModal to use RadioButton

litmus-portal/cluster-agents/subscriber/pkg/gql/subscriptions.go, litmus-portal/cluster-agents/subscriber/pkg/gql/util.go
This PR updates the pod logs feature to query argo and experiment pods dependently.
fixes #2813
=> Updated pod logs to fetch argo and experiment logs independently

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/WorkflowTable.tsx, litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/index.tsx
This PR adds:
- podGC as `OnWorkflowCompletion` when revert-chaos is enabled
=> chore(litmus-portal): Added podGC on revert-chaos

litmus-portal/authentication/api/handlers/user_handlers.go, litmus-portal/authentication/api/middleware/jwt_middlware.go, litmus-portal/authentication/api/routes/user_router.go, litmus-portal/authentication/go.sum, litmus-portal/authentication/pkg/entities/user.go, litmus-portal/authentication/pkg/user/repository.go, litmus-portal/authentication/pkg/user/service.go, litmus-portal/authentication/pkg/utils/errors.go
- `/updatestatus` API allows admin users to enable or disable a user's state.
- Disabled user will not be allowed to login. 
- Separated password validation from find user utility.
- Username was considered in …
=> Disable and Enable user from auth

litmus-portal/graphql-server/go.sum, litmus-portal/graphql-server/graph/analytics.graphqls, litmus-portal/graphql-server/graph/generated/generated.go, litmus-portal/graphql-server/graph/model/models_gen.go, litmus-portal/graphql-server/graph/schema.graphqls, litmus-portal/graphql-server/graph/schema.resolvers.go, litmus-portal/graphql-server/pkg/analytics/handler/handler.go, litmus-portal/graphql-server/pkg/analytics/types.go, litmus-portal/graphql-server/pkg/myhub/myhub.go
This PR adds:
- GQL Query to fetch dashboard details from hub
Sample Output:
`
{
"name": "node_metrics.json",
"dashboard_data": "{\"dashboardID\":\"generic_node_metrics\",\"name\":\"Node metrics\",\"information\":\"This dashboard visualizes Node level CPU, memory, disk and IO utilization metrics interleaved with chaos …
=> Added query to fetch dashboard details from hub

ADOPTERS.md, adopters/organizations/pravega.md
Signed-off-by: ajeshbaby <ajesh@chaosnative.com>
Adding Pravega as an adopter with reference to [comment](https://github.com/litmuschaos/litmus/issues/2191#issuecomment-881397381)
Thank you @SomeshJoshi19
=> Add Pravega as Adopter

litmus-portal/graphql-server/manifests/cluster/2c_litmus_deployment.yaml, litmus-portal/graphql-server/manifests/namespace/2b_litmus_deployment.yaml
* Adding named ports for service monitors
* Adding prometheus labels for pod monitors
=> Adding named ports and labels to chaos exporter deployments for monitoring automation

litmus-portal/graphql-server/pkg/analytics/handler/handler.go
fixing application dashboard crash on saving after updating panel group name with existing panels - by removing panel group update check on ids as it was removing the panel and changing its panel group id after updating it correctly
Screenshots:
- existing panels removed and group id changed to previous id after update
- panel group name updated with new group id
- panels missing for new panel group due to group id mismatch and panel removal based on `is_removed` field's value
=> fixing application dashboard crash on saving after panel group name update with existing panel association

litmus-portal/cluster-k8s-manifest.yml, litmus-portal/namespaced-k8s-template.yml, litmus-portal/platforms/okteto/litmus-portal-dev-manifest-template.yml
Currently, the server addresses are hardcoded in the frontend docker image, so that it is hard to configure the endpoints. Adding nginx config as a separate configmap and mount it with the frontend deployment.
=> Adding nginx config as a separated configmap to make it more configurable

litmus-portal/graphql-server/graph/schema.resolvers.go
Added rbac for following mutations:
- `UserClusterReg`
- `CreateDataSource`
- `CreateDashBoard`
- `UpdateDataSource`
- Rbac is added only for the mutations where projectID is passed in the request body
- Add Rbac for other mutations where project ID is not passed by adding custom queries.
=> Added rbac for mutations

litmus-portal/cluster-agents/event-tracker/controllers/eventtrackerpolicy_controller.go, litmus-portal/cluster-agents/event-tracker/pkg/utils/informers.go, litmus-portal/cluster-agents/event-tracker/pkg/utils/utils.go
* Some Kubernetes clusters don't have kubectl.kubernetes.io/last-applied-configuration annotation due to which it affects the event tracker functionality
*  Removing the event tracker dependency on "last-applied-configuration" annotation by comparing the changes of the last two object provided by the Kubernetes informer
Put an `x's in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
=> Removing the event tracker dependency from "last-applied-configuration" annotation

litmus-portal/graphql-server/pkg/database/mongodb/init.go
Fixes issue #3417 
This will fix the issue for the following case:
If a workflow is deleted and user creates a new workflow with the same name, it will not throw a duplicate workflow name error.
=> Added partialFilter in workflow name indexing

litmus-portal/authentication/api/handlers/rest/project_handler.go, litmus-portal/authentication/api/handlers/rest/user_handlers.go, litmus-portal/authentication/pkg/entities/user.go, litmus-portal/authentication/pkg/project/repository.go, litmus-portal/authentication/pkg/services/transaction_service.go, litmus-portal/authentication/pkg/utils/errors.go, litmus-portal/authentication/pkg/validations/roles.go
- Fixed Authentication API issues : 2,3,4,5,6,8,10 from https://github.com/litmuschaos/litmus-e2e/issues/362
=> Fixed Authentication API issues

litmus-portal/cluster-k8s-manifest.yml, litmus-portal/namespaced-k8s-template.yml
Adding readOnlyRootFilesystem to true for servers
Note: Mongo and frontend can't be run as read-only.
=> Adding readOnlyRootFilesystem to true for servers

mkdocs/docs/experiments/categories/pods/pod-network-latency.md
- Adds `JITTER` to the list of envs of pod-network-latency experiment
fixes #3617
=> Update pod-network-latency Docs FOR JITTER env

ADOPTERS.md, COMMERCIAL_SUPPORT.md, TRAINING_AND_COURSES.md, adopters/organizations/adidas.md, adopters/organizations/containersolutions.md, adopters/organizations/fis.md, adopters/organizations/ifood.md
Updating Adopters list in reference to the issue 
- https://github.com/litmuschaos/litmus/issues/2191#issuecomment-1134647768
- https://github.com/litmuschaos/litmus/issues/2191#issuecomment-1151145372
- https://github.com/litmuschaos/litmus/issues/2191#issuecomment-985550387
- https://github.com/litmuschaos/litmus/issues/2191#issuecomment-1154678884
- https://github.com/litmuschaos/litmus/issues/2191#issuecomment-968705665
=> Changes to the Main Repo: Added Training & Courses, Commercial Support; Updated Adopters

litmus-portal/README.md
=> Updating readme.md for 2.10.0

litmus-portal/graphql-server/pkg/cluster/handler/handler.go, litmus-portal/graphql-server/pkg/handlers/file_handler.go, litmus-portal/graphql-server/pkg/k8s/cluster.go, litmus-portal/manifests/namespace-k8s-manifest.yml
**- These changes will make ClusterIP/ Service FQDN as default endpoint for Self/Internal agents.**
**- Also now in one case when server-service-type is NodePort and User has installed Portal in Namespaced Scope mode, then the endpoint will not be generated for external agents. User has to modify the `CHAOS_CENTER_UI_ENDPOINT` env in this case with frontend access endpoint.**
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
=> Added changes for making clusterIP as default endpoint for self/internal delegates

.github/workflows/build.yml
We have some CVEs in some dependent go pkg. We will upgrade it, but till then, we are making the trivy exit code to 0;
=> changing trivy exit code to 0

litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go, litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go, litmus-portal/graphql-server/utils/misc.go
Changed the user email to base64 for the k8s labels objects, regarding to this [issue](https://github.com/litmuschaos/litmus/issues/3634). #3634 
This was implemented based on this [comment](https://github.com/litmuschaos/litmus/pull/3648#issuecomment-1192535846) for PR #3648.
=> Alter email to base64, because the regex enconding

mkdocs/docs/experiments/categories/pods/pod-dns-error.md, mkdocs/docs/experiments/categories/pods/pod-dns-error/container-runtime-and-socket-path.yaml, mkdocs/docs/experiments/categories/pods/pod-dns-spoof.md, mkdocs/docs/experiments/categories/pods/pod-http-modify-body.md, mkdocs/docs/experiments/categories/pods/pod-http-modify-body/modify-body-with-encoding-type.yaml, mkdocs/docs/experiments/categories/pods/pod-http-status-code.md, mkdocs/docs/experiments/categories/pods/pod-http-status-code/modify-body-with-encoding-type.yaml, mkdocs/docs/experiments/categories/pods/pod-http-status-code/modify-body-with-response-pre-defined.yaml
Signed-off-by: avaakash <as86414@gmail.com>
This PR adds docs for
1. Updating for response body env addition in HTTP status code experiment
2. Updating for content encoding and type env addition in HTTP status code and the modify body experiment.
3. Added clarification for the target service port
Fixes the issue: https://github.com/litmuschaos/litmus/issues/3764
=> Updated docs for new additions in HTTP Chaos

litmus-portal/graphql-server/pkg/myhub/ops/gitops.go
Reverts litmuschaos/litmus#3776
=> Adding SingleBranch:  true in the git clone options

litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/ProbeDetails.tsx, litmus-portal/frontend/src/views/CreateWorkflow/TuneWorkflow/AddProbe/index.tsx
This PR adds:
- Timeout unit to be `ms` only for httpProbe
- Removed responseTimeout from httpProbe
=> Updated probe timeout unit and removed response timeout from httpProbe

mkdocs/docs/experiments/categories/pods/pod-network-corruption.md, mkdocs/docs/experiments/categories/pods/pod-network-corruption/destination-ips-and-hosts.yaml, mkdocs/docs/experiments/categories/pods/pod-network-corruption/network-corruption.yaml, mkdocs/docs/experiments/categories/pods/pod-network-corruption/network-interface.yaml, mkdocs/docs/experiments/categories/pods/pod-network-duplication.md, mkdocs/docs/experiments/categories/pods/pod-network-duplication/destination-ips-and-hosts.yaml, mkdocs/docs/experiments/categories/pods/pod-network-duplication/network-duplication.yaml, mkdocs/docs/experiments/categories/pods/pod-network-duplication/network-interface.yaml, mkdocs/docs/experiments/categories/pods/pod-network-latency.md, mkdocs/docs/experiments/categories/pods/pod-network-latency/destination-ips-and-hosts.yaml, mkdocs/docs/experiments/categories/pods/pod-network-latency/network-interface.yaml, mkdocs/docs/experiments/categories/pods/pod-network-latency/network-latency-jitter.yaml, mkdocs/docs/experiments/categories/pods/pod-network-latency/network-latency.yaml, mkdocs/docs/experiments/categories/pods/pod-network-loss.md, mkdocs/docs/experiments/categories/pods/pod-network-loss/destination-ips-and-hosts.yaml, mkdocs/docs/experiments/categories/pods/pod-network-loss/network-interface.yaml, mkdocs/docs/experiments/categories/pods/pod-network-loss/network-loss.yaml, mkdocs/docs/experiments/concepts/chaos-resources/chaos-engine/application-details.md
Signed-off-by: avaakash <as86414@gmail.com>
This PR removes references to `ingress` from the pod-network-chaos experiments documents.
Fixes: https://github.com/litmuschaos/litmus/issues/3589 and https://github.com/litmuschaos/litmus/issues/3740
=> Update to Pod Network Docs - Removed Ingress references

litmus-portal/cluster-agents/subscriber/pkg/k8s/operations.go, litmus-portal/graphql-server/manifests/cluster/3a_agents_rbac.yaml, litmus-portal/graphql-server/manifests/namespace/3a_agents_rbac.yaml, litmus-portal/graphql-server/pkg/cluster/handler/handler.go, litmus-portal/manifests/cluster-k8s-manifest.yml, litmus-portal/manifests/namespace-k8s-manifest.yml
=> chore(subscriber): delete subscriber by labels

litmus-portal/README.md, mkdocs/docs/3.0.0-beta3/litmus-3.0.0-beta3-without-resources.yaml, mkdocs/docs/3.0.0-beta3/litmus-3.0.0-beta3.yaml, mkdocs/docs/3.0.0-beta3/litmus-namespaced-3.0.0-beta3.yaml
=> chore(rbac): adding deletecollection permissions in server

litmus-portal/README.md, mkdocs/docs/3.0.0-beta4/litmus-3.0.0-beta4-without-resources.yaml, mkdocs/docs/3.0.0-beta4/litmus-3.0.0-beta4.yaml, mkdocs/docs/3.0.0-beta4/litmus-namespaced-3.0.0-beta4.yaml, mkdocs/docs/3.0.0-beta4/litmus-portal-crds-3.0.0-beta4.yml, mkdocs/docs/3.0.0-beta4/upgrade-agent.yaml
Adding manifest and readme for litmus-3.0.0-beta4
=> Adding manifest and readme for litmus-3.0.0-beta4

.gitattributes
Currently, litmuschaos repo shows HTMl as the major language because we have a lot of HTML files, but the default lang for litmuschaos is golang. By adding `.gitattributes`, it will show the golang, bash, and javascript as the major lang for this project.
=> Adding .gitattributes to show golang as the major lang for litmus project

monitoring/utils/metrics-exporters-with-service-monitors/kube-state-metrics/deployment.yaml, monitoring/utils/metrics-exporters/kube-state-metrics/deployment.yaml
Kubernetes is migrating its image registry from [k8s.gcr.io](http://k8s.gcr.io/) to [registry.k8s.io](http://registry.k8s.io/).
Part of kubernetes/k8s.io#4780.
=> chore: migrate from k8s.gcr.io to registry.k8s.io

litmus-portal/graphql-server/pkg/authorization/middleware_test.go, litmus-portal/graphql-server/pkg/authorization/user_jwt_test.go, litmus-portal/graphql-server/pkg/authorization/validate_test.go, litmus-portal/graphql-server/pkg/rest_handlers/core_version_handler.go, litmus-portal/graphql-server/pkg/rest_handlers/core_vision_handler_test.go, litmus-portal/graphql-server/pkg/rest_handlers/file_handler.go, litmus-portal/graphql-server/pkg/rest_handlers/file_handler_test.go, litmus-portal/graphql-server/pkg/rest_handlers/get_icon_handler_test.go, litmus-portal/graphql-server/pkg/rest_handlers/playground_handler_test.go, litmus-portal/graphql-server/pkg/rest_handlers/readiness_handler.go, litmus-portal/graphql-server/pkg/rest_handlers/readiness_handler_test.go, litmus-portal/graphql-server/pkg/rest_handlers/request_logger_test.go, litmus-portal/graphql-server/pkg/rest_handlers/status_handler.go, litmus-portal/graphql-server/pkg/rest_handlers/status_handler_test.go, litmus-portal/graphql-server/server.go
Add unit tests to rest_handlers and authorization package
- rest_handlers package : 90.3%
- authorization package : 71.7%
=> [ChaosCenter]: Add unit tests to rest_handlers and authorization package in GraphQL server

.github/BUILD_IMAGE.md, litmus-portal/Makefile, litmus-portal/README.md, litmus-portal/graphql-server/pkg/cluster/model/mocks/service.go, litmus-portal/graphql-server/pkg/rest_handlers/file_handler_test.go, litmus-portal/upgrade-agents/control-plane/versions/upgrade-manager.go, mkdocs/docs/3.0.0-beta8/litmus-3.0.0-beta8-without-resources.yaml, mkdocs/docs/3.0.0-beta8/litmus-3.0.0-beta8.yaml, mkdocs/docs/3.0.0-beta8/litmus-namespaced-3.0.0-beta8.yaml, mkdocs/docs/3.0.0-beta8/litmus-portal-crds-3.0.0-beta8.yml, mkdocs/docs/3.0.0-beta8/upgrade-agent.yaml
=> Added changes for 3.0.0-beta8 ChaosCenter Release

litmus-portal/graphql-server/graph/resolver.go, litmus-portal/graphql-server/pkg/rest_handlers/file_handler.go, litmus-portal/graphql-server/pkg/rest_handlers/file_handler_test.go, litmus-portal/graphql-server/server.go
Update function parameter for passing unit test cases. 
releated pr. #4009 
=> [ChaosCenter] chore : update function parameter for passing test cases

chaoscenter/web/src/routes/RouteDestinations.tsx, chaoscenter/web/src/strings/strings.en.yaml, chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/TargetApplication/TargetApplication.tsx
=> fix: Updated target application drawer to contain labels

chaoscenter/authentication/pkg/project/repository.go, chaoscenter/graphql/server/pkg/chaos_infrastructure/infra_utils.go, chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go
- updated infra scope from 'infra' to 'cluster'
=> fix: updated infra scope from 'infra' to 'cluster'

mkdocs/docs/experiments/faq/ci-cd.md
`mkdocs/docs/experiments/faq/ci-cd.md`: improve markdown formatting
* lists
* remove extra spaces
* capitalization of Litmus name
To improve https://litmuschaos.github.io/litmus/experiments/faq/ci-cd/
=> ci-cd.md: improve markdown formatting

chaoscenter/web/config/webpack.common.js, chaoscenter/web/config/webpack.dev.js, chaoscenter/web/package.json, chaoscenter/web/src/index.html, chaoscenter/web/yarn.lock
=> fix: Updated config to fix favicon

chaoscenter/graphql/server/pkg/gitops/service.go, chaoscenter/web/src/context/AppStoreContext.tsx, chaoscenter/web/src/controllers/AddHubModalWizard/AddHubModalWizard.tsx, chaoscenter/web/src/controllers/Environments/Environment.tsx, chaoscenter/web/src/strings/strings.en.yaml, chaoscenter/web/src/strings/types.ts, chaoscenter/web/src/views/ChaosHubs/AddHubModal.tsx, chaoscenter/web/src/views/ChaosProbes/ChaosProbesTableMenu.tsx, chaoscenter/web/src/views/Environments/EnvironmentList/EnvironmentsList.tsx, chaoscenter/web/src/views/KubernetesChaosInfrastructureCreationModal/KubernetesChaosInfrastructureStepWizardConfiguration.tsx
=> fix: Fixed issues with refetch on ChaosHub, Environment and Probe screens

chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go, chaoscenter/graphql/server/pkg/database/mongodb/chaos_experiment/operations.go, chaoscenter/graphql/server/pkg/gitops/service.go, litmus-portal/graphql-server/pkg/chaos-workflow/handler/handler.go
=> Added check to prevent duplicate experiments with same name

chaoscenter/web/src/controllers/CreateNewToken/CreateNewToken.tsx, chaoscenter/web/src/strings/strings.en.yaml, chaoscenter/web/src/strings/types.ts, chaoscenter/web/src/views/AccountPasswordChange/AccountPasswordChange.tsx, chaoscenter/web/src/views/Environments/EnvironmentList/CreateEnvironment.tsx
- Show an error popup when a user enters an existing environment_id.
- Show an error popup when a user enters an incorrect password in the UpdatePassword.
Issue No. #4143 
=> [chore]: Show an error popup when a user enters an invalid info

chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go
=> added check to prevent dupicate experiment name

chaoscenter/README.md, chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go, chaoscenter/web/src/api/core/experiments/stopWorkflow.ts, chaoscenter/web/src/components/ExperimentActionButtons/ExperimentActionButtons.tsx, chaoscenter/web/src/components/RightSideBarV2/RightSideBarV2.tsx, chaoscenter/web/src/controllers/ExperimentRunDetails/ExperimentRunDetails.tsx, chaoscenter/web/src/controllers/ExperimentRunHistory/ExperimentRunHistory.tsx, chaoscenter/web/src/views/AccountPasswordChange/AccountPasswordChange.tsx, chaoscenter/web/src/views/ExperimentCreationFaultConfiguration/Tabs/Probes/SelectProbesDetail/SelectProbesDetail.tsx, chaoscenter/web/src/views/ExperimentDashboardV2/ExperimentDashboardV2Table.tsx
=> feat: Added stop/re-run button in experiment dashboard table and right sidebar

chaoscenter/web/src/components/PasswordInput/PasswordInput.module.scss, chaoscenter/web/src/components/PasswordInput/PasswordInput.module.scss.d.ts, chaoscenter/web/src/components/PasswordInput/PasswordInput.tsx, chaoscenter/web/src/components/PasswordInput/index.ts, chaoscenter/web/src/components/UserNameInput/UserNameInput.module.scss, chaoscenter/web/src/components/UserNameInput/UserNameInput.module.scss.d.ts, chaoscenter/web/src/components/UserNameInput/UserNameInput.tsx, chaoscenter/web/src/components/UserNameInput/index.ts, chaoscenter/web/src/strings/strings.en.yaml, chaoscenter/web/src/strings/types.ts, chaoscenter/web/src/views/Login/LoginPage.tsx
- Please add the links to the dependent PR that need to be merged before this (if any).
=> feat: Added view toggle for password input field

.github/workflows/codeql-analysis.yml, chaoscenter/authentication/api/handlers/rest/user_handlers_test.go, chaoscenter/graphql/server/pkg/chaos_infrastructure/infra_utils.go, chaoscenter/graphql/server/pkg/chaoshub/handler/handler.go, chaoscenter/graphql/server/pkg/chaoshub/handler/handler_test.go, chaoscenter/graphql/server/pkg/chaoshub/ops/gitops_test.go, chaoscenter/graphql/server/pkg/chaoshub/service.go, chaoscenter/graphql/server/pkg/gitops/gitops.go, chaoscenter/graphql/server/pkg/gitops/service.go, chaoscenter/subscriber/go.sum, chaoscenter/subscriber/pkg/graphql/operations.go
`ioutil` package was deprecated since 1.16
this pr replaced `ioutil` package with the `os` and `io` packages.
=> Replace deprecated package

chaoscenter/web/src/components/MainNav/MainNav.module.scss
Closes #4419 
After the changes:
https://github.com/litmuschaos/litmus/assets/99114125/347ea8d4-79e6-4a2c-877d-fcbc0c16be20
=> fixed main-nav height

chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go, chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler_fuzz_test.go, chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler_test.go, chaoscenter/graphql/server/pkg/gitops/model/mocks/service.go
Fixes #4434. This PR adds the checks for gitops update in following handlers
1. SaveChaosExperiment
2. CreateChaosExperiment
3. UpdateChaosExperiment
I think we need to discuss this a little bit more: whether we want the gitops to be triggered while just saving the chaosExperiment or also when a new experiment is scheduled to be running
=> [ Fix ] : Gitops trigger in Save, Delete, and Update Experiment

.github/workflows/codeql-analysis.yml, chaoscenter/authentication/api/handlers/rest/user_handlers_test.go, chaoscenter/graphql/server/pkg/chaos_infrastructure/infra_utils.go, chaoscenter/graphql/server/pkg/chaoshub/handler/handler.go, chaoscenter/graphql/server/pkg/chaoshub/handler/handler_test.go, chaoscenter/graphql/server/pkg/chaoshub/ops/gitops_test.go, chaoscenter/graphql/server/pkg/chaoshub/service.go, chaoscenter/graphql/server/pkg/gitops/gitops.go, chaoscenter/graphql/server/pkg/gitops/service.go, chaoscenter/subscriber/go.sum, chaoscenter/subscriber/pkg/graphql/operations.go
Reverts litmuschaos/litmus#4475
This PR is reverted since it is breaking the chaos hub experiment page. Experiment list shows 0 experiments:
The changes will be fixed in next release by @namkyu1999 🚀
=> Revert "Replace deprecated package"

chaoscenter/graphql/server/manifests/cluster/3a_agents_rbac.yaml, chaoscenter/graphql/server/pkg/probe/utils/utils.go, chaoscenter/graphql/server/utils/misc.go, chaoscenter/subscriber/go.sum, chaoscenter/web/src/views/ChaosStudio/ChaosStudio.tsx
ChaosHub's templates are not executed because of `internal server error`.
It's because our code references null ptr when we generate probes automatically.
this pr resolves this issue
FYI: [discussion in slack](https://kubernetes.slack.com/archives/CNXNB0ZTN/p1711427213471879)
=> fix: resolve templates in ChaosHub not running correctly

mkdocs/docs/experiments/categories/pods/pod-cpu-hog-exec.md, mkdocs/docs/experiments/categories/pods/pod-memory-hog-exec.md
This PR addresses the possible typo's in the documentation referenced in this issue: https://github.com/litmuschaos/litmus/issues/4564
Thank you for making this wonderful product 🙏
=> Add alternative kill commands for OpenShift

.github/workflows/build.yml, .gitleaksignore, mkdocs/docs/auth/v2.0.0/api.html, mkdocs/docs/auth/v2.0.0/swagger.yml, mkdocs/docs/auth/v3.0.0/auth-api.json
=> Added gitleaks in PR-Checks 

chaoscenter/web/src/components/KubernetesChaosInfrastructureDeploymentCards/DeploymentScopeCards.tsx
Fixes #4612 
When the ChaosCentre is namespace scoped 'Cluster-Wide access' is hidden.
=> Hide 'Cluster-Wide' Access in namespace scoped ChaosCentre

chaoscenter/graphql/server/server.go, mkdocs/docs/3.8.0/litmus-3.8.0-without-resources.yaml, mkdocs/docs/3.8.0/litmus-cluster-scope-3.8.0.yaml, mkdocs/docs/3.8.0/litmus-namespaced-3.8.0.yaml, mkdocs/docs/3.8.0/litmus-portal-crds-3.8.0.yml
=> Added installation manifest for 3.8.0

chaoscenter/authentication/api/handlers/rest/project_handler.go, chaoscenter/authentication/api/handlers/rest/project_handler_test.go, chaoscenter/authentication/api/handlers/rest/user_handlers.go, chaoscenter/authentication/api/handlers/rest/user_handlers_test.go, chaoscenter/graphql/server/go.mod, chaoscenter/graphql/server/go.sum, chaoscenter/graphql/server/server.go
=> Added necessary rbacs for invite_users and get_project_members API

chaoscenter/authentication/api/docs/swagger.json, chaoscenter/authentication/pkg/user/repository.go, chaoscenter/web/config/oats.config.ts, chaoscenter/web/src/api/auth/index.ts, chaoscenter/web/src/api/auth/schemas/User.ts, chaoscenter/web/src/controllers/AccountPasswordChange/AccountPasswordChange.tsx, chaoscenter/web/src/controllers/Login/LoginPage.tsx, chaoscenter/web/src/controllers/Overview/Overview.tsx, chaoscenter/web/src/hooks/useLogout.ts, chaoscenter/web/src/routes/RouteDestinations.tsx, chaoscenter/web/src/utils/userDetails.ts, chaoscenter/web/src/views/AccountPasswordChange/AccountPasswordChange.tsx, chaoscenter/web/src/views/CreateNewUser/CreateNewUser.tsx, chaoscenter/web/src/views/Overview/Overview.tsx, chaoscenter/web/src/views/Overview/__tests__/Overview.test.tsx, mkdocs/docs/auth/v3.9.0/auth-api.json
=> feat: Added reset password as a mandatory step if new user logs in

chaoscenter/authentication/api/main.go, chaoscenter/graphql/server/utils/variables.go, chaoscenter/manifests/litmus-cluster-scope.yaml, chaoscenter/manifests/litmus-namespaced-scope.yaml, chaoscenter/manifests/litmus-without-resources.yaml, chaoscenter/web/nginx/nginx.conf
=> update allowed origins list and nginx config

chaoscenter/authentication/api/docs/docs.go, chaoscenter/authentication/api/docs/swagger.json, chaoscenter/authentication/api/docs/swagger.yaml, chaoscenter/authentication/api/handlers/doc.go, chaoscenter/authentication/api/handlers/rest/user_handlers.go, chaoscenter/authentication/pkg/user/repository.go, chaoscenter/authentication/pkg/utils/errors.go
=> Added enhancements in password mandate logic

chaoscenter/authentication/api/main.go, chaoscenter/graphql/server/pkg/grpc/auth_grpc_client.go, chaoscenter/graphql/server/utils/variables.go, chaoscenter/manifests/litmus-getting-started.yaml, chaoscenter/manifests/litmus-installation.yaml, chaoscenter/manifests/litmus-without-resources.yaml
=> Prepended colon in the ports env

mkdocs/docs/experiments/categories/aws/AWS-experiments-tunables.md, mkdocs/docs/experiments/categories/aws/common/chaos-interval.yaml, mkdocs/docs/experiments/categories/aws/common/managed-nodegroup.yaml, mkdocs/docs/experiments/categories/aws/ec2-stop-by-tag.md, mkdocs/docs/experiments/categories/aws/ec2-stop-by-tag/instance-affected-percentage.yaml, mkdocs/docs/experiments/categories/aws/ec2-stop-by-tag/instance-tag.yaml
Related issue https://github.com/litmuschaos/litmus/issues/4807#issuecomment-2271358440
This PR fixes an issue where the [ec2-stop-by-tag](https://litmuschaos.github.io/litmus/experiments/categories/aws/ec2-stop-by-tag/) experiment fails to target the intended EC2 instance.
The [ec2-stop-by-tag](https://litmuschaos.github.io/litmus/experiments/categories/aws/ec2-stop-by-tag/) experiment encounters a `TARGET_SELECTION_ERROR` due to an incorrect retrieval of the `EC2_INSTANCE_TAG` environment variable.
```
Fault Summary:
TARGET_SELECTION_ERROR
{"errorCode":"TARGET_SELECTION_ERROR","phase":"PreChaos","reason":"failed to get the instance tag, invalid instance tag","target":"{EC2 Instance Tag: , Region: ap-northeast-2}"}
```
By correctly renaming the environment variable from `INSTANCE_TAG` to …
=> Rename env to EC2_INSTANCE_TAG

chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go
Fixes #4584 
This PR allows connections from older infras to connect with chaos centre
Infras with minor versions lower than chaos centre can now connect 
i.e 
```3.5.0 can connect with 3.7.0```
but 
```3.5.0 cannot connect with 4.x.x```
=> Allow older Infras to connect with Chaos Centre

chaoscenter/graphql/server/pkg/chaoshub/handler/handler_fuzz_test.go, chaoscenter/graphql/server/pkg/chaoshub/handler/handler_test.go
add fuzz test in chaoscenter/graphql/server/pkg/chaoshub/handler
* Removed the ./types.go example in unit test handler_test.go/TestReadExperimentFile because it returns a file does not exist error, not the file is not a yaml error that the test is intended to return.
=> test: add fuzz test in chaoshub/handler

chaoscenter/graphql/server/pkg/chaoshub/ops/gitops.go, chaoscenter/graphql/server/pkg/gitops/gitops.go, chaoscenter/graphql/server/utils/variables.go
- Added support for setting the Git username as an environment variable (GIT_USERNAME) to ensure compatibility with Bitbucket repositories.
- This change addresses an issue where Bitbucket requires the username explicitly, and the default system username did not work correctly for authentication.
- Fixed #4315 
=> fix: Add Git Username env variable #4315

chaoscenter/authentication/api/handlers/rest/project_handler.go, chaoscenter/authentication/api/handlers/rest/user_handlers.go
when password is default value, creating a project return error. but project is created. This is because there is no return code.
Related issue: https://github.com/litmuschaos/litmus/issues/4904
=> Fix condition not returning error during initial login

proposals/replace-mongoDB-features.md
- Add mongoDB features proposal
the two operators `$facet` and `$bucket` are not supported by AWS. We are using the following features in graphQL and expect that modifying them with other features or code will make it easier to run LitmusChaos on AWS DocumentDB
Also `$lookup` does not supported multiple join 
Related issue: #4459 
```
he following 2 unsupported operators were found:
$facet | found 8 time(s)
$bucket | found 1 time(s)
Unsupported operators by filename and line number:
$facet | lines = found 8 time(s)
../../litmus/chaoscenter/graphql/server/pkg/chaos_infrastructure/service.go | lines = [664, 841]
../../litmus/chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go | lines = [733, 955, 1131]
../../litmus/chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/ha …
```
=> [Proposal] Support DocumentDB by replacing certain MongoDB operations

chaoscenter/authentication/pkg/project/repository.go, chaoscenter/authentication/pkg/session/api_token_repository.go, chaoscenter/authentication/pkg/user/repository.go
In some APIs that retrieve multiple entities, if there are no entities that meet the conditions, the API returns null instead of an empty list. To ensure consistent response format, we modified the code to initialize empty slices before processing the results.
As frontend use optional chaining to safely handle null response(or not used in anywhere in case of projectStats), this change won't affect the frontend behaivor
=> Add slice initialization to avoid null response

ADOPTERS.md, adopters/organizations/pokerbaazi.md
Adding PokerBaazi as an Adopter
https://github.com/litmuschaos/litmus/issues/2191#issuecomment-2485551454
=> Add PokerBaazi as an Adopter

proposals/jvm-fault-injection.md
This is a proposal for a new type of fault: JVM fault injection
=> Proposal: JVM fault injection

chaoscenter/graphql/server/pkg/chaos_experiment/handler/handler.go, chaoscenter/graphql/server/pkg/chaos_experiment_run/handler/handler.go, chaoscenter/upgrade-agents/control-plane/go.mod
Date filters when listing experiments or experiment runs do not currently work because mongodb stores `updated_at` as an integer and we pass in strings. This PR updates to convert the date range from a string to an int. Alternatively, the type of the date filter could have been changed, but that would break existing workflows so opted not to do it that way.
Issue: https://github.com/litmuschaos/litmus/issues/5078
Slack thread: https://kubernetes.slack.com/archives/CNXNB0ZTN/p1742510947495359
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …
=> update date filter to pass integers to graphql
